### ISSUE TITLE
'NetworkManagementClient' object has no attribute '_serialize'

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#30057] opened 2023-04-25 19:18 UTC
- **Package Name**:  azure.mgmt.network
- **Package Version**:  23.0.0
- **Operating System**: Linux
- **Python Version**: 3.8.0

**Describe the bug**
Calling azure.mgmt.network.NetworkManagementClient.list_network_manager_effective_security_admin_rules() fails with AttributeError: 'NetworkManagementClient' object has no attribute '_serialize'

**To Reproduce**
1. Call this operation on any vnet for the params, with either an empty dict or a dict defining skip_token=True/False

**Expected behavior**
The operation should not attempt to access an attribute that does not exist. Instead, it should send the message to the network RP.

**Screenshots**
```
  File "X/lib/python3.8/site-packages/azure/mgmt/network/_validation.py", line 51, in wrapper
    return func(self, *args, **kwargs)
  File "/X/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "X/lib/python3.8/site-packages/azure/mgmt/network/operations/_operations.py", line 98048, in list_network_manager_effective_security_admin_rules
    _json = self._serialize.body(parameters, "QueryRequestOptions")
AttributeError: 'NetworkManagementClient' object has no attribute '_serialize'
```

**Additional context**
This problem was not present in version 22.2.0

**Comment by kashifkhan** [comment] 2023-04-25 19:27
Thanks for the feedback @jazelenk. We will investigate and get back to you asap.

**Comment by msyyc** [comment] 2023-04-26 07:02
We have found the root cause and will release fix version soon.

**Comment by msyyc** [comment] 2023-04-27 03:28
@jazelenk please try latest version: https://pypi.org/project/azure-mgmt-network/23.0.1/

**Comment by jazelenk** [comment] 2023-04-27 15:40
Confirmed: updated to 23.0.1 and it works again. Thanks for the quick turnaround!

**Comment by iscai-msft** [comment] 2023-04-27 16:24
thanks @msyyc, @jazelenk I'm going to close this issue since it has been fixed. thanks!

**Closed by iscai-msft** 2023-04-27 16:24 UTC
Labels: question, Mgmt, customer-reported, issue-addressed
