### ISSUE TITLE
NXDOMAIN error when trying to get configuration from Azure

### ISSUE THREAD

**Issue by erbek** [Azure/azure-sdk-for-python#37835] opened 2024-10-10 08:57 UTC
- **Package Name**:  azure.appconfiguration.provider
- **Package Version**: 2.0.0b1
- **Operating System**: windows
- **Python Version**:  3.11.4

**Describe the bug**
Filed to connect to azure appconfiguration resulting in error:
FAILED projects/shared-libs-python/tests/configuration/azure_config_manager/test_azure_config_manager_client.py::test_init[1] - 

dns.resolver.NXDOMAIN: The DNS query name does not exist: _origin._tcp.pai-configuration-manager.azconfig.io.

**To Reproduce**
1. Just connect to appservice configuration manager using the connection_string
self.app_config = load(connection_string=self.connection_string, selects=selects)

**Expected behavior**
Expected behavior is to receive configuration entries - it works fine in version 1.0.0 for me - however I need refresh feature

**Screenshots**

**Additional context**
The issue is in azure\appconfiguration\provider\_discovery.py lines 84-89:
![Image](https://github.com/user-attachments/assets/cf585b0f-c62c-465e-a115-0ef3a539c53f)

the NXDOMAIN error is not properly handled and it causes a failure.
I've fixed that by adding:
        except Exception as e:
            return []

in lines 90-91 but it should be fixed in the code. 
I am preparing the code fix in my branch and will ask for a pull request soon

**Comment by mrm9084** [comment] 2024-10-10 20:47
This seems to be a duplicate of this, https://github.com/Azure/azure-sdk-for-python/issues/37773, where you said it was fixed by updating a dependency.

And can you clarity what you mean by NXDOMAIN not being handled? Also do you have the same issue in the non-beta version 1.3.0 which is the latest GA release.

**Comment by erbek** [comment] 2024-10-11 06:20
This is not the same issue.
By not being handled is that exception (NXDOMAIN) I mean that this line is
condition is not met, even though the error is NXDOMAIN:
[image: image.png]
That's why I've added "all other" exception handler.
Version 1.3.0:
[image: image.png]

W dniu czw., 10 paź 2024 o 22:48 Matthew Metcalf ***@***.***>
napisał(a):

**Comment by mrm9084** [comment] 2024-10-11 16:54
@erbek, I'm unable to replicate the error. The code that is part of is for auto discovery of replica store for auto failover. The case of NXDOMAIN, is the case where the store has no replicas. I've tested that case and see NXDOMAIN thrown and caught.

Have you tried the non beta version and could you tell me what version of dnspython you have installed?

**Comment by erbek** [comment] 2024-10-16 07:40
Hi
sorry I just stopped using provider because of many reasons. My NXDOMAIN error was not catched properly. I am using 2.6.1 dnspython.
If you are still not able to reproduce ill build some temp project to doublecheck with my accounts and libs.

**Comment by mrm9084** [comment] 2024-10-21 19:18
> Hi sorry I just stopped using provider because of many reasons. My NXDOMAIN error was not catched properly. I am using 2.6.1 dnspython. If you are still not able to reproduce ill build some temp project to doublecheck with my accounts and libs.

Let me know if you can repo this, I'm unsure why it would be happening. One solution is just disabling this feature. This code is used when you have replicas of your config store for failover cases. It can be disabled on load by passing in `replica_discovery_enabled=False`

**Closed** 2024-11-15 01:27 UTC
Labels: question, Client, customer-reported, no-recent-activity, needs-author-feedback, App Configuration Provider
