### ISSUE TITLE
network_configuration_to_xml() add idletimeoutInMinutes anyway

### ISSUE THREAD

**Issue by zhitongLBN** [Azure/azure-sdk-for-python#397] opened 2015-06-25 09:38 UTC
To add a `UDP` port using update_role, event thought i put None at `IdlTimeoutInMinutes`, in fuction `network_configuration_to_xml()` in `'servicemanagement/__init__.py'` will add balise `IdlTimeoutInMinutes`, which cause server error
`Idle timeout cannot be set for endpoints with protocol udp`

please fix it thanks!!!

**Comment by lmazuel** [comment] 2015-12-22 17:41
Hello,

Sorry for the late answer. It seems to be fixed in latest version, could you confirm before I close the bug?
Thank you,

**Comment by lmazuel** [comment] 2015-12-22 18:30
Duplicate of https://github.com/Azure/azure-sdk-for-python/issues/334

**Closed by lmazuel** 2015-12-22 18:30 UTC
Labels: Management
