### ISSUE TITLE
Azure-storage-blob failing to create container when used with Azurite emulator

### ISSUE THREAD

**Issue by hayesgb** [Azure/azure-sdk-for-python#16193] opened 2021-01-15 15:45 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.7.0
- **Operating System**: Ubuntu
- **Python Version**: 3.7.x

**Describe the bug**
When attempting to create a container in the Azurite emulator, the operation fails with the following error:

```
---------------------------------------------------------------------------
HttpResponseError                         Traceback (most recent call last)
~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_container_client.py in create_container(self, metadata, public_access, **kwargs)
    291                 headers=headers,
--> 292                 **kwargs)
    293         except HttpResponseError as error:

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py in create(self, timeout, metadata, access, request_id_parameter, container_cpk_scope_info, **kwargs)
    133             error = self._deserialize(_models.StorageError, response)
--> 134             raise HttpResponseError(response=response, model=error)
    135 

HttpResponseError: Operation returned an invalid status 'The value for one of the HTTP headers is not in the correct format.'

During handling of the above exception, another exception occurred:

HttpResponseError                         Traceback (most recent call last)
<ipython-input-82-d87210cae0c0> in <module>
      1 bbs = BlobServiceClient.from_connection_string(conn_str=CONN_STR)
----> 2 bbs.create_container("data")

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/core/tracing/decorator.py in wrapper_use_tracer(*args, **kwargs)
     81             span_impl_type = settings.tracing_implementation()
     82             if span_impl_type is None:
---> 83                 return func(*args, **kwargs)
     84 
     85             # Merge span is parameter is set, but only if no explicit parent are passed

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_blob_service_client.py in create_container(self, name, metadata, public_access, **kwargs)
    513         timeout = kwargs.pop('timeout', None)
    514         container.create_container(
--> 515             metadata=metadata, public_access=public_access, timeout=timeout, **kwargs)
    516         return container
    517 

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/core/tracing/decorator.py in wrapper_use_tracer(*args, **kwargs)
     81             span_impl_type = settings.tracing_implementation()
     82             if span_impl_type is None:
---> 83                 return func(*args, **kwargs)
     84 
     85             # Merge span is parameter is set, but only if no explicit parent are passed

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_container_client.py in create_container(self, metadata, public_access, **kwargs)
    292                 **kwargs)
    293         except HttpResponseError as error:
--> 294             process_storage_error(error)
    295 
    296     @distributed_trace

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py in process_storage_error(storage_error)
    148     error.error_code = error_code
    149     error.additional_info = additional_data
--> 150     error.raise_with_traceback()
    151 
    152 

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/core/exceptions.py in raise_with_traceback(self)
    216     def raise_with_traceback(self):
    217         try:
--> 218             raise super(AzureError, self).with_traceback(self.exc_traceback)
    219         except AttributeError:
    220             self.__traceback__ = self.exc_traceback

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_container_client.py in create_container(self, metadata, public_access, **kwargs)
    290                 cls=return_response_headers,
    291                 headers=headers,
--> 292                 **kwargs)
    293         except HttpResponseError as error:
    294             process_storage_error(error)

~/anaconda3/envs/adlfs/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py in create(self, timeout, metadata, access, request_id_parameter, container_cpk_scope_info, **kwargs)
    132             map_error(status_code=response.status_code, response=response, error_map=error_map)
    133             error = self._deserialize(_models.StorageError, response)
--> 134             raise HttpResponseError(response=response, model=error)
    135 
    136         response_headers = {}

HttpResponseError: The value for one of the HTTP headers is not in the correct format.
RequestId:42e8b39c-a2ab-44ca-bfbe-d3bffd7cc818
Time:2021-01-15T15:01:51.144Z
ErrorCode:InvalidHeaderValue
Error:
  
HeaderName:x-ms-version
HeaderValue:2020-04-08
```

This does not occur with azure-storage-blob==12.6.0

**To Reproduce**
1. Start the Azurite container

```
from azure.storage.blob import BlobServiceClient


URL = "http://127.0.0.1:10000"
ACCOUNT_NAME = "devstoreaccount1"
KEY = "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="  # NOQA
CONN_STR = f"DefaultEndpointsProtocol=http;AccountName={ACCOUNT_NAME};AccountKey={KEY};BlobEndpoint={URL}/{ACCOUNT_NAME};"  # NOQA
data = b"0123456789"
bbs = BlobServiceClient.from_connection_string(conn_str=CONN_STR)
bbs.create_container("data")
```

**Expected behavior**
Azurite successfully creates the container

**Comment by tasherif-msft** [comment] 2021-01-19 06:47
Hi @hayesgb,

I will investigate this for you, in the meantime could you please try:
`blob = BlobClient.from_connection_string(conn_str=CONN_STR, api_version='2019-12-12')`
I want to see if a previous api_version would work.

thanks

**Comment by aviramha** [comment] 2021-01-19 08:33
This happens for us too. Ever since upgrading to 12.7.0 we face multiple errors:
```
E           azure.core.exceptions.HttpResponseError: The value for one of the HTTP headers is not in the correct format.
E           RequestId:9be62e60-bd8f-4c61-b6b2-83b53710318b
E           Time:2021-01-19T08:22:10.266Z
E           ErrorCode:InvalidHeaderValue
E           Error:
E
E           HeaderName:x-ms-version
E           HeaderValue:2020-04-08
```

2nd:
```
azure.core.exceptions.HttpResponseError: x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please vote your wanted features to https://github.com/azure/azurite/issues
546
E           RequestId:9edd9421-0b8e-4555-8251-afc66c9a3451
547
E           Time:2021-01-18T18:29:13.203Z
548
E           ErrorCode:FeatureNotSupported
549
E           Error:
```

**Comment by tappoz** [comment] 2021-01-21 15:59
@tasherif-msft this happens with the latest version `12.7.1` as well (released early today in the morning 2021-01-21 UTC).

The suggested fix `api_version="2019-12-12"` works.

I've replicated both the bug and the fix above with these 2 flavors of the same command:

```python
bs_conn_str = "DefaultEndpointsProtocol=https;AccountName=MY_BLOB_STORAGE;AccountKey=MY_PRIMARY_KEY;EndpointSuffix=core.windows.net"
blob = BlobServiceClient.from_connection_string(
    conn_str=bs_conn_str, 
    api_version="2019-12-12",
)
blob = BlobServiceClient(
    account_url="https://MY_BLOB_STORAGE.blob.core.windows.net",
    credential="MY_PRIMARY_KEY",
    api_version="2019-12-12",
)
```

The full script to reproduce the error:

```python
from azure.storage.blob import BlobServiceClient

# blob storage connection
blob = BlobServiceClient(
    account_url="https://MY_BLOB_STORAGE.blob.core.windows.net",
    credential="MY_PRIMARY_KEY",
    api_version="2019-12-12",
)
# container connection
bs_container_name = "MY_CONTAINER"
container = blob.get_container_client(container=bs_container_name)
print("Done with INIT")

# list some blobs
blobs_list = [blob for blob in container.list_blobs()] # <-- HERE EXCEPTIONS ARE THROWN
print(f"Found {len(blobs_list)} blobs. DONE!")
```

**Comment by tasherif-msft** [comment] 2021-01-21 21:51
Hi @hayesgb and @tappoz, we're investigating this offline and will get back to you as soon as possible.

**Comment by tasherif-msft** [comment] 2021-01-21 22:19
Hi @hayesgb and @tappoz, which version of Azurite are you running?

**Comment by tasherif-msft** [comment] 2021-01-22 03:05
Which Azurite version are you using @hayesgb and @tappoz? please note that the api version 2020-04-08 was introduced in Azurite version 3.10.0. You can also skip the API version check by passing `--skipApiVersionCheck` when starting your azurite. Let me know if this resolves your issues.

**Comment by tappoz** [comment] 2021-01-22 08:24
@tasherif-msft I am not using Azurite, but given a similar scenario I see the same exception message that can be fixed with the same suggested solution (extra field `api_version="2019-12-12"`).

My environment is this:

```
$ pip list | grep azure
azure-core                    1.10.0       
azure-storage-blob       12.7.1
$ pip list | grep ms
msrest                          0.6.19
```

**Comment by hayesgb** [comment] 2021-01-23 12:43
I’m using 3.10 as part of a unit test workflow.

**Comment by tasherif-msft** [comment] 2021-01-25 06:34
Hi @hayesgb, could you pass `--skipApiVersionCheck` when running Azurite and let me know if this fixes your problem.
@tappoz, so you're facing this issue while using your actual storage account?

**Comment by tappoz** [comment] 2021-01-25 10:29
@tasherif-msft yes.

**Comment by tasherif-msft** [comment] 2021-01-25 21:45
Hi @tappoz, I looked into this internally and it appears that some storage accounts that do not have the most recent api version `2020-04-08` enabled. This is going to be fixed in our next rollout.
In the meantime, you can set `api_version='2020-02-10'` or  `api_version='2019-12-12'` when initializing any client. Let me know if this resolves your problem.
We apologize for the inconvenience.

**Comment by tappoz** [comment] 2021-01-26 08:11
@tasherif-msft yes adding `api_version="2019-12-12"` when initializing the clients resolves the problem. Thanks :+1:

**Closed** 2021-01-31 03:10 UTC
Labels: Client, Storage, bug, customer-reported, needs-author-feedback, needs-team-attention

**Comment by aviramha** [comment] 2021-02-01 09:47
I'm not sure why is it closed. How do we solve it for good? Using a specific api version doesn't really help.

**Comment by tasherif-msft** [comment] 2021-02-02 05:33
Hey @aviramha, some accounts haven't rolled out the newest api version yet, hence this issue. This will be resolved soon without you having to do anything. 
Let me know if you have any further questions.

**Comment by aviramha** [comment] 2021-02-02 05:40
> Hey @aviramha, some accounts haven't rolled out the newest api version yet, hence this issue. This will be resolved soon without you having to do anything. 
> 
> Let me know if you have any further questions.

What about azurite? It does support newest API yet it fails

**Comment by aviramha** [comment] 2021-02-10 06:39
@tasherif-msft ?

**Comment by tasherif-msft** [comment] 2021-02-10 08:23
Hi @aviramha and @tappoz the rollout should be complete and the issue should be gone. Could you confirm this?
As for Azurite @aviramha looking at your error trace (`x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode`) is probably unrelated to the recent service version update. You can open an issue here https://github.com/Azure/Azurite
