### ISSUE TITLE
azure-eventhub/azure/eventhub/extensions/__init__.py is incompatible with packaging namespaces

### ISSUE THREAD

**Issue by pjachowi** [Azure/azure-sdk-for-python#13187] opened 2020-08-18 15:32 UTC
- **Package Name**: 
azure-eventhub

- **Package Version**: 
5.1.0

- **Operating System**:
Linux

- **Python Version**: 
3.8.2

**Describe the bug**
Existence of emptiness of the file https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/extensions/__init__.py is incompatible with packaging namespaces. It causes problem using this package in Bazel, see https://github.com/dillon-giacoppo/rules_python_external/issues/56

**To Reproduce**
1. Go into temporary directory `cd /tmp`
2. Install azure_eventhub under dir1 `pip install --target=$(pwd)/dir1 azure_eventhub`
3. Install azure-eventhub-checkpointstoreblob under dir2 `pip install --target=$(pwd)/dir2 azure-eventhub-checkpointstoreblob`
4. Create virtual environment `virtualenv venv`
5. Activate virtual environment `source venv/bin/activate`
6. Create main.py 
```
cat > main.py
import sys
sys.path.extend(['/tmp/dir1', '/tmp/dir2'])
from azure.eventhub.extensions.checkpointstoreblob import BlobCheckpointStore
```
7. Execute main.py `python ./main.py`
8. Result is an error:
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from azure.eventhub.extensions.checkpointstoreblob import BlobCheckpointStore
ModuleNotFoundError: No module named 'azure.eventhub.extensions.checkpointstoreblob'
```

**Expected behavior**
main.py should execute without errors.

**Screenshots**
N/A

**Additional context**
The problem emerges because Bazel installs dependencies in separate directories. Current layout, incompatible with packaging namespaces makes it impossible to use in applications build by Bazel, see https://github.com/dillon-giacoppo/rules_python_external/issues/56

**Comment by yunhaoling** [comment] 2020-08-19 22:35
hello @pjachowi , thanks for the report, I'm able to reproduce it locally following the steps.

and thanks for the PR, adding `__path__ = __import__('pkgutil').extend_path(__path__, __name__)` seems to be a viable solution if you want to install package in different locations. I need to do more tests/collect knowledge on packaging to see if it has some impacts that I overlook.

hey @johanste @lmazuel , I remember we've discussed about the how to structure the extension package before, do you have any suggestion on this issue?

**Comment by pjachowi** [comment] 2020-08-26 12:37
Hello @yunhaoling, did you have chance to look at the PR? As a side note I've looked into rest of Azure sdk and it looks like `__path__ = ...` is commonly used in `__init__.py`.

**Comment by pjachowi** [comment] 2020-09-03 11:52
Friendly ping @yunhaoling

**Comment by yunhaoling** [comment] 2020-09-10 02:50
hey @pjachowi , apologize for not getting back to you sooner.

Let me give you some more context here:

The empty `azure/eventhub/extensions/__init__.py` was by-design, it is intended to **NOT** make `azure.eventhub.extensions` not a namespace package which would give us performance improvement on module searching in python compared to namespace package approach.

We have two plugin packages `azure-eventhub-checkpointstoreblob` and `azure-eventhub-checkpointstoreblob` which share the same `azure.eventhub.extension` namespace. If you check the other two libraries, you would find both `azure.eventhub.extension.__init__` files are empty in these two libraries.

However, this approach is causing trouble here -- your use case.

I'm having discussion with our architects on what's the **RIGHT** approach here, there're majorly two approaches to solve the problem:
1. Making `azure.eventhub.extentions` a namespace package, just as your PR. But we may need to update the `__init__.py` in the two plugin libraries as well.
2. Create a separate namespace package library, e.g. `azure-eventhub-extensions-nspkg` which is shared by `azure-eventhub`, `azure-checkpointstoreblob` and `azure-checkpointstoreblob-aio`. But this approach seems a bit overkill.

The decision would apply to our design of other python sdks.

I'll continue to post updates here and feel free to let us know your thoughts on packaging.

**Comment by pjachowi** [comment] 2020-09-11 18:37
Thank you for the explanation.

I've searched Azure/azure-sdk-for-python repository and it seems that `__path__ = __import__('pkgutil').extend_path(__path__, __name__)` in `__init__.py` is is commonly used. [This query](https://github.com/Azure/azure-sdk-for-python/search?q=__path__+%3D+__import__%28%27pkgutil%27%29.extend_path%28__path__%2C+__name__%29&unscoped_q=__path__+%3D+__import__%28%27pkgutil%27%29.extend_path%28__path__%2C+__name__%29) returns 387 results.

What do you think when the changes will be applied?

**Comment by yunhaoling** [comment] 2020-09-14 21:58
hey @pjachowi , after a long discussion the team has agreed on the fix and I've merged your PR.
It would be carried in our next EventHub release (which is still under planning). I'll keep you updated.

Again, thanks for your patience and contribution!

**Closed** 2020-09-15 01:06 UTC
Labels: Client, Event Hubs, customer-reported, question

**Comment by ivomodrinic** [comment] 2020-12-16 12:41
> hey @pjachowi , after a long discussion the team has agreed on the fix and I've merged your PR.
> It would be carried in our next EventHub release (which is still under planning). I'll keep you updated.
> 
> Again, thanks for your patience and contribution!

Hi @yunhaoling 
It does not work on current `azure-eventhub-checkpointstoreblob==1.1.1`.
Can you share any ETA of the next release that is expected to have this fix included? We would like to use EventHub checkpoints functionality, but since this does not work we would need to think on alternative solutions, unless the fix is underway soon.

**Comment by yunhaoling** [comment] 2020-12-17 19:22
hey @ivomodrinic , we have a release plan in early Jan next year, sorry for keeping you waiting for so long.

**Comment by ivomodrinic** [comment] 2020-12-18 08:45
> hey @ivomodrinic , we have a release plan in early Jan next year, sorry for keeping you waiting for so long.
No worries @yunhaoling. Thanks for quick response and ETA.
