### ISSUE TITLE
The error "blob not found" occurs when receive event data using "event processor host"

### ISSUE THREAD

**Issue by imeya** [Azure/azure-sdk-for-python#8905] opened 2019-11-29 02:51 UTC
I'm using "event processor host"(follow [this sample code](https://github.com/Azure/azure-sdk-for-python/blob/eventhub_track1/sdk/eventhub/azure-eventhubs/examples/eph.py)).

Everything is ok. But there is a weird thing, if I create a new blob container, then use this new blob container to store checkpoint. Then I run the above code from sample, it will throw this error:

> The specified blob does not exist

The screenshot of this error:

![err1](https://user-images.githubusercontent.com/25738099/69840246-c9020000-1295-11ea-97ed-0136b2f727b6.PNG)

Even it throws this error, but it can work well and all events can be read.

I also can understand this error, because inside the new blob container, there is no such files like 0, 1 for partitions. But this error message is annoying. can you help fix this? 

Note: it only occurs for the first time since the blobs for each partition are not created. And this does not occur if I use eph in c#.

**Comment by annatisch** [comment] 2019-12-02 20:41
Thanks @imeya - we are hoping to do an EH release shortly with some fixes - We will look at whether we should/could demote the log message from ERROR to INFO

What do you think @KieranBrantnerMagee?

**Comment by KieranBrantnerMagee** [comment] 2020-08-01 18:36
Hey Imeya,
First, apologies that this sat for so long.
Second, I'd observe (from the doc link you sent) that you're on the track 1 EH library.  I'd recommend updating to 5.1.0 (pip install --upgrade azure-eventhub) and seeing if this mitigates the spurious error.

If you're still seeing it can gladly dig in and see what we can do.

Don't hesitate to let us know if any issues/blockers in this, or if the issue recurs.

**Comment by KieranBrantnerMagee** [comment] 2020-09-15 00:23
Closing this for now; feel free to reopen if the issue isn't mitigated by updating to the latest version, or if there is any further help we can provide.

**Closed by KieranBrantnerMagee** 2020-09-15 00:23 UTC
Labels: Client, Event Hubs, bug, customer-reported, needs-author-feedback, no-recent-activity
