### ISSUE TITLE
Missing dependencies after installation

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-sdk-for-python#839] opened 2016-10-28 21:27 UTC
`pip install --pre azure` does not pull all the dependencies. After installation it still asks for `msrest` and `msrestazure`

**Comment by lmazuel** [comment] 2016-10-28 21:36
Hi @toddysm 
I close this one because it's a duplicate of this one:
https://github.com/Azure/azure-sdk-for-python/issues/644

There is a random issue with pip, sometimes it doesn't follow the 'extra_requires' as it should. Didn't found an easy workaround for now. :(

**Closed by lmazuel** 2016-10-28 21:36 UTC
