### ISSUE TITLE
azure-mgmt-network is huge

### ISSUE THREAD

**Issue by yoava333** [Azure/azure-sdk-for-python#11149] opened 2020-04-30 15:20 UTC
- **Package Name**: azure-mgmt-network
- **Package Version**: 10.1.0
- **Operating System**: alpine-3.11.6
- **Python Version**: 3.8

**Describe the bug**
`azure-mgmt-network` is the biggest dependency by far for my project, the size on disk is **110MB**, which means that it slows down everything else - like building & publishing my application.

**To Reproduce**
1. `pip install azure-mgmt-network`
2. inspect the `site-packages/azure/mgmt/network` folder

**Expected behavior**
I would expect the SDK to be much lighter, for comparison the entire GCP python SDK is ~5MB and boto3+botocore is ~50MB (which includes the entire SDK). 
If I were to install `azure-mgmt-compute` & `azure-mgmt-resource` I would get another 30MB, in one of my applications the azure folder is 250MB bigger than all the rest of the filesystem combined.

**Comment by chenjianfei2017** [comment] 2020-05-01 03:18
hi @yoava333 , i checked the pkg size, it is huge because network has multi versions, when you download this pkg, it will download pkgs of all version, we will discuss this on our meeting, thx.

**Comment by RodgeFu** [comment] 2020-05-06 08:46
@lmazuel , do you have any suggestion here? is it possible to optimize the codegen to reduce the size? thanks.

**Comment by RodgeFu** [comment] 2020-05-15 10:51
We did some investigation and found that the current network package still include very old api-version. Add "Service Attention" label to include service team to confirm whether we still need to support all the api-versions, it will be helpful to reduce the size if some old api-version can be removed from the package. thanks.

**Comment by talmachani** [comment] 2020-10-04 07:31
Any update on this?

**Comment by yoav-orca** [comment] 2020-11-12 14:45
Could you update on the status of this issue? 

Azure right now is **~330MB** I cannot use the sdk it in an AWS Lambda function anymore

![image](https://user-images.githubusercontent.com/65133955/98953955-f75c0800-2505-11eb-98eb-8ac3e8735143.png)

**Comment by wagde-orca** [comment] 2020-11-16 16:10
i have the same problem as well... Please update

**Comment by allegradomel** [comment] 2020-11-16 18:20
@chenjianfei2017 - I'm from the SDN team, did you come to any conclusion about how to fix this?

**Comment by yoav-orca** [comment] 2020-12-01 16:09
The issue is only becoming worse over time, it's now **~370MB** 
![image](https://user-images.githubusercontent.com/65133955/100765350-16143700-3400-11eb-92d6-252d98777711.png)

Where azure-mgmt-network is the biggest offender with **~230MB**
![image](https://user-images.githubusercontent.com/65133955/100765491-36dc8c80-3400-11eb-8a41-075c54904de7.png)

**Comment by jsntcy** [comment] 2021-03-05 03:01
@MikhailTryakhov, can we make the package smaller? for example, deprecate some very old versions such as 2015-xx-xx.
Actually this need cross team collaboration as network has many feature teams, do you know who can be the coordinator to collect thoughts from different feature team?
Before deprecation, we need data to insure there is no users to use those deprecated version recently.
![image](https://user-images.githubusercontent.com/16348853/110060859-8d5fbb00-7da1-11eb-90a2-d7432f263437.png)

**Comment by jiasli** [comment] 2021-03-05 03:03
The sheer size of `azure-mgmt-network` even makes PyCharm unresponsive by selecting or searching for `begin_create_or_update`.

https://github.com/Azure/azure-cli/blob/b0815f704b1c3a34c4b5a4aecf9489166eef30ef/src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_virtual_network.py#L173

```py
nw_client.virtual_networks.begin_create_or_update(resource_group, ...)
```

I have to set the project to "No interpreter" for coding.

![image](https://user-images.githubusercontent.com/4003950/110061234-37d7de00-7da2-11eb-8d89-31ce84a8d945.png)

**Comment by MikhailTryakhov** [comment] 2021-03-05 03:07
Hey @jsntcy  I assume that's impossible. different customers are using different api versions and I'm not sure it's a good idea to deprecate some of them

**Comment by jsntcy** [comment] 2021-03-05 03:16
@MikhailTryakhov, 
- We know different customers use different api versions, and we can collect data from telemetry to see if all existing API versions are used, if some versions are not used recently, we may probably deprecate them; otherwise the package will be bigger and bigger in the future as Network will include all existing features in new versions.
- Also we can suggest customers to upgrade from very old version to new version for better/more features provided.
- Another possible way: can we split Network package into multiple packages for different sub services.

**Comment by MikhailTryakhov** [comment] 2021-03-05 05:39
@jsntcy can you share these metrics?

**Comment by MikhailTryakhov** [comment] 2021-03-05 05:40
@jsntcy regarding to collect data from telemetry to see if all existing API versions are used

**Comment by MikhailTryakhov** [comment] 2021-03-10 01:09
@jsntcy any update?

**Comment by kenperkins** [comment] 2021-04-02 15:28
Has there been any resolution or progress on this issue?

**Comment by MikhailTryakhov** [comment] 2021-04-02 16:40
In case that's possible to do from your side - well please do. But we have risks that we'll have sev2s due to that... that api version is supported from the backend won't be supported from Python sdk side?

**Comment by jsntcy** [comment] 2021-04-05 23:50
@MikhailTryakhov, we plan to collect data this sprint and check if we can deprecate some old APIs from SDK perspective.

**Comment by jackmuskopf** [comment] 2021-05-19 17:08
We are also suffering significant additional application design overhead due to the size of some of these mgmt packages (particularly this and compute).

**Comment by sodul** [comment] 2021-08-16 20:42
We have written a script that deletes the unreferenced older APIs. It does delete a good chunk of the API folders but not all of it. With the script the Azure directory is now just under 300MB instead of over 700MB. It is compatible with most, but not all, third party packages, as long as they do not point to a version that is trimmed.

https://github.com/clumio-code/azure-sdk-trim

**Comment by skuethe** [comment] 2021-09-27 08:01
Any update on this? Azure CLI size is getting out of hand :(

**Comment by xiangyan99** [comment] 2021-11-30 00:48
Do we have any decisions?

We have similar problem when we ship conda packages.

**Comment by yoav-orca** [comment] 2021-12-15 08:43
/unresolve
@RAY-316 the issue not addressed/resolved the issue is only getting bigger, the package size of the network along (azure-mgmt-network) is now 286MB, which is almost 3 times larger than the original issue.

**Comment by travcunn** [comment] 2022-03-11 00:10
Any updates?

**Comment by sodul** [comment] 2022-03-11 00:38
@travcunn you can try my tool, which will bring the azure packages down to something less massive (300-400MB), but that might still be too large for Lambda.
https://github.com/clumio-code/azure-sdk-trim

As far as I can tell, this is something that was reported years ago and each release is still growing bigger, so it does not seem to be a priority at Microsoft.

@jsntcy you did communicate almost a year ago, can you share if anything came out of your meetings? You can share with your product teams that some decision makers are using this bug as an example as to why Azure should be avoided in favor of AWS.

**Comment by jsntcy** [comment] 2022-03-11 07:19
@sodul, I'm not in SDK team now. @msyyc, please share the update for this issue.

**Comment by msyyc** [comment] 2022-03-11 07:31
HI, we have gradually reduced the size for several release: https://github.com/Azure/azure-sdk-for-python/issues/21301.
What size do you expect?

**Comment by jiasli** [comment] 2022-03-11 07:56
According to https://github.com/Azure/azure-sdk-for-python/issues/21301#issuecomment-958653096, 21.1MB is still too large. Azure CLI 2.34.1 (https://azcliprod.blob.core.windows.net/msi/azure-cli-2.34.1.msi) is 52.3MB, which means `azure-mgmt-network` is almost half the size of whole Azure CLI.

**Comment by msyyc** [comment] 2022-03-14 03:07
Let me paste the data in e-mail to raise more attention for architect

**Comment by prawalgangwar** [comment] 2022-05-11 09:09
Facing issues with pylance. The python language server crashes as soon as I installed azure-mgmt-network. 

```[Info  - 12:24:33 PM] (4436) Found 102 source files
[Info  - 12:24:51 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2019_12_01/operations/_operations.py (2541ms)
[Info  - 12:24:56 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2020_04_01/operations/_operations.py (4044ms)
[Info  - 12:25:04 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2020_05_01/operations/_operations.py (7680ms)
[Error - 12:25:21 PM] (4436) Error occurred on background thread: {"code":"ERR_WORKER_OUT_OF_MEMORY"}```

**Comment by lmazuel** [comment] 2023-01-09 17:36
Duplicate of https://github.com/Azure/azure-sdk-for-python/issues/17801, where we're posting most update on the topic

**Closed by lmazuel** 2023-01-09 17:36 UTC
Labels: question, Service Attention, Network - Virtual Network, Mgmt, customer-reported, needs-team-attention
