### ISSUE TITLE
[Azure Storage Queue] nowait flag for receive_message() to raise Empty error

### ISSUE THREAD

**Issue by jryberg** [Azure/azure-sdk-for-python#29683] opened 2023-03-30 20:46 UTC
**Describe the solution you'd like**
I would like a custom error "Empty" when there are no messages to read to be able to abort the function when there are nothing to handle. 

There are no graceful way of terminating a program when it's stuck on receive_message()

It would be great to add an argument to not wait for new messages and instead raise an error

**Comment by pvaneck** [comment] 2023-03-30 21:24
Thanks for the feedback. I'll tag appropriate folks to take a look at this request.

**Comment by annatisch** [comment] 2023-03-30 21:38
Thanks @jryberg - just clarify, are you referring to the singular `receive_message`, or the iterator from `receive_messages`?
I think if it's the former, this should already return `None` in the case of no messages.

In the case of the `receive_messages` iterator, I think some time ago we had discussions about adding a `max_wait_time` option here? Or maybe I'm getting mixed up with a different API... either way, that might be a solution here.
That way it would be simple to set to `0` for the scenario of "return as soon as there's no more messages waiting"
@jalauzon-msft, @vincenttran-msft - do you have any recollections here?

**Comment by jalauzon-msft** [comment] 2023-03-31 18:16
@jryberg @annatisch, yes, the single message `receive_message` will return `None` if there are no messages in the Queue. This is not actually documented correctly in the current release, but the documentation has been fixed in `main`.

If you are talking about the plural `receive_messages`, could you please share a code snippet of how you are using it? We have discussed adding a `max_wait_time` argument to this method where it would only wait the specified amount of time for new messages before exiting. This may be a good solution here.

**Comment by jryberg** [comment] 2023-04-02 09:43
@annatisch , @jalauzon-msft Thank you for your reply 

I tried both receive_message and receive_messages from my point of view they have the same problem. I really like the way Python are using their queue with get_nowait (https://docs.python.org/3/library/queue.html#queue.Queue.get_nowait). It's simple and predictable with the Empty exception

Personally I'm not a fan of None type since I will have to start comparing if it's a dict or None when reading from the queue


This is an example of a little tool I wrote to move messages from poison back to the queue.  Note that I'm using a signal_handler that signals to the processes to exit but since I can't escape source_client.receive_message() I had to sys.exit(0) after a while instead of a graceful exit

The version before were using receive_messages and I iterated over the iterator instead. I tried different things but could not find a good solution so I created this issue. 
```
#!/usr/bin/env python3

# pylint: disable=C0301
# pylint: disable=W1203

import os
import sys
import time
import logging
import signal
from queue import Queue, Empty
from threading import Thread, Lock, Event
from azure.storage.queue import QueueClient, TextBase64EncodePolicy, TextBase64DecodePolicy

# Environments
source_connection_string = os.environ.get('SOURCE_CONNECTION_STRING')
source_queue_name = os.environ.get('SOURCE_QUEUE_NAME')
destination_connection_string = os.environ.get('DESTINATION_CONNECTION_STRING')
destination_queue_name = os.environ.get('DESTINATION_QUEUE_NAME')
debug = os.environ.get('DEBUG', 'FALSE')

# Variables
threadLock = Lock()
COUNTER = 0

# Threading
NR_OF_THREADS = 10
worker_queue = Queue()
exit_event = Event()

FORMAT = '%(asctime)-15s %(levelname)s %(message)s'
if debug.upper() == "TRUE":
    logging.basicConfig(level=logging.DEBUG, format=FORMAT)
else:
    logging.basicConfig(level=logging.INFO, format=FORMAT)
# Set the logging level for all azure-* libraries
logger = logging.getLogger('azure')
logger.setLevel(logging.WARNING)

def signal_handler(signum, frame):
    _ = signum
    _ = frame
    exit_event.set()
    time.sleep(10)
    sys.exit(0)

def handle_queue(threadnr, messages):
    logging.info(f"Staring worker thread {threadnr}")
    destination_client = QueueClient.from_connection_string(conn_str=destination_connection_string,
        queue_name=destination_queue_name,
        message_encode_policy = TextBase64EncodePolicy(),
        message_decode_policy = TextBase64DecodePolicy())

    global COUNTER
    while True:
        try:
            if exit_event.is_set():
                logging.info(f"Stopping thread {threadnr}")
                destination_client.close()
                break
            payload = messages.get_nowait()
            logging.debug(f"Thread {threadnr}: Moving id {payload['message']['id']}")
            destination_client.send_message(payload['message']['content'])
            payload['client'].delete_message(payload['message']['id'], payload['message']['pop_receipt'])
            with threadLock:
                COUNTER += 1
        except Empty:
            time.sleep(1)
        except Exception as exception:
            logging.error(f"Error: {exception}")
            continue
    logging.info(f"Thread {threadnr} stopped")

def show_counter():
    max_ticks = 60
    ticks = 0
    while True:
        try:
            ticks += 1
            if ticks >= max_ticks:
                logging.info(f"Total messages moved: {COUNTER}")
                ticks = 0
            if exit_event.is_set():
                logging.info(f"Total messages moved: {COUNTER}")
                logging.info("CTRL+C was pressed, exiting...")
                break
            time.sleep(1)
        except Exception as exception:
            logging.error(f"Error: {exception}")
            continue

def run():
    logging.info("Starting...")
    signal.signal(signal.SIGINT, signal_handler)
    source_client = QueueClient.from_connection_string(conn_str=source_connection_string,
        queue_name=source_queue_name,
        message_encode_policy = TextBase64EncodePolicy(),
        message_decode_policy = TextBase64DecodePolicy())

    for i in range(NR_OF_THREADS):
        worker = Thread(target=handle_queue, args=(i, worker_queue,))
        worker.setDaemon(True)
        worker.start()

    run_counter = Thread(target=show_counter)
    run_counter.setDaemon(True)
    run_counter.start()

    while not exit_event.is_set():
        # Will hang if empty due to https://github.com/Azure/azure-sdk-for-python/issues/29683
        message = source_client.receive_message()
        payload = {
            'message': message,
            'client': source_client
        }
        worker_queue.put(payload)
    worker_queue.join()
    run_counter.join()

if __name__ == "__main__":
    run()
```

**Comment by jalauzon-msft** [comment] 2023-04-03 17:20
Hi @jryberg Johan, thanks for the additional info. Interesting, I would not expect `recevie_message` (singular) to hang on an empty queue. I think the expected behavior is to return a message if there is one or immediately return `None`. Let us investigate that and get back to you.

**Comment by vincenttran-msft** [comment] 2023-05-09 22:47
Hi @jryberg Johan, sorry for the delay! I was finally able to try to reproduce this locally this evening, but unfortunately, I was not able to reproduce this "hanging" behavior for the `receive_message` (singular) API.

With that being said, is there any chance that you could provide a concise code snippet that reliably reproduces this behavior? Otherwise, my recommendation would be to look closely at your threading logic, as I did not use any threading in my attempts in order to isolate the hang to our client code rather than me incorrectly implementing threading logic 😄 

Thanks!

**Closed** 2023-06-03 01:28 UTC
Labels: bug, Storage, Service Attention, customer-reported, no-recent-activity, needs-author-feedback
