### ISSUE TITLE
[Bug] Secret URI not populated for App Configuration Settings using Key Vault References

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/azure-sdk-for-python#20518] opened 2021-09-02 14:38 UTC
### Setup 
- **Package Name**: **`azure-appconfiguration`**
- **Package Version**: **`1.2.0`**
- **Python Version**: **`3.8.3`**

### Describe the bug
- Version **`1.1.1`** would populate the **`uri`** for secret reference configuration in **`value`** field
- However since version **`1.2.0`**, a new type **`SecretReferenceConfigurationSetting`** was introduced. There is no field populated which could help to identify or retrieve the secret

#### Code that works on version **`1.1.1`**

```
from azure.appconfiguration import AzureAppConfigurationClient
from azure.keyvault.secrets import SecretClient
from azure.identity import AzureCliCredential

import json


credential = AzureCliCredential()
config_client = AzureAppConfigurationClient(base_url= APP_CONFIG_URL, credential=credential)
secret_client = SecretClient(vault_url=KEY_VAULT_URL, credential=credential)

app_config = dict()

for namespace in NAMESPACE_FILTER.split(','):
    for config in config_client.list_configuration_settings(key_filter=f'/{namespace}/*', label_filter=LABEL_FILTER):
         if config.content_type == 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8':
             app_config[config.key.split('/')[-1]] = secret_client.get_secret(json.loads(config.value)['uri'].split('/')[-1]).value
         else:
             app_config[config.key.split('/')[-1]] = config.value
```

#### Config returned by version **`1.1.1`**
- Type of config returned - **`azure.appconfiguration._models.ConfigurationSetting`**
- Contents:
```
{
  'additional_properties': {},
  'key': <key>, 
  'label': <label>, 
  'content_type': 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8', 
  'value': '{"uri":<keyvault_uri>}', 
  'last_modified': <last_modified>, 
  'tags': {}, 
  'read_only': False, 
  'etag': <etag>'
}
```

#### Config returned by version **`1.2.0`**
- Type of config returned - **`azure.appconfiguration._models.SecretReferenceConfigurationSetting`**
- Contents:
```
{
  'key': <key>, 
  'label': <label>, 
  'content_type': 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8', 
  'etag': <etag>, 
  'last_modified': <last_modified>, 
  'read_only': False, 
  'tags': {}, 
  'secret_id': None, 
  '_value': '{"secret_uri": null}'
}
```

### Expected behavior
- **`uri`** for the referred secret should be populated so that it can be used to retrieve the secret value using **`SecretClient`**

**Comment by xiangyan99** [comment] 2021-09-02 14:47
Thanks for the feedback, we’ll investigate asap.

**Comment by DhavalShewale** [comment] 2021-09-07 06:53
@xiangyan99 / @YalinLi0312 : Any update on this?

**Comment by xiangyan99** [comment] 2021-09-07 22:53
@DhavalShewale  Thanks for the feedback.

Could you tell us where you get the content:

```py
{
  'key': <key>, 
  'label': <label>, 
  'content_type': 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8', 
  'etag': <etag>, 
  'last_modified': <last_modified>, 
  'read_only': False, 
  'tags': {}, 
  'secret_id': None, 
  '_value': '{"secret_uri": null}'
}
```
?

SecretReferenceConfigurationSetting helps parse the value string and exposes property secret_id which is the uri you mentioned. Also it is a sub-type of ConfigurationSetting. Its value property has same semantic meaning of its parent type.

Thanks.

**Comment by DhavalShewale** [comment] 2021-09-08 12:40
@xiangyan99: Content is basically the `config` returned by `config_client.list_configuration_settings`. I have shared the entire code in the orignal bug report for your ready reference.

In version `1.1.1`, `ConfigurationSetting` was returned for configuration referring key vault. The `value` field was populated as follows:
```
{"uri":"https://<keyvault-name>.vault.azure.net/secrets/<secret-name>"}
```
The value field can then be subsequently parsed to retrieve the secret value from keyvault.

However in version `1.2.0`,  `SecretReferenceConfigurationSetting` is returned for configuration referring key vault. There is no `value` field available in this model and the `secret_id` field is populated as `None`. So there is no way to identify the `secret-it` or `uri` of the keyvault secret.

**Comment by xiangyan99** [comment] 2021-09-09 20:18
Thank you for providing the information @DhavalShewale.

We have figured out the cause. We will update the issue when we have a fix.

**Comment by DhavalShewale** [comment] 2021-09-16 06:30
@xiangyan99 
qq... Do you think this bug report qualifies under the bug bash program as this is a major bug that renders the library version `1.2.0` unusable

**Comment by xiangyan99** [comment] 2021-09-30 23:41
@DhavalShewale sorry for the late update. We are still under discussion how to fix the bug without any data loss. :(

The root cause is when we receive the value 

{"_**uri**_":"https://<keyvault-name>.vault.azure.net/secrets/<secret-id>"}, our SDK wrongly looks for "_**secret_uri**_" rather than "_**uri**_".

It works fine if you save and load the ConfigSetting both using our SDK. But in your case, if the ConfigSetting is created via portal, it does not work correctly.

If your scenario is always using portal to create the setting and using client SDK to consume it, I would suggest you pinning version 1.1.1 as a work around until 1.3 is released.

We will keep you posted about how the fix goes and sorry for the inconvenience.

**Comment by xiangyan99** [comment] 2021-10-21 15:32
@DhavalShewale We have merged the fix. It will be available in next release.

**Closed** 2021-11-12 22:02 UTC
Labels: bug, Client, customer-reported, App Configuration, issue-addressed
