### ISSUE TITLE
IdleTimeoutInMinutes attribute let user can not add udp endpoint

### ISSUE THREAD

**Issue by gotostack** [Azure/azure-sdk-for-python#334] opened 2015-03-19 02:39 UTC
Commit ID: 5c9bde5062d6bae0a35d2761ff63fa64de8576be
ConfigurationSetInputEndpoint will always has the attribute
self.idle_timeout_in_minutes = idle_timeout_in_minutes

then, use this class to add an endpoint to an VM , you will get an exception from the azure services:
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>An idle timeout was specified for endpoint aaaa with protocol udp. Idle timeout cannot be set for endpoints with protocol udp.</Message></Error>

**Comment by gotostack** [comment] 2015-03-19 03:26
But get an exsited endpoint, it has the idle_timeout_in_minutes attribute.
{'protocol': u'udp', 'name': u'udp9011', 'local_port': u'9011', 'load_balanced_endpoint_set_name': u'', 'idle_timeout_in_minutes': 4, 'enable_direct_server_return': False, 'port': u'9011', 'load_balancer_probe': None}

**Comment by huguesv** [comment] 2015-03-19 18:01
The reason you are getting 4 when querying is because the class initializes the field to 4, and the xml deserializer doesn't see the xml element in the response, so it doesn't touch the field, leaving it set to 4.

It would be better to have the class initialize the field to 4, except for the fact that the deserializer looks at the (default) value of each field to determine what type each field is.  If it's set to None, it doesn't know so it stores it as a string.  Not that great either.

I think what you should do in this case is set the value to None when creating the endpoint, and ignoring the value when querying, since it doesn't apply for udp.

We're working towards a solution that will obsolete the current serialization/deserialization code.  For now we just have to put up with the current deficiencies for a bit longer :(

**Comment by gotostack** [comment] 2015-03-23 05:09
Hi, I have a small solution here:
I change the code ：
https://github.com/Azure/azure-sdk-for-python/blob/master/azure/servicemanagement/__init__.py#L2780
to L2785
            xml += _XmlSerializer.data_to_xml(
                [('Protocol', endpoint.protocol),
                 ('EnableDirectServerReturn',
                  endpoint.enable_direct_server_return,
                  _lower),
                 ('IdleTimeoutInMinutes', endpoint.idle_timeout_in_minutes)])
to
            attrs = [('Protocol', endpoint.protocol),
                     ('EnableDirectServerReturn',
                      endpoint.enable_direct_server_return,
                      _lower)]
            if endpoint.protocol.lower() == 'tcp':
                attrs.append(('IdleTimeoutInMinutes', endpoint.idle_timeout_in_minutes))
            xml += _XmlSerializer.data_to_xml(attrs)

**Comment by zooba** [comment] 2015-04-21 16:52
The problem here is that you can't do this:

```python
rdp_ep2 = ConfigurationSetInputEndpoint()
rdp_ep2.name = "RDP_UDP"
rdp_ep2.port = 3389
rdp_ep2.local_port = 3389
rdp_ep2.protocol = "UDP"
net_config.input_endpoints.input_endpoints.append(rdp_ep2)
```

I haven't set the idle timeout, and yet I can't create a VM with this endpoint because the XML being sent has the property set. gotostack's fix handles this fine, but the problem is more general:

```python
os_config = WindowsConfigurationSet(VM_NAME, admin_username='...', admin_password='...')
os_config.domain_join = None
os_config.win_rm = None
```

If I don't reset `domain_join` and `win_rm`, then the create request fails because they aren't initialized properly (i.e. "you haven't specified a domain").

We need to better handle unset values to avoid generating the XML for them. There is far too much guesswork required right now.

**Comment by lmazuel** [comment] 2019-04-09 22:03
This package is now deprecated, and we do not plan any update on it, hence closing it.
Feel free to contribute to it, we're otherwise still happy with contributions :)
Thanks,

**Closed by lmazuel** 2019-04-09 22:03 UTC
Labels: ASM
