### ISSUE TITLE
azure3.0 import error

### ISSUE THREAD

**Issue by lx1054331851** [Azure/azure-sdk-for-python#2042] opened 2018-02-22 07:23 UTC
my code is:
```python
from azure.storage.blob import ContentSettings
```
error occurred as below:
```python
 File "C:/Users/lx105/PycharmProjects/spider/WGSN/WGSNSpider.py", line 7, in <module>
    from azure.storage.blob import ContentSettings

  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\azure\storage\blob\__init__.py", line 6, in <module>
    from .appendblobservice import AppendBlobService

  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\azure\storage\blob\appendblobservice.py", line 30, in <module>
    from ._deserialization import (

  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\azure\storage\blob\_deserialization.py", line 18, in <module>
    from azure.storage.common._deserialization import (

ImportError: cannot import name '_to_int'
```

I can not find module '_to_int' in the '_deserialization' file.

**Comment by lmazuel** [comment] 2018-02-22 21:06
@zezha-msft that's actually in the storage repo. Do you know why?
Thanks,

**Comment by zezha-msft** [comment] 2018-02-23 01:25
Thanks @lmazuel for tagging me.

Hi @lx1054331851, it is a [known issue](https://github.com/Azure/azure-cosmosdb-python/issues/19) caused by the cosmosdb sdk depending on an older version of azure-storage-common. I'll follow up with them to get this resolved ASAP. Thanks!

**Comment by lmazuel** [comment] 2018-02-23 18:29
Closing this issue, @lx1054331851 please follow resolution on the issue @zezha-msft mentionned. Thanks!

**Closed by lmazuel** 2018-02-23 18:29 UTC
Labels: Bug, Storage
