### ISSUE TITLE
 azure-mgmt-storagecache

### ISSUE THREAD

**Issue by taheni149** [Azure/azure-sdk-for-python#10526] opened 2020-03-26 13:10 UTC
- **Package Name**:  azure-mgmt-storagecache
- **Package Version**:  0.2.0
- **Operating System**: RHEL 7.6
- **Python Version**: 2.7.3

**Describe the bug**
When we install the module with python installed with the system:
which python: /usr/bin/python
pip install azure-mgmt
pip install azure-mgmt-storagecache
azure.mgmt.storagecache  
=> pass successfully

But when we install the package with python installed on central path, 
The package  installed successfully without any error message. But we have the following issue:

$ python
Python 3.7.2 (default, Mar 18 2019, 08:03:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.mgmt.storagecache import StorageCacheMgmtClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.storagecache'

Checking with the command :

$ pip show azure.mgmt.storagecache
Name: azure-mgmt-storagecache
Version: 0.2.0
Summary: Microsoft Azure MyService Management Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: <path>/3.7.2/rh70_64/modules
Requires: msrestazure, msrest, azure-common
Required-by:

And when I checked  the path  ls  <path>/3.7.2/rh70_64/modules/azure/mgmt, I don’t find the folder “storagecache” 

Thanks & Best Regards
Taheni

**Comment by kaerm** [comment] 2020-03-26 17:43
@taheni149 thanks for contacting us, tagging the right team to take a look at this: @nickzhums

**Comment by dw511214992** [comment] 2020-03-27 02:15
Hi @taheni149 
I find the python you filled in the issue is 2.7.3, but the version you showed in command is 3.7.2. So please make sure you use corresponding pip with python.

Also, Please use `StorageCacheManagementClient` instead of `StorageCacheMgmtClient`. e.g.
```
 from azure.mgmt.storagecache import StorageCacheManagementClient
```
Please try again and let me know the result.
Thank you.

**Comment by blueww** [comment] 2020-09-18 04:07
@dw511214992

As the customer has not responds for a long time, do you mind to close it.
And as this issue is for StorageCache SDK, but not storage SDK, do you think we should add a new tag for “StorageCache", to separate the storageCache issues from Storage issues?

**Comment by lilyjma** [comment] 2021-01-13 21:25
Since there hasn't be any activity in this issue for a while, I'll close it for now. @taheni149, if you still need help/have questions after trying out the suggestion above, please reopen the issue.

**Closed by lilyjma** 2021-01-13 21:25 UTC
Labels: Mgmt, Service Attention, Storage, bug, customer-reported
