### ISSUE TITLE
Metadata is returned as 'None' when querying metrics with `filter` parameter

### ISSUE THREAD

**Issue by kshilovskiy** [Azure/azure-sdk-for-python#21281] opened 2021-10-15 11:26 UTC
- **Package Name**: azure-monitor-query
- **Package Version**:  1.0.0
- **Operating System**: Mac OS 11.4
- **Python Version**: 3.9.7

**Describe the bug**
I am trying to get the eventhub namespace metrics split by the eventhub name. Therefore I am using `*` as the filter value: `entityname eq '*'`.
The returned data is indeed split by the entity name. However there is no metadata provided. So I am not able to understand 
what entities the values belong too.

**To Reproduce**
I am using this code:
```python
metrics_uri = os.environ['METRICS_RESOURCE_URI']

response = client.query_resource(
    metrics_uri,
    metric_names=["IncomingMessages"],
    timespan=timedelta(days=1),
    granularity=timedelta(hours=24),
    filter="entityname eq '*'",
    aggregation='Total'
)

for metric in response.metrics:
    print(metric.name + ' -- ' + metric.display_description)
    for time_series_element in metric.timeseries:
        print(f"Metadata {time_series_element.metadata_values}")
        for metric_value in time_series_element.data:
            print(f"{metric_value.timestamp} -- {metric_value.total}")
```
`METRICS_RESOURCE_URI` is the the eventhub namespace.

**Expected behavior**
Metadata is returned and contains the name of the event hub.

**Screenshots**
Here is the output from the above code

![image](https://user-images.githubusercontent.com/1021893/137479792-6a26de20-4196-4211-af89-efbb74dfd422.png)

**Additional context**
The metadata is returned correctly with Azure CLI

**Comment by rakshith91** [comment] 2021-11-01 07:33
Hi @kshilovskiy, Thanks for reporting the issue - it will be fixed in this PR https://github.com/Azure/azure-sdk-for-python/pull/21513 and will be released in the upcoming release next week.

**Comment by rakshith91** [comment] 2021-11-03 00:23
@kshilovskiy The issue is addressed and will be pushed to release early next week

**Closed** 2021-11-10 04:02 UTC
Labels: question, Client, customer-reported, issue-addressed, Monitor - Query
