### ISSUE TITLE
Errors noticed with latest versions of azure-identity + azure-keyvault-keys

### ISSUE THREAD

**Issue by rachari** [Azure/azure-sdk-for-python#8316] opened 2019-10-31 13:46 UTC
On installing the latest versions of azure-identity and azure-identity, which install azure-core as a dependency, I noticed the following error message:-

**ModuleNotFoundError: No module named 'azure.core.pipeline.policies.authentication'**

However, this doesn't happen if the following versions are installed -
azure-core==1.0.0b4
azure-identity==1.0.0b4
azure-keyvault-keys==4.0.0b4

So apparently, something is broken in the latest versions of mentioned packages, most probably in azure-core

**Comment by kaerm** [comment] 2019-10-31 20:05
@rachari thanks for reporting this! Our team will take a look at this //cc: @chlowell

**Comment by lmazuel** [comment] 2019-10-31 20:23
Hi @rachari 
`azure-core` and `azure-identity` 1.0 are designed to work on the future `azure-keyvault-keys` 4.0.0 (all versions stable).

There was indeed some breaking changes from b4 version to stable version, we are aware of them and have been made carefully. The one you mention was for instance declared in the `azure-core` ChangeLog as a coming breaking changes.

While you while at some preview packages (in your case KV), please use them in sync (all b4), and do not try a stable `azure-core` with a preview `azure-keyvault-keys`. 

You can workaround this in the meantime:
```shell
pip install azure-core==1.0.0b4 azure-keyvault-keys==4.0.0b4 azure-identity==1.0.0b4
```

I'm closing this issue since the root cause is known, please feel free to open a new one once the stable release of KV is done is still encounter issues.

Thank you!

**Closed by lmazuel** 2019-10-31 20:23 UTC
Labels: Azure.Core, Azure.Identity, Client, customer-reported
