### ISSUE TITLE
inconsistent encoding behaviour in QueueClient.send_message()

### ISSUE THREAD

**Issue by F-Schmidt1** [Azure/azure-sdk-for-python#12204] opened 2020-02-19 13:34 UTC
### Which service(blob, file, queue) does this issue concern?
Queue

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-queue==12.1.0

#### Repro:
Following the documentation at https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-queue#sending-messages

```
from azure.storage.queue import QueueClient
queue = QueueClient.from_connection_string(conn_str="<connection_string>", queue_name="my_queue")
queue.send_message('msg')
queue.send_message('msg2')
queue.send_message('msg10')
```
The first message shows up correctly, while the second message seems to not be encoded correctly. This happens every time a queue message with the content 'msg2' is sent.

![queue-msg](https://user-images.githubusercontent.com/61054913/74838576-19807b00-5324-11ea-9ab0-752141e351b0.PNG)

EDIT:
When viewing the messages in the storage explorer, it is stated that the messages are stored  'without encoding'. 
I tried to enforce Base64 encoding, by ammending the call to the QueueClient:
```
from azure.storage.queue import QueueClient, TextBase64EncodePolicy
queue = QueueClient.from_connection_string(conn_str="<connection_string>", queue_name="my_queue", encode_policy=TextBase64EncodePolicy)
```
However, this does not affect the encoding of the messages. What am i missing?

**Comment by xiafu-msft** [comment] 2020-07-10 18:28
Hi @F-Schmidt1 

Sorry about the late response. The encoding doesn't mean that the text would be displayed in the encoded format, if you want your text to be encrypted, you should [use encryption](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-queue/tests/test_queue_encryption.py#L75) instead of encoding. Encoding is just for when the queue message is transferred in the network. 

Since it looks like this is not a bug, we will close it for now. Feel free to reopen it if you have any questions or concern!

**Closed by xiafu-msft** 2020-07-10 18:28 UTC
Labels: Client, Storage, customer-reported, question
