### ISSUE TITLE
i can't use python sdk for chinese azure

### ISSUE THREAD

**Issue by LeiyuanBlog** [Azure/azure-sdk-for-python#17937] opened 2021-04-09 07:00 UTC
soure code:
    AZURE_AUTH = settings.AZURE_AUTH.get(area)
    tenant_id = AZURE_AUTH.get("AZURE_TENANT_ID")
    client_id = AZURE_AUTH.get("AZURE_CLIENT_ID")
    client_secret = AZURE_AUTH.get("AZURE_CLIENT_SECRET")
    credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
    nsg_client = NetworkManagementClient(credential, self.subscription_id, base_url=auth.AZURE_ENDPOINT)
    nsg = nsg_client.network_security_groups.list_all()

error logs:
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS500011: The resource principal named https://management.azure.com was not found in the tenant named {***********}. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**Comment by kristapratico** [comment] 2021-04-09 15:53
Closing this as it is an exact duplicate of #17936.

**Closed by kristapratico** 2021-04-09 15:53 UTC
Labels: customer-reported, needs-triage, question
