### ISSUE TITLE
'InteractiveBrowserCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-python#9756] opened 2020-02-06 22:30 UTC
- **Package Name**: azure-mgmt-authorization, azure.identity
- **Package Version**: 0.60.0, 1.2.0
- **Operating System**: Windows 10 Enterprise
- **Python Version**: 3.7.3

**Describe the bug**
I am unable to use azure.identity.InteractiveBrowserCredential to authenticate to azure.mgmt.authorization.AuthorizationManagementClient.

**To Reproduce**
1. Run the following code:

```
# This script requires the following modules:
#	python -m pip install azure-identity
#	python -m pip install azure-mgmt-authorization
#
# This script runs under Python 3.4 or later.

from azure.identity import InteractiveBrowserCredential
from azure.mgmt.authorization import AuthorizationManagementClient
from azure.mgmt.authorization.models import RoleAssignmentCreateParameters

import uuid

# The ID of your Azure subscription. You can find this in the Azure Dashboard under Home > Subscriptions.
subscription_id = "INSERT SUBSCRIPTION ID"

resource_id = "INSERT RESOURCE ID"

interactive_credential = InteractiveBrowserCredential()

def create_role_assignment (resource_id) :
# See:
# https://github.com/Azure-Samples/compute-python-msi-vm#role-assignement-to-the-msi-credentials
	authorization_client = AuthorizationManagementClient(interactive_credential, subscription_id)

# Get the ID of the Contributor role.
	role_name = 'Contributor'
	roles = list(authorization_client.role_definitions.list(
		resource_id,
		filter="roleName eq '{}'".format(role_name)
	))
	assert len(roles) == 1
	contributor_role = roles[0]

create_role_assignment (resource_id)
```

Output:
```
Traceback (most recent call last):
  File "issue.txt", line 34, in <module>
    create_role_assignment (resource_id)
  File "issue.txt", line 29, in create_role_assignment
    filter="roleName eq '{}'".format(role_name)
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\paging.py", line 143, in __next__
    self.advance_page()
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Program Files (x86)\Python\Lib\site-packages\azure\mgmt\authorization\v2018_01_01_preview\operations\_role_definitions_operations.py", line 287, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "C:\Program Files (x86)\Python\Lib\site-packages\msrest\pipeline\requests.py", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'InteractiveBrowserCredential' object has no attribute 'signed_session'
```

**Expected behavior**
I am able to use azure.identity.InteractiveBrowserCredential to authenticate to azure.mgmt.authorization.AuthorizationManagementClient.

**Additional context**
Possibly related to: https://github.com/Azure/azure-sdk-for-python/issues/9725
That is, possibly azure.mgmt.authorization does not support azure.identity yet?

**Comment by chlowell** [comment] 2020-02-06 22:58
> **Additional context**
> Possibly related to: #9725
> That is, possibly azure.mgmt.authorization does not support azure.identity yet?

That's correct, no `azure-mgmt-*` accepts `azure-identity` credentials. Work to change that is tracked by #9310. I'll close this is a duplicate of #9725. Please feel free to open another issue if you encounter other problems.

**Closed by chlowell** 2020-02-06 22:58 UTC
Labels: Mgmt
