### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.62', 52098), raddr=('52.239.140.10', 443)>

### ISSUE THREAD

**Issue by lukin0110** [Azure/azure-sdk-for-python#14565] opened 2020-10-16 14:59 UTC
- **azure-storage-blob**: 
- **12.5.0**: 
- **Linux 39a68fd14e65 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux**:
- **Python 3.8.3**: 

**Describe the bug**
We've enabled a few warning filters in our application with `warning.simplefilter` and we're seeing a python warning when we download a file from the blob storage. `ResourceWarning: unclosed <ssl.SSLSocket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.62', 52098), raddr=('52.239.140.10', 443)>`

**To Reproduce**
```
client = BlobServiceClient.from_connection_string("<connection string here>").get_blob_client(container="<container name>", blob="<blob name>")
raw_data = client.download_blob().readall()
with gzip.open(BytesIO(raw_data), "rb") as fh:
    data = pickle.load(fh)  # noqa: S301
```

**Expected behavior**
No warning or a proper way to close the stream.

**Screenshots**
NA

**Additional context**
NA

**Comment by xiafu-msft** [comment] 2020-10-16 22:13
Hi @lukin0110 

So you also saw this warning when only executing this two lines?
```
client = BlobServiceClient.from_connection_string("<connection string here>").get_blob_client(container="<container name>", blob="<blob name>")
raw_data = client.download_blob().readall()
```

**Comment by lukin0110** [comment] 2020-10-17 09:46
Hi @xiafu-msft 

The correct way to reproduce is:
```
import warnings
from azure.storage.blob import BlobServiceClient

warnings.simplefilter("default", ResourceWarning)

CONNECTION = "<connection string here>"
CONTAINER = "<container name here>"
BLOB_NAME = "<blob name here>"

client = BlobServiceClient.from_connection_string(CONNECTION).get_blob_client(container=CONTAINER, blob=BLOB_NAME)
raw_data = client.download_blob().readall()
```

**Comment by xiafu-msft** [comment] 2020-10-20 06:28
Hi @lukin0110 

Thanks for your code!
can you try this and see if you still get this warning:
```
with BlobServiceClient.from_connection_string(CONNECTION).get_blob_client(container=CONTAINER, blob=BLOB_NAME) as client:
    raw_data = client.download_blob().readall()
```

**Comment by lukin0110** [comment] 2020-10-20 07:56
Heh @xiafu-msft,

Using it as a context is still showing the warning.

**Comment by xiafu-msft** [comment] 2020-10-21 06:20
Hi @lukin0110 

Thanks for reporting this issue. I was able to reproduce. 
The problem is we created a session and didn't close it https://github.com/Azure/azure-sdk-for-python/blame/master/sdk/core/azure-core/azure/core/pipeline/transport/_requests_basic.py#L244

@xiangyan99 could you please find people to confirm we want to close the session before return.

**Comment by lukin0110** [comment] 2020-10-21 06:59
Thanks for the quick follow up!

**Comment by tasherif-msft** [comment] 2021-01-29 22:42
Hi @lukin0110, this is actually intended behavior. When you run 
```
import warnings
from azure.storage.blob import BlobServiceClient

warnings.simplefilter("default", ResourceWarning)

CONNECTION = "<connection string here>"
CONTAINER = "<container name here>"
BLOB_NAME = "<blob name here>"

client = BlobServiceClient.from_connection_string(CONNECTION).get_blob_client(container=CONTAINER, blob=BLOB_NAME)
raw_data = client.download_blob().readall()
```
You're creating a blob client from your BlobServiceClient and not closing any sessions.
If you want to ensure all sessions are closed, you must close your parent client as well.
You can achieve this by doing:
```
BlobServiceClient.from_connection_string(CONNECTION) as sc:
    bc = sc.get_blob_client(container="test", blob="blob.txt")
    raw_data = client.download_blob().readall()
```
This ensures that all session are closed since the child class is inheriting the same session.

You can also do:
```
bsc = BlobServiceClient.from_connection_string(CONNECTION)
bc = sc.get_blob_client(container="test", blob="blob.txt")
raw_data = client.download_blob().readall()
bsc.close()
```
Hope this helps! 
Let me know if there anything else needed

**Comment by lukin0110** [comment] 2021-02-01 23:19
@tadam-msft thanks for clarifying. I've applied your suggestion. The resource warning is not appearing anymore.

**Comment by tasherif-msft** [comment] 2021-02-01 23:23
Hi @lukin0110! fantastic :)

**Closed by tasherif-msft** 2021-02-01 23:23 UTC
Labels: Storage, customer-reported
