### ISSUE TITLE
VirtualMachine Update to change tags is slow to complete

### ISSUE THREAD

**Issue by zinkj** [Azure/azure-sdk-for-python#10321] opened 2020-03-16 20:08 UTC
- **Package Name**: azure-mgmt-compute
- **Package Version**: 11.1.0
- **Operating System**: Windows 10
- **Python Version**: 3.6.8

**Describe the bug**
Setting tags on a Virtual Machine in azure always takes ~31 seconds. In the UI and from powershell this is a 1-2 second operation

**To Reproduce**
1. Have an azure VM configured with or without tags.
2. Use the python azure-mgmt-compute operation virtual_machines.update
3. Provide update parameters with updated tags only.

**Expected behavior**
Tags are updated similar to UI or Powershell

**Additional context**
I've added some logging around this to make sure it was not the wait method of the poller object polling too slowly:

```set_tag_task = self._compute_client.virtual_machines.update(Const.RESOURCE_GROUP_NAME, name, update_params)
self.logger.info("Update Request received {}".format(set_tag_task.status()))
while set_tag_task.status() != "Succeeded":
   self.logger.info(set_tag_task.status())
   time.sleep(1)
self.logger.info("Task complete {}".format(set_tag_task.status()))


[2020-03-16 15:59:49] InstanceManager: INFO - Update Request received InProgress
[2020-03-16 15:59:49] InstanceManager: INFO - InProgress
...
[2020-03-16 16:00:19] InstanceManager: INFO - InProgress
[2020-03-16 16:00:20] InstanceManager: INFO - Task complete Succeeded
[2020-03-16 16:00:20] InstanceManager: INFO - Instances ['demo01'] successfully tagged

**Comment by Drewm3** [comment] 2020-03-16 23:35
@kaerm, if the python SDK is operating significantly slower than PowerShell or UI then I believe the issue needs to be first reviewed by the python SDK team because the issue sounds to be specific to the SDK as compared to the backend service. If the issue was in the backend service, then we would see similar times across PowerShell, UI and the python SDK.

**Comment by kaerm** [comment] 2020-03-17 01:40
@nickzhums to the review then :)

**Comment by nickzhums** [comment] 2020-03-17 03:40
@RodgeFu could you let someone take a look to see why the SDK call is slower than Powershell / UI ? thanks

**Comment by RodgeFu** [comment] 2020-03-17 03:46
Crystal can help to have a look. thanks.

**Comment by RodgeFu** [comment] 2020-03-18 09:41
assign to crystal to have some initial investigation. thanks.

**Comment by chunyu3** [comment] 2020-03-20 01:53
I am investigating.

**Comment by xiangyan99** [comment] 2021-11-30 00:35
@chunyu3 any updates?

**Closed** 2021-12-22 16:03 UTC
Labels: bug, Compute, Mgmt, customer-reported, issue-addressed

**Comment by sg3-141-592** [comment] 2022-12-11 06:16
I think this needs re-opening. The issue is still present of slow tagging. As an example, from a simple Python program I have that adds a tag I see the following times to apply.

It can be as fast as 1-2 seconds for a tag, but it often takes 30 seconds plus.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/5122866/206889317-6111af3b-ca89-48b6-9185-befb7aa9c11d.png">

/unresolve
