### ISSUE TITLE
Unable to Pickle ServiceBus Message Object

### ISSUE THREAD

**Issue by dgokeeffe** [Azure/azure-sdk-for-python#12902] opened 2020-08-05 06:35 UTC
- **Package Name**: azure-servicebus
- **Package Version**: 7.0.0.0b4
- **Operating System**: Red Hat 4.8.5-39
- **Python Version**: 3.6.8

**Describe the bug**
When attempting to pickle.dump() an array of Message objects a TypeError is raised.

**To Reproduce**
1. Attempt to pickle a Message object

**Expected behavior**
The object is pickled correctly

**Screenshots**
```
import pickle
from azure.servicebus import Message

msgs = [Message(body={"test"})]
pickle.dump(msgs, open("./dump", "wb")
```
```
File "stringsource", line 2, in uamqp.c_uamqp.StringValue.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by lmazuel** [comment] 2020-08-05 18:01
Closing as duplicate of https://github.com/Azure/azure-sdk-for-python/issues/12901

**Closed by lmazuel** 2020-08-05 18:01 UTC
Labels: customer-reported, needs-triage, question
