### ISSUE TITLE
DefaultAzureCredential fails with timeout shelling out to az

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#15319] opened 2020-11-13 19:49 UTC
- **Package Name**: azure.identity
- **Package Version**: 1.4.1
- **Operating System**:Linux
- **Python Version**: 3.7.3

**Describe the bug**
We are routinely seeing failures using azure.identity.DefaultAzureCredential.
We try to wrap operations in retry loops where we can, but this is impractical
with paging objects when the lists are long.

The exception itself is also puzzling. Is azure.identity.DefaultAzureCredential
really shelling out to az? If so, what is az doing? Is there an alternate
credential class that we should be using?

Here is an example:

self.az_compute is azure.mgmt.compute.ComputeManagementClient
    File REDACTED
      return list(self.az_compute.virtual_machines.list(resource_group))
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/paging.py", line 122, in __next__
      return next(self._page_iterator)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/paging.py", line 74, in __next__
      self._response = self._get_next(self.continuation_token)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/mgmt/compute/v2020_06_01/operations/_virtual_machines_operations.py", line 1041, in get_next
      pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 211, in run
      return first_node.send(pipeline_request)  # type: ignore
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 71, in send
      response = self.next.send(request)
    [Previous line repeated 1 more time]
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/policies/_retry.py", line 436, in send
      response = self.next.send(request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_base.py", line 69, in send
      _await_result(self._policy.on_request, request)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
      result = func(*args, **kwargs)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
      self._token = self._credential.get_token(*self._scopes)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/identity/_credentials/default.py", line 140, in get_token
      return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
    File "/REDACTED/venv/lib/python3.7/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token
      raise ClientAuthenticationError(message=message)
  azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
  Attempted credentials:
        AzureCliCredential: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 10 seconds

**To Reproduce**
I don't have a single, deterministic case for this, but any application which runs for hours doing Azure ops will eventually hit this problem and choke.

**Comment by chlowell** [comment] 2020-11-13 21:28
Yes, it's really shelling out to `az get-access-token`, as captured in the error message. There's clearly significant overhead in that approach; the feature was designed for low intensity scenarios like local development. I'd be surprised to see it take more than 10 seconds in such a scenario, but of course at a high enough level of utilization or low enough level of resources a machine may not be able to beat the deadline.

> Is there an alternate credential class that we should be using?

It depends on your application. There are more performant credentials for authenticating users and service principals, but only AzureCliCredential (or DefaultAzureCredential, which uses it) can authenticate via the CLI. Does your scenario require the CLI?

**Comment by jazelenk** [comment] 2020-11-13 21:48
We do not require the CLI. When we use UAMI assigned to the VM for auth, we use ManagedIdentityCredential. For user-based auth, we assume that the user has already done "az login --use-device-code", and we use DefaultAzureCredential.

**Comment by chlowell** [comment] 2020-11-13 22:03
You could use [DeviceCodeCredential](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.5.0/azure.identity.html#azure.identity.DeviceCodeCredential) instead. That would be much faster. Is it okay to send users through the device code flow every time they run your application?

**Comment by jazelenk** [comment] 2020-11-14 09:53
No, it's not okay to make them re-auth every time they run. We want to re-use the auth they already have from previous logins.

**Comment by jazelenk** [comment] 2020-11-14 10:38
For us, this is complicated by the fact that conflicting dependencies prevent us from having azure.cli in our application's virtualenv.

**Comment by chlowell** [comment] 2020-11-16 16:32
In the last azure-identity beta (1.5.0b2) DeviceCodeCredential can use a persistent cache so you don't need interactive authentication every run:
```py
DeviceCodeCredential(enable_persistent_cache=True, allow_unencrypted_cache=True)
```
`allow_unencrypted_cache` configures the credential to fall back to using a plaintext file when encryption isn't possible, e.g. in an SSH session (libsecret provides the encryption).

We plan to revise this configuration API before our next stable release, so although it offers a workaround for this problem today, you would need to update your code before moving to 1.6.0.

**Comment by jazelenk** [comment] 2020-11-16 21:20
Oooh, thanks! That sounds like what I want.

**Comment by chlowell** [comment] 2020-12-09 22:31
Were you able to work around this with DeviceCodeCredential?

**Comment by jazelenk** [comment] 2020-12-10 21:47
While waiting for the new identity module, I worked around this by subclassing azure.identity._credentials.azure_cli.AzureCliCredential and overloading get_token() to do retries. It's not perfect, but it got us out of the weeds.

**Comment by chlowell** [comment] 2021-05-13 15:40
I'm closing this issue because azure-identity 1.6.0 is available now with a stable API for persistent token caching (the [user_authentication sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/samples/user_authentication.py) demonstrates it). AzureCliCredential doesn't have this new API (it still invokes the CLI for every token request) but DeviceCodeCredential does, allowing you to authenticate a user with the same flow as "az login --use-device-code" and save that user's authentication data for future use. Thanks for opening this issue! Please open another if you encounter another problem, or reopen this one if I misunderstand your requirements.

**Closed by chlowell** 2021-05-13 15:40 UTC
Labels: Azure.Identity, Client, question
