### ISSUE TITLE
Error "IMDS endpoint unavailable", although it's available

### ISSUE THREAD

**Issue by TiunovNN** [Azure/azure-sdk-for-python#11757] opened 2020-06-02 10:39 UTC
- **Package Name**: azure-identity
- **Package Version**: 1.3.1
- **Operating System**: Ubuntu 14/Ubuntu18
- **Python Version**: 3.6.5

**Describe the bug**
Some time after the service starts, the error appears and is thrown out every time until the service restarts.

`azure.identity._exceptions.CredentialUnavailableError: IMDS endpoint unavailable`

**To Reproduce**
```python
"""
# requirements.txt
azure-identity==1.3.1
aiohttp==3.6.2
aioresponses==0.6.4
"""

import pytest
import aioresponses
import asyncio
from azure.identity import CredentialUnavailableError
from azure.identity.aio._credentials.managed_identity import ImdsCredential


class Endpoints:
    # https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http
    IMDS = "http://169.254.169.254/metadata/identity/oauth2/token"


async def test_ctx():
    with aioresponses.aioresponses() as m:
        m.get(Endpoints.IMDS, payload=dict(foo='bar'))
        m.get(
            'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=scope',
            status=400)
        cred = ImdsCredential()

        with pytest.raises(CredentialUnavailableError):
            resp = await cred.get_token('scope')

        # From this moment forward, error "IMDS endpoint unavailable" will be thrown out permanently
        m.get(Endpoints.IMDS, payload=dict(foo='bar'))
        m.get(
            'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=scope',
            status=200)
        resp = await cred.get_token('scope')


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ctx())
```

**Expected behavior**
Recover after this error and work properly.

**Additional context**
Possible, This error occurred after this fix: [Issue #10488](https://github.com/Azure/azure-sdk-for-python/issues/10488)

I believe the best solution is to check `if not self._endpoint_available` [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py#L106)

**Comment by chlowell** [comment] 2020-06-03 00:40
This is the intended behavior. Your code simulates a VM that has no managed identity, for example because the feature is disabled on that VM. We didn't want an instance of the credential to keep attempting to authenticate in that scenario. If it were to try again and succeed, that could cause unexpected behavior such as a chained credential changing its method of authentication between requests. I suggest creating another instance if you want to try authenticating with managed identity again without restarting your application.

**Comment by TiunovNN** [comment] 2020-06-03 06:00
@chlowell, Thanks for answer!

> Your code simulates a VM that has no managed identity, for example because the feature is disabled on that VM

Indeed, the problem has occurred on a VM with enabled managed identity. I don't know why, but azure cloud gave response with error. Other services are continuing work with managed identity at the same time.

> We didn't want an instance of the credential to keep attempting to authenticate in that scenario.

I think this solution is good for short-lived program, but it is bad for long-lived program such as web-service.

>  I suggest creating another instance

In this case, we have to recreate service client, and his pipeline. Is there a better solution?

**Comment by chlowell** [comment] 2020-06-08 23:03
> Indeed, the problem has occurred on a VM with enabled managed identity. I don't know why, but azure cloud gave response with error. Other services are continuing work with managed identity at the same time.
> 

You mean the endpoint responded 400 after working for some period of time, then later responded 200 again, without any changes to the VM's configuration?
 
> In this case, we have to recreate service client, and his pipeline. Is there a better solution?
>
I think it's the best workaround for now. Anything else would require modifying the internal state of the credential or client.

**Comment by TiunovNN** [comment] 2020-06-09 08:51
> You mean the endpoint responded 400 after working for some period of time, then later responded 200 again, without any changes to the VM's configuration?

Yes. This is exactly what I meant

> Anything else would require modifying the internal state of the credential or client.

```python
# azure.identity._credentials.managed_identity.ImdsCredential.get_token
            try:
                token = await self._client.request_token(scopes, method="GET", params=params)
            except HttpResponseError as ex:
                # 400 in response to a token request indicates managed identity is disabled,
                # or the identity with the specified client_id is not available
                if ex.status_code == 400:
                    self._endpoint_available = False  # <--- None
```
Why are you assign `False` to `self._endpoint_available`? It has been verified that the endpoint is available at startup.

**Comment by chlowell** [comment] 2020-06-09 16:13
We assign that variable `False` to prevent the credential sending requests we expect to fail. With managed identity disabled the endpoint is "available" in that it responds, however it always responds 400 to token requests. `_identity_available` would perhaps be a better name.

How often do you see this transient 400 behavior?

**Comment by chlowell** [comment] 2020-07-21 19:13
I'm closing this issue because the problem is apparently a transient fault of the endpoint. To make the credential resilient against this particular fault without affecting its behavior in other scenarios, we would need a way to distinguish it from the endpoint having no configured identity. If you continue to see this failure, please reopen this issue with details of the endpoint's response. The easiest way to get that information from our library is to enable debug logging on the credential with `logging_enable=True`, for example `ManagedIdentityCredential(logging_enable=True)`.
That will log the credential's requests and their responses at `DEBUG` level. Please note that means secrets such as access tokens will be logged in plaintext.

**Closed by chlowell** 2020-07-21 19:13 UTC
Labels: Azure.Identity, Client, customer-reported, question
