### ISSUE TITLE
Backup Usage Summaries of VaultRecoveryServicesBackup gives End of Paging error

### ISSUE THREAD

**Issue by shreyasmoolya09** [Azure/azure-sdk-for-python#12569] opened 2020-07-16 05:20 UTC
- **Package Name: azure-mgmt-recoveryservicesbackup**: 
- **Package Version: 0.8.0**: 
- **Operating System: windows10**:
- **Python Version: 3.8**: 

**Describe the bug**
I have created a `RecoveryServicesBackupClient`. I am then using `iterator_object = backup_usage_summaries.list(resource_group_name, vault_name)` method to create an iterator object. On Using `next(iterator_object)` to iterate through it, it gives me an End of Paging error.

I also tried iterating using a for loop and tried printing the items. The execution stops after execution of for loop without any error. 

Any azure developer can help resolve this bug?
**To Reproduce**

```
credentials = ServicePrincipalCredentials(tenant, client_id, client_secret)
subscription_client = SubscriptionClient(credentials=credentials)
subscriptions_list = subscription_client.subscriptions.list()
iterable = next(subscriptions_list)
subscription_id = iterable.subscription_id
recovery_backup_client = RecoveryServicesBackupClient(credentials=credentials, subscription_id=subscription_id)
iteraton_1 = recovery_backup_client.backup_usage_summaries.list(resource_group_name, vault_name)
next(iteration_1)
End of Paging
```

**Expected behavior**
next(iteration_1) should give an iterable and can be printed

**Comment by pvrk** [comment] 2020-07-16 19:01
@pratimaupadhyay02: Can you please take a look?

**Comment by pvrk** [comment] 2020-09-24 10:53
Sincere apologies for the delay. Investigation was delayed due to other priorities and will be taken up very soon.

**Comment by mepand** [comment] 2021-03-21 16:37
Team has started investigating this. Will update the thread once we have ETA for the fix.

**Comment by akshayneema** [comment] 2021-04-23 05:42
Hey @shreyasmoolya09! The backup_usage_summaries API requires a filter string to be passed for it to return the correct output. If the filter string is not provided it returns an empty list. In your case, it is returning an empty list, therefore on doing _next(iteration_1)_ it gives _StopIteration: End of paging_ error which means that it has already reached the end of the iterator object as the list was empty. 

To solve this issue please try passing the appropriate filter string also. For example -

- Use _recovery_backup_client.backup_usage_summaries.list(resource_group_name, vault_name, "type eq 'BackupProtectedItemCountSummary'")_ to get Protected Item Count Summary for that vault. 

- Use _recovery_backup_client.backup_usage_summaries.list(resource_group_name, vault_name, "type eq 'BackupProtectionContainerCountSummary'")_ to get Protection Container Count Summary for that vault. 

Thanks.

**Comment by smoolya17** [comment] 2021-04-24 06:34
If the docs string to these sorts of methods can be updated it would be much easier to browse through such useful methods

**Comment by mepand** [comment] 2021-04-29 09:42
Thanks for the feedback @smoolya17. We will work on it. Is your issue resolved with the correction Akshay suggested above ?

**Comment by smoolya17** [comment] 2021-04-29 09:56
Yes it does. Thank you so much

**Comment by pvrk** [comment] 2021-05-13 12:00
Closing since the issue is resolved. Will work on updating doc samples.

**Closed by pvrk** 2021-05-13 12:00 UTC
Labels: Mgmt, Recovery Services Backup, Service Attention, customer-reported, question
