### ISSUE TITLE
_filtered_accounts in shared_token_cache.py does not filter accounts by tenant correctly

### ISSUE THREAD

**Issue by robwe** [Azure/azure-sdk-for-python#11551] opened 2020-05-20 13:04 UTC
- **Package Name**: identity
- **Package Version**: 1.4.0b4
- **Operating System**:
- **Python Version**: 3.7

**Describe the bug**
I am using the latest version (16.5.5) of Visual Studio 2019. The _filtered_accounts() function of SharedTokenCacheBase assumes, that that the second part of the home_account_id of an account consist of the tenant id. At least in the cache used by VS 2019, located at %LocalAppData%\.IdentityService, this is not true. The tenant id is contained in the realm element of the account. Hence the SharedTokenCacheCredential is not usable for VS 2019.

**Expected behavior**
SharedTokenCacheCredential should work for VS 2019, i.e. the cache located at %LocalAppData%\.IdentityService.

**Additional context**
The fix is in _filtered_accounts() in shared_token_cache.py to replace
`_, tenant = account["home_account_id"].split(".")`
with 
`tenant = account["realm"]`

I further recommend to change the function comment to: 
return list of accounts matching username (if given) and tenant_id

**Comment by kaerm** [comment] 2020-05-20 17:21
Thanks @robwe for reporting this, @chlowell could you take a look at this

**Comment by chlowell** [comment] 2020-05-20 18:13
In short, this is by design. Is the credential not working as you expect when you provide a tenant ID?

Longer explanation: the second part of `home_account_id` is a tenant ID, specifically that of the user's home tenant. An account's `realm` is the ID of the tenant in which the user authenticated. These two IDs differ when a user authenticates in a foreign tenant. `SharedTokenCacheCredential` uses the home tenant ID when searching for a refresh token by way of an account because in the cache, accounts and refresh tokens are joined on `home_tenant_id`.

**Comment by robwe** [comment] 2020-05-21 23:52
My Microsoft account "myEmail" is also a User of three Azure Active Directories with three different tenant ids (guid5, guid6, guid7). In the Subscription of the tenant with id guid5 there is a Key Vault with an Access Policy for my user "myEmail". I want to get a secret from that vault. Here is my code:
```
from azure.identity import SharedTokenCacheCredential
from azure.keyvault.secrets import SecretClient
 
myKeyVaultUrl = "https://mykeyvault.vault.azure.net"
tenantThatTheKeyVaultBelongsTo = "guid5"
 
credential = SharedTokenCacheCredential(tenant_id = tenantThatTheKeyVaultBelongsTo)
keyVaultSecretClient = SecretClient(vault_url = myKeyVaultUrl, credential = credential)
secretValue = keyVaultSecretClient.get_secret("key1")

```
When I run it, I get the exception:

> The cache contains no account matching the specified tenant: guid5. To authenticate with
> SharedTokenCacheCredential, login through developer tooling supporting Azure single sign on.
> Discovered accounts: (username: myEmail, tenant: guid2)

The file %LocalAppData%\.IdentityService\V2AccountStore.json contains the following content:

```
[{
    "Stale": false,
    "IsPersonalizationAccount": true,
    "Properties": {
      "IdentityProvider": "guid3",
      "IsMSA": "True",
      "Vsid": "guid4",
      "MissingTenants": "[]",
      "HomeTenant": "guid3",
      "IdentityServiceTenants": "see below",
      "IdentityServiceScopes": "[]",
      "AadConfiguration": "see below",
      "IdentityAndConfigurationHash": "guid1.guid2:hexString1",
      "IdTokenPayload": "see below",
      "Providers": "null"
    },
    "DisplayInfo": {
      "UserName": "myEmail",
      "DisplayName": "First Last",
      "ProviderContextText": "Microsoft account",
      "ProviderLogo": "...",
      "UserLogo": "..."
    },
    "UniqueId": "guid1.guid2:hexString1",
    "ProviderId": "552afc90-145a-469c-8c31-943595db4a66"
  }
]

"IdentityServiceTenants":
[{
    "UniqueId": "guid1.guid2",
    "TenantId": "guid3",
    "FriendlyName": "Microsoft account",
    "IsOwned": true
  }, {
    "UniqueId": "guid1.guid2",
    "TenantId": "guid5",
    "FriendlyName": "Tenant 1",
    "IsOwned": true
  }, {
    "UniqueId": "guid1.guid2",
    "TenantId": "guid6",
    "FriendlyName": "Tenant 2",
    "IsOwned": true
  }, {
    "UniqueId": "guid1.guid2",
    "TenantId": "guid7",
    "FriendlyName": "Tenant 3",
    "IsOwned": true
  }
]

"AadConfiguration":
{
  "AuthenticationQueryParameters": null,
  "AsmEndPoint": "https://management.core.windows.net/",
  "Authority": "https://login.microsoftonline.com/",
  "AzureResourceManagementEndpoint": "https://management.azure.com/",
  "ClientIdentifier": "guid8",
  "EnvironmentName": "AzureCloud",
  "GraphEndpoint": "https://graph.windows.net/",
  "MsaHomeTenantId": "guid3",
  "NativeClientRedirect": "urn:ietf:wg:oauth:2.0:oob",
  "PortalEndpoint": "https://portal.azure.com/",
  "ResourceEndpoint": "https://management.core.windows.net/",
  "ValidateAuthority": true,
  "VisualStudioOnlineEndpoint": "https://app.vssps.visualstudio.com/",
  "VisualStudioOnlineAudience": "guid9",
  "AzureResourceManagementAudienceEndpoints": ["https://management.core.windows.net/"]
}

"IdTokenPayload":
{
  "aud": "guid8",
  "iss": "https://login.microsoftonline.com/guid3/v2.0",
  "iat": 1589787542,
  "nbf": 1589787542,
  "exp": 1589791442,
  "aio": "...",
  "altsecid": "1:live.com:...",
  "idp": "https://sts.windows.net/guid2/",
  "preferred_username": "myEmail",
  "sub": "...",
  "tid": "guid3",
  "uti": "...",
  "ver": "2.0"
}
```

The reason for the exception is that _filtered_accounts() returns no accounts, because the second part of account["home_account_id"] is guid2, which is different from guid5. In fact, it is different from all tenant ids, including my home tenant (guid3).

When I run my code again, but this time with tenantThatTheKeyVaultBelongsTo = guid2, then I get the following exception:

> Azure Active Directory error '(invalid_client) AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

When I apply all the code changes suggested in issues [11549](https://github.com/Azure/azure-sdk-for-python/issues/11549), [11550 ](https://github.com/Azure/azure-sdk-for-python/issues/115) and this issue, then the code at the top of this comment works.

**Comment by chlowell** [comment] 2020-05-28 18:49
Thanks for all the details, I think I grasp the situation now. First, one quick clarification: `SharedTokenCacheCredential` reads a different file, %LocalAppData%\.IdentityService\msal.cache. I don't know how it lines up with V2AccountStore.json.

Regardless, I do see a problem with the credential here. Its `tenant_id` parameter specifies a desired home tenant as a means of choosing between accounts having the same username. But I don't think you need that. You write in #11550 that all accounts in your cache have the same home_account_id. As I commented in that issue, these accounts are therefore functionally identical; `SharedTokenCacheCredential` doesn't need additional information to choose the "right" one. Even so, the credential will fail you because you need to authenticate in a foreign tenant and it doesn't provide a means to configure that, as you describe in #11549. I think that's the key problem.

This is not to say the credential's account selection logic isn't problematic. It reflects limitations of the cache and doesn't serve all scenarios. Because we can't make changes to the cache, we've preferred building other credentials over struggling with these limitations in `SharedTokenCacheCredential`.

So before getting into how we might change `SharedTokenCacheCredential` I'd like to ask, what led you to use it? Are you writing Python in Visual Studio? Do you prefer authenticating through Visual Studio to authenticating through VS Code or the Azure CLI?

**Comment by robwe** [comment] 2020-05-29 05:21
msal.cache is not directly readable, but in the debugger I saw that it corresponds to what is in V2AccountStore.json, so I used that for illustration.
Mainly I develop in C# using Visual Studio 2019. As VS contains a Python development module (Workload), it was quite natural to stick to the same IDE and use it also for Python development. I have not used VS Code so far. My team uses Team Foundation Version Control, hence we are logged in via VS all the time anyway. That is why it is very handy to use the shared token cache.

**Comment by chlowell** [comment] 2020-07-08 15:43
Thanks again for all the details. I'm closing this issue because the behavior described at the top is correct for the scenarios `SharedTokenCacheCredential` supports. I'm leaving #11549 open as a request to support authenticating in foreign tenants.

**Closed by chlowell** 2020-07-08 15:43 UTC
Labels: Azure.Identity, Client, customer-reported, question
