### ISSUE TITLE
DefaultAzureCredential no longer allows a custom `client_id` parameter to be passed in

### ISSUE THREAD

**Issue by ms-lolo** [Azure/azure-sdk-for-python#13072] opened 2020-08-12 18:04 UTC
- **Package Name**: azure-identity
- **Package Version**:  1.4.0
- **Operating System**: Any
- **Python Version**: Any

**Describe the bug**
`DefaultAzureCredential` no longer allows a custom `client_id` parameter to be passed in. This change is currently hard-coding the lookup of the `AZURE_CLIENT_ID` environment variable regardless of whether it is found in `kwargs`: https://github.com/Azure/azure-sdk-for-python/blob/c6388a01fc731ba8fba3de122aec799c384f59da/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L103

**To Reproduce**
1.  try to create an instance of `DefaultAzureCredential(client_id=some_id)`

**Expected behavior**
I would expect to overwrite the default behavior of looking up the environment variable.

**Screenshots**
N/A

**Additional context**
This is particularly tricky on machines with multiple identities.

Initially asked about this here: https://github.com/Azure/azure-sdk-for-python/issues/10931#issuecomment-673016243 and was told to file a bug :)

**Comment by kaerm** [comment] 2020-08-12 18:15
Thanks @ms-lolo, @chlowell could you take a look at this

**Comment by chlowell** [comment] 2020-08-12 18:18
I'm closing this as a duplicate of #12991 but want to thank you for opening it--I wasn't aware this was being used 😊. `DefaultAzureCredential(client_id=...)` may have worked but isn't formally part of the API, so it isn't documented or tested. We plan to formally support it, perhaps through a different keyword argument, in the next beta release.

**Closed by chlowell** 2020-08-12 18:18 UTC
Labels: Azure.Identity, Client, customer-reported, question
