### ISSUE TITLE
Single request uploads of large "readable" data stream are slow (capped at ~8Mbps)

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-python#11044] opened 2020-04-24 17:21 UTC
- **Package Name**: 
azure-core (pipeline)
- **Package Version**: 
latest
- **Operating System**:
Windows 10 Enterprise (1909) . But this seems to be platform independent issue.
- **Python Version**: 
platform win32 -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- C:\git\azure-sdk-for-python\venv\Scripts\python.exe
- **References**
Root cause analysis brought me to these issues filled against Python httplib. Confirmed experimentally (see below).
https://bugs.python.org/issue21790
https://bugs.python.org/issue31945
https://stackoverflow.com/questions/48719893/why-is-the-block-size-for-python-httplibs-reads-hard-coded-as-8192-bytes

**Describe the bug**
When trying to push large amount of data (4000MB in my case) that's "readable stream" (e.g. BytesIO or file reader - anything implementing "read") then the upload speed caps at around 8Mbps.
(For the context I'm working on 4000MB block upload support for Azure Storage SDK).

**To Reproduce**
Execute [test_put_block_stream_large](https://github.com/Azure/azure-sdk-for-python/blob/ace5cc1cc18a38b12e5aacf4f46b4919cf970c36/sdk/storage/azure-storage-blob/tests/test_large_block_blob.py#L117-L134) with LARGE_BLOCK_SIZE bumped to some large value (i.e. 4000MB upcoming , or 100MB currently supported threshold).

OR

Use [scenario from my fork](https://github.com/kasobol-msft/azure-sdk-for-python/blob/149c9c67fb3ce8d240abfa0fa3da5a9a37253a34/sdk/storage/azure-storage-blob/tests/test_largest_block_blob.py#L105-L131) as reference.

**Expected behavior**
Upload speed of "readable" data is not capped by httpclient and can leverage full network bandwith available.

**Possible solution**
The https://bugs.python.org/msg305571 suggest quite handy workaround that could be part of pipeline I guess. So far I didn't see any way to inject different blocksize to httpclient.

**Screenshots**

Original test:

I was uploading 4000MB of data in single request without any modifications using "readable" stream. That took over 1 hour!!
![image](https://user-images.githubusercontent.com/61715331/80238927-26fffd00-8614-11ea-8e81-2c11c004ae8e.png)
![image](https://user-images.githubusercontent.com/61715331/80238959-33845580-8614-11ea-9e56-d6e8ae6b5231.png)

Turns out httpclient is using 8192 byte buffer when readable stream is passed:

![image](https://user-images.githubusercontent.com/61715331/80239038-5d3d7c80-8614-11ea-9320-0daa827aad0d.png)
![image](https://user-images.githubusercontent.com/61715331/80239059-67f81180-8614-11ea-8493-a8099ac8d5ee.png)
![image](https://user-images.githubusercontent.com/61715331/80239093-747c6a00-8614-11ea-96ed-20cb2718d856.png)

Then I started to play with blocksize. I was editing http client's source and bumping the blocksize.

After bumpting to 8192*1024 upload speed was more than 2X faster
![image](https://user-images.githubusercontent.com/61715331/80239376-fa98b080-8614-11ea-89aa-caa647efccac.png)
![image](https://user-images.githubusercontent.com/61715331/80239404-07b59f80-8615-11ea-9a55-60d3ca41de7e.png)

And after bumping it to 10*8192*1024 I managed to upload that payload in ~4 and half minute.
![image](https://user-images.githubusercontent.com/61715331/80239479-29af2200-8615-11ea-90d8-4b8d37309ace.png)

**Additional context**
This is going to impact future users of "large block"/"large blob" (4000MB new limit for single block / 200TB limit for single blob). Users of that feature are most likely work with streams - either uploading data from network or data produced on the fly by computations. Therefore it's important to address this deficiency.

**Comment by kaerm** [comment] 2020-04-28 18:36
Thanks @kasobol-msft for the detailed description, @chlowell can you take a look at this

**Comment by chlowell** [comment] 2020-04-28 18:46
Sure. Looks like it's an issue users will encounter through the storage libraries, that may require a change in azure-core. @lmazuel, @rakshith91, @xiangyan99, your thoughts?

**Comment by mikeharder** [comment] 2020-04-30 00:05
My first reaction is this is something we should fix ASAP.  I will gather more data and investigate possible fixes.

**Comment by mikeharder** [comment] 2020-09-10 22:31
I spent some time investigating this issue, and while I haven't fully isolated the root cause(s), I have several conclusions:

1. It seems to only repro on Windows client machines, not Linux.  I suspect this is due to differences in the OS networking stack.  But any changes should be perf tested on both Windows and Linux.
2. The regression is much larger when network throughput is lower and/or latency is higher.  Specifically, it may not repro when using a storage account in the same region, but it should repro when using a storage account far away (e.g. client in West US, storage in Australia).
3. The biggest regression appears to be in the azure-core Pipeline layer.  In my tests, the regression doesn't repro when using raw `http.client` or the `requests` package, but it does repro when using the `azure-core` Pipeline or the Storage SDK.  But @kpajdzik has seen some regressions at the `http.client` layer from his personal machine.

# Repro Steps
1. Create a storage account in a region far away from your client.
2. Create a blob container in the storage account, and generate a SAS token.
3. Construct the URL for testing upload perf.  It should look like `https://<account>.blob.core.windows.net/<container>/<blob>?<sas-token>`.
4. Clone the repro app at https://github.com/mikeharder/python-storage-perf
5. `pip install -r requirements.txt`
6. `python app.py <url> <size>` (10MB is a good starting size)

**Comment by mikeharder** [comment] 2020-10-02 19:03
A similar issue was reported against curl on Windows that might be related:

https://curl.haxx.se/mail/lib-2018-07/0080.html

**Comment by mikeharder** [comment] 2020-11-05 02:46
This should be fixed by #14442:

 &nbsp; |Stream (Mbps)| &nbsp; |Array (Mbps)| &nbsp; |
-----|-----|-----|-----|-----
**azure-core**|**Pipeline**|**stage\_block**|**Pipeline**|**stage\_block**
1.8.2|5.93|5.88|287|302
#14442|271|302|270|284

@kasobol-msft: Would you like to verify as well?

**Comment by kasobol-msft** [comment] 2020-11-05 17:52
@mikeharder works like a charm.

**Closed** 2020-11-07 02:45 UTC
Labels: Azure.Core, Client, bug
