### ISSUE TITLE
AutoML running on Azure compute instance should be able to tell us we are passing the wrong datatype 

### ISSUE THREAD

**Issue by chen-bowen** [Azure/azure-sdk-for-python#15926] opened 2020-12-28 18:18 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Ex. From the sample notebooks here, [sample-notebook-credit-card-fraud](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb ), we are expected to pass a TabularDataSet object to AutoML config. However, for some beginners, we often are used to passing a pandas dataframe to any training algorithms. But the error message generated here is not very helpful as it doesn't recognize that we have passed a dataframe to it instead it's showing an "Unknown" type.

```
ConfigException: ConfigException:

Message: Input of type 'Unknown' is not supported. 

Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]
```

This has made troubleshooting way harder than it should be

**Describe the solution you'd like**
Once we pass a datatype that is not accepted by Azure Compute Instance, at least we should given which line and what datatype is wrong for the compute instance. Right now we are only thrown a long exception that's not very helpful

**Describe alternatives you've considered**
It should be easy to just add a line of type detection when this error happens

**Comment by kvijaykannan** [comment] 2021-02-12 15:22
Thanks for raising this. Engineering team is looking into this to get it fixed.

**Comment by kvijaykannan** [comment] 2021-02-16 18:15
This has been fixed.

**Comment by swatig007** [comment] 2021-02-17 21:48
Closing since the issue is fixed

**Closed by swatig007** 2021-02-17 21:48 UTC
Labels: Client, ML-AutoML, Machine Learning, customer-reported, question
