### ISSUE TITLE
transient playback error possibly due to astroid / wrapt version incompatibility

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22391] opened 2022-01-08 00:59 UTC
This has been hard to track down because it appears to be transient and oftentimes will resolve upon re-run. These errors started to appear beginning around Jan 4th.

The error I see in the logs is 
> ERROR: astroid 2.5 has requirement wrapt<1.13,>=1.11, but you'll have wrapt 1.13.3 which is incompatible

Some examples:
TA - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1277122&view=logs&j=6b0f58a2-2e70-5c7e-39b0-96edbdc2c961&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=915101bf-b1f2-5cf5-ea77-216603fe6fcc&l=1660
FR - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1281844&view=logs&j=92b97d34-cf4d-5fc2-e574-c46d36e621e2&t=22fc1b08-c6b5-52f6-00fb-ed3e5e692f60&l=1835
Tables - https://dev.azure.com/azure-sdk/public/_build/results?buildId=1281843&view=logs&j=92b97d34-cf4d-5fc2-e574-c46d36e621e2&t=22fc1b08-c6b5-52f6-00fb-ed3e5e692f60&l=1373 

It seems to fail on random python versions, sometimes on whl, sdist, or latestdependency (like in the above examples). 

Edit: one thing these 3 libraries have in common is that they have all migrated to test proxy

**Comment by kristapratico** [comment] 2022-01-10 19:07
This is now happening in metricsadvisor as well (which just merged test proxy work): https://dev.azure.com/azure-sdk/public/_build/results?buildId=1284955&view=logs&j=92b97d34-cf4d-5fc2-e574-c46d36e621e2&t=22fc1b08-c6b5-52f6-00fb-ed3e5e692f60&l=1323

**Comment by kristapratico** [comment] 2022-01-13 18:42
Another possible pattern we're seeing is that this seems to occur only on Windows machines.

**Comment by scbedd** [comment] 2022-01-21 22:59
```
BuildLogLine
| where Timestamp >= now(-31d)
| where Message startswith "ERROR: astroid 2.5 has requirement wrapt<1.13"
| join kind=leftouter (Build | project BuildNumber, BuildId, DefinitionName) on $left.BuildId == $right.BuildId
| project DefinitionName, BuildId, BuildNumber, Timestamp, Message
| sort by BuildNumber desc
| summarize InstanceCount=count() by DefinitionName, OccurenceDay=bin(Timestamp, 1d)
| sort by OccurenceDay, DefinitionName desc
```

Not great. I believe we already have `astroid` pinned, so I'm a bit confused why the alternate version of `wrapt` is reserving.

![image](https://user-images.githubusercontent.com/45376673/150610941-95856a40-11e5-4724-afe8-17367672ca86.png)

**Comment by kristapratico** [comment] 2022-01-21 23:21
@scbedd do you have an idea of whether the error is due to the dependency conflict or the non-empty directory like in this issue?
https://github.com/Azure/azure-sdk-for-python/issues/22489

I'm not sure myself. 😭

**Comment by scbedd** [comment] 2022-01-21 23:47
The non-empty directory issue is something that I'm actually surprised we haven't seen before. It's a windows-specific issue because only Windows would ever have problems like this. I think that `virtualenv` got bumped somehow, which means the seed environments are different, which also means that a pip install on an existing folder may run into an issue. It's not guaranteed, which is why we still get some passes, but there is something there. Notice that it's along the lines of "that folder isn't empty" and "that folder" includes the _pip CLI_. That's our entrypoint to call the pip install of the dev_requirements and test_tools.txt!

It may be related to this specific issue, but I'm not certain.  

Right now, I'm just confused as to why `wrapt` or `astroid` are getting pulled in _at all_. I'm doing a local debug with `pipgrip` to understand that.

**Comment by scbedd** [comment] 2022-01-22 00:32
I think we can confidently see that they are both occurring on Windows, but they aren't necessarily correlated.

![image](https://user-images.githubusercontent.com/45376673/150616777-a18512b2-231c-4ecc-82f6-f15e34166f9c.png)

**Comment by scbedd** [comment] 2022-01-22 01:06
Ok. This is a real issue, but is not a blocking one. I don't believe that this error is the cause of our failed builds. In fact, we only see actual failed builds when we hit that Win 145 error. 

[Here's an example build where we **didn't** see the win 145 error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1313135&view=logs&j=f1ee1d4b-0f4d-518d-a9ec-fcb3c5520813&t=616ee2f3-0694-5de2-9996-c0bd7ce45190)

Ok, so it's green even when this crops up. That means this is still an issue, but isn't the end of the world. I was still _super_ confused why this was even happening.

After running `pipgrip` on our test_tools.txt file, I figured out where our issue is coming from:

```
pylint==2.5.2 (2.5.2)
├── astroid<=2.5,>=2.4.0 (2.5)
│   ├── lazy-object-proxy>=1.4.0 (1.7.1)
│   └── wrapt<1.13,>=1.11 (1.12.1)
├── ...
```

Locally, from dev_requirements.txt we have a relative rec on `azure-devtools`, and `test_tools.txt` has a pinned `pylint` package.

`azure-devtools` -> `vcrpy ~= 3.0.0` -> `wrapt==1.13.3`
`pylint==2.5.2` -> `astroid==2.5` -> `wrapt<1.13.0`

Depending on installation order, we may or may not see this compatibility error, but in all cases, we don't actually exercise any code that fails. That's why we see ERROR on a green build. 

This issue should stay open to eliminate the ERROR output, but this is not a blocker like the win error 145 is.

**Comment by scbedd** [comment] 2022-01-25 03:23
Closing this to watch via build log queries. Will re-open on reoccurence.

**Comment by scbedd** [comment] 2022-01-25 20:16
![image](https://user-images.githubusercontent.com/45376673/151052673-430a35b2-3afe-4447-8b18-668cf571e53c.png)

We definitely stamped this out.

**Closed** 2022-01-25 22:25 UTC
Labels: Central-EngSys
