### ISSUE TITLE
Creating Puppet Image using Java SDK doesn't  have puppet works fine with Azure CLI

### ISSUE THREAD

**Issue by saraswat2385** [Azure/azure-sdk-for-python#595] opened 2016-05-11 11:03 UTC
I am just trying to create Puppet VM on azure using Azure java SDK and using puppet labs VM image to build my machine.

 when i do the same using Azure UI or Azure Cli it's works fine but when i do it using Azure Java Sdk machine is created but puppet is not installed on that.

Tried with all three images 

||Publisher||Offer||Sku||
|PuppetLabs|PuppetEnterprise|2015.3|
|PuppetLabs|PuppetEnterprise|3.2|
|PuppetLabs|PuppetEnterprise|3.7|

**Comment by lmazuel** [comment] 2016-05-11 14:31
This is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/596

**Closed by lmazuel** 2016-05-11 14:31 UTC
