### ISSUE TITLE
`proxy_startup.py` should properly pull new image versions if one exists

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#25677] opened 2022-08-11 21:36 UTC
This should be based against `eng/common/testproxy/target_version.txt`

**Comment by mccoyp** [comment] 2022-08-17 17:44
Closing as a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/22162.

**Closed by mccoyp** 2022-08-17 17:44 UTC
Labels: Client, Azure.Core, Central-EngSys
