### ISSUE TITLE
reinstalling causes partial uninstall

### ISSUE THREAD

**Issue by abdulito** [Azure/azure-sdk-for-python#584] opened 2016-04-20 04:24 UTC
reinstall azure when if its already installed causes some modules to be uninstalled

```
sudo pip install "azure==1.0.1"
sudo pip install "azure==1.0.1" --upgrade --force-reinstall

```

then if you do this import it fails

```
from azure.storage.blob import BlobService


 ImportError: No module named azure.storage.blob
```

I am using python 2.7.6 on Ubuntu 12.10

Thanks!

**Comment by lmazuel** [comment] 2016-04-20 14:47
Hi,

I'm not able to reproduce your problem in this environment:
- Ubuntu 15.10
- Python 2.7.10
- Pip 1.5.6
- Virtualenv (not as root)

The most possible cause is an older version of pip in your system. Could try to update pip to a newer one? At least, could you give the version of pip you use?

Thank you,

**Comment by lmazuel** [comment] 2016-04-20 15:20
I reproduce it with:
- Ubuntu 12.04.5
- Python 2.7.3
- pip 1.1
- Virtualenv

However, by upgrading just pip using `pip install -U pip` the problem is gone (pip 8.1.1)

It's clear that it is a bug in an old version of pip. Please update your pip installer for this scenario to work.

I close this bug, feel free to re-open it if you really think we should handle this here.

Thank you,

**Closed by lmazuel** 2016-04-20 15:20 UTC
