### ISSUE TITLE
Wrong parsing of error message (string encoding problems)

### ISSUE THREAD

**Issue by wvxvw** [Azure/azure-sdk-for-python#10952] opened 2020-04-21 06:44 UTC
In `msrestazure/azure_exceptions.py` you have a method `CloudErrorData.__str__`, which does this: `return error_bytes.decode('ascii')`, however, the service may return something like this:

```
"Azure Error: InvalidTemplateDeployment
Message: The template deployment 'westus2-rex-deploy-integ-az-replixio-35720035-deployment' is not valid according to the validation procedure. The tracking id is '9859c46f-79bd-4eb8-8b9d-03c12b1b6c83'. See inner errors for details.
Exception Details:
	Error Code: OverlappingSubnetsNotPermittedInSecurityRule
	Message: Security rule parameter SourceAddressPrefix for rule with Id /subscriptions/b647b92c-2417-4934-8aac-fe47f3d8dd05/resourceGroups/westus2-rex-deploy-integ-az-replixio-35720035/providers/Microsoft.Network/networkSecurityGroups/initiator-0-nsg/securityRules/SshAccess contains overlapping subnets [77.137.10.74/32, 77.137.10.74/32], which is not permitted.
	Error Code: QuotaExceeded
	Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: westus2, Current Limit: 10, Current Usage: 8, Additional Required: 4, (Minimum) New Limit Required: 12. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22b647b92c-2417-4934-8aac-fe47f3d8dd05%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the \xe2\x80\x98Details\xe2\x80\x99 section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests."
```
Formatting added for readability.

Notice the `\xe2\x80\x98Details\xe2\x80\x99` part. This will prevent the error from being displayed, instead, you'll get a different error about bad string encoding. This is, obviously, also a problem on the server side, which formats the message incorrectly. Regardless of the double bug, the client side should be smart enough to be able to display the usable parts of the error message by, for example, specifying the recovery strategy for encoding errors s.a. "ignore" or "replace", or use a different codec.

**Comment by lmazuel** [comment] 2020-04-21 17:00
Hi @wvxvw 
This is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/10893

Error has been fixed in msrestazure 0.6.3:
https://github.com/Azure/msrestazure-for-python/issues/143
https://github.com/Azure/msrestazure-for-python#2020-03-17-version-063

> pip install -U msrestazure

Please open a new issue if necessary

Thanks!

**Closed by lmazuel** 2020-04-21 17:00 UTC
Labels: triage
