### ISSUE TITLE
[azure-storage-blob] list_blobs() cannot work with include=metadata

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-sdk-for-python#12926] opened 2020-08-06 07:32 UTC
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.4.0-b1
- **Operating System**: Windows
- **Python Version**: 3.7.7

**Describe the bug**

When listing blobs in a container with metadata information, as description mentioned and track1 behavior, we could add --include=metadata to get such  results.

But when I use it in new sdk, I can get the response with metadata information in raw response [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/operations/_container_operations.py#L1212) as shown below but after deserialization it is skipped and change to None.
```
b'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="https://zuhdefault.blob.core.windows.net/" ContainerName="test1">
<MaxResults>2</MaxResults><Blobs>
<Blob><Name>a.txt</Name><VersionId>2020-08-06T03:20:00.9910412Z</VersionId>
<IsCurrentVersion>true</IsCurrentVersion><Properties><Creation-Time>Tue, 14 Jul 2020 07:58:04 GMT</Creation-Time>
<Last-Modified>Thu, 06 Aug 2020 03:20:00 GMT</Last-Modified><Etag>0x8D839B79AAF1A66</Etag>
<Content-Length>1200</Content-Length><Content-Type>text/plain; charset=utf-8</Content-Type><Content-Encoding />
<Content-Language /><Content-CRC64 /><Content-MD5>4edJNByMxQgCm9dVVN4KWQ==</Content-MD5>
<Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier>
<AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState>
<ServerEncrypted>true</ServerEncrypted></Properties><Metadata><test>1</test></Metadata><OrMetadata /></Blob>
<Blob><Name>ast.md</Name><Properties><Creation-Time>Tue, 14 Jul 2020 07:58:05 GMT</Creation-Time>
<Last-Modified>Tue, 14 Jul 2020 07:58:05 GMT</Last-Modified><Etag>0x8D827CBA3A2B2BC</Etag>
<Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding />
<Content-Language /><Content-CRC64 /><Content-MD5>1B2M2Y8AsgTpgAmY7PhCfg==</Content-MD5>
<Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier>
<AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState>
<ServerEncrypted>true</ServerEncrypted></Properties><Metadata /><OrMetadata /></Blob></Blobs>
<NextMarker>2!72!MDAwMDA5IWZpbGUxLnR4dCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-</NextMarker>
</EnumerationResults>'
```

I am guessing it is because Model `ListBlobsFlatSegmentResponse` doesn't include metadata properties. But I think if we have such behavior to include metadata, we should return response with metadata and it will be fine to align with track1 behavior.

If there is anything misuse, feel free to let me know.  

**To Reproduce**
1. list_blobs() with include=metadata 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Juliehzl** [comment] 2020-08-12 01:59
Hi @kaerm, it seems @xgithubtriage is  not valid name.

**Comment by kaerm** [comment] 2020-08-12 18:14
It should be working - there is some weirdness around github and how it displays team handles

**Comment by xiafu-msft** [comment] 2020-08-21 08:50
Hi @Juliehzl 

I'm not able to reproduce it, the test in this pr is working https://github.com/Azure/azure-sdk-for-python/pull/13260

**Comment by tasherif-msft** [comment] 2020-10-07 05:48
Hi @Juliehzl, it should be working. As you have mentioned our list blobs operation is using `ListBlobsFlatSegmentResponse` however it does deserialize metadata. It has an attribute `segment` that gets desarialized. This attribute has a dependency on `BlobFlatListSegment` class which contains an attribute `BlobItermInternal` class which contains the `metadata` attribute. 

Please let us know if you need further help. Otherwise we can proceed to close this issue.

**Closed** 2020-10-29 08:00 UTC
Labels: Client, Service Attention, Storage, needs-author-feedback, no-recent-activity
