### ISSUE TITLE
SubscriptionClient does not include tags

### ISSUE THREAD

**Issue by fxdgear** [Azure/azure-sdk-for-python#22180] opened 2021-12-15 04:35 UTC
- **Package Name**: azure-mgmt-resource
- **Package Version**: azure-mgmt-resource==20.0.0
- **Operating System**: Python docker image
- **Python Version**: 3.9.6

**Describe the bug**
The SubscriptionClient does not return tags

**To Reproduce**
1. Navigate to this website: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals
2. Follow the example here: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals#authenticate-using-environment-variables
3. for each subscription returned in the list try `print(subscription.tags)` and witness it say None. 

```
In [26]: for sub in sub_list:
    ...:     print(sub.tags)
    ...: 
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

**Expected behavior**
I would expect to see key value listing of the tags I've assigned on to each subscription.

**Comment by yunhaoling** [comment] 2021-12-15 18:32
thanks @fxdgear for reaching out! we'll investigate it ASAP.

**Comment by fxdgear** [comment] 2021-12-16 15:35
@yunhaoling Any progress on this? 

or at least a suggestion for a workaround? 

Looking at the docs and community posts, it's not clear how to do things in the MS ecosystem. 

I'm currently blocked by not being able to list subscriptions with their tags.

**Comment by yunhaoling** [comment] 2021-12-16 18:05
@fxdgear apologize that I'm not familiar with the subscription mgmt sdk..

@msyyc @SaurabhSharma-MSFT could you take a look and give suggestion?

**Comment by SaurabhSharma-MSFT** [comment] 2021-12-17 01:50
@fxdgear Do you have any tags assigned to these subscriptions.  I have tested this in my environment by adding some tags to the subscription and I am getting back the results. (Please check below)
![image](https://user-images.githubusercontent.com/38112130/146475408-64b7377d-6c9d-40a1-afff-eb578b784c25.png)
Result:
![image](https://user-images.githubusercontent.com/38112130/146475442-a318d22c-9240-4d5f-ab8a-fca09990e19b.png)

**Comment by fxdgear** [comment] 2021-12-17 01:51
Yes I do. 

I didn't include a screenshot in the issue.

**Comment by fxdgear** [comment] 2021-12-17 03:28
Is there else I can help debug this issue? Is there a permission I need to ensure exists? 

What is the minimum required permissions needed to make this work? 

This service account does one thing and one thing only. Read subs and their tags. It doesn't need and shouldn't need excess permissions.

**Comment by fxdgear** [comment] 2021-12-17 17:08
![Screenshot from 2021-12-17 10-08-11](https://user-images.githubusercontent.com/146550/146581801-c740c370-f30a-4ffb-a819-7b00b41c84ab.png)

**Comment by fxdgear** [comment] 2021-12-17 17:13
FYI the role assignment for my app is "Reader". 

Is there a different role I should be using?

**Comment by fxdgear** [comment] 2021-12-17 17:56
I've since added `Tag Contributer` to my service principal

![Screenshot from 2021-12-17 10-55-17](https://user-images.githubusercontent.com/146550/146587529-bf8a134c-6776-4c2f-a1f8-1e76086b6247.png)


But now when I try to use the above example I am now getting the following error: 

```
AttributeError: 'EnvironmentCredential' object has no attribute 'signed_session'
```

**Comment by fxdgear** [comment] 2021-12-17 18:07
I've even added `Owner` now to my service principal and I'm still getting nothing for tags. 

Since I've started getting errors using the `EnvironmentCredential` I've switched over to using the ServicePrincipalCredentials: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals#serviceprincipalcredentials-azurecommon

AND I'm still getting None for the tags.

**Comment by SaurabhSharma-MSFT** [comment] 2021-12-17 19:40
@fxdgear I have given `contributor` access to the service principal but it worked with only `Tag Contributor` access as well.

**Comment by fxdgear** [comment] 2021-12-17 19:55
Can you check with only `Reader`?

**Comment by fxdgear** [comment] 2021-12-17 20:02
I've changed my service principal to only `Tag Contributer` and I'm still getting `None` for tags.

**Comment by fxdgear** [comment] 2021-12-17 20:07
```root@68b5c9edf09e:/app# ipython
Python 3.9.6 (default, Jun 29 2021, 19:18:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from azure.identity import EnvironmentCredential
   ...: from azure.mgmt.resource import SubscriptionClient
   ...: 
   ...: credential = EnvironmentCredential()
   ...: subscription_client = SubscriptionClient(credential)
   ...: 
   ...: sub_list = subscription_client.subscriptions.list()

In [2]: for sub in sub_list:
   ...:     print(sub.tags)
   ...: 
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

when I use the az cli tool I can get the tag for a specific sub: 

```
❯ az tag list --resource-id /subscriptions/fc58a142-2e74-48ff-974c-cde6e008f8f5
{
  "id": "/subscriptions/fc58a142-2e74-48ff-974c-cde6e008f8f5/providers/Microsoft.Resources/tags/default",
  "name": "default",
  "properties": {
    "tags": {
      "test": "bar"
    }
  },
  "type": "Microsoft.Resources/tags"
}
```

When I then change my python script to only look for the previoysly mentioned sub:

```
In [5]: for sub in sub_list:
   ...:     if sub.id == "/subscriptions/fc58a142-2e74-48ff-974c-cde6e008f8f5":
   ...:         print(sub.tags)
   ...: 
None
```

**Comment by fxdgear** [comment] 2021-12-17 20:11
There is clearly something different between my environment and your environment. I'm trying to understand what this difference is.

**Comment by SaurabhSharma-MSFT** [comment] 2021-12-21 03:14
@fxdgear Is your docker image windows or ubuntu ?

**Comment by fxdgear** [comment] 2021-12-21 03:19
```dockerfile
FROM python:3.9
```

**Comment by SaurabhSharma-MSFT** [comment] 2021-12-21 03:27
@fxdgear Thanks, I have checked with Reader access, and it worked fine to me. I am however using Python 3.7.9 but I don't think that is going to make much difference.  Also, azure-mgmt-resource is `20.0.0` and azure-mgmt-subscription version is `2.0.0`.

**Comment by fxdgear** [comment] 2021-12-21 03:39
Dockerfile: 

```dockerfile
FROM python:3.7

RUN pip install boto3 ipdb azure-mgmt-subscription azure-identity azure-mgmt-resource google-cloud-resource-manager

WORKDIR /app

COPY . ./

CMD ["python", "azure_utils.py"]
```

azure_utils.py:
```python
from azure.identity import EnvironmentCredential
from azure.mgmt.resource import SubscriptionClient

credential = EnvironmentCredential()
subscription_client = SubscriptionClient(credential)

sub_list = subscription_client.subscriptions.list()
for sub in sub_list:
    print(sub.tags)
```

run command: `docker build -t azure-fails:latest .`
then run  `docker run --rm -it -e AZURE_CLIENT_SECRET=<client_secret> -e AZURE_TENANT_ID=<tenant_id> -e AZURE_CLIENT_ID=<client_id> azure-fails:latest`

**Comment by fxdgear** [comment] 2021-12-21 16:32
@SaurabhSharma-MSFT So what I've done now is updated my python script to be like the following: 

```python
for sub in sub_list:
    print(subscription_client.subscriptions.get(sub.subscription_id).tags)
```
And by fetching each sub individually i can get the tags. 
```python
{'team': 'Cloud'}
{'team': 'Observability'}
{'team': 'Stack'}
```

This seems like incorrect behavior. I shouldn't have to make an additional request for each subscription to fetch the tags. They _should_ show up in the original request to the sub list. 

But the tags do not show up when i am iterating through the object list.

**Comment by BigCat20196** [comment] 2021-12-28 03:01
Hi @fxdgear Thank you for yoour feedback,but  I can't reproduce your issue. When I run the following code, I can get the `tag`.

```
sub_list = subscription_client.subscriptions.list()
for sub in sub_list:
    print(sub.tags)
```

![image](https://user-images.githubusercontent.com/51037443/147522649-288dd665-3038-4234-82a9-3ee9dc6b0280.png)


My Env:
python image from docker pull
Python 3.10.1
azure-mgmt-resource: 20.0.0

Could you pls provide more details? such as:  could you get the results through the following code:
```
sub_list = subscription_client.subscriptions.list()
for sub in sub_list:
    print(sub.as_dict()['tags'])
```

**Comment by fxdgear** [comment] 2021-12-28 18:42
@BigCat20196 

```traceback
Traceback (most recent call last):
  File "/app/azure_utils.py", line 38, in <module>
    print(sub.as_dict()["tags"])
KeyError: 'tags'
```

**Comment by BigCat20196** [comment] 2021-12-29 05:50
@fxdgear, This means that there is no `tags` attribute in the returned result, but I will not report an error even if tags is empty when I run the above code. Have you made any changes to the SDK code? 

If not, I suggest you reinstall the SDK code and try again.

FYI:
- pip uninstall azure-identity -y
- pip uninstall azure-mgmt-resource -y
- pip install azure-identity
- pip install azure-mgmt-resource

**Comment by fxdgear** [comment] 2021-12-29 15:50
@BigCat20196 I'm running this in a docker container so each time I run the sample app it is run from a pristine state. In my comment above https://github.com/Azure/azure-sdk-for-python/issues/22180#issuecomment-998444762 I showed you the command that I run to execute the container. Every time I execute my code it's run in a pristine state.

Because my example code is executed in a container it's not possible for me to alter the SDK code. Therefore you'll have to trust me when I say that I have not made any changes to the SDK code. I did try to debug what's going on at one point, but tbh there's too many abstractions built into the python SDK for me to spend too much time trying to debug it over the holidays. But again because it's run in a container anytime I decide to start over I just delete the container and re-run it. Using the `--rm` flag allows me to automatically delete the container every time the container quits. 

I'm not sure what to tell you here. I've tried multiple variations of access permissions on my service principal I've proven to you that the tags exist. Both by screen shot and by azure cli. I have even proven to you that the tags exist when I get each subscription individually. 

If you still think the python code is working as expected, then I bet the problem exists somewhere else. Please help me help you in helping me. Because I'm not sure where the issue exists at this point. Permissions, Azure service level, python level, something happening in one of the abstractions? There's too many layers for me to unpack here to be able to understand what's going on.

**Comment by msyyc** [comment] 2021-12-31 03:36
Hi, Python SDK is generated automatically with swagger. Since SDK team can't reproduce your error, we should think about whether it is problem of service. You could use [rest api](https://github.com/Azure/azure-rest-api-specs/blob/81ab10cd9d46a85258b710c6150ec48021c6d202/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/subscriptions.json#L129) to call service directly and see the return result.
If result contains `tags`, it proves that SDK has problems;
If result contains no `tags`, it proves that service has problem.

**Comment by fxdgear** [comment] 2021-12-31 16:43
@msyyc Thanks for the help here. 

I used the rest API and there were no tags included in the result: 

```bash
❯ curl -X GET -H "Authorization: Bearer [access_token]" -H "Content-Type: application/json" "https://management.azure.com/subscriptions?api-version=2020-01-01" | jq | grep "tags"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--100 13409  100 13409    0     0  29665      0 --:--:-- --:--:-- --:--:-- 29731
```

So according to your analysis it proves that the service has a problem. 

What are the next steps? 

I just double checked the access permissions for my service account, and it has `Reader` and `Tag Contributor` roles assigned to the "Root Tenant  Group".

**Comment by msyyc** [comment] 2022-01-04 05:49
Hi, you could make issue in https://github.com/Azure/azure-rest-api-specs and there will be service team to help.

**Comment by vladimirjoanovic** [comment] 2022-04-08 00:39
Would it be possible to share the way you added a tag to the subscription?  Can you ever see the tag on the subscription eg. in portal?

**Comment by rthorn17** [comment] 2022-04-12 19:08
Hi @fxdgear - I am the PM on the engineering team for tags.  Are you still having this issue?  We are not able to reproduce the issue in our test environment, but we want to make sure you are not experiencing it either.  Please let me know if you are still experiencing the same behavior.

**Closed** 2022-06-11 08:03 UTC
Labels: bug, Service Attention, Mgmt, customer-reported, ARM - Tags, no-recent-activity, needs-team-attention, needs-author-feedback

**Comment by elygre** [comment] 2022-09-24 06:46
@rthorn17 I have the same issue. Using the REST api, I can see that "az rest --url https://management.azure.com/subscriptions?api-version=2020-01-01" returns tags for some subscriptions, but not for all. Using the "/subscriptions/<guid>" endpoint will return the full set of tags. I have an open service request on the matter. Send me an email to "eirik dot lygre at cgi dot com" if you want to engage.

**Comment by HoiDam** [comment] 2022-11-01 05:58
I am encountering this issue also Please help
