### ISSUE TITLE
containerregistry list_manifest_properties unable to deserialize buildx v0.10.0 manifests

### ISSUE THREAD

**Issue by mhaley-tignis** [Azure/azure-sdk-for-python#28469] opened 2023-01-24 20:12 UTC
- **Package Name**: azure-containerregistry
- **Package Version**: 1.0.0
- **Operating System**: Ubuntu 22.04.1 LTS
- **Python Version**: Python 3.9.11

**Describe the bug**
The `ContainerRegistryClient` is unable to properly serialize manifests stored in an azure container repository. Our github docker builds started to use [buildx v0.10.0](https://github.com/docker/buildx/releases/tag/v0.10.0). As part of this release a new `--attest` field was added that by default will generate a minimal attestation for oci images. This attestation can be seen in the container manifest I fetched from azure CR below.
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 2199,
      "digest": "sha256:86fed9f0203a09f13cbbb9842132e9000eeff51b3de0d4ff66ee03ab0e860d1f",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 566,
      "digest": "sha256:b808af65792ab617b9032c20fb12c455dc2bf5efe1af3f0ac81a129560772d35",
      "annotations": {
        "vnd.docker.reference.digest": "sha256:86fed9f0203a09f13cbbb9842132e9000eeff51b3de0d4ff66ee03ab0e860d1f",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}
```
Here is the stack trace:
```
Traceback (most recent call last):
  File "/tmp/azure/main.py", line 8, in <module>
    for manifest in manifests:
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/containerregistry/_container_registry_client.py", line 316, in extract_data
    list_of_elem = cls(list_of_elem)
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/containerregistry/_container_registry_client.py", line 242, in <lambda>
    lambda objs: [
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/containerregistry/_container_registry_client.py", line 243, in <listcomp>
    ArtifactManifestProperties._from_generated(  # pylint: disable=protected-access
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/containerregistry/_models.py", line 67, in _from_generated
    return cls(
  File "/home/mhaley/.pyenv/versions/devtool/lib/python3.9/site-packages/azure/containerregistry/_models.py", line 48, in __init__
    self._architecture = ArtifactArchitecture(self._architecture)
  File "/home/mhaley/.pyenv/versions/3.9.11/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/home/mhaley/.pyenv/versions/3.9.11/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid ArtifactArchitecture
```

It seems that there is no enum value for `unknown` platform and os.

**To Reproduce**
```
from azure.containerregistry import ContainerRegistryClient, ArtifactManifestOrder
from azure.identity import DefaultAzureCredential

registry_url = "https://repo-name.azurecr.io"
registry_image_name = "image-name"
client = ContainerRegistryClient(registry_url, DefaultAzureCredential(), audience="https://management.azure.com")
manifests = client.list_manifest_properties(registry_image_name, order_by=ArtifactManifestOrder.LAST_UPDATED_ON_DESCENDING, results_per_page=10)
for manifest in manifests:
    print(manifest)
    break
```

**Expected behavior**
I expect that `list_manifest_properties` is able to properly serialize a valid manifest found in azureCR.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment] 2023-01-24 21:09
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment] 2023-02-16 21:28
Hi @mhaley-tignis , thanks for your report! We haven't got a chance to investigate this issue yet, we'll back to it asap. Thanks for your patience!

**Comment by FlrnFrmm** [comment] 2023-03-29 15:13
I run into the same problem basically, therefore I would like to give it a 👍  also from my side.

**Comment by YalinLi0312** [comment] 2023-04-04 02:50
Hi @FlrnFrmm and @mhaley-tignis , **can you provide the way to upload the manifest in the sample above?** 
In my test, it's not allowed to upload the sample manifest though the operation `upload_manifest()` in our sdk for now. It should not be a problem to serialize the manifest while listing.

cc: @northtyphoon **Should we support upload the sample manifest?** It returns the error below for now:
`azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{"Reason":{}}}]}`

**Comment by mhaley-tignis** [comment] 2023-04-13 18:45
> Hi @FlrnFrmm and @mhaley-tignis , **can you provide the way to upload the manifest in the sample above?**

We are using this github action to build and upload our docker images https://github.com/tignis/docker-github-action which we use with github workflows like this:

```
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push docker image
        uses: tignis/docker-github-action@v1.2.1
        with:
          images: |
            repo-name.azurecr.io/my-private-project
          acr-username: ${{ secrets.AZURE_APP_ID_ACR }}
          acr-password: ${{ secrets.AZURE_PASSWORD_ACR }}
          pip-extra-index-url: ${{secrets.PIP_EXTRA_INDEX_URL}}"
```

Our github action is just a wrapper around the `docker/build-push-action@v2` action.

Hope this helps!

**Comment by YalinLi0312** [comment] 2023-05-04 00:10
Hi @mhaley-tignis , can you try it with our [latest preview](https://pypi.org/project/azure-containerregistry/1.1.0b4/)? We have some updates in deserialization, I don't see any error with the code snippet in `Reproduce` above.

**Comment by mhaley-tignis** [comment] 2023-05-05 13:40
Hi @YalinLi0312, I just tried version `1.1.0b4` and still get the same error. I can see in the [source code](https://github.com/Azure/azure-sdk-for-python/blob/azure-containerregistry_1.1.0b4/sdk/containerregistry/azure-containerregistry/azure/containerregistry/_models.py#L23-L36) that "unknown" is still not a valid architecture for the enum value. Similar for the `ArtifactOperatingSystem` enum. Adding `UNKNOWN = "unknown"` to both seems to solve the problem. This PR illustrates the fixes required to make things work https://github.com/Azure/azure-sdk-for-python/pull/30259.

I am unable to get the dev environment setup so I cannot help get tests in order. I hope this helps.

**Comment by YalinLi0312** [comment] 2023-05-09 17:58
@mhaley-tignis Thanks for your confirm! No worries, I can take over your PR.

**Comment by YalinLi0312** [comment] 2023-05-10 23:43
Hi @djyou, do you think we should support "unknown" as a known value in `architecture` and `os`? I got several issues from customer with the same error so far.

**Comment by lmazuel** [comment] 2023-06-30 20:47
Duplicate of https://github.com/Azure/azure-sdk-for-python/issues/30077

**Closed by lmazuel** 2023-06-30 20:47 UTC
Labels: bug, question, Container Registry, Client, customer-reported, needs-team-attention
