### ISSUE TITLE
azure-mgmt-costmanagement CostManagementClient does not handle api_version

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#18957] opened 2021-05-26 14:02 UTC
- **Package Name**: azure-mgmt-costmanagement
- **Package Version**: 1.0.0
- **Operating System**: Linux
- **Python Version**: 3.7.3

**Describe the bug**
The default api_version used by CostManagementClient  is incorrect (https://github.com/Azure/azure-sdk-for-python/issues/16102, https://github.com/Azure/azure-sdk-for-python/issues/17351). When I specify the correct API version explicitly while constructing CostManagementClient , it is ignored.

**To Reproduce**
1. CostManagementClient(api_version='2019-11-01')
2. attempt to use this client
3. observe it failing because it uses the wrong API version anyway

**Expected behavior**
I expect that when I specify an api_version string when constructing CostManagementClient , that API version is used.

**Comment by swathipil** [comment] 2021-05-26 15:03
@jazelenk Thanks for your question! Directing it to the people who can answer it.

**Comment by msyyc** [comment] 2021-05-27 06:09
Hi @service team, 'azure-mgmt-costmanagement'==1.0.0 according to tag (https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cost-management/resource-manager#tag-package-2020-06). However, in issue 'https://github.com/Azure/azure-sdk-for-python/issues/16102', customer gets the following error which indicates that '2020-06-01' is not supported. Could you help to check it?

`azure.core.exceptions.ResourceNotFoundError: (InvalidResourceType) The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'. The supported api-versions are '2018-05-31,2018-08-31,2018-08-01-preview,2018-10-01-preview,2018-12-01-preview,2019-01-01,2019-03-01-preview,2019-04-01-preview,2019-05-01-preview,2019-10-01,2019-11-01'.`

**Comment by jazelenk** [comment] 2021-05-27 12:29
This is not the same issue as #16102. That issue is about the default api_version being incorrect. This issue is about CostManagementClient ignoring the api_version kwarg.

**Comment by msyyc** [comment] 2021-05-28 02:12
(1) 'azure-mgmt-costmanagement' is single-api package. Its api version is hardcoded and can't be changed anyway.
(2) The problem is a service problem. They merge swagger of '2020-06-01'(https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2020-06-01). Howerver, it seems that '2020-06-01' is not supported until now.

**Comment by msyyc** [comment] 2021-05-28 03:16
@jazelenk  It may take long time to wait for service deployment. How about that : we publish a new package with older api-version '2019-11-01'. 
Please check whether the private package works well:https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/14584/azure-sdk-for-python-track2/track2_azure-mgmt-costmanagement/azure_mgmt_costmanagement-1.0.0b1-py2.py3-none-any.whl. If it works well, we will publish it next week. (please ignore the strange package version)

**Comment by jazelenk** [comment] 2021-05-28 13:47
This issue is not about the problem API version; the issue for that is #16102. This issue is about the fact that CostMangaementClient silently ignores the api_version kwarg. Neither updating the CostManagement RP nor updating the swagger fixes this issue.

**Comment by msyyc** [comment] 2021-05-31 01:46
please pay attention to my comment before:
![image](https://user-images.githubusercontent.com/70930885/120128521-c4a10500-c1f4-11eb-8b1a-a78edcd89271.png)

Anyway, we have merged the PR (https://github.com/Azure/azure-rest-api-specs/pull/14584) to revert to older API. If https://portal.azure-devex-tools.com/api/sdk-dl-pub?p=Azure/14584/azure-sdk-for-python-track2/track2_azure-mgmt-costmanagement/azure_mgmt_costmanagement-1.0.0b1-py2.py3-none-any.whl works well, we could publish new package for you.

**Comment by msyyc** [comment] 2021-06-10 02:27
new package for '20219-11' : https://pypi.org/project/azure-mgmt-costmanagement/2.0.0/

**Comment by jazelenk** [comment] 2021-12-09 09:08
What further information is required?

**Comment by jazelenk** [comment] 2021-12-09 09:28
Sorry! I missed the previous messages back in May. :-( I tested with that package, and unfortunately the api_version argument is  still silently ignored.

**Closed** 2021-12-22 10:04 UTC
Labels: bug, Service Attention, Mgmt, issue-addressed, Cost Management - Query
