### ISSUE TITLE
DeviceCodeCredential from docker run in container does not output the code

### ISSUE THREAD

**Issue by giseliramos** [Azure/azure-sdk-for-python#27543] opened 2022-11-16 17:59 UTC
- **Package Name**:  azure-identity
- **Package Version**:  1.9.0
- **Operating System**: Ubuntu 18.04.6 LTS
- **Python Version**: Python 3.7.5

**Describe the bug**
When using a bash script to call the following container:
```
docker run --entrypoint ./run_python_script.sh <mycontainer>
```
And in the script `run_python_script.sh` from the container I call a python script (by `python -m myscript.py`) that simply invokes the following:
```
creds = DeviceCodeCredential()
```
It simply stops here, and I don't see the output code for the login. If I enter interactively in the container and call directly the python script, I can see the code and the python scripts proceeds normally.

**Comment by xiangyan99** [comment] 2022-11-16 23:48
Thanks for reaching out.

creds = DeviceCodeCredential() only creates the object. It does not do anything. Did you call creds.get_token()?

**Comment by giseliramos** [comment] 2022-11-17 18:40
Hi, I actually use it later in the code to retrieve a secret from key vault:
```
secret_client = SecretClient(f'https://{secret_data["keyvault"]}.vault.azure.net/', credential=creds)
```
If I call directly the python script from inside container, it works ok, by showing the code. But starting from bash script to docker run the container and call the python script from script, it does not show the code :( 
How I use the creds.get_token? Inside the SecretClient constructor?

**Comment by xiangyan99** [comment] 2022-11-17 21:17
creds.get_token will be called automatically when your SecretClient needs a token.

IOW, when you use your SecretClient and call a method, SecretClient calls creds.get_token and get the token on your behalf.

Coud you share more about your scenario?

Is it by design that secret_client = SecretClient(f'https://{secret_data["keyvault"]}.vault.azure.net/', credential=creds) does not try to get token if no other methods are called.

**Comment by giseliramos** [comment] 2022-11-18 12:00
Sure, I'll try to detail the scenario. First, I have a script `trigger_container.sh`, that have the following:
```
docker run --shm-size=512m \
           --ipc=host \
           --rm \
           --gpus=all \
           -v $BASE_DIR:/<workingdir> \
           -w <workingdir> \
           --entrypoint ./run_python_script.sh \
           $CONTAINER_IMG
```
So, it specifies an entrypoint, another script called `run_python_script.sh`. Inside this script (running from the $CONTAINER_IMG):
```
python -m mycustommodule --someargs <etc>
```
And finally in the mycustommodule python part:
```
# auth part
def get_secrets(secrets_items):
    recovered_secrets = {}
    creds = DeviceCodeCredential()
    for secret_name, secret_data in secrets_items.items():
        secret_client = SecretClient(f'https://{secret_data["keyvault"]}.vault.azure.net/', creds)
        recovered_secrets[secret_name] = secret_client.get_secret(secret_data['secret_key']).value
    return recovered_secrets
   ```
   So, if I run by using the script `trigger_container.sh`, when I reach the part of the `get_secrets`, it does not show the code I need to authenticate (I'm on a ssh session, so interactive login is not useful here).

But if I enter in the container (by `docker run -it`) and I call manually with `python -m mycustommodule --someargs <etc>` I'm able to see the code to login.

So maybe is some question with the device code not being able to correctly stdout ou stderr? Or I need to change something in the bash script or python script to enable correct stdout/stderr?

**Comment by xiangyan99** [comment] 2022-11-18 19:55
Thanks for the detailed information.

Can you try add

import logging
logging.basicConfig(level=logging.DEBUG)

in our code so we can get more hints to tell us what happens? :)

**Comment by giseliramos** [comment] 2022-11-18 20:22
Okay, I´ve found the problem. I discovered that I need to use the flag `-it` in the `docker run` command, so by using:
```
docker run -it --shm-size=512m < ... >
```
With this flag I was finally able to see the code :smile: The logging info in debug mode yields the following if I don´t use the docker `-it` flag (I´ve redacted sensitive info):

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mycustomkeyvault.vault.azure.net:443
DEBUG:urllib3.connectionpool:https://mycustomkeyvault.vault.azure.net:443 "GET /secrets/mycustomStorageKey/?api-version=7.3 HTTP/1.1" 401 97
INFO:azure.identity._internal:A token was requested for a different tenant than was configured on the credential, and the requested tenant ID was used to authenticate. Configured tenant ID: organizations, Requested tenant ID aaaa-bbbb-cccc

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "GET /my-tenant-id/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753

DEBUG:msal.authority:openid_config = {'token_endpoint': 'https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/my-tenant-id/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/my-tenant-id/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/my-tenant-id/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG:msal.application:Broker enabled? False
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /my-tenant-id/oauth2/v2.0/devicecode HTTP/1.1" 200 473
DEBUG:msal.telemetry:Generate or reuse correlation_id: xxxxxxxx-xxxxxx
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /my-tenant-id/oauth2/v2.0/token HTTP/1.1" 400 510
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /my-tenant-id/oauth2/v2.0/token HTTP/1.1" 400 510
<last message above is repeated>
```
Not sure if this log is useful. If the log does not give any new info, I guess that you can close the issue. Anyway, thanks for the help!

**Comment by xiangyan99** [comment] 2022-11-18 20:24
The log looks correct.

Thanks for your updates and I will close the issue. :)

**Closed by xiangyan99** 2022-11-18 20:24 UTC
Labels: question, Client, customer-reported, Azure.Identity, needs-author-feedback
