### ISSUE TITLE
Bug bash to find samples for Key Vault that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15112] opened 2020-11-08 19:31 UTC
_Update from @ramya-rao-a_ 

Review the Python samples for Key Vault in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Key Vault Python samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Key+Vault%22&type=&language=python)
- [Key Vault Python  samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=python)

Additionally, ensure the samples that live next to the source code for Service Bus in this repo shows up in [Key Vault Python  samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=python). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by lmazuel** [comment] 2020-11-30 22:59
Duplicate of https://github.com/Azure/azure-sdk-for-python/issues/15122

**Comment by ramya-rao-a** [comment] 2020-12-11 02:10
@lmazuel Re-opening this issue after adding more details to the issue description. Using this issue to find the outdated samples, https://github.com/Azure/azure-sdk-for-python/issues/15122 will be used to actually fix them

**Comment by mccoyp** [comment] 2020-12-12 00:09
Below are the rendering issues found in the [reference docs](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) -- some are rendering/linking related, while some are content-related but need further investigation before fixing in source code.

| Bug type | Description | Source |
|---|---|---|
| Docs content | General KV overview page mentions that 4.x is recommended under "Libraries for data access", but there should also be a note about this under "Version 1.x.x" | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Rendering | Management library overview page is empty on docs, despite there being non-empty (even if sparse) READMEs on GitHub. We'll need to follow up with Scott to see why this is | [link](https://docs.microsoft.com/python/api/overview/azure/keyvault/management?view=azure-python) |
| Linking | Clicking the "Reference" link for azure-keyvault from KV overview page brings up the preview KV overview instead of the legacy overview | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Docs content | README that's linked to from the `azure-keyvault` "GitHub" link in reference docs is in a tag (but not a branch) in the repo. The link to the reference docs from the README is outdated, but I'm not sure how to update it to the legacy docs page since there's no branch with the legacy README content | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Linking | Link for Python in the "Reference" TOC node in the KV service overview page directs to the management package reference, when it should probably link to the general KV overview | [link](https://docs.microsoft.com/azure/key-vault/general/overview) |
| Content/rendering | `begin_create_certificate` shows "HttpResponseError" under "Exceptions" twice, and lists all possible parameters as "Required" when some are optional keyword-only arguments. These issues exist for all methods that have required parameters (denoted by `:param x x:` in their docstring) as well as keyword arguments specified in their docstring (denoted by `:keyword x x:`). Methods that have only keyword arguments denoted by `:keyword x x:` don't render with duplicate exceptions in the reference docs, but their parameters are still listed as "Required". Keyword arguments that are denoted by `:param x x:` in docstrings don't show up as "Required" (see [`JsonWebKey`](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.jsonwebkey?view=azure-python)), but these can't coexist with required parameters | [link](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.certificateclient?view=azure-python#begin-create-certificate-certificate-name--policy----kwargs-) |
| Content/rendering | `KeyVaultKey` has code block examples in its docstring, such that they render in the [package class list](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys?view=azure-python) and aren't put in an "Examples" section like we do for other classes. Should this be changed? Can multiple examples be put in a single docstring using the `Example: literalinclude::` pattern? | [link](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.keyvaultkey?view=azure-python) |

**Comment by mccoyp** [comment] 2020-12-15 20:02
Outdated samples from Azure-Samples:

* [key-vault-recovery-python](https://github.com/Azure-Samples/key-vault-recovery-python)
* [key-vault-python-client-side-encryption](https://github.com/Azure-Samples/key-vault-python-client-side-encryption)
* [key-vault-python-network-acl](https://github.com/Azure-Samples/key-vault-python-network-acl) (broken links)
* [key-vault-python-storage-accounts](https://github.com/Azure-Samples/key-vault-python-storage-accounts)
* [key-vault-python-authentication](https://github.com/Azure-Samples/key-vault-python-authentication)

**Comment by ramya-rao-a** [comment] 2020-12-15 20:11
Thanks @mccoyp!
If we are done with the fact finding mission, lets close this issue and use https://github.com/Azure/azure-sdk-for-python/issues/15122 to actually track updating of these samples

**Closed** 2020-12-15 21:48 UTC
Labels: Client, KeyVault
