### ISSUE TITLE
Unable to parse HTTP header

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-sdk-for-python#737] opened 2016-08-11 14:54 UTC
Same as:  https://github.com/Azure/azure-sdk-for-ruby/issues/400

```
Traceback (most recent call last):
  File "/home/barrett/Installers/pycharm-4.5.4/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/barrett/Installers/pycharm-4.5.4/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/barrett/Git/bnr_robot_software/src/bnr_analytics/bnr_distributed_common/test/scratch.py", line 28, in <module>
    timeout=5)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 972, in receive_subscription_message
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 700, in peek_lock_subscription_message
    return _create_message(response, self)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/_serialization.py", line 100, in _create_message
    elif str(int(float(value))) == value:
ValueError: could not convert string to float: max-age=31536000
```

```
✗ pip freeze | grep azure               
azure==1.0.3
azure-common==1.1.4
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.1
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==1.0.0
azure-servicebus==0.20.2
azure-servicemanagement-legacy==0.20.2
azure-storage==0.31.0
 ✗ python ../bnr_distributed_common/test/scratch.py 
1
PT1M
PT2M
Traceback (most recent call last):
  File "../bnr_distributed_common/test/scratch.py", line 28, in <module>
    timeout=5)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 972, in receive_subscription_message
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/servicebusservice.py", line 700, in peek_lock_subscription_message
    return _create_message(response, self)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicebus/_serialization.py", line 100, in _create_message
    elif str(int(float(value))) == value:
ValueError: could not convert string to float: max-age=31536000
```

**Comment by lmazuel** [comment] 2016-08-11 16:42
Hi @bearrito 

This was supposed to be fixed in 0.20.2 of servicebus (https://github.com/Azure/azure-sdk-for-python/pull/657)
I take a look right now.

**Comment by bearrito** [comment] 2016-08-11 16:53
I was running in a virtualenv, maybe I had site packages enabled. I'll double check on my end.

**Comment by lmazuel** [comment] 2016-08-11 17:23
Based on the "line 100", you are using the 0.20.2 version (the fix in 0.20.2 was added line 87, then the previous exception came from line 99). I wasn't able to reproduce it yet, but seems a real problem.

**Comment by lmazuel** [comment] 2016-08-11 17:29
I executed exactly the same code (it seems):
```python
self.sbs.receive_subscription_message(self.topic_name, 'MySubscription', True, 5)
```
But was not able to reproduce it. Could you confirm the state of your double check?

**Comment by bearrito** [comment] 2016-08-11 17:35
Looks fine. I confirmed I had an issue with my virtualenv.

I think this ticket can be closed.

**Comment by lmazuel** [comment] 2016-08-11 17:39
Ok, no problem! Feel free to re-open the issue if necessary :)

**Closed by lmazuel** 2016-08-11 17:39 UTC
