### ISSUE TITLE
[Tables] Delete Entity Returning Unauthorized, Query Entities Not

### ISSUE THREAD

**Issue by sejohnson-at-griffis** [Azure/azure-sdk-for-python#15653] opened 2020-12-04 17:52 UTC
- **Package Name**:  azure-data-tables (reproducable in azure-cosmosdb-tables)
- **Package Version**: 12.0.0b3
- **Operating System**: Windows 10
- **Python Version**: 3.8.6

**Describe the bug**
After creating a TableClient from azure.data.tables.aio, a call to table_client.query_entities is successful. Just a few lines later, a call to table_client.delete_entity is not, and returns a ClientAutheniticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

I've tried this with azure.cosmosdb.table as well: Using similar calls, the query call is successful, but the delete call returns an AzureSigningError: Incorrect padding.

I have verified that the key is 88 characters long, ends with ==, and is DIRECTLY copied from the storage account in question. It obviously works for the query_entities call.

**To Reproduce**
1. Create an Azure Storage Account, add a table to it, and name the table "Locator". Add a few entities with a column called LocatorHash, with any string value you like.
2. Run the following code:

```
    from azure.data.tables.aio import TableClient
    from azure.core import MatchingConditions

    table_name = 'Locator'
    email_hash = '...' #Can be any string value contained in the LocatorHash column
    table_client = TableClient(account_url='https://<YOURACCOUNTNAME>.table.core.windows.net', table_name=table_name, credential=os.environ['STORAGE_ACCOUNT_ACCESS_KEY'])
    async with table_client:
        locator_entities = table_client.query_entities(filter=f"LocatorHash eq '{email_hash}'")
        coroutines = []
        async for locator_entity in locator_entities:
            logging.info(f"Deleting record: {locator_entity}")
            # error occurs on this line
            await table_client.delete_entity(row_key=locator_entity['RowKey'], partition_key=locator_entity['PartitionKey'], etag=locator_entity['_metadata']['etag'], match_condition=MatchConditions.Unconditionally)
```

**Expected behavior**
Entities are deleted rather than receiving an AuthError.

**Screenshots**

*When using azure.data.tables.aio*
![image](https://user-images.githubusercontent.com/73712865/101196573-27d32580-361e-11eb-85e7-64d1bd034982.png)

*When using azure.cosmosdb.table -- note, had to edit code to be synchronous*
![image](https://user-images.githubusercontent.com/73712865/101196973-b8aa0100-361e-11eb-98e5-97de9f73e227.png)

**Comment by annatisch** [comment] 2020-12-06 17:41
Thanks @sejohnson-at-griffis - Could you please try removing the `etag` and `match_condition` parameters from the delete call? `Unconditionally` is the default behaviour, so it should work as expected.
I have a suspicion this error is because the `etag` value is not a valid combination with `Unconditionally` - and rather than catching it we maybe sending the extra header to the service and causing request signing issues....

**Comment by sejohnson-at-griffis** [comment] 2020-12-07 16:01
> Thanks @sejohnson-at-griffis - Could you please try removing the `etag` and `match_condition` parameters from the delete call? `Unconditionally` is the default behaviour, so it should work as expected.
> I have a suspicion this error is because the `etag` value is not a valid combination with `Unconditionally` - and rather than catching it we maybe sending the extra header to the service and causing request signing issues....

Hey there,

Thanks for the suggestion. Unfortunately, same error. I've actually tried just about every combination of those parameters I can think of... and I can't think of a reason the etag would cause an auth error anyway, as it's not part of the auth header in the first place, right?

I'm also struggling to find the actual documentation for this library anywhere. All I can find is a brief one-page document.

**Comment by sejohnson-at-griffis** [comment] 2020-12-07 16:57
I tried using a batched execution mode as well (code will follow). The code here actually completes execution successfully... but does not delete the entities from the table! (????) Is it just pretending to delete them and calling it a day?

Notes:
I have to build a list out of the return from query_entities because query_entities returns an "AsyncItemPaged", which I cannot filter or iterate over except with an async for loop. 

Build a set (distinct list) of PartitionKeys (as batches can only cover one PartitionKey at a time).

For each PartitionKey in this batch, delete the entities belonging to it.

```
async with table_client:
        # try:
        locator_entities = table_client.query_entities(filter=f"LocatorHash eq '{email_hash}'")
        locator_entity_list = []
        async for locator_entity in locator_entities:
            locator_entity_list.append(locator_entity)
        for key in { entity['PartitionKey'] for entity in locator_entity_list }:
            batch = table_client.create_batch()
            for locator_entity in filter(lambda x: x['PartitionKey'] == key, locator_entity_list):
                delete_entity = {}
                delete_entity['row_key'] = locator_entity['RowKey']
                delete_entity['partition_key'] = locator_entity['PartitionKey']
                batch.delete_entity(row_key=locator_entity['RowKey'], partition_key=locator_entity['PartitionKey'])
            table_client.send_batch(batch)
```

**Comment by seankane-msft** [comment] 2020-12-07 19:11
Here is the documentation for the async library: https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables.aio.tableclient?view=azure-python-preview

Here is the documentation for the sync library: https://docs.microsoft.com/en-us/python/api/azure-data-tables/azure.data.tables?view=azure-python-preview

I worked with your initial code and I was able to confirm that deletes were happening. Here is the full snippet that I was able to get working:

```
from azure.data.tables.aio import TableClient
from azure.core import MatchConditions
from azure.core.exceptions import ResourceExistsError
import random, string, asyncio, logging

def random_string(N=50):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))

async def delete_entities():
    base_entity = {
        "PartitionKey": "pk001",
        "RowKey": "rk000",
        "LocatorHash": ""
    }

    table_name = 'Locator'
    email_hash = "" #Can be any string value contained in the LocatorHash column
    table_client = TableClient(account_url=f'https://{account_name}.table.core.windows.net', table_name=table_name, credential=credential)
    try:
        await table_client.create_table()
    except ResourceExistsError:
        pass

    for i in range(25):
        try:
            new_entity = base_entity.copy()
            new_entity["LocatorHash"] = random_string()
            new_entity["RowKey"] += str(i)
            await table_client.upsert_entity(new_entity)
            email_hash = new_entity["LocatorHash"]
        except ResourceExistsError:
            pass

    async with table_client:
        f = f"LocatorHash eq '{email_hash}'"
        locator_entities = table_client.query_entities(filter=f)

        async for locator_entity in locator_entities:
            print(f"Deleting record: {locator_entity['PartitionKey']}, {locator_entity['RowKey']}")
            # error occurs on this line
            await table_client.delete_entity(row_key=locator_entity['RowKey'], partition_key=locator_entity['PartitionKey'], etag=locator_entity['_metadata']['etag'], match_condition=MatchConditions.Unconditionally)

async def main():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(asyncio.new_event_loop())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(await delete_entities())

if __name__ == "__main__":
    asyncio.run(delete_entities())
```

It's possible I'm misunderstanding this code, in which case please clarify for me. Otherwise, this code is functional and I was able to confirm in the Storage Explorer that the last inserted entity was then deleted.

**Comment by seankane-msft** [comment] 2020-12-07 19:26
In addition @sejohnson-at-griffis can you confirm the environment variable is correctly stored? I've accidentally stored env vars with quotes around them and that will cause issues on authentication.

**Comment by seankane-msft** [comment] 2020-12-07 19:38
> batch.delete_entity(row_key=locator_entity['RowKey'], partition_key=locator_entity['PartitionKey'])
>             table_client.send_batch(batch)

@sejohnson-at-griffis In this last line the `send_batch` needs an `await` before it, that is likely the reason the async batching was not working either.

**Comment by sejohnson-at-griffis** [comment] 2020-12-07 19:47
@seankane-msft 

Looks like adding the "await" operator to the batch call worked -- the records were successfully deleted. I'd prefer not to have to use the acrobatics required to group the query return into a set of partition keys, but I still can't get the original method (the same one you used) to work. Not sure why. Obviously my key/environment variable is working correctly if I can use the batch calls...

I've even directly copied your code from `async with table_client` down to the delete call. Same error. Notably, the error still doesn't occur until the delete call -- the query completes successfully.

**Comment by seankane-msft** [comment] 2020-12-07 20:02
It looks like this code is running within an Azure Functions library, if that is correct could this possible be an issue with the Azure Functions code itself? Without being able to reproduce the issue it is difficult for me to assist with debugging. I concur that the issue is unlikely to be with the key because your query call is working as intended.

**Comment by sejohnson-at-griffis** [comment] 2020-12-07 20:31
You're correct, it is running in an Azure Function. However, I'm not sure why that would cause the issue, unless the Function is modifying the HTTP headers on the way out... and it doing that to _only_ the delete call seems unlikely. I also tried directly copying your code from above into a plain 'ol .py file and running it... but I'm getting a RuntimeError('Event loop is closed') when it hits the `async with table_client` line. Could this be a Windows issue?

**Comment by annatisch** [comment] 2020-12-08 17:01
Hi @sejohnson-at-griffis - could you give us an example of what a typical row key and partition key look like for the entities you're trying to delete? e.g. any special characters, formatting, length etc.
I'm wondering if there might be a bug in the auth request signing, which uses this information to form the auth header....

**Comment by sejohnson-at-griffis** [comment] 2020-12-08 17:06
@annatisch 

Sure.

The PartitonKey is just a simple string -- there are only a dozen or so. I can't provide an exact value (business-specific stuff), but "A Simple String" is a perfect example. All alpha, no numbers, no special characters. Guaranteed. The RowKey is an email address: johndoe@test.com. The only other column here is the Hash column, which is an alphanumeric string. (It's a SHA256 hash in X2 format.)

Interesting additional information: I tried going to _full_ manual route yesterday: REST API. I manually signed the requests and tried sending them over both `aiohttp` (async) and `requests`. Same result! Using manual signing, I could get the query to work, but the delete would return a 403 with the same header.

**Comment by annatisch** [comment] 2020-12-08 17:14
Thanks @sejohnson-at-griffis!
That's very interesting! Is it possible that you have authorization for querying but not deleting of entities? Though I don't recall that you can get that kind of granularity with an account key (account owner) as opposed to a SAS token.... as the docs say:
```
This operation can be performed by the account owner and by anyone with a shared access signature that has permission to perform this operation.
```

We can re-test using similar values as you to keep trying to repro... is this the guide you used to implement your manual request signing?
https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key

**Comment by sejohnson-at-griffis** [comment] 2020-12-08 17:19
@annatisch 

That is correct -- I used the Shared Key Lite format. A couple of other details:

I'm running this code in a local Azure Functions dev environment. It's running on the Python 3.8.6 stack. It's a HTTP-triggered function, which I'm using Insomnia to trigger. I'm on Windows 10 Build 18363 (I am currently blocked from upgrading due to the NVMe SSD issues). It might be worth spinning up a local Azure Function to see if it's an issue with the Azure Functions runtime, though that does seem unlikely...

I thought about it possibly being an access level issue, but that seems to have been dispelled -- obviously, I can delete records through the `async batch` method, so unless there's a bug with the permissioning of _specifically_ the non-batch method, I don't think that's it...

**Comment by annatisch** [comment] 2020-12-09 18:31
Hi @sejohnson-at-griffis - are you able to confirm whether the `delete` operation fails for _every_ entity - or maybe just one is raising the error? I'm wondering if one of the email address has an interesting character in it that's preventing the rest from deleting.
For example, if you wrap the delete operation in a try/except - do any of the deletes complete successfully?

We had a bug in the blobs SDK where operations on a blob name with an "=" character in them were failing authentication exclusively on the async pipeline - which definitely has familiar symptoms to what we're seeing here.
Alternatively - if it _is_ consistent for every entity - I wonder if it's in the urlencoding of the "@" character in the email addresses.
@seankane-msft - could you re-run your test using a random "foo@bar.com" email address to make sure those characters are encoding correctly for both the URL and the auth signing?

**Comment by sejohnson-at-griffis** [comment] 2020-12-09 18:41
Hey @annatisch - As far as I can tell, it's failing for every `delete`, but I'm only really testing with my own email address, sejohnson@griffisresidential.com. I can just about guarantee the PartitionKey isn't causing the issue, as those values are the simplest of simple strings -- just alphas and spaces. Additionally, the way I was originally doing this had a try/catch wrapped around the delete calls. When I ran it, I never got a delete to work correctly -- meaning either I was just incredibly (un?)lucky and it failed on just the first one each time, or it was failing on everything. Either way, it does seem that the email address row key is the only common denominator, especially given that it fails on REST as well.

As for the URL encoding, that's definitely a possibility... I think the only request that gets an email passed to it is the delete request, so that could explain why only that one is failing. I wonder if get_entity would fail if passed an email with an "@" in it? Let me see if I can make some time today to poke around.

**Comment by seankane-msft** [comment] 2020-12-09 18:46
@sejohnson-at-griffis I was able to confirm what @annatisch hypothesized. Changing my RowKey to be `foo@bar.com` would fail on a delete. It also fails on a `upsert_entity` call, but will succeed on a `create_entity`. The `get_entity` was unsuccessful as well.

**Comment by sejohnson-at-griffis** [comment] 2020-12-09 18:47
@seankane-msft I hate that this is a bug for you guys, but it is so validating to know that I'm not crazy!

**Comment by annatisch** [comment] 2020-12-09 19:12
Awesome @seankane-msft - we're making progress!
Let's add a test for this in the test suite and start focusing on this method:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/tables/azure-data-tables/azure/data/tables/_authentication.py#L59
And this method:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/tables/azure-data-tables/azure/data/tables/_table_client_base.py#L64
Which I would suspect are the two most likely sources of missing urlencoding (or double urlencoding maybe?).

**Comment by seankane-msft** [comment] 2020-12-15 22:01
@sejohnson-at-griffis I have a fix out on PR #15813 , hopefully we can get this resolved soon. This bug fix will go out with the GA release, which is being planned for early next year.

**Comment by sejohnson-at-griffis** [comment] 2020-12-15 22:17
Thanks @seankane-msft and @annatisch! At least we've got the batch workaround until it goes through. Appreciate the hard work!

**Comment by seankane-msft** [comment] 2020-12-16 16:49
@sejohnson-at-griffis good news, I was able to fix this issue and get it merged in this morning. Thank you again for reporting and for your patience while we fixed it up. This will go out with our GA release early next year. If you have no other questions, I will close this issue tomorrow. Otherwise, let me know

**Closed** 2020-12-18 19:06 UTC
Labels: Tables, customer-reported, needs-team-attention, question
