### ISSUE TITLE
Invalid Vault URL doesn't throw exception

### ISSUE THREAD

**Issue by asimarora** [Azure/azure-sdk-for-python#16970] opened 2021-02-26 19:13 UTC
If we call this API with Invalid Key Vault but with a Good Service Principle it still returns a valid "azure.keyvault.secrets._client.SecretClient" object instead of throwing an exception. Please either provide an API something like isValid() or return a NULL object or any third option which suits design best. 

secret_client = SecretClient(vault_url="https://abcd.vault.azure.net/", credential=credential)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 416b3381-c82f-c348-9358-59c20e9aee1f
* Version Independent ID: be9b2deb-9d8c-d17e-4208-c3bb5d0ee933
* Content: [azure.keyvault.secrets.SecretClient class](https://docs.microsoft.com/en-us/python/api/azure-keyvault-secrets/azure.keyvault.secrets.secretclient?view=azure-python#feedback)
* Content Source: [docs-ref-autogen/azure-keyvault-secrets/azure.keyvault.secrets.SecretClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-keyvault-secrets/azure.keyvault.secrets.SecretClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment] 2021-02-26 20:55
Thanks for the feedback, we’ll investigate asap.

**Comment by mccoyp** [comment] 2021-02-26 23:34
Hello, thank you for creating an issue! This is expected behavior; client constructors don't check whether a given vault exists, since this would require making a call to the service. If the vault URL provided to the client is invalid, or you don't have necessary permissions, an error from [azure-core](https://docs.microsoft.com/python/api/azure-core/azure.core.exceptions?view=azure-python) will raise when you perform an operation.
```
>>> vault_url = "https://nonexistentvaultdoesnotexist.vault.azure.net"
>>> client = SecretClient(vault_url, DefaultAzureCredential())
>>> client.get_secret('secret_name')
Traceback (most recent call last):
...
azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001E313946198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```
You raise a good though -- some validation upon construction would be convenient. I can leave this issue open for now and discuss with the team whether this would be possible, and come back with an update.

**Comment by asimarora** [comment] 2021-02-27 17:27
> Hello, thank you for creating an issue! This is expected behavior; client constructors don't check whether a given vault exists, since this would require making a call to the service. If the vault URL provided to the client is invalid, or you don't have necessary permissions, an error from [azure-core](https://docs.microsoft.com/python/api/azure-core/azure.core.exceptions?view=azure-python) will raise when you perform an operation.
> 
> ```
> >>> vault_url = "https://nonexistentvaultdoesnotexist.vault.azure.net"
> >>> client = SecretClient(vault_url, DefaultAzureCredential())
> >>> client.get_secret('secret_name')
> Traceback (most recent call last):
> ...
> azure.core.exceptions.ServiceRequestError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001E313946198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
> ```
> 
> You raise a good though -- some validation upon construction would be convenient. I can leave this issue open for now and discuss with the team whether this would be possible, and come back with an update.

**Comment by mccoyp** [comment] 2021-03-01 21:09
Update: this is something we'll keep in the back of our minds moving forward, but validating the client via the vault URL isn't something we'll add at the moment. Since an operation's success requires a valid vault and any necessary permissions, validating that the URL points to an existing vault doesn't provide very much information about whether or not operations will succeed. I would recommend wrapping service calls in try/except blocks that check for the errors defined in [azure-core](https://docs.microsoft.com/python/api/azure-core/azure.core.exceptions?view=azure-python) when necessary.

Thank you again for providing this feedback! I'll close this issue, but please feel free to ask any further questions.

**Closed by mccoyp** 2021-03-01 21:09 UTC
Labels: Client, KeyVault, bug, customer-reported

**Comment by asimarora** [comment] 2021-03-02 08:10
Hello,
I still don't think issue closed is justified because Constructor is returning a valid object even there is nothing initialized properly. 
Anyhow thanks for looking into this.
