### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Imekan** [Azure/azure-sdk-for-python#19387] opened 2021-06-22 14:22 UTC
I am trying to run a selenium webdriver script using python  but I am getting that error as shown in the caption.

Any help?

**Comment by chlowell** [comment] 2021-06-23 16:38
Thanks for opening this issue. Which Azure SDK libraries are you using? Could you please add a small code sample that reproduces this error?

**Comment by Imekan** [comment] 2021-06-24 11:00
Thank you for your swift response

 see the script below
This is a selenium_python script to register a user on ebay site
import time
from lib2to3.pgen2 import driver

from selenium import webdriver
driver = webdriver.Chrome=("C:\\Users\\ienang\\Documents\\chromedriver.exe")

# Locate the url to invoke the browser(ebay url)
driver.get("https://www.ebay.com/")

myPageTitle = driver.title
print(myPageTitle)

# to maximize the window
driver.maximize_window()

# To sign into ebay site
# sign_in = ***@***.***="mainContent"]/div[3]/span/a')
# sign_in.click()

# Email = ***@***.***'
# email = ***@***.***="userid"]')
# email.send_keys(Email)
# time.sleep(4)
# driver.quit()

# to click on register
register = ***@***.***="gh-ug-flex"]/a')
register.click()

# Fill the form
Firstname = "Imekan"
firstname = driver.find_element_by_id("firstname")
firstname.send_keys(Firstname)

Lastname = 'Enang'
lastname = driver.find_element_by_name("lastname")
lastname.send_keys(Lastname)

Email = ***@***.***'
email = driver.find_element_by_name("Email")
email.send_keys(Email)

Password = 'Ukam54321@'
password = driver.find_element_by_name("password")
password.send_keys(Password)
time.sleep(3)

# Click on Create account
createButton = ***@***.***=EMAIL_REG_FORM_SUBMIT]")
createButton.click()














On 6/23/21, Charles Lowell ***@***.***> wrote:
> Thanks for opening this issue. Which Azure SDK libraries are you using?
> Could you please add a small code sample that reproduces this error?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Azure/azure-sdk-for-python/issues/19387#issuecomment-866992998


-- 
"If we place cheap value on human life and say we love God, we lie.
Value for life is the reason for good hospitals, roads, security,
etc." - Sam Adeyemi

**Comment by chlowell** [comment] 2021-06-24 16:13
Thanks for the details. I don't see the Azure SDK in your script, so I assume this error is from Selenium. I'm closing this issue because it doesn't appear related to the Azure SDK (please comment or reopen if I missed the connection). [Selenium docs](https://selenium-python.readthedocs.io/) or [StackOverflow](https://stackoverflow.com/questions/tagged/python+selenium) are better resources for help with Selenium.

**Closed by chlowell** 2021-06-24 16:13 UTC
Labels: customer-reported, needs-team-attention, question
