### ISSUE TITLE
azure.cosmos hierarchical partition key bug

### ISSUE THREAD

**Issue by Willem-J-an** [Azure/azure-sdk-for-python#37638] opened 2024-09-30 12:19 UTC
- **Package Name**: 
azure.cosmos
- **Package Version**: 
4.7
- **Operating System**:
any
- **Python Version**: 
any

**Describe the bug**
[See source here](https://github.com/Azure/azure-sdk-for-python/blob/d42433bf36fc85eaf45489d0f7946533f637c4dd/sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py#L159)
When using hierarchical partition key in azure cosmos, there seems to be a bug. The code checks that the amount of provided partition keys is not greater or equal than the amount of keys configured. The code fails if I provide 2 values for my 2 keys.
```
ValueError: 2 partition key components provided. Expected less than 2 components (number of container partition key definition components).
```

[The docs](https://learn.microsoft.com/en-us/azure/cosmos-db/hierarchical-partition-keys?tabs=python%2Cbicep#perform-a-keyvalue-lookup-point-read-of-an-item) show that a 3 part key is configured, and 3 values are provided.

**To Reproduce**
1. Configure hierarchical partition key on a container
2. query it and provide all the corresponding key parts

**Expected behavior**
I would expect if I configure two hierarchical keys, and provide the two corresponding hierarchical partition values that should work.

**Comment by Willem-J-an** [comment] 2024-09-30 12:24
The code now also misaligns with the error messages, expected value parts LESS THAN key parts; if I replace the >= operator with > it aligns to the message, and works.
```py
        if len_pk_value > len_paths:
            raise ValueError(
                f"{len_pk_value} partition key components provided. Expected less than {len_paths} " +
                "components (number of container partition key definition components)."
            )
```

**Comment by kashifkhan** [comment] 2024-09-30 13:24
Thank you for the feedback @Willem-J-an . We will investigate and get back to you asap.

**Comment by bambriz** [comment] 2024-10-16 22:43
Hello @Willem-J-an thanks for bringing this to my attention. The part of the code you posted is actually working as intended. This code should trigger when a prefix partition query is being made, however it shouldn't be triggering if the length of the provided partition key matches the length in the partition key definition, so this would indicate there is a bug in where the SDK determines if this is a prefix partition key query ( a prefix partition key query is when you are using an incomplete hierarchical partition key to make a query ie a full partition key would be USA/California/Los Angeles and incomplete one would be USA/California or just USA) or a regular query. Is this for the sync or async client?

**Comment by Willem-J-an** [comment] 2024-10-17 02:59
Hi, it's for the sync client, all I'm doing is:
```py
container.query_items(query, (part1, part2) )
```
Query is just select * from c as r order by r.uploaded_time
The partition key has 2 parts, and I'm providing both.

**Comment by bambriz** [comment] 2024-10-17 20:48
Hi @Willem-J-an thank you for your quick response. I understand the issue now. My suspicion was correct, there seems to be a check for the partition key to be a list, and by passing it as a tuple it ends up bypassing that check and attempting your query as a prefix partition query. I will go ahead and add a fix to this, but that won't be available until the next release, so I would suggest to pass the pk value as a list for now.

**Comment by bambriz** [comment] 2024-10-28 21:52
@Willem-J-an this [PR 38136](https://github.com/Azure/azure-sdk-for-python/pull/38136) should allow the usage of tuples when it is merged and added to the next available release.

**Closed** 2024-11-12 19:40 UTC
Labels: question, Cosmos, Service Attention, Client, customer-reported, needs-team-attention
