### ISSUE TITLE
Add DefaultAzureCredential authentication support to ContentModeratorClient

### ISSUE THREAD

**Issue by YossiMicrosoft** [Azure/azure-sdk-for-python#32171] opened 2023-09-21 14:16 UTC
**Is your feature request related to a problem? Please describe.**
As part of the zero-touch work, we want to have a managed identity authentication for all of our services.

**Describe the solution you'd like**
I would like that ContentModeratorClient will support DefaultAzureCredential as authentication method.

**Describe alternatives you've considered**
I have tried using something like:
```
token_url: Final[str] = "https://cognitiveservices.azure.com/.default"
# Get the Azure Credential
credential = DefaultAzureCredential()
# Acquire a token
api_key: str = credential.get_token(token_url).token
```
And it didn't worked.

**Additional context**
Using:
azure-cognitiveservices-vision-contentmoderator = "1.0.0"

**Comment by swathipil** [comment] 2023-09-21 15:39
Hi @YossiMicrosoft - Thanks for opening an issue. We'll take a look at this asap.
In the meantime, would you be able to provide the following information?
* An error log/stack trace.
* A code sample to reproduce the issue.

**Comment by pvaneck** [comment] 2023-09-22 23:17
While the `azure-cognitiveservices-vision-contentmoderator` source code does reside in this repository, it seems the team maintaining it have long since abandoned it (latest release in 2019), so it's very unlikely this will get implemented unfortunately. 

I marked this as a feature request for now, but some discussions will need to happen with the Cognitive Services team regarding the future of how users should be interacting with their services.

**Comment by YossiMicrosoft** [comment] 2023-09-26 11:51
If I have DefaultAzureCredential token, is there a way for me to acquire the resource key?
That way even if it will not be implemented directly the same logic could be used.

**Comment by pvaneck** [comment] 2023-09-28 01:47
You can try using the `azure-mgmt-cognitiveservices` package to query the resource keys for the service. An example can be found here:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitiveservices/azure-mgmt-cognitiveservices/generated_samples/list_keys.py

Looks like you'll need your subscription ID, resource group name, and cognitive services account name (I believe this corresponds to name you gave your content moderator service).

Then can get the keys by accessing the response `key1` or `key2` fields.

```python
client = CognitiveServicesManagementClient(
    credential=DefaultAzureCredential(),
    subscription_id="sub-id",
)
keys = client.accounts.list_keys(
    resource_group_name="rg-name",
    account_name="content-moderator-service-name",
)
print(keys.key1)
print(keys.key2)
```

**Comment by lmazuel** [comment] 2024-05-08 22:17
Closing this issue, as the service is deprecated and no longer functional:
https://learn.microsoft.com/en-us/azure/ai-services/content-moderator/overview

> Azure Content Moderator is being deprecated in February 2024, and will be retired by February 2027. It is being replaced by [Azure AI Content Safety](https://learn.microsoft.com/en-us/azure/ai-services/content-safety/overview), which offers advanced AI features and enhanced performance.

Please use the azure-ai-contentsafety SDK instead:
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/contentsafety/azure-ai-contentsafety

**Closed by lmazuel** 2024-05-08 22:17 UTC
Labels: feature-request, question, Cognitive Services, Client, customer-reported, needs-team-attention, Cognitive - Content Moderator
