### ISSUE TITLE
is_current_version returning none instead of false

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-python#28447] opened 2023-01-23 10:30 UTC
- **Package Name**:  azure.storage.blob
- **Package Version**: 12.14.1
- **Operating System**:linux
- **Python Version**: 3.10.8

**Describe the bug**

When listing blobs, the is_current_version property is none for blobs that have different versions but is not the current version.
When listing blob, the is_current_version property is none for blobs that have no other versions.

**To Reproduce**
1. Make a container with a blob that has 2 version and a blob that none. Then run
```
blobs = container_client.list_blobs(include=["versions"])
for blob in blobs:
    print(blob)
```

**Expected behavior**
When listing blobs, the is_current_version property is *false* for blobs that have different version but is not the current version.
When listing blobs, the is_current_version property is *true* for blobs that have different versions but it is the current version.
When listing blobs, the is_current version property is *true* or none for blobs that have no other versions.

**Additional context**

**Comment by kashifkhan** [comment] 2023-01-23 14:19
Thank you for the feedback @AWendland-CryptoCompare . We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment] 2023-01-23 23:56
Hi @AWendland-CryptoCompare Alex, thanks for bringing this up. I did some testing to confirm it does seem like we never really set `is_current_version` to `False`. It is either `True` or `None`. This seems to be because the service never returns the `IsCurrentVersion` property on blobs that are not the current version, meaning we interpret that as `None` rather than `False`.

While I don't feel this is not a big issue since `if blob.is_current_version` will evaluate the same whether the value is `False` or `None`, there is perhaps an opportunity to improve this slightly. We could consider checking to see if a blob has a `VersionId` property and does not have `IsCurrentVersion`, we could manually set `is_current_version` to `False`.

**Comment by AWendland-CryptoCompare** [comment] 2023-01-24 07:57
Hi Jacob, thanks for looking into it. What you say makes sense. The main behaviour I found counter intuitive is that blobs with no other versions have is_current_version property set to none - the same as a blob that has other versions and is not the current version.
Personally I found it counter intuitive to have to check the version_id as well as the is_current_version to determine if a blob had other versions.
Thanks for working on this, any improvements would be greatly appreciated.

**Comment by vincenttran-msft** [comment] 2023-02-17 23:44
Hi @AWendland-CryptoCompare Alex, sorry for the delay on this! I have just attached the pull request that will fix this behavior to better reflect `is_current_version` in all cases you have mentioned in your original post. Copying from your provided expected behavior:

**Expected behavior**
When listing blobs, the is_current_version property is **false** for blobs that have different version but is not the current version.
When listing blobs, the is_current_version property is **true** for blobs that have different versions but it is the current version.
When listing blobs, the is_current version property is **true** or none for blobs that have no other versions.

Thanks again for your contribution! This issue will close alongside the merge of the attached pull request 😄

**Comment by AWendland-CryptoCompare** [comment] 2023-02-20 14:17
Hi @vincenttran-msft, thanks so much for the feature. That is really handy :)

**Comment by jalauzon-msft** [comment] 2023-02-22 00:23
Hi @AWendland-CryptoCompare Alex, so we are having some internal discussions around this change, and I wanted to check back in with you to get a little more detail about what you are trying to accomplish. Would you mind sharing a little more about your scenario and why you need to check if a blob has other versions in this way?

Also are you working with multiple Storage accounts where some have versioning enabled and others do not? I could see this particularly being the bigger issue since there wouldn't be a good way to differentiate between a blob with other versions on an account with versioning and just a blob on an account without versioning.

**Comment by AWendland-CryptoCompare** [comment] 2023-02-22 09:29
Hi Jacob @jalauzon-msft, sure thing:
We discovered that our azure storage costs where ballooning. The cause was version control on a storage account that one team had turned on to do data cleaning, however another part of the company was rewriting files sometimes (this was to do with quarantining late messages and inputting them in the correct files). The result was a large volume of old versions of a certain type.
I then needed to go through the files of this type to delete the old versions. I did using list_blobs with the name_starts_with parameter and the includes parameter set to add versions. Then I needed to identify old versions of the blobs, to do this I used the is_current_version property however my first dry run was deleting files that were the latest version of files (as some of the files were not overwritten). This is when I realised that blobs without another version had this property set to none as well as blobs that were not the latest version. I added in some additional logic to catch this by checking the version_id field which is set to none if there are no other versions. - This is why I thought the logic of this field was slightly off as I anticipated it being true even if there were not other versions.
I personally do work with multiple accounts where some have versioning turned on, and others do not. Though the cause of this was turning on versioning when we do a data clean and not being fully aware of other micro-processes.  
Please let me know if more context is required to help you.

**Comment by jalauzon-msft** [comment] 2023-03-23 18:03
Hi @AWendland-CryptoCompare Alex, thanks for your patience on this issue. After some further internal discussion we've come to the conclusion that making the change from `None` to `False` in the case where blobs have other versions but is not the latest would be considered a breaking change to the library is a subtle way. We have a very strict policy around breaking changes, so unfortunately, we won't be able to make this change as is.

Hopefully using the workaround of also checking `version_id` is sufficient for your scenario. If not, and you feel strongly about wanting a change to the SDK here, our only option for a fix would likely be adding a new property with a different name that exhibits the correct behavior and deprecating the old one (we wouldn't be able to remove it). Please let us know if you would like us to consider this but note it would go into the backlog and may take a while for us to get to :).

Another possible option for a workaround (arguably less efficient than your current one) is that you can check whether versioning is enabled on a Storage account programmatically using the `BlobServiceClient,get_service_properties` API. This returns a dictionary where you'd want to look for the `is_versioning_enabled` bool element (not 100% on the name). Then you could just not delete any blobs on accounts where versioning is disabled.

Hopefully one of these workarounds can work for you and sorry we weren't able to make the fix as is. Thanks.

**Comment by AWendland-CryptoCompare** [comment] 2023-03-24 07:34
Hi @jalauzon-msft Jacob, thanks for the update on this change. I can only imagine the strange implication of changing the response variable!

If you could add this task to the backlog, I believe other users would find it useful. Though I guess you could gauge this depending on if anyone else finds this post. I understand this might be a low priority issue and not fixed for quite a while.

Thanks for the additional information for a work around!

**Comment by jalauzon-msft** [comment] 2023-12-15 23:03
Closing this as this is not a change we will be able to make easily. If anyone finds this issue and is experiencing something similar to OP, please see the couple of workarounds suggested throughout the discussion. If the described workarounds do not end up resolving your issue, please feel free to comment or open a new issue. Thanks.

**Closed by jalauzon-msft** 2023-12-15 23:03 UTC
Labels: feature-request, Storage, customer-reported, needs-team-attention
