### ISSUE TITLE
SubscriptionClient Error: AttributeError: 'InteractiveBrowserCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by rfernand2** [Azure/azure-sdk-for-python#10274] opened 2020-03-12 09:10 UTC
azure-identity==1.2.0
azure-mgmt-resource==2.2.0
python==3.6.10
Windows 10

**Describe the bug**
The following code to list subscriptions gives the above error:

```
from azure.identity import InteractiveBrowserCredential
from azure.mgmt.resource import SubscriptionClient

credential = InteractiveBrowserCredential()  
sub_client = SubscriptionClient(credentials=credential)
ops = sub_client.operations
subs = ops.list()
for sub in subs:
    print("sub=", sub)
```

**Comment by chlowell** [comment] 2020-03-12 14:02
Closing this as a duplicate of #9756. In brief, no azure-mgmt-* accepts azure-identity credentials. Work to change that is tracked by #9310.

**Closed by chlowell** 2020-03-12 14:02 UTC
Labels: Azure.Identity, Mgmt
