### ISSUE TITLE
Bug - CSS displaying odd size.

### ISSUE THREAD

**Issue by christianrolph** [Azure/azure-sdk-for-python#16434] opened 2021-01-30 18:51 UTC
It looks like the CSS for some of the bullets is showing font much larger than others. See the image below.
![image](https://user-images.githubusercontent.com/55676161/106365250-17bb8780-62e9-11eb-89a3-1308112b5e84.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d7ab9a-6ee1-2956-b11f-48c3b0028202
* Version Independent ID: b455c79b-93a6-aaa3-8f0d-b2cc3d60db77
* Content: [azure.cognitiveservices.vision.face.operations.PersonGroupPersonOperations class](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-face/azure.cognitiveservices.vision.face.operations.persongrouppersonoperations?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cognitiveservices-vision-face/azure.cognitiveservices.vision.face.operations.PersonGroupPersonOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-cognitiveservices-vision-face/azure.cognitiveservices.vision.face.operations.PersonGroupPersonOperations.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by xiangyan99** [comment] 2021-02-01 16:42
Thanks for the feedback, we’ll investigate asap.

**Comment by lmazuel** [comment] 2021-12-17 18:11
The issue is caused by an incorrect conversion from MD (origin format of the doc) to RST (needed format by the doc processor). This issue has been fixed in recent version of the generator (aka track2).

Keeping this issue opened, until Face SDK comes to track2

**Comment by udbj** [comment] 2022-10-29 14:59
Still looks weird today, almost one year later. 
![font_size](https://user-images.githubusercontent.com/20730509/198838523-30941ccf-ffc5-4bdb-a3a5-8795a298fafb.png)

**Comment by xiangyan99** [comment] 2023-08-18 16:24
@danieljurek I don't think they have updated to track2.

**Comment by danieljurek** [comment] 2023-08-21 19:33
Assigning to @kristapratico for routing. From Laurent's comments above, this issue will be resolved when face releases a track 2 package.

**Closed** 2024-03-15 18:17 UTC
Labels: bug, Docs, Service Attention, customer-reported, Cognitive - Face
