### ISSUE TITLE
[azure-cognitiveservices-knowledge-qnamaker] Need to enter runtime key twice once in generate answer and once in client creation

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-python#12633] opened 2020-07-21 07:03 UTC
- **Package Name**:  azure-cognitiveservices-knowledge-qnamaker
 Need to enter runtime key twice once in generate answer and once in client creation

runtimeClient = QnAMakerRuntimeClient(runtime_endpoint=queryingURL, credentials=CognitiveServicesCredentials(queryRuntimeKey)) 

 

generate_answer(client=runtimeClient,kb_id=kb_id,runtimeKey=**queryRuntimeKey**) 

 

def generate_answer(client, kb_id, runtimeKey): 

    authHeaderValue = "EndpointKey " + **runtimeKey** 

    answer = client.runtime.generate_answer(kb_id, QueryDTO(question = "How do I manage my knowledgebase?"), dict(Authorization=authHeaderValue)) 

    print(f"{answer}.")

**Comment by lmazuel** [comment] 2021-12-17 00:44
This package has been replaced by https://pypi.org/project/azure-ai-language-questionanswering/. We believe the issue is addressed in the new one, and we won't fix the old one (deprecated).

**Closed by lmazuel** 2021-12-17 00:44 UTC
Labels: question, Client, Cognitive - QnA Maker
