### ISSUE TITLE
[Devtool]Question about GlobalResourceGroupPreparer 

### ISSUE THREAD

**Issue by xiafu-msft** [Azure/azure-sdk-for-python#13565] opened 2020-09-04 05:18 UTC
**Is your feature request related to a problem? Please describe.**
In Python2, the primary_endpoint in `storage_account` and `account_key` created by GlobalResourceGroupPreparer are unicode, is it possible to make it str? since the account name/key is not expected to have unicode char.

Thanks for your help!

**Describe the solution you'd like**
the type of account key and url in account object are in str format

**Describe alternatives you've considered**
https://github.com/Azure/azure-sdk-for-python/pull/13530/commits/d7300c9ad053cdda9ed9bde1d4b93c424684acd0

**Additional context**

**Comment by lmazuel** [comment] 2020-11-10 18:48
@xiafu-msft what is the actual problem with unicode type, that should be transparent. What is the exception or stacktrace or problem caused by it?

**Comment by lmazuel** [comment] 2020-12-28 22:17
Closing, @xiafu-msft please ping me offline if this is still needed

**Closed by lmazuel** 2020-12-28 22:17 UTC
Labels: Client, EngSys, needs-author-feedback, no-recent-activity, question
