### ISSUE TITLE
Keyvault 7.5 dropped sas_definition API bindings

### ISSUE THREAD

**Issue by NCarter3** [Azure/azure-sdk-for-python#36002] opened 2024-06-10 17:27 UTC
- **Package Name**: azure-keyvault-keys
- **Package Version**: 4.9
- **Operating System**: Ubuntu
- **Python Version**: 3.10

**Describe the bug**

In this PR (https://github.com/Azure/azure-sdk-for-python/pull/31525), generated bindings for all API versions were dropped in favor of a single set of generated bindings for a single API. This is great. Except some of the models and operations did not get generated by the new pattern. Here are the ones that are important to me:

SasDefinitionBundle
SasDefinitionUpdateParameters
SasDefinitionCreateParameters
SasDefinitionAttributes
get_sas_definition
set_sas_definition
update_sas_definition

These are now missing from the package. Please add them back!

**To Reproduce**
1. Search for the above symbols in the latest keyvault packages and see that they do not appear.

**Expected behavior**

I expect these API bindings to exist.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by xiangyan99** [comment] 2024-06-10 21:43
Thanks for the feedback, we’ll investigate asap.

**Comment by mccoyp** [comment] 2024-06-10 22:15
Hi @NCarter3, thank you for opening an issue. As new API versions have been released, we've updated our code generation approach to reduce the amount of excess code we produce for each library. For example, at one point we separated the specifications for certificate-, key-, and secret-related types since we only need to generate types that are relevant for each library.

The SAS-related models and methods that you mention here are Storage-specific items that weren't considered relevant for `azure-keyvault-*` libraries, and were previously only generated for older API versions that didn't have the domain-specific separation that I mention above.

Could I ask how you were accessing these types, and what your use scenario is? Were you importing these items from the `_generated` directory, or through a public API?

**Comment by NCarter3** [comment] 2024-06-10 22:51
You are accurately observing that I was getting to these via the _KeyVaultClient that is internal to KeyVaultClientBase. So tsk tsk to me for doing that ;) 
I had assumed it was an oversight that these methods were not exposed on KeyClient.
Am I missing that these methods are in a different, storage-related package?

**Comment by mccoyp** [comment] 2024-06-11 00:50
@NCarter3 My understanding is that managing Storage keys with Key Vault is a legacy feature (see [Key Vault's feature documentation](https://learn.microsoft.com/azure/key-vault/secrets/overview-storage-keys)), and as such is wasn't carried over when the legacy [azure-keyvault](https://pypi.org/project/azure-keyvault/1.1.0/) library -- which is now just a [metapackage](https://pypi.org/project/azure-keyvault/) -- was deprecated in favor of separate `azure-keyvault-*` libraries. `azure-keyvault` was the last Python library to include public API support for this feature.

I can discuss this further with the SDK and service teams to confirm our support plan for this, but my understanding is that the deprecated support was intentional as the service feature was marked as a legacy one.

**Comment by mccoyp** [comment] 2024-06-19 17:54
Hi again @NCarter3, thank you for your patience. I've confirmed that this is a legacy feature, which is why it was intentionally unsupported in our newer Python libraries like `azure-keyvault-keys` -- similarly, Storage discontinued support after service version 2018-03-28 and the Azure CLI discontinued support in version 2.54.

As the [feature documentation](https://learn.microsoft.com/azure/key-vault/secrets/overview-storage-keys) states, it's recommended to update to Microsoft Entra ID authentication. [Microsoft Entra managed identity](https://learn.microsoft.com/entra/identity/managed-identities-azure-resources/) is a particularly useful and secure solution that removes the need for credentials like passwords or SAS tokens.

**Closed** 2024-06-26 22:33 UTC
Labels: question, KeyVault, customer-reported, issue-addressed
