### ISSUE TITLE
Typing mismatch between DaaLakeFileSystem download_file and BlobContainerClient download_blob

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#34858] opened 2024-03-20 16:09 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.19.1
- **Operating System**: Mac OS X
- **Python Version**: 3.11

**Describe the bug**

We are using this code:

```python
    blob_container_client: ContainerClient = current_app.config[CONFIG_BLOB_CONTAINER_CLIENT]
    try:
        blob = await blob_container_client.get_blob_client(path).download_blob()
    except ResourceNotFoundError:
        logging.info("Path not found in general Blob container: %s", path)
        if current_app.config[CONFIG_USER_UPLOAD_ENABLED]:
            try:
                user_oid = auth_claims["oid"]
                user_blob_container_client = current_app.config[CONFIG_USER_BLOB_CONTAINER_CLIENT]
                user_directory_client: FileSystemClient = user_blob_container_client.get_directory_client(user_oid)
                file_client = user_directory_client.get_file_client(path)
                blob = await file_client.download_file()  # type: ignore
            except ResourceNotFoundError:
                logging.exception("Path not found in DataLake: %s", path)
                abort(404)
        else:
            abort(404)
    if not blob.properties or not blob.properties.has_key("content_settings"):
        abort(404)
    mime_type = blob.properties["content_settings"]["content_type"]
```

When we run mypy, we get this error on the line that calls download_file:

```
app.py:129: error: Incompatible types in assignment (expression has type "azure.storage.filedatalake.aio._download_async.StorageStreamDownloader", variable has type "azure.storage.blob.aio._download_async.StorageStreamDownloader[bytes]")  [assignment]
```

That is because we first set blob to the result of download_blob, and then set it to the result of download_file, and they have these subtly different types. Given the similarity in types, I am wondering if the SDK team plans to merge the types. I am able to use the blob's very similarly, so the difference in type hasn't made an effect on the usage. Or perhaps you have a suggestion for what type to set blob to explicitly so that the typing is correct.

**To Reproduce**
1. Check out this branch:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1395/
3. Cd into app/backend and run "python -m mypy ."

**Comment by jalauzon-msft** [comment] 2024-03-27 01:01
Hi @pamelafox Pamela, you are mixing two different SDKs here, the `ContainerClient` from `azure-storage-blob` and the `FileSystemClient` from `azure-storage-file-datalake` so the different return types are expected. While they do technically represent the same resource, you are referencing that resource in two different ways.

Is there any particular reason you are using the two different types of clients? My recommendation would be to stick to one client from one SDK and if your Storage account is an HNS account, it is recommended to use the datalake SDK exclusively. Mixing the client types and SDKs can lead to some trouble if you are not careful as, while some operations are the same/similar between Blob and Datalake, others differ greatly.

Unless, of course, you have multiple Storage accounts where one is HNS and one is not, then maybe your approach is okay. In that case, you would still need to reconcile the different types as they are different by design. The `StorageStreamDownloader` type from the two SDKs is similar today, but that may not always be the case. Depending on how you use the `blob` variable below, you could use a different variable name, or you may have to branch your code a little differently.

**Comment by pamelafox** [comment] 2024-03-27 05:07
Yes, we are intentionally using 2 SDKs, as we first look if the blob is in Azure Blob storage, and if it isnt, we check the DaaLake storage.

This is the full code that comes after:
```
    if not blob.properties or not blob.properties.has_key("content_settings"):
        abort(404)
    mime_type = blob.properties["content_settings"]["content_type"]
    if mime_type == "application/octet-stream":
        mime_type = mimetypes.guess_type(path)[0] or "application/octet-stream"
    blob_file = io.BytesIO()
    await blob.readinto(blob_file)
    blob_file.seek(0)
    return await send_file(blob_file, mimetype=mime_type, as_attachment=False, attachment_filename=path)
```

It currently works for the return values from both SDKs, so that's why I was hoping for an explicit common type / interface. I can make the type error go away if I put this before the blob fetching calls:

```
    blob: Union[azure.storage.blob.aio._download_async.StorageStreamDownloader[bytes], azure.storage.filedatalake.aio._download_async.StorageStreamDownloader]
```

However that's not nice since it references private variables. I wasn't able to make it happy with the public version of StorageStreamDownloader for whatever reason.

I could also branch the code entirely for the two return types, which feels a little silly now given all the same code works, but maybe that'd be more future-proof if I can't type it.

Thanks for the tips!

**Comment by jalauzon-msft** [comment] 2024-03-27 18:59
@pamelafox, thanks for confirming your usage, it's a more interesting question then. I'm curious why you couldn't get MyPy to be happy with public types. Did you try to alias your types with something like this? I would think that could work, if not I agree reaching in for private types isn't the best idea.

```py
from azure.storage.blob import StorageStreamDownloader as BlobDownloader
from azure.storage.filedatalake import StorageStreamDownloader as DatalakeDownloader

blob: Union[BlobDownloader, DatalakeDownloader]
```

Unfortunately, I don't think we'll want to add any explicit common interface in the SDK as these types are meant to be separate and we don't have a great mechanism for code that is common across multiple SDKs. 

As for branching the code entirely, I'm not sure whether this makes sense or not. On the one hand these types are meant to be separate and are not meant to be used in a mixed fashion like this but, on the other hand, they have the same API structure which we guarantee will not change so it should continue to just work like this. I would say if you were only ever going to download the file like this, it's probably fine to leave the code as-is, assuming you can work out the type, but if you start performing other operations, it would be best to branch the code because there can be differences between Blob and Datalake.

**Comment by pamelafox** [comment] 2024-03-27 20:31
Ah, mypy is actually happy when I correctly import them from aio instead of the root-

from azure.storage.blob.aio import StorageStreamDownloader as BlobDownloader
from azure.storage.filedatalake.aio import StorageStreamDownloader as DatalakeDownloader

And then I have:

blob: Union[BlobDownloader, DatalakeDownloader]

before the rest of my code

So we'll do that for now, it's fairly clear what's going on. I think you can close this issue since you've clarified the typing mismatch is intentional, as they're from different SDKs.

**Comment by jalauzon-msft** [comment] 2024-03-27 20:47
Ah sorry I missed the fact it was async! Yeah, that import looks good. Thanks for confirming, will close this now.

**Closed by jalauzon-msft** 2024-03-27 20:47 UTC
Labels: Storage, Service Attention, Client, needs-team-attention
