### ISSUE TITLE
ChainedTokenCredential and DefaultAzureCredential should fail on unexpected errors

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-python#8298] opened 2019-10-30 18:43 UTC
Currently the `ChainedTokenCredential` and `DefaultAzureCredential` will swallow errors raised from credentials contained within the chain. This is problematic in the case that users specify incorrect credentials as they might end up authenticating with credentials that they didn't intend.

In .NET we have added a specific exception type, `CredentialUnavailableException` as a sentinel for errors which are expected. For example the `EnvironmentCredential` will raise this in the case that all necessary environment variables are specified. Other language should provide a similar mechanism to distinguish between expected errors and unexpected.

**Comment by chlowell** [comment] 2019-10-31 21:38
Closing as a duplicate of #8166

**Closed by chlowell** 2019-10-31 21:38 UTC
Labels: Azure.Identity, Client
