### ISSUE TITLE
ResourceExistsError is raised eventhough the blob does not exist yet but credentials to storage account were wrong

### ISSUE THREAD

**Issue by christianholland** [Azure/azure-sdk-for-python#26919] opened 2022-10-19 11:45 UTC
- **Package Name**: azure.storage.blob
- **Package Version**: 
- **Operating System**: Windows
- **Python Version**: 3.6.8

**Describe the bug**
In my python script I would like to catch various errors that can occur during blob upload. 
For test purposes I have provided wrong credentials to `BlobServiceClient` and I get the error ` 'azure.core.exceptions.ResourceExistsError'` which is the same error that I get when the blob really already exists. The only difference I see is that ErrorCode has changed to the correct error: `ErrorCode:PublicAccessNotPermitted`.

Wouldnt it be better to raise a different error when a file already exist or when the credentials are wrong?

**Comment by vincenttran-msft** [comment] 2022-10-19 21:57
Hi @christianholland Christian, thanks for your inquiry. Unfortunately, I am not able to reproduce your findings locally. Maybe it would be helpful if you could provide a code sample?

I am getting an `ErrorCode:AuthenticationFailed` (expected behavior) when providing incorrect credentials (I have tried both an incorrect key, and an incorrect account url).

Attached below is the code-sample of what I used to attempt to reproduce your findings. I would also recommend that you use the latest version of the `azure-storage-blob` package, as it is always recommended to use the latest version when possible!

```
from azure.storage.blob import BlobServiceClient

account_url = f"https://<storage_account_name>.blob.core.windows.net"
account_key = <storage_account_key>
blob_service_client = BlobServiceClient(account_url, account_key)
data = b'a'*4*1024*1024
blob_client = blob_service_client.get_blob_client(container=<container_name>, blob=<blob_name>)
blob_client.upload_blob(data)
```

Thanks!

**Comment by vincenttran-msft** [comment] 2022-10-26 19:07
Hi @christianholland Christian, after speaking with my colleagues, I believe I am seeing what behavior you are observing. It is related to when attempting to access a Storage account that has public access `Disabled` without providing the account key. I am currently working on a fix and will attach it to the issue once it is resolved. Thanks for your contribution 😄

**Comment by vincenttran-msft** [comment] 2023-03-28 23:20
Hi @christianholland sorry for the delay, we've had some higher priority work items that have caused this item to be delayed. However, upon returning to address this issue, my testing has revealed the Service behavior has changed! Now instead of returning a `PublicAccessNotPermitted`, this scenario is returning a `NoAuthenticationInformation` error, which I believe more accurately represents the cause of your error.

With that being said, I will go ahead and close this issue as I believe it has been sufficiently resolved! Thanks again for your contribution!

**Closed by vincenttran-msft** 2023-03-28 23:20 UTC
Labels: Storage, question, Service Attention, Client, customer-reported, needs-team-attention
