### ISSUE TITLE
AzureML wokspace environments build failing SDKV1

### ISSUE THREAD

**Issue by obiii** [Azure/azure-sdk-for-python#34418] opened 2024-02-22 10:10 UTC
- **Package Name**: azureml-sdk
- **Package Version**: V1
- **Operating System**: Linux
- **Python Version**:3.10 

**The bug**
We have been building ML environments using docker files in Azure workspace using a CI pipeline. It used to work fine until today we tried to rebuild the environment with new conda dependencies.

The build job fails with a weird error, which seems to be an internal bug. Here is the screenshot of the job:

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/1be910f5-dba4-4d7f-be7b-6a1faf91978f)

On examining logs, we see this:

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/6cfaf192-1391-4b4a-a169-075662ebb64e)

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/74bc0e92-9ce0-4c3b-afb8-aa1fb0b9e9b3)

The script above "script.py" is Azures's internal script. I believe it's missing an exists_ok=True in mkdir(name, mode). That's why it complains that the file is already present?

We use 
`az ml environment create --name "$azureEnvPrefix" --build-context $dockerContext --dockerfile-path Dockerfile --resource-group ${{parameters.resourceGroupName}} --workspace-name ${{parameters.workspaceName}} --tags "dev=$timestamp.CI" "ready_for=${{parameters.targetTag}}"`

in a CI task to create envs.

**Comment by isaudagar** [comment] 2024-02-29 12:49
Hi @obiii , 
Could you please provide more details and reproduce steps to investigate the root cause.

**Comment by obiii** [comment] 2024-02-29 14:58
> Hi @obiii , Could you please provide more details and reproduce steps to investigate the root cause. 

Hi, I assume you mean the docker files. Please let me know otherwise. The docker files are generated by a CI pipeline that I cannot share but here are the resultant files that the CI pipeline uses to build images,

**Dockerfile**
```
ARG CONDA_FILE
ARG IMAGE_NAME
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

RUN echo "CONDA_FILE: conda_dependencies/preprocess_conda_dependencies.yml"
RUN echo "IMAGE_NAME: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04"

COPY conda_dependencies/preprocess_conda_dependencies.yml conda_env.yml

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN echo "source /opt/miniconda/etc/profile.d/conda.sh && conda activate" >> ~/.bashrc

RUN cat conda_env.yml

RUN source /opt/miniconda/etc/profile.d/conda.sh && \
    conda activate && \
    conda install conda && \
    pip install cmake && \
    conda env update -f conda_env.yml
```
conda_dependencies/preprocess_conda_dependencies.yml
```
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip:
      - numpy==1.23.5
      - pandas==2.1.4
      - prophet==1.1.5
      - SQLAlchemy==2.0.23
      - urllib3==2.1.0
      - pyodbc==5.0.1
      - mlflow==2.9.1
      - azureml-mlflow==1.54.0.post1
      - azureml-core==1.54.0.post1
      - azureml-dataset-runtime==1.54.0.post1
```

The command inside the CI ppl to build the images:
`az ml environment create --name "$azureEnvPrefix" --build-context $dockerContext --dockerfile-path Dockerfile --resource-group ${{parameters.resourceGroupName}} --workspace-name ${{parameters.workspaceName}}`

You can provide values for the argument according to your setup. For us the file structure is as follows:

```
projectName/
    ml_service/
        docker/
            Dockerfile
            conda_dependencies/
                preprocess_conda_dependencies.yml
```
[
dockerBaseDir="ml_service/docker"
dockerContext="$(System.DefaultWorkingDirectory)/$dockerBaseDir"
](url)

**Comment by obiii** [comment] 2024-03-04 09:27
Hi @isaudagar , is there any update on this please?

**Comment by Junnu-akhila** [comment] 2024-03-04 12:54
Hello @obiii, I have trying to run the above files and getting some errors. Can you please provide the conda.sh file details?

**Comment by obiii** [comment] 2024-03-05 15:23
Hi @Junnu-akhila , Here is the conda.sh file.
```
export CONDA_EXE='/opt/miniconda/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/opt/miniconda/bin/python'

# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
__conda_exe() (
    "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
)

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix "$@")" || \return
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix reactivate)" || \return
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    # In dev-mode CONDA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA:+x}" ] && [ -n "${WINDIR+x}" ]; then
        PATH="$(\dirname "$CONDA_EXE")/condabin${PATH:+":${PATH}"}"
    else
        PATH="$(\dirname "$(\dirname "$CONDA_EXE")")/condabin${PATH:+":${PATH}"}"
    fi
    \export PATH

    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi
```export CONDA_EXE='/opt/miniconda/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/opt/miniconda/bin/python'

# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
__conda_exe() (
    "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
)

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__conda_activate() {
    if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
        # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
        # after conda updated to >= 4.4. See issue #6173.
        PS1="$CONDA_PS1_BACKUP"
        \unset CONDA_PS1_BACKUP
    fi
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix "$@")" || \return
    \eval "$ask_conda"
    __conda_hashr
}

__conda_reactivate() {
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __conda_exe shell.posix reactivate)" || \return
    \eval "$ask_conda"
    __conda_hashr
}

conda() {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        activate|deactivate)
            __conda_activate "$@"
            ;;
        install|update|upgrade|remove|uninstall)
            __conda_exe "$@" || \return
            __conda_reactivate
            ;;
        *)
            __conda_exe "$@"
            ;;
    esac
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    # In dev-mode CONDA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA:+x}" ] && [ -n "${WINDIR+x}" ]; then
        PATH="$(\dirname "$CONDA_EXE")/condabin${PATH:+":${PATH}"}"
    else
        PATH="$(\dirname "$(\dirname "$CONDA_EXE")")/condabin${PATH:+":${PATH}"}"
    fi
    \export PATH

    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi

**Comment by obiii** [comment] 2024-03-06 09:16
> Hi @isaudagar , is there any update on this please?

Hi, in case you need the image build logs:
[build_log.txt](https://github.com/Azure/azure-sdk-for-python/files/14507446/build_log.txt)

Please let me know if there is any updated. Thanks :)

**Comment by Junnu-akhila** [comment] 2024-03-06 15:08
Hi @obiii 
 
The FileExistsError typically occurs in Python when you attempt to create a file or directory that already exists. However, looking at the command you provided, it seems that the error might not be directly related to file creation.
In your Dockerfile, you're using conda env update -f conda_env.yml command to update a Conda environment using a YAML file (conda_env.yml). This error might occur if one of the packages specified in conda_env.yml is already installed in the environment or if the environment itself already exists.
Here are a few things to check and troubleshoot:
Check Environment Existence: Ensure that the Conda environment specified in the conda_env.yml file exists before attempting to update it. You can use conda env list to see the list of existing environments.
Check Package Versions: If a package specified in conda_env.yml is already installed but with a different version, Conda might raise an error. Make sure the versions specified in the YAML file are compatible with the current environment.
Clean Environment: If you're okay with removing the existing environment and recreating it from scratch, you can use conda env remove -n <environment_name> to remove the existing environment before running the update command.
Check File Paths: Ensure that the conda_env.yml file is located in the correct directory and that the path is correctly specified in the RUN command.
Permissions: Ensure that the user running the Dockerfile has the necessary permissions to create and modify Conda environments and install packages.

**Comment by obiii** [comment] 2024-03-08 10:16
> Hi @obiii
> 
> The FileExistsError typically occurs in Python when you attempt to create a file or directory that already exists. However, looking at the command you provided, it seems that the error might not be directly related to file creation.
> 
> In your Dockerfile, you're using conda env update -f conda_env.yml command to update a Conda environment using a YAML file (conda_env.yml). This error might occur if one of the packages specified in conda_env.yml is already installed in the environment or if the environment itself already exists.
> 
> **Here are a few things to check and troubleshoot:** **Check Environment Existence:** Ensure that the Conda environment specified in the conda_env.yml file exists before attempting to update it. You can use conda env list to see the list of existing environments. **Check Package Versions:** If a package specified in conda_env.yml is already installed but with a different version, Conda might raise an error. Make sure the versions specified in the YAML file are compatible with the current environment. **Clean Environment:** If you're okay with removing the existing environment and recreating it from scratch, you can use conda env remove -n <environment_name> to remove the existing environment before running the update command. **Check File Paths:** Ensure that the conda_env.yml file is located in the correct directory and that the path is correctly specified in the RUN command. **Permissions**: Ensure that the user running the Dockerfile has the necessary permissions to create and modify Conda environments and install packages.

Hi,

But its not our dockerfile that problematic. Its the azure's internal. Please look at the screenshot, it says: **"/azureml-envs/image-build/lib/python3.8/os.py"**

I have tried changing the dependencies, and trimming them to just one or two. I have tried changing base images but nothing works. And this docker setup is being used in our other projects which I fear will crash now if we ever try to rebuilt the environments. This environment that we are talking about was working fine a month ago and I just added a single pycountry dependency.

**Comment by Junnu-akhila** [comment] 2024-03-14 19:32
Hi @obiii,

Previously i faced some issues with /opt/miniconda/profile.d/conda.sh. Now it was resolved. It is in progress and once i find anything i will update you.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/bc2f96e7-3062-46d2-932b-980ffd5e0808)

**Comment by Junnu-akhila** [comment] 2024-03-19 18:29
Hi @obiii,

I have run the Docker file successfully and while creating the ML environment, I'm getting below error. It is in progress.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/db1bccfd-8163-4021-8844-452cc9d3a11b)

**Comment by obiii** [comment] 2024-03-19 20:57
> Hi @obiii,
> 
> I have run the Docker file successfully and while creating the ML environment, I'm getting below error. It is in progress.
> 
> ![image](https://private-user-images.githubusercontent.com/142422872/314185677-db1bccfd-8163-4021-8844-452cc9d3a11b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODIwNzMsIm5iZiI6MTcxMDg4MTc3MywicGF0aCI6Ii8xNDI0MjI4NzIvMzE0MTg1Njc3LWRiMWJjY2ZkLTgxNjMtNDAyMS04ODQ0LTQ1MmNjOWQzYTExYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMDU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGRjZjg2YmI3Y2I4ZDQwNzJmZTQ3MGQ0YWJkNmNlMDVjODMxZWE3N2M2YTRlNGFlZGU1OTFiOThkNzVhNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u2mcVh4aJDFD9DbDnmsinGsB2eENseYIE6igql0T9SA)

Hi @Junnu-akhila, just to update you, the same works if the environment is built in the registry instead of the workspace, not sure why tho!

**Comment by Junnu-akhila** [comment] 2024-03-21 10:21
Hi @obiii - 

May I know which python version you are using?
Docker file run successfully, After updating python version 3.11 to 3.10 in preprocess_conda_dependencies.yml file. Could you please try with python3.10 version.

Thank you.

**Comment by Junnu-akhila** [comment] 2024-03-21 14:22
Hi @obiii ,

create my_env.yml file by using below code:

$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: newdockerenv
build:
  path: ml_service/docker

please run below command if you get any ml extension issue,
Command:
az extension add --name azure-cli-ml 

you can use below command for ml environment creating in workspace:
az ml environment create --file my_env.yml --resource-group <your RG name> --workspace-name <workspace anme>

![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/d781b7d7-787a-42ad-a26d-6fd026823527)

If you will get any issue, please let me
Thank you.

**Comment by Junnu-akhila** [comment] 2024-03-25 12:26
Hi @obiii,
Could you please confirm, is this issue resolved or not?

**Comment by obiii** [comment] 2024-03-25 14:02
> az ml environment create --file my_env.yml --resource-group --workspace-name

I tried your method above: It doesn't work. This is the trace:

> The yaml file you provided does not match the prescribed schema for Environment yaml files and/or has the following issues:
> 
> Error: 
> 1) A least one unrecognized parameter is specified
> 
> Details: Validation for EnvironmentSchema failed
> 
> (x) build:
> - Field may not be null.
> 
> (x) path:
> - Unknown field.
> 
> Resolutions: 
> 1) Remove any parameters not prescribed by the Environment schema. 
> Visit this link to refer to the Environment schema if needed: https://aka.ms/ml-cli-v2-environment-yaml-reference.
> If using the CLI, you can also check the full log in debug mode for more details by adding --debug to the end of your command

Also, even if this works, we do not have my_env.yaml files for all the environments. We have **`docker.template`** file that gets filled according to which environment is being built and it produces a Dockerfile that is used with **`az ml command`** as explained above (referenced).

A Dockerfile produced the template, for a specific preprocess environment is as follows:

```
# Start with a base image, for example:
# FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

# Use the provided environment variables for conda and environment file paths
ARG CONDA_FILE
ARG IMAGE_NAME
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

RUN echo "CONDA_FILE: conda_dependencies/preprocess_conda_dependencies.yml"
RUN echo "IMAGE_NAME: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04"

COPY conda_dependencies/preprocess_conda_dependencies.yml conda_env.yml

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN echo "source /opt/miniconda/etc/profile.d/conda.sh && conda activate" >> ~/.bashrc

RUN cat conda_env.yml

RUN source /opt/miniconda/etc/profile.d/conda.sh && \
    conda activate && \
    conda install conda && \
    pip install cmake && \
    conda env update -f conda_env.yml --prune
```

We want to use such Dockerfiles to build the environments:
az ml environment create --name "$azureEnvPrefix" --build-context $dockerContext --dockerfile-path Dockerfile --resource-group <someName> --workspace-name <someName>

**Comment by obiii** [comment] 2024-03-25 14:19
> Hi @obiii
> 
> May I know which python version you are using? Docker file run successfully, After updating python version 3.11 to 3.10 in preprocess_conda_dependencies.yml file. Could you please try with python3.10 version.
> 
> Thank you.

Hi, tried this, doesn't work. Results in same error.

**Comment by Junnu-akhila** [comment] 2024-03-27 13:37
> > az ml environment create --file my_env.yml --resource-group --workspace-name
> 
> I tried your method above: It doesn't work. This is the trace:
> 
> > The yaml file you provided does not match the prescribed schema for Environment yaml files and/or has the following issues:
> > Error:
> > 
> > 1. A least one unrecognized parameter is specified
> > 
> > Details: Validation for EnvironmentSchema failed
> > (x) build:
> > 
> > * Field may not be null.
> > 
> > (x) path:
> > 
> > * Unknown field.
> > 
> > Resolutions:
> > 
> > 1. Remove any parameters not prescribed by the Environment schema.
> >    Visit this link to refer to the Environment schema if needed: https://aka.ms/ml-cli-v2-environment-yaml-reference.
> >    If using the CLI, you can also check the full log in debug mode for more details by adding --debug to the end of your command
> 
> Also, even if this works, we do not have my_env.yaml files for all the environments. We have **`docker.template`** file that gets filled according to which environment is being built and it produces a Dockerfile that is used with **`az ml command`** as explained above (referenced).
> 
> A Dockerfile produced the template, for a specific preprocess environment is as follows:
> 
> ```
> # Start with a base image, for example:
> # FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
> 
> # Use the provided environment variables for conda and environment file paths
> ARG CONDA_FILE
> ARG IMAGE_NAME
> FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
> 
> RUN echo "CONDA_FILE: conda_dependencies/preprocess_conda_dependencies.yml"
> RUN echo "IMAGE_NAME: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04"
> 
> COPY conda_dependencies/preprocess_conda_dependencies.yml conda_env.yml
> 
> RUN rm /bin/sh && ln -s /bin/bash /bin/sh
> RUN echo "source /opt/miniconda/etc/profile.d/conda.sh && conda activate" >> ~/.bashrc
> 
> RUN cat conda_env.yml
> 
> RUN source /opt/miniconda/etc/profile.d/conda.sh && \
>     conda activate && \
>     conda install conda && \
>     pip install cmake && \
>     conda env update -f conda_env.yml --prune
> ```
> 
> We want to use such Dockerfiles to build the environments: az ml environment create --name "$azureEnvPrefix" --build-context $dockerContext --dockerfile-path Dockerfile --resource-group --workspace-name

Hi @obiii ,

you need add some space after build in my_env.yml file:

$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: newdockerenv
build:
    path: ml_service/docker

By using below command, i have successfully created ML environment.

az ml environment create --file my_env.yml --resource-group --workspace-name
![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/9a11a0a3-3497-4098-90d1-008d0f4450ca)

I have able to create the environment by using your command,

az ml environment create --name "$azureEnvPrefix" --build-context $dockerContext --dockerfile-path Dockerfile --resource-group --workspace-name

![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/64f8da9c-fb71-4ebf-8365-00c65c8d82bc)

![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/e32cf863-7459-4770-8bca-80c3dc814bc5)

![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/ceffb052-8358-4c6f-a56d-9e8b40c12aee)


By using python 3.11 version, we facing process 'python' exited with status code 1.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/682253e2-2bf6-47a3-afa7-60dc86d29152)

By using python3.10 , Job is succeeded,
![image](https://github.com/Azure/azure-sdk-for-python/assets/142422872/305da4b7-e75a-4f39-9b0d-e758e8b408e1)


Could you please try with above process?

Thank you.

**Comment by shekshavalicentific** [comment] 2024-03-27 13:46
Hi @obiii Can you use the below screenshot by creating the my_env.yml. You need to provide the four spaces in front of path in build section and we tried two ways and environments created.
![image](https://github.com/Azure/azure-sdk-for-python/assets/143018748/aa247991-f870-42d3-be51-1f755e795c9c)

If you will get any issues after using this approach we will work on it.

**Comment by Junnu-akhila** [comment] 2024-04-02 05:28
Hi @obiii 
Could you please confirm, is this issue resolved or not?

**Comment by obiii** [comment] 2024-04-04 10:42
Hi @Junnu-akhila 

Sorry for late response. I tried it and it creates the environment but it doesn't build:

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/a77a6848-ebde-4a79-928d-034a0475296b)

On checking logs I see:

![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/cfe5b204-d37b-40a8-bb75-4a279b94875b)
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/a6dede07-8003-45a9-89bf-ad2f6d87d574)
![image](https://github.com/Azure/azure-sdk-for-python/assets/17766651/f1b2cc08-9c3a-4826-997b-20ffa599a33c)

**Comment by Junnu-akhila** [comment] 2024-04-04 13:07
Hi @obiii,
As per your errors, you need to provide Docker file path in Docker context.
Thank you.

**Comment by obiii** [comment] 2024-04-04 15:29
Hi @Junnu-akhila
I realized. Thanks for correcting. It still fails, even if it does not fail,  the solution is not what we are looking for. We cannot create env.yml files for each environment and use az command to create an environment using the env.yml files. 

I am not sure why it doesn't build the env in workspace. For now, we have decided to use a shared ML registry for building environments. And interestingly, the same CI pipeline, dockerfile, and context, same code successfully builds the environment in the registry.

**Comment by Junnu-akhila** [comment] 2024-04-08 18:15
Hi @obiii,

We tried, what you suggested, and we are able to create a ML Environment. As you said, now you are using ML registries for ML Environment, and it is working fine. Shall i close this? If you need anything we will work on this.
Thank you.

**Closed** 2024-04-08 22:28 UTC
Labels: Machine Learning, Service Attention, Client, customer-reported, needs-team-attention
