### ISSUE TITLE
Diverging returns on calls to storage account versions breaks eventhub checkpointing

### ISSUE THREAD

**Issue by casperlehmann** [Azure/azure-sdk-for-python#15785] opened 2020-12-14 12:35 UTC
- **Package Name**: azure.eventhub.extensions.checkpointstoreblobaio._blobstoragecsaio
- **Package Version**: main branch
- **Operating System**: macos
- **Python Version**: 2.8.6

**Describe the bug**
When using Azure Data Lake Gen 2 as a backend for storing checkpoints for EventHubs, reads of the partitions fail, because ownership information is attempted read from the parent directory rather than the partitions themselves.

KeyError: 'ownerid' occurs because ownderid is not a property of the parent folder, but a property of the partition.

```
WARNING:azure.eventhub.extensions.checkpointstoreblobaio._blobstoragecsaio:An exception occurred during list_ownership for namespace 'evhns.servicebus.windows.net' eventhub 'xy-streams' consumer group '$Default'. Exception is KeyError('ownerid')
WARNING:azure.eventhub.aio._eventprocessor.event_processor:EventProcessor instance 'a78e2794-8471-xxxx-xxxx-62xxxxxxxx2b' of eventhub 'xy-streams' consumer group '$Default'. An error occurred while load-balancing and claiming ownership. The exception is KeyError('ownerid'). Retrying after 10.285318052421541 seconds
```

The implementation of these checks seem to have been written against the old blob storage endpoints (which still work), but for some reason the call to ADLSG2 is broken. Thus this might be a Storage bug rather than an EventHub bug.

**To Reproduce**
1. Setup an eventhub and send data to it.
2. Subscribe to eventhub with checkpoints stored in v1. This works.
3. Subscribe to eventhub with checkpoints stored in v2. This fails.

```
# publish.py
import asyncio
from azure.eventhub.aio import EventHubProducerClient
from azure.eventhub import EventData
from datetime import datetime

async def run():
    producer = EventHubProducerClient.from_connection_string(conn_str="Endpoint=sb://endpointconnectionstring", eventhub_name="xy-streams")
    async with producer:
        event_data_batch = await producer.create_batch()
        timestamp = datetime.now().strftime("%d-%b-%Y (%H:%M:%S.%f)")
        event_data_batch.add(EventData(f'First event  {timestamp}'))
        event_data_batch.add(EventData(f'Second event {timestamp}'))
        event_data_batch.add(EventData(f'Third event  {timestamp}'))

        await producer.send_batch(event_data_batch)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

```
# receive.py
import asyncio
from azure.eventhub.aio import EventHubConsumerClient
from azure.eventhub.extensions.checkpointstoreblobaio import BlobCheckpointStore

STORAGE_CONNECTION_STR = "DefaultEndpointsProtocol=https;AccountName=..."
BLOB_CONTAINER_NAME = "events"
CONNECTION_STR = "Endpoint=sb://endpointconnectionstring"
EVENTHUB_NAME = "xy-streams"

async def on_event(partition_context, event):
    print("Received the event: \"{}\" from the partition with ID: \"{}\"".format(event.body_as_str(encoding='UTF-8'), partition_context.partition_id))
    await partition_context.update_checkpoint(event)


async def receive(client):
    """
    Without specifying partition_id, the receive will try to receive events from all partitions and if provided with
    a checkpoint store, the client will load-balance partition assignment with other EventHubConsumerClient instances
    which also try to receive events from all partitions and use the same storage resource.
    """
    await client.receive(
        on_event=on_event,
        starting_position="-1",  # "-1" is from the beginning of the partition.
    )

async def main():
    checkpoint_store = BlobCheckpointStore.from_connection_string(STORAGE_CONNECTION_STR, BLOB_CONTAINER_NAME, api_version='2014-02-14') # Changing the api_version has not worked for me
    client = EventHubConsumerClient.from_connection_string(
        CONNECTION_STR,
        consumer_group="$Default",
        eventhub_name=EVENTHUB_NAME,
        checkpoint_store=checkpoint_store
    )
    async with client:
        await receive(client)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Expected behavior**
Storage v1 and Storage v2 should work the same.

**Additional context**
The EventHub SDK uses the method `list_blob_flat_segment` to check ownership and contents of the target directory. 
This works in Blob Storage in a Storage account V1. But when running against a ADLS Gen 2 the list_blob_flat_segment call receives a bad response.
Specifically, the deserialization happening here:

https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/_generated/aio/operations_async/_container_operations_async.py#L1148

If we log the result from the v1 storage account, we get:

```
{
  'additional_properties': {'Blobs': None},
  'service_endpoint': 'https://StorageV1.blob.core.windows.net/',
  'container_name': 'containername',
  'prefix': 'eventstoeventhub.servicebus.windows.net/bi-streams/$default/ownership',
  'marker': None,
  'max_results': None,
  'segment': <azure.eventhub.extensions.checkpointstoreblobaio._vendor.storage.blob._generated.models._models_py3.BlobFlatListSegment object at 0x1xxxxxxx0>,
  'next_marker': ''
}
```

This is the info we are querying for. But if we try the same thing with the v2 Storage Account in ADLSG2, we get:

```
blob.metadata: {'hdi_isfolder': 'true'}
```

This means that the file we are logging is actually an Azure HDInsight directory. Specifically, it is the parent directory of the files that we are interested in.

V1, in other words, iterates over the contents of `Folder_Parent`, and we get an array of [`File_0`, `File_1`, `File_2`]. Whereas V2 iterates over an array of `Folder_Parent` itself, so we get [`Folder_Parent`].

```
Folder_Parent: {'hdi_isfolder': 'true'}
|- File_0 {'additional_properties': {'Blobs': None}, ...}
|- File_1 {'additional_properties': {'Blobs': None}, ...}
|- File_2 {'additional_properties': {'Blobs': None}, ...}
```

- I suspect this is a bug in the storage libraries rather than EventHub, but even if that is the case, I'd say there needs to be separate test cases for V1 and V2 in the EventHub SDK.
- Likewise, tests should be maintained for both sync and async versions of the library.

**Comment by casperlehmann** [comment] 2020-12-14 19:31
Probably related: https://stackoverflow.com/questions/63354884/azure-eventhubs-python-checkpointing-with-blob-storage-keyerror-issue-in-ev

I'm in West Europe.

**Comment by yunhaoling** [comment] 2020-12-15 21:46
hey @casperlehmann, thanks for the report and detailed debugging process.

We  confirmed it's a bug in the azure-eventhub-checkpointstoreblob(-aio) when working with the ADLSGen2 and the root cause is as what you have found -- the parent node is returned which contains no metadata info.

We had a PR out to fix the issue: https://github.com/Azure/azure-sdk-for-python/pull/15752

it will be included in our next release.

**Comment by casperlehmann** [comment] 2020-12-21 12:31
Good to hear it. Thanks. Do you have an estimate on the release?

**Comment by yunhaoling** [comment] 2020-12-21 19:53
@casperlehmann , yes, we have a release plan in January, thanks for you patience!

**Comment by yunhaoling** [comment] 2021-01-12 19:32
hey @casperlehmann , we have released azure-eventhub-checkpointstoreblob(-aio) v1.1.2 which includes the fix, please upgrade to the latest version.
```bash
pip install azure-eventhub-checkpointstoreblob --upgrade  # for sync
pip install azure-eventhub-checkpointstoreblob-aio --upgrade  # for async
```

I'm closing this issue now, feel free to reopen if you still have issue with the latest libraries.

**Closed by yunhaoling** 2021-01-12 19:32 UTC
Labels: Client, Event Hubs, customer-reported, question
