### ISSUE TITLE
get the RU and autoscaling  of exist mongodb  which in cosmos account 

### ISSUE THREAD

**Issue by tengfei86** [Azure/azure-sdk-for-python#29644] opened 2023-03-29 03:57 UTC
- **azure.cosmos.CosmosClient**: 
- **4.3.1**: 
- **centos 7**:
- **Python 3.10.6**: 

**Describe the bug**
i want to get the RU and autoscaling of exist mongodb database  which in cosmos account ,
could you give me some suggestions ?
Thanks 

**To Reproduce**
```python
client = CosmosClient("https://mongodb-tiger-esaosp.mongo.cosmos.azure.com:443/",credential=COSMOS_ACCOUNT_KEY,consistency_level='Session')
   cosmos_db = client.get_database_client(DATABASENAME)
   db_offer = cosmos_db.read_offer()
 
```
**Expected behavior**
Create the database successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/524484/227158811-e477b9cd-b76c-413f-96c3-d6ed30798e2a.png)

**Additional context**

**Comment by pvaneck** [comment] 2023-03-29 04:10
Hey, @tengfei86. Thanks for opening an issue. 

@simorenoh, perhaps you might be able to help?

**Comment by simorenoh** [comment] 2023-03-29 13:26
@pvaneck our cosmos client is only meant to be used with SQL API accounts as shared here: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-python-get-started?tabs=env-virtual%2Cazure-cli%2Cwindows

I have already spoken with @tengfei86 and recommended they open a new issue to see if somebody who works with Mongo can help them, since the misunderstanding here is they are attempting to use our cosmos client to connect to a mongo db account. Here is the other issue for reference: https://github.com/Azure/azure-sdk-for-python/issues/29537

**Comment by simorenoh** [comment] 2023-03-29 13:43
Here are different API's that use Cosmos (https://learn.microsoft.com/azure/cosmos-db/choose-api) - only the No SQL one is meant to be used with the cosmos client in question

**Comment by simorenoh** [comment] 2023-03-29 23:55
@gahl-levy this user is asking for Mongo information, could you share some resources with them please?

**Comment by tengfei86** [comment] 2023-03-31 05:53
> @tengfei86 To get the RU and autoscaling of an existing MongoDB database in a Cosmos account, you can go into your Cosmos DB account and click on ‘New Container’. [When choosing a throughput option, check the ‘Autoscale’ radio button and enter the maximum amount of RU/s you want your container to scale to](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-provision-autoscale-throughput?tabs=api-async).
/unresolve
@simorenoh , From the @ram-msft 's advice ,it looks like the CosmosClient from Java SDK can get the RU of exist db , my understanding is that CosmosClient from Python SDk is not support this feature ,right ?

**Comment by simorenoh** [comment] 2023-03-31 13:37
@tengfei86 the issue is not what features we support/ don't support, the issue here is you're trying to access the NoSQL API with your MongoDB account. It's like trying to access my outlook email account through gmail - yes, they're both email services, but it doesn't mean that gmail will let me access my account since it is a fully different email service.

**Comment by tengfei86** [comment] 2023-04-02 14:45
> @tengfei86 the issue is not what features we support/ don't support, the issue here is you're trying to access the NoSQL API with your MongoDB account. It's like trying to access my outlook email account through gmail - yes, they're both email services, but it doesn't mean that gmail will let me access my account since it is a fully different email service.

Got it ,thanks

**Comment by tengfei86** [comment] 2023-04-06 06:15
> 

@gahl-levy  any update for my issue ?

**Comment by tengfei86** [comment] 2023-04-06 06:31
> @tengfei86 To get the RU and autoscaling of an existing MongoDB database in a Cosmos account, you can go into your Cosmos DB account and click on ‘New Container’. [When choosing a throughput option, check the ‘Autoscale’ radio button and enter the maximum amount of RU/s you want your container to scale to](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-provision-autoscale-throughput?tabs=api-async).

```
    private final String databaseName = "fsas";
    private final String containerName = "job";

    private CosmosDatabase database;
    private CosmosContainer container;
    private String HOST = "mongodb-tiger-esaosp.mongo.cosmos.azure.com";
    private String MASTER_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    protected static Logger logger = LoggerFactory.getLogger(App.class);
    public static void main( String[] args )
    {

        App app = new App();
        try {
            app.cosmosClient();
        } catch (Exception e) {
           e.printStackTrace();
           logger.error(String.format("Cosmos getStarted failed with %s", e));
        } finally {
           app.shutdown();
        }
    }

    public void cosmosClient() throws Exception {
            client = new CosmosClientBuilder()
                        .endpoint(HOST)
                        .key(MASTER_KEY)
                        .consistencyLevel(ConsistencyLevel.EVENTUAL)
                        .contentResponseOnWriteEnabled(true)
                        .buildClient();


                // Get a reference to the resource
                 CosmosContainer container = client.getDatabase(databaseName).getContainer(containerName);
                // Read the throughput on a resource
                 ThroughputProperties autoscaleContainerThroughput = container.readThroughput().getProperties();
                //
                // The autoscale max throughput (RU/s) of the resource
                 int autoscaleMaxThroughput = autoscaleContainerThroughput.getAutoscaleMaxThroughput();
                // The throughput (RU/s) the resource is currently scaled to
                 int currentThroughput = autoscaleContainerThroughput.getManualThroughput();
                 logger.info("current Throughtput is {}",currentThroughput);


    }
```

![image](https://user-images.githubusercontent.com/524484/230289052-e4acd59d-78de-4789-b4b6-60a9e4bf91a8.png)
@ram-msft @pvaneck 
when i run the above code , always raise 404 exception ,i don't know the root cause ,
i think there should  be  two  possible  reasons ,
The first one is that  the endpoint format  is  wrong  , "mongodb-tiger-esaosp.mongo.cosmos.azure.com" or "https://mongodb-tiger-esaosp.mongo.cosmos.azure.com:443/",
The second one is that cosmos don't support mongo as  @simorenoh  said before  
Could you give me some suggestions  ?

**Comment by tengfei86** [comment] 2023-04-10 02:11
@gahl-levy  Hi ,do you have any further suggestions ?

**Comment by tengfei86** [comment] 2023-04-13 01:31
Hi Guys, you can close this issue if you think you don't need to feedback

**Comment by xiangyan99** [comment] 2023-04-21 16:54
Given cosmos team did not respond, closing the issue.

**Closed by xiangyan99** 2023-04-21 16:54 UTC
Labels: Cosmos, customer-reported, needs-team-attention, CXP Attention
