### ISSUE TITLE
`lropoller.result` returns incomplete data

### ISSUE THREAD

**Issue by gjolly** [Azure/azure-sdk-for-python#22941] opened 2022-02-07 16:42 UTC
- **Package Name**: azure-core
- **Package Version**: 1.22.0
- **Operating System**: Linux - Ubuntu Impish 21.10
- **Python Version**: Python 3.9.7

**Describe the bug**

The `result` method of `azure.core.polling.lropoller` returns invalid data. Even after the operation is completed (`wait` has returned), `result` returns data with all fields set to None. We noticed this recently and it wasn't the case before (~1 week ago).

**To Reproduce**

Run the following script:

```
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.resource import SubscriptionClient
from azure.identity import DefaultAzureCredential

LOCATION = 'francecentral'
GROUP_NAME ='test-group'
SUBSCRIPTION_ID = 'XXXXXXXXXXXXXXXXXXX'

credentials = DefaultAzureCredential()

resource_client = ResourceManagementClient(credentials, SUBSCRIPTION_ID)
resource_client.resource_groups.create_or_update(
        GROUP_NAME, {'location': LOCATION})

network_client = NetworkManagementClient(credentials, SUBSCRIPTION_ID)
public_ip_addess_params = {
    'location': LOCATION,
    'public_ip_allocation_method': 'Dynamic'
}

op = network_client.public_ip_addresses.begin_create_or_update(
    GROUP_NAME,
    GROUP_NAME,
    public_ip_addess_params
)

op.wait()
print(op.result())
```

The output is:

```
{'additional_properties': {'status': 'Succeeded'}, 'id': None, 'name': None, 'type': None, 'location': None, 'tags': None, 'extended_location': None, 'sku': None, 'etag': None, 'zones': None, 'public_ip_allocation_method': None, 'public_ip_address_version': None, 'ip_configuration': None, 'dns_settings': None, 'ddos_settings': None, 'ip_tags': None, 'ip_address': None, 'public_ip_prefix': None, 'idle_timeout_in_minutes': None, 'resource_guid': None, 'provisioning_state': None, 'service_public_ip_address': None, 'nat_gateway': None, 'migration_phase': None, 'linked_public_ip_address': None, 'delete_option': None}
```

Even if the "status" is "Succeeded", non of the fields are set.

**Expected behavior**

Some of the fields should be set (eg the `id`)

**Additional context**

The behavior causes our application to fail where it wasn't failing before and while we did not change the code. We think that the issue happens on Azure side.

**Comment by xiangyan99** [comment] 2022-02-08 01:02
Thanks for the feedback, we’ll investigate asap.

**Comment by iscai-msft** [comment] 2022-02-11 21:22
closing this issue because the core patch release (release 1.22.1) unblocks end users. However, the real root cause of the issue are SDKs generated from incorrect swaggers, but @lmazuel is escalating that through different channels

**Closed by iscai-msft** 2022-02-11 21:22 UTC
Labels: bug, Network - Virtual Network, Mgmt, customer-reported
