### ISSUE TITLE
AzureML SDK Copier.copy_volume() takes at most 2 positional arguments (4 given) - Internal Error with right syntax

### ISSUE THREAD

**Issue by edgBR** [Azure/azure-sdk-for-python#30833] opened 2023-06-21 07:18 UTC
Environment:

```Dockerfile

FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN echo "source /opt/miniconda/etc/profile.d/conda.sh &&             conda activate" >> ~/.bashrc

RUN echo  $'channels:\n\
  - anaconda\n\
  - conda-forge\n\
  - defaults\n\
dependencies:\n\
  - python=3.10.10\n\
  - pip:\n\
      - azureml-sdk==1.51.0\n\
      - azureml-dataset-runtime==1.51.0\n\
      - azureml-pipeline==1.51.0\n\
      - stringcase==1.2.0\n\
      - numba==0.56.4\n\
      - numpy==1.23.5\n\
      - pandas==2.0.0\n\
      - scipy==1.10.1\n\
      - scikit-learn==1.2.2\n\
      - xgboost==1.7.5\n\
      - scikit-lego==0.6.14\n\
      - fastparquet==2023.2.0\n\
' > conda_env.yml
        RUN source /opt/miniconda/etc/profile.d/conda.sh &&             conda activate &&             conda install conda &&             pip install cmake &&             conda env update -f conda_env.yml
```

**Describe the bug**
AzureML fails to upload data. The syntax is absolutely correct.

**To Reproduce**
Code:

```python
output_dir = os.path.join('./outputs/data_output/')
timestamp = datetime.now().strftime('%H_%M_%S')
os.makedirs(output_dir, exist_ok=True)
output_file_path_case_level = os.path.join(output_dir,
                                           args.score_output_case_file_name.split('.')[0] +
                                           '_' +
                                           timestamp +
                                           '.parquet')
output_file_path_portfolio_level = os.path.join(output_dir,
                                                args.score_output_portfolio_file_name.split('.')[0] +
                                                '_' +
                                                timestamp +
                                                '.parquet')

ml_and_dr_data = pd.concat(
    [final_data, processed_dr_data], axis=0, ignore_index=True)

ml_and_dr_data_cleaned = _clean_final_file(ml_and_dr_data)

ml_and_dr_data_final = _redistribute_cashflows(final_df=ml_and_dr_data_cleaned,
                                               rd_path=args.input_data_path,
                                               rd_file=args.rd_file,
                                               datastore=datastore_object,
                                               aml_run=run)
ml_and_dr_data_final["tgt_period"] = ml_and_dr_data_final["tgt_period"].astype(int)

ml_and_dr_data_final.to_parquet(
    path=output_file_path_case_level,
    index=False,
    coerce_timestamps="ms",
    allow_truncated_timestamps=True)

logging.info(f"Case level predictions saved to {output_file_path_case_level}")

portfolio_predictions = _aggregate_cashflows(
    case_level_df=ml_and_dr_data_final,
    aggregation_keys=['adf_name', 'adf_pipeline_run_id', 'aml_pipeline_run_id',
                      'model_name', 'model_version', 'model_snapshot', 'model_last_updated',
                      'portfolio_name', 'portfolio_code_gdwh', 'tgt_period', 'snapshot_date',
                      'tgt_month', 'day_since_reg_date', 'transaction_type', 'cashflow_type',
                      'reporting_entity_code', 'country', 'currency'],
    prediction_column='redistributed_prediction',
    cumulative_prediction_column='redistributed_prediction_acc',
    debt_size_col='rem_total_amt')

portfolio_predictions.to_parquet(
    path=output_file_path_portfolio_level, 
    index=False, 
    coerce_timestamps="ms", 
    allow_truncated_timestamps=True)
logging.info(f"Portfolio level predictions saved to {output_file_path_portfolio_level}")

output_data_path = DataPath(datastore, args.output_data_path)

Dataset.File.upload_directory(src_dir=output_dir,
                              target=output_data_path,
                              overwrite=True)
```

Code fails when launched as an azure pipeline step job:

```python
INFO:__main__:Absolute predictions in SEK calculated
INFO:__main__:Case level predictions saved to ./outputs/data_output/scored_data_case_level_07_02_31.parquet
INFO:__main__:Aggregating cashflows at portfolio level
INFO:__main__:Portfolio level predictions saved to ./outputs/data_output/scored_data_portfolio_level_07_02_31.parquet
Validating arguments.
Arguments validated.
'overwrite' is set to True. Any file already present in the target will be overwritten.
Uploading files from '/mnt/azureml/cr/j/3f81205414384e2ebd885c0ed53deb33/exe/wd/outputs/data_output' to 'cashflow/inference_data_loadings/scored_data/2022-09-01/'
INFO:__main__:Unable to upload predictions to azure datapath:cashflow/inference_data_loadings/scored_data/2022-09-01/, Copier.copy_volume() takes at most 2 positional arguments (4 given)
Cleaning up all outstanding Run operations, waiting 300.0 seconds
5 items cleaning up...
Cleanup took 0.4441568851470947 seconds
Traceback (most recent call last):
  File "score/score.py", line 702, in <module>
    score_execution(args=args,
  File "score/score.py", line 653, in score_execution
    raise e
  File "score/score.py", line 646, in score_execution
    Dataset.File.upload_directory(src_dir=output_dir,
  File "/opt/miniconda/lib/python3.10/site-packages/azureml/data/_loggerfactory.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.10/site-packages/azureml/data/dataset_factory.py", line 928, in upload_directory
    FileDatasetFactory._upload_directory(src_dir, target, pattern, overwrite, show_progress)
  File "/opt/miniconda/lib/python3.10/site-packages/azureml/data/dataset_factory.py", line 991, in _upload_directory
    copier.copy_volume(volume_info, "", show_progress, False)
TypeError: Copier.copy_volume() takes at most 2 positional arguments (4 given)
```

Code works locally:

![image](https://github.com/Azure/azure-sdk-for-python/assets/14976422/9ab6a947-1d00-4e61-aa52-bf5dfab39420)

**Expected behavior**
The code just works as usual.

**Comment by ma11034** [comment] 2023-06-21 07:27
Hi! 
Faced same thing, no code change. Got this:
![Screenshot 2023-06-21 at 10 25 30](https://github.com/Azure/azure-sdk-for-python/assets/86479735/0ffd9157-9eb2-4786-b0ad-988aa304b3c5)

BR,
M

**Comment by obiii** [comment] 2023-06-21 07:28
We are facing the same issue. The code works fine when run locally but when run as an ml job, with the same dependencies as local, it results in the error:
**TypeError: Copier.copy_volume() takes at most 2 positional arguments (4 given).**

**Comment by pmbb2h** [comment] 2023-06-21 07:42
Same problem here, no code changes, and I am encountering this error:

TypeError: Copier.copy_volume() takes at most 2 positional arguments (4 given).

**Comment by cardoner1993** [comment] 2023-06-21 08:11
Same problem here. Previous execution done on the 11th of June worked fine but since this week the job is failing in Azure Databricks when running from a pipeline.

**Comment by edgBR** [comment] 2023-06-21 08:55
I really hope that they fix it and they don't shield behind migrating to sdk2.0....

**Comment by kashifkhan** [comment] 2023-06-21 15:10
Thank you for the feedback. We will investigate and get back to yall asap. 

cc @azureml-github

**Comment by cardoner1993** [comment] 2023-06-23 07:38
Hi @kashifkhan any solution for this ? Maybe pin some library version ?

**Comment by jarandaf** [comment] 2023-06-23 08:17
I am also experiencing this issue. Any update?

**Comment by krishnamohannadimpalli** [comment] 2023-06-26 02:43
Hi @kashifkhan Is there a workaround ? When can we expect this to be fixed.

**Comment by anliakho2** [comment] 2023-06-26 23:09
There seems to be some issue with your python environment. 
The extra arguments in copy_volume() method were added as part of **azureml-dataprep==4.11.1** and corresponding **azureml-dataprep-rslex==2.18.1** The code to consume those methods was only supposed to be released as part of azureml-sdk=1.52.0, however looking at the code it was accidentally picked up by 1.51.post1 release.
This means that to fix the issue you either need to upgrade to 1.52.0 release or downgrade to 1.51.0 release of azureml-core package (part of azureml-sdk)

**Comment by anliakho2** [comment] 2023-06-26 23:35
@kashifkhan @luigiw @jarandaf @edgBR @obiii FYI

**Comment by edgBR** [comment] 2023-06-27 06:39
Hi, we downgraded to 1.50 and is working. However we will consider 1.52.

BR
E

**Comment by josegarciav** [comment] 2023-09-29 18:56
I am facing the same issue!

**Comment by josegarciav** [comment] 2023-10-02 19:08
> I am facing the same issue!

The issue was resolved when removing these lines
<img width="575" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/57261516/03e2805f-a082-4129-9a1b-a1267019331f">


<img width="523" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/57261516/dc6e2286-2a0f-49af-8b6b-1cb62ff3acd2">

**Comment by SturgeonMi** [comment] 2023-10-06 16:14
#23137 Close it here since the issue is gone using azureml-sdk=1.50.0 and will reopen if 1.52.0 doen't work.

**Closed** 2023-10-06 17:17 UTC
Labels: question, Machine Learning, Service Attention, customer-reported
