### ISSUE TITLE
ImportError: cannot import name RecoveryServicesBackupClient from azure.mgmt.recoveryservicesbackup

### ISSUE THREAD

**Issue by eliassal** [Azure/azure-sdk-for-python#32925] opened 2023-11-02 17:38 UTC
- **Package Name**: azure.mgmt.recoveryservicesbackup
- **Package Version**: 
- **Operating System**: Fedora 37
- **Python Version**:  Python 3.11.5

**Describe the bug**
I am trying to run an ansible playbook to create a VM in Azure in a specific resource group, after creating "credentials" file in .azure directory with the following items

> subscription_id=XXXXX-4725-XXXX-8e3b-XXXXX
> client_Id=XXXXX-a923-4023-XXXX-XXXXXXX
> secret= xvfsdeXXXV1811111XXXXXXXXXXXX
> tenant=XXXXXXX-XXXX-4e88-af13-XXXXXX

I get

> an exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/lib/python3.11/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on fedora.salam.net's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

**To Reproduce**
1. mentioned above

**Expected behavior**
Create VM on Azure

**Screenshots**

**Additional context**
This was happening on 2nd fedora 37 VMs. on the 2nd one I issued 
`az upgrade`
and az-cli was upgraded to 2.53.1. On this VM when I run the same playbook, I get

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named '**azure.mgmt.recoveryservicesbackup.models**'
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on puppetmaster29's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

When I try 
`pip install azure.mgmt.recoveryservicesbackup.models`

I get

> ERROR: Could not find a version that satisfies the requirement azure.mgmt.recoveryservicesbackup.models (from versions: none)
> ERROR: No matching distribution found for azure.mgmt.recoveryservicesbackup.models
> 

Something strange happens on the 1st VM regarding upgrading az-cli, when I run az --version I get a message

> Your current Azure CLI version is 2.52.0. Latest version available is 2.53.1.

when I run az upgrade, it says

```
Dependencies resolved.
Nothing to do.
Complete!
CLI upgrade failed or aborted
```

**Comment by kashifkhan** [comment] 2023-11-02 18:57
Thank you for your feedback @eliassal . We will investigate and get back to you asap.

**Comment by ChenxiJiang333** [comment] 2023-11-03 07:14
Hi, @eliassal 
You need to use this command `pip install azure.mgmt.recoveryservicesbackup` instead, please take another try.

**Comment by eliassal** [comment] 2023-11-03 09:33
Hi Chen, when I ran

`pip install azure.mgmt.recoveryservicesbackup`

It seems that this item is already there as you can notice in the output of the command

> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: azure.mgmt.recoveryservicesbackup in /usr/lib/python3.11/site-packages (6.0.0)
> Requirement already satisfied: isodate<1.0.0,>=0.6.1 in /home/salam/.local/lib/python3.11/site-packages (from azure.mgmt.recoveryservicesbackup) (0.6.1)
> Requirement already satisfied: azure-common~=1.1 in /usr/lib/python3.11/site-packages (from azure.mgmt.recoveryservicesbackup) (1.1.28)
> Requirement already satisfied: azure-mgmt-core<2.0.0,>=1.3.2 in /usr/lib/python3.11/site-packages (from azure.mgmt.recoveryservicesbackup) (1.3.2)
> Requirement already satisfied: azure-core<2.0.0,>=1.24.0 in /home/salam/.local/lib/python3.11/site-packages (from azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (1.29.5)
> Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from isodate<1.0.0,>=0.6.1->azure.mgmt.recoveryservicesbackup) (1.16.0)
> Requirement already satisfied: requests>=2.18.4 in /usr/lib/python3.11/site-packages (from azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (2.28.1)
> Requirement already satisfied: typing-extensions>=4.6.0 in /home/salam/.local/lib/python3.11/site-packages (from azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (4.8.0)
> Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3.11/site-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (2.1.0)
> Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (3.3)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure.mgmt.recoveryservicesbackup) (1.26.16)
>

**Comment by eliassal** [comment] 2023-11-03 16:20
Hi, just to let you know that I used amother wsl2 ubuntu on my win 10 box, installed ansible tried to run the same command, I got same errors as for the other 2, no module msrestazure, I did
`pip install msrestazure`
then no module  azure.cli, I did
`pip install azure.cli`
then I got no azure.mgmt.network, I did
`pip install azure.mgmt.network`
then got no azure.storage.blob, I did 
`pip install azure.storage.blob`
then I got no  azure.mgmt.automation, I did
`pip install azure.mgmt.automation`

Then the exact s**ame error for azure.mgmt.recoveryservicesbackup.models**, when I tried to pip it indicated no such module as on the other 2 machines

**Comment by ChenxiJiang333** [comment] 2023-11-06 03:22
@eliassal 
This error was caused by ansible plugins, and I found that they had made a fix for it. Please track that issue wait for the fix merged.
https://github.com/ansible-collections/azure/issues/1260#issuecomment-1723531288

**Closed** 2023-11-17 22:33 UTC
Labels: question, Mgmt, customer-reported, issue-addressed
