### ISSUE TITLE
[azure-storage-blob] BlobClient upload_blob does not use headers parameter for multi-block uploads.

### ISSUE THREAD

**Issue by jboelter** [Azure/azure-sdk-for-python#13506] opened 2020-09-02 05:22 UTC
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.4.0
- **Operating System**:  WSL / Ubuntu 20.04.1 LTS / 4.19.104-microsoft-standard / Windows 10.0.19041.450
- **Python Version**: 3.8.2

**Describe the bug**
`BlobClient` `upload_blob()` does not inject the headers parameter if the upload takes the multi-block upload code path (single block upload works).

**To Reproduce**

The provided headers will not be injected into the request if the object size exceeds `blob_settings.max_single_put_size` (default 64 * 1024 * 1024).  Starting from a SAS URL.

```python
        object = io.BytesIO(bytearray(1024*1024*100))
        blob = BlobClient.from_blob_url(url)
        blob.upload_blob(
           object,
           headers={'x-custom-header':'value'}, # BUG in the Azure SDK
        )
```

**Expected behavior**

The `headers` parameter to `upload_blob` should work for both single PUT uploads and multi-block uploads.

Fix appears to be just passing `headers` to `upload_data_chunks` [1](https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L120) [2](https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py#L95) and `upload_substream_blocks` [1](https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L132) [2](https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/aio/_upload_helpers.py#L107) in `upload_block_blob`. Not sure where else this may show up.

**Additional context**

We use a custom outgoing reverse proxy that expects certain headers.

Workaround the issue with a `raw_request_hook`.

```python
        def hook(args):
            args.http_request.headers.update({'x-custom-header':'value'})

        blob = BlobClient.from_blob_url(url)
        blob.upload_blob(
            object,
            raw_request_hook=hook,
        )
```

**Comment by xiafu-msft** [comment] 2020-09-08 23:49
Hi @jboelter 

Thanks for reaching out and finding the workaround to unblock yourself.
It looks like we are passing header value when commit the block list, https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L150

We will do further investigation about what's going wrong there.

**Comment by jboelterintc** [comment] 2020-09-22 16:13
> Hi @jboelter
> 
> Thanks for reaching out and finding the workaround to unblock yourself.
> It looks like we are passing header value when commit the block list,
> 
> https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L150
> 
> Do you need that customized header on each put block request?

The headers should be on every outgoing request. As noted in the bug, the headers are absent from `upload_data_chunks` and `upload_substream_blocks`. Not if this may show up in other call paths.

**Comment by jboelter** [comment] 2020-09-22 16:14
> Hi @jboelter
> 
> Thanks for reaching out and finding the workaround to unblock yourself.
> It looks like we are passing header value when commit the block list,
> 
> https://github.com/Azure/azure-sdk-for-python/blob/900aa7d23212f528aec352b9bff2a87cd5294720/sdk/storage/azure-storage-blob/azure/storage/blob/_upload_helpers.py#L150
> 
> Do you need that customized header on each put block request?

The headers should be on every outgoing request. As noted in the bug, the headers are absent from `upload_data_chunks` and `upload_substream_blocks`. Not if this may show up in other call paths.

**Comment by xiafu-msft** [comment] 2020-09-24 05:31
Hi @jboelter 

It looks like we intended to only add the customized header in the exact "write" operation (change blob content) which is upload blob or commit block list operation. So it's not a bug....
While I think it doesn't hurt if we add it to all internal requests! We will post a pr to add customized header to all sub requests soon!

**Comment by tasherif-msft** [comment] 2020-10-06 00:45
Hi @jboelter just wanted to let you know that we have a PR up for this issue. I'll let you know once its merged.

**Closed** 2020-10-20 23:20 UTC
Labels: Client, Service Attention, Storage, customer-reported, needs-team-attention, question
