### ISSUE TITLE
Import error in Azure storage blob client

### ISSUE THREAD

**Issue by KiaraShannen** [Azure/azure-sdk-for-python#28991] opened 2023-02-24 09:37 UTC
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.10.0
- **Operating System**: Databricks Driver: Standard_DS3_v2 · Workers: Standard_DS3_v2 · 1 worker · 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)
- **Python Version**: 3.9

**Describe the bug**
Error first noticed on: 23-02-2023

--> Error on the following import: from azure.storage.filedatalake import DataLakeServiceClient
Error message: 
ImportError: cannot import name 'Self' from 'typing_extensions' (/databricks/python/lib/python3.9/site-packages/typing_extensions.py)

Self is listed within a function as:
Self = typing.Self 
typing is imported in the typing_extensions file.

[https://github.com/python/typing_extensions/blob/main/src/typing_extensions.py](Type extension source code url) 

**To Reproduce**
code:
```
import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

install( "azure-storage-file-datalake")
install( "azure.identity")

import os, uuid, sys
from azure.storage.filedatalake import DataLakeServiceClient
``` 
Error happens on the last import

**Expected behavior**
Import without error

**Screenshots**
<img width="831" alt="Schermafbeelding 2023-02-24 om 10 24 43" src="https://user-images.githubusercontent.com/66114523/221141570-9bf69401-397c-4bb1-9a02-8ce28efda1c3.png">

<img width="833" alt="Schermafbeelding 2023-02-24 om 10 25 25" src="https://user-images.githubusercontent.com/66114523/221141699-a45d8358-f994-43eb-9311-bc3871800c46.png">

<img width="830" alt="Schermafbeelding 2023-02-24 om 10 25 45" src="https://user-images.githubusercontent.com/66114523/221141773-2e293d1e-1cd5-44f4-8f39-2d68f8900780.png">

**Comment by jalauzon-msft** [comment] 2023-02-25 00:48
Hi @KiaraShannen, can you tell what version of `typing_extensions` ended up getting installed in your environment? `typing_extensions.Self` was introduced in version `4.0.0` and the Datalake SDK properly defines its requirement here:
https://github.com/Azure/azure-sdk-for-python/blob/31006414db13c61fd6f6d350d4202859e8004420/sdk/storage/azure-storage-file-datalake/setup.py#L80

So `pip` should have grabbed the correct version for you but if you somehow got a lower version, updating `typing_extensions` should help.

**Comment by Timmofo** [comment] 2023-02-27 16:07
Hi all,

@jalauzon-msft, this issue was not with typing-extensions. I did some tests and it did not fix the issue.

I had the same issue since 23-02, also on Databricks with exactly the same setup as OP. I suspect that the issue is with Databricks. Upgrading the cluster from 11.3 LTS to 12.1 ML fixed the issue for me. Cheers!

**Comment by jalauzon-msft** [comment] 2023-02-27 18:26
Thanks for the tip @Timmofo Tim! We have seen these type of Import issues in the past with Databricks. I'm not too familiar with Databricks but it seems they do special something with Python dependencies sometimes.

@KiaraShannen if possible, could you please try and update your Databricks version as Tim has done to see if it resolves the issue for you? Thanks.

**Comment by jalauzon-msft** [comment] 2023-03-03 20:23
Thanks for confirming @KiaraShannen. I'm going to go ahead and close this issue then as it seems to have been an issue with Databricks.

I'm not sure on the plans for the next LTS version of Databricks but I assume the next LTS version will also contain the fix. You will need to contact the Databricks team, likely through Azure Support, to get more information on that. If you wish to continue to use your LTS version, you can also consider pinning your `azure-storage-file-datalake` dependency to the previous version that was working.

**Closed by jalauzon-msft** 2023-03-03 20:23 UTC
Labels: Storage, question, Service Attention, customer-reported, needs-team-attention

**Comment by oliverbeagley-pgg** [comment] 2023-03-06 16:31
For databricks users still on runtime 11.3 LTS, (which uses `typing_extensions==3.10.0.2`) a workaround is to pin the storage package `azure-storage-blob<12.15.0` as version `12.15.0` was the first release to use `Self`
