### ISSUE TITLE
Uncaught Exception in DefaultAzureCredential

### ISSUE THREAD

**Issue by PhysWiz314** [Azure/azure-sdk-for-python#31032] opened 2023-07-07 16:07 UTC
- **Package Name**: azure-identity
- **Package Version**: 1.13.0
- **Operating System**: AzureML Instance: Ubuntu 20.04
- **Python Version**: 3.8

**Describe the bug**
When using DefaultAzureCredential, there is an exception coming from ManagedIdentityClient that causes DefaultAzureCredential to stop trying different methods and ends up failing to get credentials.

I can work around this by using AzureCliCredential (or one of the other credential methods) but I cannot use this workaround when using other packages like `mltable` or `azure-fsspec` since they seem to run their own credential routine.

**To Reproduce**
1. I don't know what it is about my Managed Identity setup that causes this, but you need to trigger the raise [here](https://github.com/Azure/azure-sdk-for-python/blob/a700c453f3dd768de8e5bae08fa6e675ded661df/sdk/identity/azure-identity/azure/identity/_internal/managed_identity_client.py#L52).
2. The `ClientAuthenticationError` makes it back to [this](https://github.com/Azure/azure-sdk-for-python/blob/a700c453f3dd768de8e5bae08fa6e675ded661df/sdk/identity/azure-identity/azure/identity/_credentials/chained.py#L88) try/except where it is caught as an `Exception` and the for loop is broken.

**Expected behavior**
DefaultAzureCredential loops though all selected credential routines until it receives a token.

**Screenshots**
Only 2 credentials attempted.
![251795502-5cec91d3-2ac7-485c-bc5d-8d10990acd15](https://github.com/Azure/azure-sdk-for-python/assets/32742580/96ad7aba-a023-4804-9f0a-79ac1928cc3f)

**Additional context**
I don't seem to have this problem from my local computer but I have to work on AzureML instances and that is where this pops up.
There is likely a deeper problem here but I found that specifically catching the ClientAuthenticationError allows the routine to proceed and get a proper credential.

**Comment by kashifkhan** [comment] 2023-07-10 13:26
Thank you for the feedback @PhysWiz314 . We will investigate and get back to you asap.

**Comment by xiangyan99** [comment] 2023-07-10 17:38
Thanks for reaching out.

Could you share more information?

Is this a machine that managed by machine learning studio?

Did you configure managed identity on that machine?

Thanks.

**Comment by PhysWiz314** [comment] 2023-07-10 17:58
> Thanks for reaching out.
> 
> Could you share more information?
> 
> Is this a machine that managed by machine learning studio?
> 
> Did you configure managed identity on that machine?
> 
> Thanks.

Yes, this is an instance that is set up inside Machine Learning Studio. There is no Managed Identity set up on the machine. To give a bit more context on why it works on my laptop, here is the history of attempts to find a credential. For some reason the error code for `ManagedIdentityCredential` is different and properly caught by the loop in `get_token`.

![image](https://github.com/Azure/azure-sdk-for-python/assets/32742580/bef86b37-d5a3-4d6f-93a3-60ffb2d7928b)

**Comment by xiangyan99** [comment] 2023-07-10 18:34
Thanks for the information.

It is by design that DefaultAzureCredential continues to attempt other credentials if managed identity is not configured and stops if managed identity is configured but we fail to get a valid token.

It is a known issue that managed identity in machine learning studio does not work correctly with identity library.

**Comment by PhysWiz314** [comment] 2023-07-10 18:42
@xiangyan99 Thanks for letting me know that it is a known issue. Is there a fix coming for this? We are upgrading our internal packages to Azure SDK v2 but this is a huge blocker since `mltable` and `azure-fsspec` can't be used to load data so we can work with it on our ML studio instances.

**Comment by xiangyan99** [comment] 2023-07-10 19:09
To help me understand better, do you want to use managed identity for the authentication?

If not, you can either not configure managed identity for those hosted machines or use DefaultAzureCredential(exclude_managed_identity_credential=true) to opt out the managed identity in your code.

**Comment by PhysWiz314** [comment] 2023-07-10 20:45
No I don't want to use managed identity for authentication and yes I can use the `exclude_managed_identity_credential` for my own code. Unfortunately this does not work for packages like `mltable` or `azure-fsspec`.

Here is the situation that led me to discover this issue.
I would like to load a data asset that is registered in my ML workspace. I was following this [example](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-data-interactive?view=azureml-api-2&tabs=datastore#table-asset) in the documentation.

The issue is that `mltable` and `azure-fsspec` don't seem to use the token/credentials that I have already loaded and try to get a new token (pictured below) which runs into the issue I described.
![image](https://github.com/Azure/azure-sdk-for-python/assets/32742580/4035130b-08b8-4fa9-b6d7-1e58419e2b53)

**Comment by PhysWiz314** [comment] 2023-07-12 22:05
Small Update: I looked into `mltable` and `azure-fsspec` and they hide the call to DefaultAzureCredential pretty deep within private functions making it essentially impossible for a user that is having this problem to use them or exclude credential methods with flags.

> and stops if managed identity is configured but we fail to get a valid token

Wouldn't it be a better idea to throw a warning (so that the user knows that ManagedIdentity wasn't used) instead of stopping and continue to try other credential methods? This would mitigate the issue described here but still let users know there is an issue with their ManagedIdentity setup if something goes wrong.
In my case, Managed Identity is not set up but the code behaves as if it is so I know I can safely ignore the warning.

**Comment by PhysWiz314** [comment] 2023-08-15 16:28
/unresolve

As it turns out, `mlflow` also uses `DefaultAzureCredential()` to authenticate which again fails when it tries to use ManagedIdentityCredential to get a token. Again, I cannot provide arguments to this call to exclude ManagedIdentityCredential so I am now unable to use `mlflow`, `azure-fsspec` and `mltable` which are key components of being able to run code on an AzureML workspace compute instance. Is there any way to get some help with this?

> It is a known issue that managed identity in machine learning studio does not work correctly with identity library.

Again, is this being worked on? Is there a way for me to track progress (i.e. a bug report, issue in GitHub etc)?

Another very simple solution would be to move ManagedIdentityCredential to the bottom of the list of authentication methods to try. That way it is still tried but the user would be able to use another method to authenticate properly.

**Comment by pvaneck** [comment] 2023-08-16 03:15
@xiangyan99 Can you reference any open issues regarding allowing users to specifiy their own credentials for the ML SDKs? I feel like something like credential instances should definitely be provided by the user and not instantiated from within the SDK itself. 

When `DefaultAzureCredential` should continue with the authentication flow versus when it should terminate the flow has been a bit of debatable topic. The current prevailing sentiment is that for deployed service credentials (such as `EnvironmentCredential` and `ManagedIdentityCredential`), if the prerequisites for a credential are met and an _attempt_ to retrieve an access token is made, if the token request to Azure Active Directory fails to yield a token, then the flow should stop with a thrown exception. This is to provide a more predicatable deployed behavior without any surprise authentications with developer credentials.

Overall, I think the solution to this problem needs to be solved in the libraries like `mltable` itself. 

In the meantime, I think one way of circumventing the use of `ManagedIdentityCredential` is to remove "prerequisite" envvars that are checked to determine if a specific credential should be used. For Azure ML, `MSI_ENDPOINT` and `MSI_SECRET` are checked. Removing MSI_ENDPOINT from the python envvars might be able to do the trick assuming it persists through the usage for where `mltable`, `mlflow`, etc. are being called. Worth a shot, I think.

```python
import os
from azure.identity import DefaultAzureCredential

os.environ.pop('MSI_ENDPOINT', None)

credential = DefaultAzureCredential()
credential.get_token("https://management.azure.com/.default")
```

**Comment by xiangyan99** [comment] 2023-08-16 15:07
Since the issues are in mlflow, azure-fsspec, @luigiw do you know who is the best person to take a look?

**Comment by PhysWiz314** [comment] 2023-08-16 15:48
Thanks @pvaneck for the detailed response!

> The current prevailing sentiment is that for deployed service credentials (such as EnvironmentCredential and ManagedIdentityCredential), if the prerequisites for a credential are met and an attempt to retrieve an access token is made, if the token request to Azure Active Directory fails to yield a token, then the flow should stop with a thrown exception. This is to provide a more predicatable deployed behavior without any surprise authentications with developer credentials.

This makes sense.

> Overall, I think the solution to this problem needs to be solved in the libraries like `mltable` itself.

I agree with this sentiment. Ideally users would be able to provide the credential to the library or at the very least arguments that would enable/disable credential methods that the DefaultAzureCredential class sets up. I plan to open up issues/feature requests to see if this can be done. I was hoping that the issue could easily be solved here instead of having each individual library have to change their use.

I tried out your workaround and that works well. That was going to be my next line of thinking so you have saved me a bunch of time trying to track something like that down. Thanks!

**Comment by PhysWiz314** [comment] 2023-08-16 16:18
FYI I did end up trying to set up a Managed Identity to get that authentication method to work. Unfortunately this results in the same error when using a Compute Instance in an ML Workspace.

I was able to trace the issue to the `AZURE_CLIENT_ID` environment variable not being set in the instances (it seems to be held in `DEFAULT_IDENTITY_CLIENT_ID` instead). This means that the Managed Identity doesn't have a `client_id` to work with and when the request for a token is made, a 404 is returned which isn't caught and ends with the "No token returned" error.

I confirmed that this was the issue by adding a `managed_identity_client_id` argument to `DefaultAzureCredential`. This adds the required query parameter to the URL and I could successfully get a token.
![image](https://github.com/Azure/azure-sdk-for-python/assets/32742580/625ebd44-113b-41b1-843c-c9557849e017)

Next, I tried to set the `AZURE_CLIENT_ID` environment variable so that the `ManagedIdentityCredential` could use it, but ran into issues with Environment checks. Ultimately `DefaultAzureCredential` was throwing errors trying to use `EnvironmentCredential` instead of the `ManagedIdentityCredential`. I'm not sure if this is known or not but figured I would share what I found in case it is useful.

The only think I haven't tested is if this is the same cause for the "No token returned" error when I didn't have a Managed Identity set up. I'll have to wait for my IT team to remove the Managed Identity from my compute instance before I can test that properly.

**Comment by pvaneck** [comment] 2023-08-18 22:58
Thanks for the additional details! Didn't know about the `DEFAULT_IDENTITY_CLIENT_ID` envvar. I will need to investigate to see if we should try checking for that variable inside our ManagedIdentityCredential as a fallback for client_id or perhaps instead try to have `AZURE_CLIENT_ID` be populated in the ML Compute instance by default.

When you had set the `AZURE_CLIENT_ID` envvar yourself, what error were you receiving from DefaultAzureCredential? From what I understand it should skip EnvironmentCredential if no complete set of environment variables is found ([reference](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python)).

**Comment by pvaneck** [comment] 2023-08-19 00:14
I am not too familiar with Azure ML, but trying on a newly created Azure ML compute instance, I was not able to use ManagedIdentityCredential (getting the same 404 and "no token received") until I found and clicked this "Authenticate" button, 

![image](https://github.com/Azure/azure-sdk-for-python/assets/1868861/802c253b-087d-4756-8af1-6d26655429b3)

Then I was able to authenticate using `DefaultAzureCredential` without setting `AZURE_CLIENT_ID`. 

```sh
DEBUG:urllib3.connectionpool:http://127.0.0.1:46808 "GET /MSI/auth?api-version=2017-09-01&resource=https://storage.azure.com HTTP/1.1" 200 None
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Content-Type': 'application/json'
    'Date': 'Fri, 18 Aug 2023 23:03:17 GMT'
    'Transfer-Encoding': 'chunked'
<azure.core.pipeline.PipelineResponse object at 0x7f8fefb42b20>
DEBUG:msal.token_cache:event={
    "data": {},
    "response": {
        "access_token": "********",
        "expires_in": 1508,
        "expires_on": 1692401306,
        "resource": "https://storage.azure.com",
        "token_type": "Bearer"
    },
    "scope": [
        "https://storage.azure.com"
    ]
}
DEBUG:azure.identity._internal.get_token_mixin:AzureMLCredential.get_token succeeded
DEBUG:azure.identity._internal.decorators:ManagedIdentityCredential.get_token succeeded
```

Not sure what this  "Authenticate" step specifically, but seems like it did some extra setup to allow the /MSI endpoint to work.

**Comment by PhysWiz314** [comment] 2023-09-01 17:59
> Not sure what this "Authenticate" step specifically, but seems like it did some extra setup to allow the /MSI endpoint to work.

Hey @pvaneck I finally had a chance to try this out. I had a bit of an odd experience since the "Authenticate" button seemed to fail. I shutdown and re-started my instance and the message to Authenticate disappeared and the credentials started working.

I had a colleague reproduce our steps and they had the same experience as you. No Token before Authenticate but works fine after so I think it is a good work around.

I typically connect to my instance through VSCode so I had never seen the Authenticate button before. It would be nice to know what steps that runs so that it can be duplicated in terminal or code so that users aren't forced to log into the portal if they otherwise don't need to.

> When you had set the AZURE_CLIENT_ID envvar yourself, what error were you receiving from DefaultAzureCredential? From what I understand it should skip EnvironmentCredential if no complete set of environment variables is found

Since I've Authenticated using your method, I can't seem to reproduce the Environment Variable error I was getting. I'm not sure how often the authentication has to be re-done so if I see it needing to be done again, I'll try it out and post the error here.

Thanks for all of your help with this!

**Comment by pvaneck** [comment] 2023-09-07 22:25
Thanks, @PhysWiz314 

@luigiw @azureml-github Is there any documentation available that has information about what exactly that "Authenticate" button in the portal does and if it's possible to replicate it programmatically?

**Comment by guolin1** [comment] 2023-12-29 20:00
I am facing a similar issue with `DefaultAzureCredential` failing when `ManagedIdentityCredential` is not disabled via `exclude_managed_identity_credential=True`. For me, the workaround of removing `MSI_ENDPOINT` and `MSI_SECRETE` from environment variables did not work. Similar to @PhysWiz314, I need to use `azureml-fsspec` which does not allow me to configure `DefaultAzureCredential` to disable `ManagedIdentityCredential`. 

More context: the job is running in a Linux HPC development environment without any domain links. I use azure-cli for authentication. 

Are there other workarounds that would allow me to disable ManagedIdentityCredential without needing to pass any arguments to DefaultAzureCredential and that would propagate to other tools like azureml-fsspec?

**Comment by pvaneck** [comment] 2024-08-06 22:52
Hey, apologies all for the late loop back on this. I'll try to give a write-up based on what I have found from my testing with the current state of Azure ML.

### Regarding managed identity endpoint behavior in Azure ML

The behavior of the managed identity endpoint in an Azure ML compute instance relies on the instance's configuration. The compute instance can be configured to use a system-assigned managed or user assigned identities, but not [both](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-identity-based-service-authentication?view=azureml-api-2&tabs=cli#compute-cluster). Also, by default, SSO is enabled for Azure ML compute instances.

These are the following scenarios when **no client ID** is provided to the ManagedIdentityCredential/DefaultAzureCredential (MIC/DAC):

1. **SSO is enabled and managed identity is enabled**: MIC/DAC will authenticate the user identity (logged-in user).
2. **SSO is enabled and managed identity is disabled**: MIC/DAC will authenticate the user identity (logged-in user).
3. **SSO is disabled and managed identity is enabled**: MIC/DAC will authenticate the managed identity.
4. **SSO is disabled and managed identity is disabled**: I don't believe this is possible, as you need to provision with one or the other. 

In essence, if SSO is enabled, and a user wants to authenticate with the managed identity, the user needs to pass in the app/client ID of the managed identity which will be stored in the `DEFAULT_IDENTITY_CLIENT_ID` envvar.

```python
cred = DefaultAzureCredential(managed_identity_client_id=os.environ.get("DEFAULT_IDENTITY_CLIENT_ID"))
```
or 

```python
cred = ManagedIdentityCredential(client_id=os.environ.get("DEFAULT_IDENTITY_CLIENT_ID"))
```

### Dealing with DAC instances you don't have control over

However, since some of these ML libraries (`mltable`, `azure-fsspec`, etc.) have embedded DACs that users can't customize or configure, users can't pass in the client ID of the managed identity. If the MI envvars are set, and we try and fail to use them, then it's intentional for it to halt the chain (as mentioned in the [above comment](https://github.com/Azure/azure-sdk-for-python/issues/31032#issuecomment-1679898498)). I don't think we are changing that pattern anytime soon. In this case, depending on what the user wants to do, they can either:

- Set the `AZURE_CLIENT_ID` envvar to the client ID of the managed identity. This will allow the libraries to authenticate with the managed identity. ```os.environ["AZURE_CLIENT_ID"] = os.environ.get("DEFAULT_IDENTITY_CLIENT_ID", "")```
- Force `DefaultAzureCredential` to skip `ManagedIdentityCredential` by deleting some environment variables that are used for checking the presence of a managed identity environment.
    
```python
os.environ.pop("MSI_ENDPOINT", None)
```

If your environment also has access to the Azure IMDS endpoint (`http://169.254.169.254`), you'll also need to force that check to fail to prevent `ManagedIdentityCredential` from being used with IMDS. This can be done by setting the following environment variable to some value that will fail when a request is sent.

```python
os.environ["AZURE_POD_IDENTITY_AUTHORITY_HOST"] = "FakeAuthorityHost"
```

### Conclusion

If SSO is enabled, then the user identity will be used in the default case where nothing is specified. This setting can be checked in the compute settings, like in the image below. Role assignments to resources should be assigned to the user.

<img width="505" alt="ml-compute-sso-setting" src="https://github.com/user-attachments/assets/c016b899-2226-4d5f-aae9-8e23134519aa">

Workarounds and approaches for using the managed identity, if desired, are outlined above. However, ultimately, I feel credential customization should be something that is enabled by the ML libraries themselves. I'm unaware of how/where `mltable` and `azure-fsspec` are maintained, and if a mechanism for allowing user-supplied credentials is something that is in the works.

If credential customization options are something that is still needed/desired, I encourage you or anyone else to open a new, targeted issue requesting this feature with specifics of the library being used.

**Closed by pvaneck** 2024-08-06 22:52 UTC
Labels: question, Machine Learning, Service Attention, Client, customer-reported, needs-team-attention

**Comment by PhysWiz314** [comment] 2024-08-13 15:38
Thanks a lot for this write up @pvaneck! I appreciate the response and work that went into figuring this issue out.
