### ISSUE TITLE
Azure Billing API not working for CSP Account

### ISSUE THREAD

**Issue by mamathy** [Azure/azure-sdk-for-python#2602] opened 2018-05-22 06:26 UTC
Using below python api for Azure Billing,

_commerce_client  = UsageManagementClient(credentials, subscription_id)
usage_list = commerce_client.usage_aggregates.list(start, end)_

It will works fine for EA account,but throw exception for CSP account as follows,

**Operation returned an invalid status code 'Bad Request'**

**Comment by lmazuel** [comment] 2018-05-29 20:02
Closing as duplicate of https://github.com/Azure/azure-sdk-for-python/issues/2624

Thanks,

**Closed by lmazuel** 2018-05-29 20:02 UTC
