### ISSUE TITLE
Allow specification of options when creating BlobClient from ContainerClient or BlobServiceClient

### ISSUE THREAD

**Issue by jchartmann** [Azure/azure-sdk-for-python#35308] opened 2024-04-22 21:16 UTC
**Is your feature request related to a problem? Please describe.**
Options, such as `max_single_put_size`, `max_block_size`, and `timeout` are only available when creating a `BlobClient` through a `BlobClient` constructor. `ContainerClient.get_blob_client` or `BlobServiceClient.get_blob_client` cannot specify these options and there's no method to set options post initialization.

This means that, if specifying options is desired, container or service clients cannot be re-used.

**Describe the solution you'd like**
Add the ability to specify options for the initialization of `BlobClient` in (at least) `ContainerClient.get_blob_client` and `BlobServiceClient.get_blob_client`.

**Describe alternatives you've considered**
- Add the ability to set options on `BlobClient` post-initialization

**Comment by jalauzon-msft** [comment] 2024-05-09 17:29
Hi @jchartmann Josh, thanks for you feature request. This is something that has already come up in #25871 and while this is an older issue, it is something we eventually would like to solve. It is a bit tricky though for reasons outlined in my response there. Also, in that issue you'll see a workaround you _could_ consider. It uses the private member of the client though which is subject to change, without warning, in a future release.

Anyway, hope that helps a bit. I'm going to close this as a duplicate of that issue. That issue may auto close in a few months but hopefully we get to it before then. Thanks!

**Closed by jalauzon-msft** 2024-05-09 17:29 UTC
Labels: Storage, question, Service Attention, Client, customer-reported, needs-team-attention
