### ISSUE TITLE
Python docs fail on azure-ai-ml

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-python#30801] opened 2023-06-16 07:51 UTC
Error:

> <CI INFO>: Generating xref map...
> ##[error]Process completed with exit code 0 and had 3 error(s) written to the error stream.
> Async Command Start: Add Build Tag
> Build '367844' has following tags now: reference_Python
> 

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=367844&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment] 2023-06-16 17:59
Closing, this is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/30774

**Closed by danieljurek** 2023-06-16 17:59 UTC
Labels: Network - Virtual Network, Client
