### ISSUE TITLE
Container Registry Content Validation Issue for github.io website

### ISSUE THREAD

**Issue by Yionse** [Azure/azure-sdk-for-python#37116] opened 2024-08-30 08:54 UTC
1.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/index.html#delete-blob):
![image](https://github.com/user-attachments/assets/f04a88a2-a867-42ef-8fc1-4194767ce15a)
[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.0.0b1/index.html):
![image](https://github.com/user-attachments/assets/b22f9cc5-27b2-45c1-a64a-2b76e8896e2b)

**Reason:**
Link validation issue: Display error.

2.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/index.html#delete-blob):
![image](https://github.com/user-attachments/assets/31032041-cdf7-496f-8ea5-584ec4775f3b)

**Reason:**
Link validation issue: Target Link Service not match.

3.

Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/azure.containerregistry.html):
![image](https://github.com/user-attachments/assets/e673b2be-9c9e-40cb-ab84-1c0b5b420f61)
![image](https://github.com/user-attachments/assets/b19b23da-d461-4410-ae1b-408d1b83fe07)
[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/azure.containerregistry.aio.html):
![image](https://github.com/user-attachments/assets/73102bbe-1229-44a3-ab9a-d9db5c5f667d)

**Reason:**
Typing annotation issue: Please unify the format, update to `**kwargs:Any` or `**kwargs`. In addition, missing type annotation for parameter `message`.

4.  
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/azure.containerregistry.html):
    ![image](https://github.com/user-attachments/assets/1cc53e0c-977c-41ac-9eae-2e07424adaed)
    [link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.v2018_02_01_preview.operations.html):
    ![image](https://github.com/user-attachments/assets/058e61da-c831-4d6c-b8d9-a14231ae1a9a)

**Reason:**
Format validation Issue: Extra symbols `~` or `-`.

5.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.v2023_11_01_preview.models.html):
![image](https://github.com/user-attachments/assets/66ba28e1-f662-4d40-b14c-11156fbf15ae)
![image](https://github.com/user-attachments/assets/a33a51e1-7897-4c03-9d01-52039e873c7a)

**Reason:**
Format validation issue: Text exceeds page size.

6.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.html):
![image](https://github.com/user-attachments/assets/8b5ae2de-3013-4916-a6eb-fea829f262a1)

**Reason:**
Format validation Issue: Layout Error.

7.
Section [link1](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.html),[link2](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.v2023_11_01_preview.models.html),[link3](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-containerregistry/10.3.0/azure.mgmt.containerregistry.v2018_02_01_preview.operations.html),[link4](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/azure.containerregistry.html),[link5](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-containerregistry/1.2.0/index.html#delete-blob):
![image](https://github.com/user-attachments/assets/91917f3e-ca27-46bf-ba6c-356dcc24b299)

**Reason:**
Format validation Issue: Extra symbols `_`.

@rohit-ganguly, @lmazuel, @sandeep-sen, @lmolkova, @YalinLi0312 for notification.

**Comment by ChenxiJiang333** [comment] 2024-09-03 08:45
@YalinLi0312 please help take a look on issue 1&2 in this page for it does not belong to mgmt issue.

**Comment by YalinLi0312** [comment] 2024-09-10 01:23
Hi @ChenxiJiang333 , I just shipped a PR to fix the issues and will prepare a release after to update the website content.

**Comment by YalinLi0312** [comment] 2024-09-10 01:43
I notice one of the issue is about "~" and "-" on "Error", the "~" should not be there and I've addressed in client package in the PR link above, but the "-" is expected.

**Closed** 2024-09-12 23:18 UTC
Labels: Docs, Container Registry, Mgmt, needs-team-attention, test-manual-pass
