### ISSUE TITLE
Source codes are missing on PyPi

### ISSUE THREAD

**Issue by jangsutsr** [Azure/azure-sdk-for-python#1156] opened 2017-05-09 14:23 UTC
Hi,

I noticed the latest versions of `azure-mgmt-nspkg` and `azure-nspkg` has only binary wheels but not source codes uploaded to PyPi. This blocks our dependency update workflow, could you upload the source codes to PyPi asap? Much appreciated!

**Comment by lmazuel** [comment] 2017-05-09 15:54
Hi @jangsutsr 

It's on purpose, this package is only necessary for whl installation (note that no setup.py has it, this dependency is added automatically when our custom `bdist_wheel` command is called). More details of this process [here](https://github.com/Azure/azure-storage-python/pull/290).

But please, describe me your workflow so I can understand if I miss something :)

**Comment by jangsutsr** [comment] 2017-05-09 16:37
@lmazuel It's mainly a policy constraint, because we are using Red Hat's build system and it disallows using Python dependencies without source distribution included. Before we were using `azure-.*nspkg` 1.0 and those includes source distributions even if it's unnecessary to.

**Comment by glaubitz** [comment] 2017-05-10 08:42
@lmazuel I'm packaging the SDK for openSUSE and SUSE Linux Enterprise and I'm running into the same problem.

**Comment by glaubitz** [comment] 2017-05-10 09:17
@lmazuel Also, is there a reason why ```pip install --pre azure``` does not install all packages from the SDK? It would be nice if it did because then we could pull all packages with a single command line:

```pip download --pre --no-binary :all: azure```

**Comment by lmazuel** [comment] 2017-05-22 16:39
Hi @glaubitz , @jangsutsr 
About the source files, we currently apply some logic into the `bdist_wheel` step in our packages that I didn't replicate yet in `azure-nspkg` (because this package is only interesting as a wheel). Publishing the sources, means that using setuptools you will install `azure-nspkg` 2.0.0 (currently with the lack of sources, it's 1.0.0), and will break setuptools users. If you need the source right now, you can take it on Github. From PyPI, I will need to apply the same `bdist_wheel` step to be sure setuptools users on PyPI are safe. On my roadmap.

About the question "why not all packages", it's because some of them are first preview version with lack of tests and review. We want to make clear by manual install, that they might break in a close future. `azure`bundle contains packages correctly tested at the SDK and/or at the CLI level. Goal is of course to have everything in `azure` eventually.

**Comment by glaubitz** [comment] 2017-05-23 13:51
@lmazuel Wouldn't tagging those packages as "preview" help here?

**Comment by lmazuel** [comment] 2017-05-23 16:47
@glaubitz that's an excellent question. I guess it's now possible, but back in time the entire ARM eco-system was in preview (I released 2.0.0 last week, but before that it was 2.0.0rc6 and latest stable was 1.0.0 from August 2015).
So currently, all X.Y.Z versioned packages are in "azure" (X != 0), some 0.Y.Z are in "azure", but have not yet be confirmed as stable by the team (reading semantic versioning, it's acceptable that 0.Y.Z might introduce breaking changes), and several 0.Y.Z are not in "azure" because they are not tested enough, or not stable enough.
In an ideal world, all packages in "azure" should be X.Y.Z packages, and not stable should be X.Y.ZrcX.
I will consolidate the packages versioning in the next release to make it more simple to use.
Thanks for the feedback :)

**Comment by lmazuel** [comment] 2017-09-07 00:17
I'm closing this one, since I just released on PyPI the source for all nspkg packages. Sorry for the delay, I had to make sure no side effect will come.

**Closed by lmazuel** 2017-09-07 00:17 UTC
Labels: Packaging
