### ISSUE TITLE
[BUG] Cannot import ComputerVisionClient with azure-cognitiveservices-vision-computervision 0.7.0

### ISSUE THREAD

**Issue by KnowledgeSharer1337** [Azure/azure-sdk-for-python#17659] opened 2021-03-30 12:20 UTC
Dear Sir or Madam,

in this [file](https://github.com/MicrosoftLearning/mslearn-ai900/blob/main/01%20-%20Image%20Analysis%20with%20Computer%20Vision.ipynb) it is not possible to execute the following command without getting an exception/error using `azure-cognitiveservices-vision-computervision 0.7.0`:

`from azure.cognitiveservices.vision.computervision import ComputerVisionClient`

I had to downgrade to `azure-cognitiveservices-vision-computervision 0.5.0` through `pip install azure-cognitiveservices-vision-computervision==0.5.0` to make the mentioned command work.

With best regards

**Comment by jsquire** [comment] 2021-03-30 12:44
Transferring this to the Python repository so that we can bring this to the attention of the team members best able to assist.

**Comment by KranthiPakala-MSFT** [comment] 2021-11-01 23:21
@ryogok , @TFR258 , @tburns10  Following up to see if there is any update on this issue? - Thank you

**Comment by lmazuel** [comment] 2021-12-17 19:29
I cannot reproduce with 0.7.0, nor with the latest 0.9.0:
![image](https://user-images.githubusercontent.com/1050156/146597739-0facfa75-ef10-4c81-ab24-888b1c32f2e6.png)

I believe the issue is likely environment based, please update the issue with additional information like full error trace, or anything to help us find why it fails on your particular environment. thanks!

**Closed** 2022-01-08 08:03 UTC
Labels: question, Service Attention, Client, customer-reported, no-recent-activity, needs-author-feedback, Cognitive - Computer Vision
