### ISSUE TITLE
VirtualMachineOperations list_all() method returns invalid ID value

### ISSUE THREAD

**Issue by chouseknecht** [Azure/azure-sdk-for-python#574] opened 2016-04-13 20:01 UTC
The ID attribute on the VirtualMachine objects being returned seems to include a resourceGroups value in ALL CAPS rather than mixed case.  Here is an example of an ID value being returned:

/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/GALAXY-PRODUCTION/providers/Microsoft.Compute/virtualMachines/xxxxxxxxxxx

Notice the 'GALAXY-PRODUCTION' value for resourceGroups. In this case it is expected to be 'galaxy-production'.

**Comment by lmazuel** [comment] 2016-04-13 20:26
The resource group name is not case sensitive, there is no difference between 'GALAXY-PRODUCTION' and 'galaxy-production'. You will use the same Resource group.

Then, it's not an invalid ID, since you can use it with no problem. If not, can you provide an example of scenario where the caps version in the ID prevents you for using the SDK?

**Comment by chouseknecht** [comment] 2016-04-14 18:58
The issue is that I'm relying on the ID to figure out the resource group to which the VM belongs. The VM object doesn't include the resource group. 

It's not an issue with the SDK. It's an inconsistency in the API. Is there a way to kick this to the API team?

**Comment by lmazuel** [comment] 2016-04-14 22:45
@devigned Do you have a contact in Compute team to discuss this point?

**Comment by devigned** [comment] 2016-04-15 00:13
@singhkay, can you provide some guidance on this one?

**Comment by singhkay** [comment] 2016-04-15 00:22
@chouseknecht Is this only with VM APIs?

**Comment by chouseknecht** [comment] 2016-04-18 21:24
I have only tried using VirtualMachineOperations with the Compute Management Client, so I don't know if other operations return the resource group name in all caps. I do know that other clients (i.e. storage management, network management, etc.) return the resource group name as expected - in mixed case. VM operations is the first and only place I have seen it show up in all caps, that's why it feels like a bug.

**Comment by singhkay** [comment] 2016-04-18 22:41
@chouseknecht Got it, let me check with the compute dev team and see what's up.

**Comment by lmazuel** [comment] 2017-01-11 19:01
Hi @chouseknecht 
In october 2016 we released version [0.30.0](https://pypi.python.org/pypi/azure-mgmt-compute) of the `azure-mgmt-compute` package (current is 0.32.1) based on a new RestAPI version. I re-tested recently (2016-12-22) with this new RestAPI version and wasn't able to reproduce it anymore. Could you confirm you no longer experience this issue?
Thank you,

**Comment by ernstp** [comment] 2017-09-20 11:51
Looks like this is fixed now indeed.

**Comment by lmazuel** [comment] 2017-09-20 15:41
@singhkays for guidance

**Comment by singhkays** [comment] 2017-09-20 16:46
@lmazuel In the past when I've discussed with the dev team, the answer has been that this is expected. The case on the rg name is not expected to be preserved. cc: Adding @nibhat since he owns Compute RP and might want to look into this

**Comment by Drewm3** [comment] 2019-09-19 02:07
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.

**Closed by Drewm3** 2019-09-19 02:07 UTC
Labels: Compute - VM, Feature Request, RestAPI, Service Attention
