### ISSUE TITLE
async/aio ContentSafetyClient object cannot be reused with `async with` without reconstructing

### ISSUE THREAD

**Issue by mr-flannery** [Azure/azure-sdk-for-python#36869] opened 2024-08-13 14:24 UTC
- **Package Name**: azure-ai-contentsafety 
- **Package Version**:  1.0.0
- **Operating System**: Mac/linux
- **Python Version**: 3.11.9

**Describe the bug**
When the same instance of `azure.ai.contentsafety.aio.ContentSafetyClient` is called multiple times in a `async with client` block, the second call will throw an exception `'NoneType' object has no attribute '__aenter__'`.

This is caused by `__aexit__` in `ContentSafetyClient` ultimately calling `__aexit__` in `AioHttpTransport`, which calls `self.close()`, which sets `self.session` to `None`.

This seems unfortunate to me, since it either requires reconstructing the client for every call (which can be cumbersome because the code that constructs the client might be arbitrarly far removed from the code using the client) or manually calling `close()` on the client (which seems error-prone and should be exactly what `async with` should prevent me from having to do myself).

**To Reproduce**

```python
from azure.ai.contentsafety.aio import ContentSafetyClient

client = ContentSafetyClient(
    endpoint=endpoint,
    credential=AzureKeyCredential(key),
    api_version=version,
)

for i in range(2):
  async with client:
   await client.analyze_text(
      AnalyzeTextOptions(
          text="test", categories=["Hate"]
      )
  )
```

**Expected behavior**
Above code should not throw exceptions.

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment] 2024-08-13 15:04
Thanks for reaching out.

This is by design that once a transport is closed, you cannot open it again.

Please create a new instance or keep it open if you want to reuse it.

**Comment by mr-flannery** [comment] 2024-08-14 09:26
/unresolve

Thanks for the quick response! Would you mind sharing what design considerations went into this? We found a workaround that works for us, so we're fine with this staying as it is. At the same time I'm geniunely curious why the client could not e.g. open a new session if session is `None`. Without being aware of all the details, that sounds like a reasonable and rather straight-forward approach to me.

**Comment by xiangyan99** [comment] 2024-08-14 19:46
The session is closed by the client when the client runs out of the context manager.

In this case, the entire client object is disposed. It may run into a weird state that the session is reopened while other components of the client are disposed.

**Closed by xiangyan99** 2024-08-14 19:46 UTC
Labels: question, customer-reported, needs-team-attention
