### ISSUE TITLE
Long time to access blobList

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-sdk-for-python#26464] opened 2022-09-27 02:09 UTC
- **Package Name**: 
- **Package Version**: 
- Package            Version
------------------ ---------
azure-common       1.1.28
azure-core         1.25.1
azure-identity     1.11.0
azure-mgmt-core    1.3.2
azure-mgmt-storage 20.1.0
azure-storage-blob 12.13.1

- **Operating System**: Ubuntu 18.04.1
- **Python Version**:  Python 3.8.11

**Describe the bug**
They find that the first access to blobList is taking 0.7 to 0.8 seconds and want to know why.
Also, when there are no hits for the tag search and the number of loops is 0, it still takes the same amount of time, and they want to know why this is.
In their scenario they are searching for the past 12 hours of blobs and they appear to have hourly tags, so there are about 13 tag searches performed at 0.8s for 10.4s total. The whole processing takes around 12s and is hitting a timeout when they try to get files with images.
They believe the issue is that the return value of find_blobs_by_tags is the ItemPaged class and that the next processing on this is taking time.
https://docs.microsoft.com/en-us/python/api/azure-core/azure.core.paging.itempaged?view=azure-python

**To Reproduce**
This is the provided code.
    # Tag search
    blobList = container_client.find_blobs_by_tags(f'\\'Date\\'='{tmpStr}' and \\'VmsCameraId\\'='{vms_camera_id}'')
    # Tag list loop
    for i,blob in enumerate(blobList):
        # Skip thumbnail and go to next file
        jpegidx = blob.name.find('jpeg')

**Expected behavior**
Each loop should not take as long, and loops with 0 hits should be much faster than loops with hits.

**Screenshots**

**Additional context**
(Reporting an issue on behalf of a customer through Azure support. My team has almost no Python experience and I am translating the report, sorry if anything is unclear.)

**Comment by jalauzon-msft** [comment] 2022-10-05 23:37
Hi @dcbrown16 Dillion, the time it takes to query blobs by tags can be affected by many different things such as:
- How many blobs are in the container
- How many results are returned by a query. A large response can take time to parse on the client, especially in Python.
- Network speed and other networking factors
- Client load

I don't feel like 0.8 seconds is unreasonable for a single query depending on the above factors. This request will have to go to the service, the service will have to perform the search through all blobs in the container, and then the client will have to deserialize the results. To their point about 0 results still taking time, even if there are no results, the request still has to go to the service and the service will still has to perform the search. This piece of the execution time will be the same whether there are any results or not.

To the point about `ItemPaged`, it is true the `next` method will take time since that method as where the request to the service is made. We need to make a request to get any results, even if there are no results. The client has no way of knowing there are no results.

I'm happy to look further if the customer can provide some more details on the factors above or more specifically cite where they think the issue is in `ItemPaged` but, as I mentioned, this time does not sound unreasonable to me. They may need to consider increasing whatever timeout they have for this operation or try some other optimizations. Thanks.

**Comment by jalauzon-msft** [comment] 2023-03-14 18:36
Closing this as its fairly old and seems like it was addressed.

**Closed by jalauzon-msft** 2023-03-14 18:36 UTC
Labels: Storage, Client
