### ISSUE TITLE
[EventHubs] EventHubConsumerClient starting_position + checkpoint_store

### ISSUE THREAD

**Issue by ervandew** [Azure/azure-sdk-for-python#17297] opened 2021-03-11 23:06 UTC
- **azure-eventhub**: 
- **5.2.1** (but code looks the same on master): 
- **Linux 5.10.15**:
- **3.7.7**: 

**Describe the bug**
When creating a consumer with a checkpoint_store and receiving with a starting_position other than '-1', that starting_position is ignored if the checkpoint_store has an existing offset.

**To Reproduce**
1. push some events
2. consume some events with a checkpoint_store to initialize an offset
3. stop the consumer
4. push some events
5. attempt to start the consumer with the same checkpoint_store and a starting_position of `@latest`
6. note that events pushed in step 4 are received.

**Expected behavior**
In the above steps, the events from step 4 should not be consumed when the starting_position is set to `@latest`.

**Additional context**
I solved the problem by monkey patching azure.eventhub._eventprocessor._eventprocessor_mixin.EventProcessorMixin.get_init_event_position:

    def get_init_event_position(self, partition_id, checkpoint):
        # type: (str, Optional[Dict[str, Any]]) -> Tuple[Union[str, int, datetime], bool]
        checkpoint_offset = checkpoint.get("offset") if checkpoint else None

        event_position_inclusive = False
        if isinstance(self._initial_event_position_inclusive, dict):
            event_position_inclusive = self._initial_event_position_inclusive.get(
                partition_id, False
            )
        elif isinstance(self._initial_event_position_inclusive, bool):
            event_position_inclusive = self._initial_event_position_inclusive

        event_position = "-1"  # type: Union[int, str, datetime]

        # MODIFIED: move checkpoint_offset from first conditional to last (adding
        # initial check that self._initial_event_position is set to something other
        # than '-1')
        if self._initial_event_position != '-1':
          if isinstance(self._initial_event_position, dict):
              event_position = self._initial_event_position.get(partition_id, "-1")  # type: ignore
          else:
              event_position = cast(
                  Union[int, str, datetime], self._initial_event_position
              )
        elif checkpoint_offset:
            event_position = checkpoint_offset

        return event_position, event_position_inclusive

I'm not sure if that is the best solution for this case or not, but now I can specify both a checkpoint_store and a starting_position of `@latest` and the consumer behaves as expected.

**Comment by yunhaoling** [comment] 2021-03-12 16:27
hey @ervandew, thanks for reaching out!

The behavior is by design if a checkpoint store is provided, then the SDK will use the offset provided by the checkpoint store ignoring the `starting_position`.

This is noted in the [docstring of `starting_position`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py#L361-L367):

>Start receiving from this event position if there is no checkpoint data for a partition. Checkpoint data will be used if available. This can be a dict with partition ID as the key and position as the value for individual partitions, or a single value for all partitions. The value type can be str, int or datetime.datetime. Also supported are the values "-1" for receiving from the beginning of the stream, and "@latest" for receiving only new events. Default value is "@latest".

When checkpointstore is used, we assume people want to handle all of the events and checkpoints information are kept so that no event is missed.

May I ask what's your scenario to make you want to skip certain events and start receiving with the latest events? Maybe you could use azure-eventhub SDK without using the checkpointstoreblob.

**Comment by ervandew** [comment] 2021-03-12 16:41
we had a case where we wanted to skip over the current set of events on the eventhub, but we still want to record our offset going forward.

So the flow was:
1. configure our consumer to start at `@latest`, allowing it skip over the history
2. on the next restart of the consumer, let it start at `-1` (load the offset from the checkpoint store)

With the current unpatched logic, step 1 only works  if we don't specify a checkpoint store, but then that means that step 2 would consume the history that we were trying to skip in the first place.

**Comment by yunhaoling** [comment] 2021-03-26 16:14
hey @ervandew , there's actually a pragmatic approach that you could build by using the `BlobCheckpointStore` itself and the last sequence/offset information provided by the event hub consumer client. And I think it's the right approach for the comprehensive scenario -- introducing  behavior change on starting_postition would further complicate the conceptual model of checkpointstore blob usage.

The `BlobCheckpointStore` itself has an `update_checkpoint` method which takes checkpoint information (dict) and it could be called manually to update the checkpoint.

And in the case that you want to update the checkpoint to be the latest one in the event hub partition, you could get the latest sequence/offset information by `EventHubConsumerClient.get_partition_properties(partition_id)`.

so this approach gives you a more fine grained control over the checkpoint (you could specify either to the latest or any specific sequence/offset to resume receiving from).

The code will be like this:

```python
def manual_update_checkpoint(consumer_client, checkpointstoreblob, ...):
    parititon_properties = consumer_client.get_partition_properties(partition_id)
    latest_offset_for_partition = parititon_properties['last_enqueued_offset']
    latest_sequence_number_for_partition = parititon_properties['last_enqueued_sequence_number']

    checkpoint = {
        "fully_qualified_namespace": fully_qualified_namespace,
        "eventhub_name": eventhub_name,
        "consumer_group": consumer_group,
        "partition_id": partition_id,
        "offset": latest_offset_for_partition,
        "sequence_number": latest_sequence_number_for_partition
    }
    checkpointstoreblob.update_checkpoint(checkpoint)
```

Please let me know your thoughts on this, thanks!

**Comment by ervandew** [comment] 2021-03-29 18:09
There are certainly ways to manually update the checkpoint, but I don't users of this api should have to jump through those hoops. To me a 'starting_position' is just that, where i want to start. I'm of the opinion that supplying that position shouldn't negate the automatic checkpoint update i would otherwise receive. If i don't want to record checkpoints, then I would omit the checkpoint store when creating my client. To supply one and have it ignored seems like an anti pattern to me.

**Comment by yunhaoling** [comment] 2021-04-09 17:22
hey @ervandew , thanks for sharing you thoughts on this -- I need to think more on this one and will bring feature crews' attention to the behavior of the sdk when both checkpoint in `checkpointstore` and `starting_position` are available.

I'll post updates here.

**Comment by yunhaoling** [comment] 2021-05-26 21:18
hey @ervandew , apologize for not getting back to you sooner.
We had an internal team discussion around this and I'll post updates here:

The bad news is that we could not change the current behavior of `starting_position`. The reasoning is that
- By design the `starting_position` is ignored when `checkpoint_store` is provided, it would be a breaking change if we change the behavior.
- The issue with using "starting_position" is that when a checkpoint exists, a consumer restart will use the same code (which has starting point defined) to create a new processor instance and when it resumes processing events it may lose a lot of events because starting position was set to latest or process duplicate events because it was set to earliest or some specific sequence number.

-------------

The good news is that we discussed another way to handle this scenario by introducing new API on the checkpoint_store to clear/reset the checkpoints pragmatically.

I have created a separate for introducing new API on the `checkpoint_store`: https://github.com/Azure/azure-sdk-for-python/issues/18968.

------------

I'm sorry about the inconvenience that has been brought to you and that we could not make the behavioral change.

I'm closing the issue now. But don't hesitate to reach out to us if you have more thoughts. You're also welcomed to continue the discussion within the newly-created issue!

**Closed by yunhaoling** 2021-05-26 21:18 UTC
Labels: Client, Event Hubs, Messaging, customer-reported, needs-team-attention, question

**Comment by ervandew** [comment] 2021-05-26 22:59
I looked over that separate proposal and that sounds like a good compromise. Thanks for the help and i'll monitor that issue for future use.

**Comment by yunhaoling** [comment] 2021-06-23 15:50
hey @ervandew , our team is discussing over the different approaches, and we'd like to understand more about your scenario and your thoughts.

One concern we had about introducing the new api on checkpoint store is that the method might be called during runtime which might lead to concurrency issue. Let's suppose there're multiple event hub consumers running which rely on the same storage for checkpointing. On one host, the clear checkpoint is called, however, other consumer are still doing checkpoints, which could potentially lead the checkpoint into an inconsistent status.

What's your scenario
- are you running your application on a single node or multiple nodes(server/vm/docker container/etc.)?
- in your current case, what's your step if you want to receive the latest with your workaround? would you stop all the nodes first?

**Comment by ervandew** [comment] 2021-06-23 16:10
> are you running your application on a single node or multiple nodes(server/vm/docker container/etc.)?

currently we are running 1 consumer node per eventhub partition

> in your current case, what's your step if you want to receive the latest with your workaround? would you stop all the nodes first?

yeah, my patch is to `EventProcessorMixin.get_init_event_position` which is called at startup, so we have to restart the consumers to leverage that.
