### ISSUE TITLE
0.50.3 docs keep mentioning 0.50.2

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#13738] opened 2020-09-11 12:57 UTC
This is clearly a minor issue but it might relate to the way docs are generated: the docs for the current stable version

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.3/index.html

keep mentioning 0.50.2 all over. This is quite annoying and does not give much confidence that the docs are really up-to-date.

**Comment by KieranBrantnerMagee** [comment] 2020-09-11 20:21
Let me take full responsibility for this one, when we pushed out the latest preview I clearly had some gaps properly find-replacing all the old version IDs.

Adam has been so prudent as to already have begun addressing this in [this PR](https://github.com/Azure/azure-sdk-for-python/pull/13719/files) and I will attempt to fast-track the rest of the fixes while alongside looking into doing an out-of-band doc release to update it as your perception is 100% justified and I'd like to address that asap.

Keeping this open to track that work; once again thanks as always for your eyes on this.

**Comment by andreacassioli** [comment] 2020-09-13 18:58
Hi @KieranBrantnerMagee the overall docs need a check. For instance in

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.3/index.html

the link to SDK code points to 

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus

which is your development branch. This is very confusing especially if one is used to take a look at the code of the library, as many might want to do in an open source setup. Other links are confusing as well, including the fact that the main page of the repo is not the stable but the development. I have many time search down to examples, to then realise that it is not the version I am looking for.

I know you are trying to finalise version 7, but many developers will remain on 0.50.3 for a while (me included). So I guess you will need to keep these docs in good shape for a while.

**Comment by KieranBrantnerMagee** [comment] 2020-09-14 23:07
Pushed out a small PR to address the top-level links that weren't version-specific and would thus be misdirecting folks;  thanks as always for the eyes and calling this out++

Regarding the 0.50.2, turns out the problem is slightly more interesting, it looks like although 0.50.3 went out as a package the doc release never succeeded, so we'll be getting two birds with one stone with the aformentioned PR and then doing a doc push to get it out.

re: master being the development branch, that's for better or for worse a decision a bit above head; long-running feature branches+merging into master at release at least were... discouraged, due to pain they incurred in the past.

That said, do feel free to take a peek at the PR and let me know if there were any links you saw outside of the obvious ones in README.

**Comment by swathipil** [comment] 2021-01-20 23:01
Hi @andreacassioli, just updated the links + version numbers in the [docs](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-servicebus/0.50.3/index.html#migration-from-0211-to-0503). Closing the issue for now, but please let me know if you spot any other inconsistencies/things that need to be updated!

**Closed by swathipil** 2021-01-20 23:01 UTC
Labels: Client, MQ, Service Bus, customer-reported, question
