### ISSUE TITLE
[Question] Azure Graph depreciation

### ISSUE THREAD

**Issue by lucasvazq** [Azure/azure-sdk-for-python#16039] opened 2021-01-08 16:02 UTC
Hi at all,
At my job I am faced with a problem related to the depreciation of ADAL in favor of MSAL. I am somewhat confused on this issue and would like to receive some help or guidance for solving the situation.
I am working on an application that uses `azure-common` and` azure-graphrbac` to get a list of Azure users.
If I'm not mistaken, this workflow would be obsolete in no time and I should migrate it to use MSAL and Microsoft Graph.
The inconvenience I have is that I can't find an alternative library to replace the mentioned ones, or maybe, I'm going the wrong way.

This is a sample of the code I use:

```python
from azure.common.credentials import ServicePrincipalCredentials
from azure.graphrbac import GraphRbacManagementClient

credentials = ServicePrincipalCredentials(
    client_id=azure_application_id,
    secret=azure_application_secret,
    tenant=azure_domain,
    resource="https://graph.windows.net",
)
graphrbac_client = GraphRbacManagementClient(credentials, azure_domain)
users = graphrbac_client.users.list()
```

Thanks!

**Comment by lmazuel** [comment] 2021-01-09 01:08
Hello,

I'm going to close this issue as duplicate of https://github.com/Azure/azure-sdk-for-python/issues/14022 but still will give some context here:

- MSAL is available here: https://github.com/AzureAD/microsoft-authentication-library-for-python
- We would recommend nowadays to not use MSAL directly, but azure-identity http://pypi.python.org/pypi/azure-identity (which wrap MSAL). `azure-identity` is the replacement for the auth part of `azure-common`
- That being said, we don't have yet support for `azure-identity` in `azure-graph`, see the last answer in the related link. There is wrapper that should allow `azure-identity` to be understood by `azure-graphrbac` here: https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py

All that being said, deprecation means no support, but the endpoints won't be shutdowned soon, it would just mean that if you encoutner bug in those libraries, fix might not come.

This could be useful reading too:
https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/

Thanks! Please comment on the duplicate issue if you have additional questions.

**Closed by lmazuel** 2021-01-09 01:08 UTC
Labels: customer-reported, needs-triage, question
