### ISSUE TITLE
provide CloudEndpoints data currently in azure-cli-core in standalone package

### ISSUE THREAD

**Issue by jazelenk** [Azure/azure-sdk-for-python#14464] opened 2020-10-13 17:31 UTC
- **Package Name**: azure-cli-core
- **Package Version**: 2.13.0
- **Operating System**:Linux
- **Python Version**: 3.7

**Describe the bug**
azure.cli.core.cloud provides very useful information about endpoints and DNS suffixes for various Azure clouds. Unfortunately, azure-cli-core itself comes with a log of baggage, including dependencies on specific versions of other Azure packages that prevents us from being able to mix it into our applications. It would be very helpful if this data were available in a separate package with no or minimal dependencies on other SDK packages. It could be imported into azure.cli.core with the same names for seamless compatibility. A _get API that takes in a string such as the azEnvironment strings from the metadata service would be generically useful, but really the important thing is to have the data itself in some importable form. 

**To Reproduce**
1. attempt to use a recent azure-cli-core such as 2.13.0 with recent SDK packages such as azure-mgmt-resource==15.0.0

**Comment by lmazuel** [comment] 2020-10-13 18:30
Hey Jim, it's a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/5561

They are available in msrestazure too in the meantime:
https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py

I appreciate the feedback, means to me we should put this one upper in the priority list, but I'm closing your issue since it's a duplicate. Feel FREE to write a comment into #5561 with your two cents on it as you did here.

Thanks!

**Closed by lmazuel** 2020-10-13 18:30 UTC
Labels: needs-triage

**Comment by jazelenk** [comment] 2020-10-13 18:53
Perfect, thank you!
