### ISSUE TITLE
Force cancellation of Azure subscription even if it has existing resources

### ISSUE THREAD

**Issue by szaher** [Azure/azure-sdk-for-python#10814] opened 2020-04-13 20:19 UTC
- **Package Name**: azure-mgmt-subscription
- **Package Version**: 0.5.0
- **Operating System**: Ubuntu 18.04 LTS
- **Python Version**: python 3.6.9

**Describe the bug**
When cancelling Azure subscription the request fails if the subscription has resources. There should be a flag or something to force cancellation of subscription even if it has resources ( as it's the case in the portal)

**To Reproduce**
1. create an azure subscription from library or EA portal
2. try to cancel the subscription using the azure-mgmt-subscription library

**Expected behavior**
When cancelling the subscription; there should be a flag or header to ignore existing resources within this subscription.

**Screenshots**

**Additional context**
```
from azure.mgmt import subscription
from azure.common import credentials
sub_client = subscription.SubscriptionClient(creds)
sub_client.subscriptions.cancel(subscription_id=subscription_id,
                                                        custom_headers={"Cache-Control": "no-cache"})
there should be something like 
sub_client.subscriptions.cancel(subscription_id=subscription_id, ignore_existing_resources=True,
                                                        custom_headers={"Cache-Control": "no-cache"})

```

**Comment by kaerm** [comment] 2020-04-13 23:22
@szaher thanks for the feedback, @nickzhums could you take a look at this?

**Comment by RodgeFu** [comment] 2020-04-17 04:48
assign to Zim to check why the flag is not available in sdk while it's supported in portal. thanks.

**Comment by anuragdalmia** [comment] 2020-06-04 19:51
Investigating

**Comment by anuragdalmia** [comment] 2020-06-04 22:50
This behavior is currently by design. We explicitly did not enable this to prevent accidental cancellations of subscriptions with active resources that could impact prod services. If you would like to cancel subscriptions, you should be able to delete all resources and then cancel the subscriptions via the APIs. The reason we support this in UX and not in API is that the UX has enough warnings and functionality to review what is being deleted which will not be the case via API. 

I will be closing this for now. Please re-open if you disagree and share the functionality that doesnt get addressed by existing APIs.

**Comment by Gill-Bates** [comment] 2020-12-01 10:51
@anuragdalmia **I totally disagree!** It is very important to me, to disable a Subscription with REST. I cannot understand the reasoning that this step is automatically too dangerous. The subscription is "read-only", nothing is deleted. I can also delete a resource group. Please include the possibility to deactivate the subscription programmatically, even if there are resources in it!

**Comment by anuragdalmia** [comment] 2020-12-24 17:54
@Gill-Bates apologies for the delay. Can you help me understand your specific scenario where you need to do this.

**Comment by Dilergore** [comment] 2021-01-14 10:23
Hello,

@anuragdalmia We would also like to have a force setting. We have an internal type of Subscription called dev-sandbox. There are pre-defined budgets for such subscriptions. It is very-very important to us to stay within those budget boundaries what we set. We would like to use the REST API to cancel a subscription once the budget is reached in an automated way. This would enable us to have an automation which could provide the end users the following features & functionalities:
- Form based automation to request a budget increase (with auto enable for the sub)
- Automation to cancel a sub when a budget is reached
- Automation to enable a sub at the beginning of the month (when the budget period resets)

I don't really see a reason why you could not implement a simple additional property in the POST with the necessary documentation (including warnings).

**Comment by Gill-Bates** [comment] 2021-01-14 11:00
@anuragdalmia Disabled Subscription will stop generating costs. I want to disable a Subscription, when the Budget is reached, to make sure, no additional costs are generated. Deleting the resources would be very bad.

**Comment by anuragdalmia** [comment] 2021-01-14 17:45
Thanks @Gill-Bates , @Dilergore  for the detailed explanations. Let me review this and get back with options.

**Comment by Dilergore** [comment] 2021-01-15 06:04
@anuragdalmia Thank You!

Moreover let me add this a bit more:

I think originally you have the 90 days cancellation period with keeping the resource to give the end users time to figure out whether they really do not need the subscription and its contents. In the same time you do not offer any other way to get rid of a subscription. So there is as well an illogical thinking here because either I should be able to cancel the sub as it is and keep it intact or delete it forever if I cannot do that. You said that we could delete all the resources first, but if I delete everything then the subscription won't be different from a new one I could create so basically the sub could go away instantly. (I get that other than resources there can be other settings like some preview flags or manually turned on settings from the MS side but at this point I do not think it matters that much).

On the top of this if a customer creates an automation for this today they need to delete everything to do it. So then my question becomes: what is better? If they delete everything and cancel and realize they screwed up or if they just cancel and then they realize the mistake and able to enable and everything goes as it was before... See?

**Comment by Dilergore** [comment] 2021-02-15 09:09
Hi @anuragdalmia,

Have you had a chance to look into this?

**Comment by anuragdalmia** [comment] 2021-02-16 06:19
@Dilergore yes, we are still looking into this. This ask is officially in our backlog and we are figuring out a way to prioritize this. Will keep you posted.

**Comment by saursinha** [comment] 2021-03-07 10:41
I am facing the same issue using the Azure Rest API, the Cancel API call fails with the error "There are existing resources associated with subscription. Delete them before cancelling the subscription".

We have a similar use case using Sandbox Subscriptions. We find it safer to Cancel the Subscription instead of deleting resources from it.

**Comment by Vegoo89** [comment] 2021-06-17 13:26
This behaviour can be achived by adding parameter `IgnoreResourceCheck=true` to URI

`https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/cancel?IgnoreResourceCheck=true&api-version=2019-03-01-preview`

This is basically as it's done via portal.
I just hope Microsoft won't disable this behaviour.
In my opinion, it's much more secure than just deleting all resources.

**Comment by OscartGiles** [comment] 2021-08-12 15:34
What permissions are required to cancel subscriptions?

I created this role:

```json
{
    "properties": {
        "roleName": "cancel-role",
        "description": "",
        "assignableScopes": [
            "/subscriptions/{sub_id}"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Subscription/cancel/action",
                    "Microsoft.Subscription/enable/action"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

This API endpoint works:
```
/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/enable
```

This one doesn't:
```
/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/cancel
```

I get the following error message:

> Only subscription owners can perform this operation. Contact your subscription owner to perform this operation

I need to assign a role to a managed identity which can cancel subscriptions but not do anything else.

Strangely giving the role `Action` permission `*` and `notAction` `Microsoft.Subscription/cancel/action` does not stop you from being able to cancel subscriptions.

**Closed** 2021-12-28 10:02 UTC
Labels: feature-request, Service Attention, Mgmt, customer-reported, Subscription, issue-addressed

**Comment by erwinkramer** [comment] 2022-06-03 08:33
/unresolve

> Strangely giving the role `Action` permission `*` and `notAction` `Microsoft.Subscription/cancel/action` does not stop you from being able to cancel subscriptions.

This is still the case, I've set a Custom Role and assigned it to a group (at subscription level) of which i'm member of, this is part of the custom role:

```
"assignableScopes": [
            "/subscriptions/sdfsdf...",
            "/subscriptions/28ssdf..."
        ],
        "permissions": [
            {
                "actions": [
                    "*"
                ],
                "notActions": [
                    "Microsoft.Subscription/cancel/action",
                    "Microsoft.Subscription/rename/action",
```

And i can still cancel and rename a subscription (I've waited at least 12 hours before checking again). I don't have any significant other roles on that subscription, except some reader role.
