### ISSUE TITLE
[Test-Proxy] Proxy Cert Trusting sometimes doesn't work

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-python#21626] opened 2021-11-05 21:06 UTC
@kristapratico is trying to migrate [a single textanalytics test](https://github.com/Azure/azure-sdk-for-python/compare/main...kristapratico:ta-test-proxy?expand=1) to Test-Proxy.

Locally, when she runs the trust-cert script and sets environment variables, she still cannot get through SSL Cert validation.

@mccoyp and @YalinLi0312 did not have this issue. 

What's up here?

**Comment by kristapratico** [comment] 2021-11-05 21:59
Complains of a self-signed certificate:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /record/start (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1122)')))`

**Comment by kristapratico** [comment] 2021-11-12 00:29
@scbedd I think we can close this. My issue was that I had a VERY old image and once updating to the latest (despite some annoying docker caching issues that @mccoyp helped me through) everything "just worked".

**Closed** 2021-11-12 19:03 UTC
Labels: Central-EngSys
