### ISSUE TITLE
ContainerClient delete_blobs account_name missing in URL for the part requests

### ISSUE THREAD

**Issue by Autom3** [Azure/azure-sdk-for-python#36629] opened 2024-07-25 11:11 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.20.0
- **Operating System**: Linux Manjaro
- **Python Version**: 3.9

**Describe the bug**
Calling delete_blobs on a ContainerClient causes a batch request without the account name at the start of the URL

The line with the bug can be found here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client_helpers.py#L160
```py
f"/{quote(container_name)}/{quote(str(blob_name), safe='/~')}{query_str}",
```

By changing the above line to:
```py
f"/{quote(self.account_name)}/{quote(container_name)}/{quote(str(blob_name), safe='/~')}{query_str}",
```
The issue is fixed

**To Reproduce**
1. Create a BlobServiceClient and run `blob_service_client.get_container_client("some_bucket").delete_blobs("some_path")`
2. This results in a `PartialBatchErrorException`, because the URL doesn't have the account name

**Expected behavior**
the url should be /<account_name>/<container_name>/<blob_name>/

**Screenshots**
n/a

**Additional context**
Related issue: https://github.com/Azure/Azurite/issues/1809

**Comment by vincenttran-msft** [comment] 2024-07-25 19:19
Hi @Autom3 , thanks for your inquiry! I have attempted to get a repro locally but have been unsuccessful. However, I do think there may actually be something else causing your issues here, as our [documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=microsoft-entra-id#sample-request) and my local testing does not indicate the necessity of the account name in the URI.

Could you please share a code snippet and what the failures look like on your end? Attached below was my attempt at reproducing your issue locally (this code successfully deletes three blobs in the container as described in `blob_list`):

```
from azure.storage.blob import BlobServiceClient

blob_service_client = BlobServiceClient.from_connection_string("<CONN_STR>")

container_name = "<my_container_name>"
blob_list = "<my_blob_list" # i.e. "'test/a.txt', 'test/b.txt', 'test/c.txt'"

container_client = blob_service_client.get_container_client(container_name)
container_client.delete_blobs(blob_list)
```

Thanks!

**Comment by Autom3** [comment] 2024-07-29 13:57
You're right, the issue doesn't occur with an azure storage account, only with a local azurite instance.

**Comment by jalauzon-msft** [comment] 2024-07-31 20:53
Hi @Autom3, would you mind sharing a code sample that you were using with Azurite? My guess is that the issue comes from what the account url looks like for Azurite versus Storage. Depending on the sample, this may be something we need to think about fixing in the SDK.

**Comment by Autom3** [comment] 2024-08-04 19:57
Hi @jalauzon-msft 

Here's the code I used, I the functionality out into a separate single script file. If you run it with azurite as the storage, you should get an error: "There is a partial failure in the batch operation."
I also added a workaround, if you comment out the lines for the delete_blobs call, it should work as expected.

```py
from io import BytesIO
import os
from typing import BinaryIO, Optional

from azure.core.exceptions import ResourceExistsError
from azure.storage.blob import BlobServiceClient


AZURE_MAX_BATCH = 256


class AzureClient:
    def __init__(
        self, endpoint: str, account_name: str, account_key: str, secure: bool
    ) -> None:
        connection_string = {
            "DefaultEndpointsProtocol": "https" if secure else "http",
            "AccountName": account_name,
            "AccountKey": account_key,
        }
        if endpoint:
            connection_string["BlobEndpoint"] = endpoint
        else:
            connection_string["EndpointSuffix"] = "core.windows.net"

        self.blob_service_client = BlobServiceClient.from_connection_string(
            ";".join(f"{k}={v}" for k, v in connection_string.items()),
            initial_backoff=0,
            increment_base=0,
            retry_total=0,
            retry_to_secondary=False,
            random_jitter_range=0,
            retry_connect=0,
            retry_read=0,
            retry_status=0,
        )

    def create_container(self, container_name: str) -> None:
        self.blob_service_client.create_container(container_name)

    def upload_blob(
        self,
        container_name: str,
        name: str,
        data: BinaryIO,
        length: Optional[int] = None,
    ) -> None:
        self.blob_service_client.get_container_client(container_name).upload_blob(
            name, data, length=length, overwrite=True
        )

    def remove_objects(self, container_name: str, names: list[str]) -> None:
        # We can only remove at most #AZURE_MAX_BATCH blobs at once, split into chunks if needed
        # Replace this with itertools.batched in python 3.12
        for i in range(0, len(names), AZURE_MAX_BATCH):
            name_sublist = names[i : i + AZURE_MAX_BATCH]

            # Can't use delete_blobs due to this issue: https://github.com/Azure/azure-sdk-for-python/issues/36629
            self.blob_service_client.get_container_client(container_name).delete_blobs(
                *name_sublist
            )

            # Current work-around:
            for name in name_sublist:
                self.blob_service_client.get_container_client(
                    container_name
                ).get_blob_client(name).delete_blob()


if __name__ == "__main__":
    container_name = "testing"

    storage_account_name = os.environ.get("STORAGE_ACCOUNT_NAME", "devstoreaccount1")
    storage_endpoint = os.environ.get(
        "STORAGE_ENDPOINT", f"http://127.0.0.1:10000/{storage_account_name}"
    )

    client = AzureClient(
        storage_endpoint,
        storage_account_name,
        os.environ.get(
            "STORAGE_ACCOUNT_KEY",
            "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==",
        ),
        os.environ.get("STORAGE_SECURE", False),
    )

    try:
        client.create_container(container_name)
    except ResourceExistsError:
        pass

    paths = [f"test/blob_{i}" for i in range(3)]

    for path in paths:
        client.upload_blob(container_name, path, BytesIO(b"random data"))

    client.remove_objects(container_name, paths)
```

**Comment by vincenttran-msft** [comment] 2024-08-20 18:46
Hi @Autom3 , thank you for being patient and for providing the helpful feedback and code samples to help us identify the root cause. As it turns out, the issue is only pertinent to the following scenario:

- Using Azurite local Storage
- Using a batch API

With that being said, we have gone ahead and added a flag that will apply this fix to all batch APIs when Azurite is being used. The above pull-request I have linked contains the fixes, and so upon successfully merging that PR, this issue will also be marked as resolved. 
Thanks again for the help and your patience!

**Closed** 2024-08-20 18:46 UTC
Labels: Storage, question, Service Attention, Client, customer-reported, needs-team-attention
