### ISSUE TITLE
"Failed to open mgmt link" when using custom_endpoint_address in AWS lambda deployment

### ISSUE THREAD

**Issue by dedsec594** [Azure/azure-sdk-for-python#20241] opened 2021-08-12 18:20 UTC
- **azure-eventhub**: 
- **5.3.0 and 5.6.0**: 
- **AWS Lambda**:
- **Python 3.7**: 

**Describe the bug**
When running our python script to connect to an eventhub through a custom endpoint it fails. It fails with the error "Failed to open mgmt link: MgmtOpenStatus.Error". The code is run from AWS lambda with a static IP address. The custom endpoint points to an Azure firewall that filters the traffic coming from our IP address. When we run the same code locally it connects fine. However, running it in AWS lambda fails to make the connection with the above error.

**To Reproduce**
1. 

**Expected behavior**
A successful connection

**Screenshots**

**Additional context**
Exact error: Failed to open mgmt link: MgmtOpenStatus.Error

**Comment by dedsec594** [comment] 2021-08-16 13:46
Can anyone shed some light on this issue?

**Comment by swathipil** [comment] 2021-08-16 14:53
@dedsec594 - thanks for your patience and bringing this to our attention! Directing this to the right people, so they can help you.

**Comment by swathipil** [comment] 2021-08-16 14:54
@dedsec594 Would you be able to add the steps to reproduce the behavior?

**Comment by swathipil** [comment] 2021-08-16 15:21
Ah, okay - this is great @dedsec594. Thanks for the additional information! We'll investigate ASAP!

**Comment by swathipil** [comment] 2021-08-24 02:00
Hi @dedsec594 - I apologize for the lack of updates this past week! I am working on reproducing this issue so I can track down what the root problem might be. This is currently my number one priority, so I'm hoping I can have some sort of answer to you soon. Thank you for your patience!

**Comment by swathipil** [comment] 2021-08-24 18:32
@dedsec594 I have a few updates.

1) Would you be able to turn on the uamqp logging and share the logs? You can do so by adding the snippets of code shown here: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-eventhub#logging . This will show us the network trace and might help us find the underlying issue.

2) The custom endpoint feature has actually only been tested with Application Gateways and not Firewall. So, it could be that we don't currently support this feature. I am creating and testing with a Firewall right now to check whether this will work. If not, I can discuss this with the EventHubs SDK team and open up a feature request.

I will continue to keep you updated today, thanks!

**Comment by dedsec594** [comment] 2021-08-24 18:44
We are working on that now as we speak. Ill let you know when we have logs. As to the firewall issue, it does work through the firewall already. That is when we run the code locally on our computers and not in AWS Lambda. It only fails when running from the Lambda.

**Comment by dedsec594** [comment] 2021-08-24 19:18
4T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Auth closed, destroying session on connection: b'fc1d766a-027a-4663-8858-f50599491f84'.
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Finished shutting down CBS session on connection: b'fc1d766a-027a-4663-8858-f50599491f84'.
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'send called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_send_async':1181)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'Cannot send encoded bytes' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'on_bytes_encoded':268)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'saslclientio_close called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_close_async':1130)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'xio_close failed' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'on_bytes_encoded':272)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Connection b'fc1d766a-027a-4663-8858-f50599491f84' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Connection b'fc1d766a-027a-4663-8858-f50599491f84' state changed from <ConnectionState.END: 13> to <ConnectionState.END: 13>
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'saslclientio_close called while not open' (b'/data/src/vendor/azure-uamqp-c/src/saslclientio.c':b'saslclientio_close_async':1130)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    b'xio_close failed' (b'/data/src/vendor/azure-uamqp-c/src/connection.c':b'connection_close':1437)
[INFO]    2021-08-24T19:06:09.521Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Connection shutdown complete b'fc1d766a-027a-4663-8858-f50599491f84'.
[ERROR]    2021-08-24T19:06:09.522Z    b73cd47d-29db-464c-9e0d-f0602deccf82    Task exception was never retrieved
future: <Task finished coro=<async_get_events() done, defined at /var/task/lambda_function.py:37> exception=ConnectError('Failed to open mgmt link: MgmtOpenStatus.Error\nFailed to open mgmt link: MgmtOpenStatus.Error')>
Traceback (most recent call last):
File "/opt/uamqp/async_ops/session_async.py", line 101, in mgmt_request_async
mgmt_link = self._mgmt_links[node]
KeyError: None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/azure/eventhub/aio/_client_base_async.py", line 208, in _management_request_async
description_fields=MGMT_STATUS_DESC,
File "/opt/uamqp/async_ops/client_async.py", line 328, in mgmt_request_async
loop=self.loop)
File "/opt/uamqp/async_ops/session_async.py", line 110, in mgmt_request_async
raise errors.AMQPConnectionError("Failed to open mgmt link: {}".format(mgmt_link.open))
uamqp.errors.AMQPConnectionError: Failed to open mgmt link: MgmtOpenStatus.Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 49, in async_get_events
props = await get_props(consumer)
File "/var/task/lambda_function.py", line 53, in get_props
props = await consumer.get_eventhub_properties()
File "/opt/azure/eventhub/aio/_consumer_client_async.py", line 630, in get_eventhub_properties
EventHubConsumerClient, self
File "/opt/azure/eventhub/aio/_client_base_async.py", line 255, in _get_eventhub_properties_async
mgmt_msg, op_type=MGMT_OPERATION
File "/opt/azure/eventhub/aio/_client_base_async.py", line 248, in _management_request_async
raise last_exception
azure.eventhub.exceptions.ConnectError: Failed to open mgmt link: MgmtOpenStatus.Error
Failed to open mgmt link: MgmtOpenStatus.Error

**Comment by swathipil** [comment] 2021-08-24 21:26
Thanks for the logging! It looks like there are issues with establishing the initial connection.
Usually, if things are working locally but not in Azure Functions/AWS Lambda, it is due to some inbound/outbound networking configurations. Do you think there might be any rules/configurations for your Lambda that might be causing issues here?

**Comment by dedsec594** [comment] 2021-08-25 13:07
Our lambdas are set to deny all inbound connections and allow all outbound connections. Nothing more specific than that.

**Comment by dedsec594** [comment] 2021-08-30 18:13
Our engineer found this GitHub issue which may also be linked to the same problem. Wanted to share in case it brought any light to the situation.

https://github.com/Azure/azure-c-shared-utility/issues/428

**Comment by swathipil** [comment] 2021-08-30 21:27
@dedsec594 thanks for linking this issue. I'm working on adding certs to my deployed function so that I can test just the Azure Application Gateway, without an Azure Firewall. Have you tested the solutions proposed in the linked issues to see if this is actually the problem?

**Comment by swathipil** [comment] 2021-08-30 23:40
@dedsec594 I just tested running the sample with the Application Gateway as the custom endpoint and it was successful. I also took a look at the issue that you linked, and it looks like that issue addressed here. https://github.com/Azure/azure-uamqp-python/issues/167

Were you able to try this? https://github.com/Azure/azure-sdk-for-python/issues/16816#issuecomment-782133443

**Comment by swathipil** [comment] 2021-09-07 18:57
OOB investigation details:
- After troubleshooting with the AWS + FireEye team, found that there was a problem with the SSL cert.
- More specifically: "Turns out bad SSL certificate was getting in our way, which is now fixed. Mac and Linux don’t apply same level of strictness (for cert validation) which prevented us from catching the issue locally."
- Solution: "updat[ing] the certificate to include the full chain."

Issue resolved - so closing issue.

**Closed by swathipil** 2021-09-07 18:57 UTC
Labels: question, Event Hubs, Client, customer-reported, Messaging, issue-addressed
