### ISSUE TITLE
BlobClient.start_copy_from_url takes too much time to copy blob

### ISSUE THREAD

**Issue by vijaydulange1310** [Azure/azure-sdk-for-python#24293] opened 2022-05-04 15:59 UTC
- azure-storage-blob==12.8.1
- 12.8.1 
- windows
- Python 3.8 

Using BlobClient.start_copy_from_url method to copy blob across storage account.
For 50GB vhd, it is taking more than 20 minutes
Where I tried azcopy to copy blob.It got completed in 4-5 mins

Expected behavior:
It should take same time as azcopy to copy blob.

**Comment by swathipil** [comment] 2022-05-04 16:42
Hey @vijaydulange1310 - Thanks for your question! Tagging the right people to address this.

**Comment by navba-MSFT** [comment] 2022-05-05 04:31
@vijaydulange1310 Thanks for reaching out to us and sharing this feedback. Could you please try with the [async version of start_copy_from_url ](https://github.com/Azure/azure-sdk-for-python/blob/1446fbfdb0bc3bd68675ab1c6f336dfdb8eb54f8/sdk/storage/azure-storage-blob/samples/blob_samples_common_async.py#L194) code and test if that gives a low latency ? Awaiting your reply.

Also could you please check if you application is running on the server / VM that is in the same region (location) as that of Storage account ? This is to isolate the network latency.

**Comment by vijaydulange1310** [comment] 2022-05-05 05:25
We are trying to copy blob across  storage account located in different region. Anyway copy is working in async mode. we are waiting for success copy status.
blob_client = blob_service_client.get_blob_client(container="conatiner1", blob="blobname")
blob_client.start_copy_from_url(sasurl)
while True:
        props = blob_client.get_blob_properties()
        status = props.copy.status
        if status == "success":
            # Copy finished
            break
        time.sleep(10)

**Comment by navba-MSFT** [comment] 2022-05-05 05:27
@vijaydulange1310 Thanks for getting back. So can you confirm if you are seeing a better performance by testing using the async mode ? Awaiting your reply.

**Comment by vijaydulange1310** [comment] 2022-05-05 05:49
No.. To get copy status as success,  more than 20 mins are required for 50GB blob.

**Comment by navba-MSFT** [comment] 2022-05-05 05:59
@vijaydulange1310 Could you please share the below details over email ? 

Storage Account name of source and destination account.
Time of the issue when the copy operation was performed in UTC

My email: navba@microsoft.com

**Comment by vijaydulange1310** [comment] 2022-05-05 07:52
Can I know for what purpose this information will be used as it is organization account.

**Comment by navba-MSFT** [comment] 2022-05-05 07:55
@vijaydulange1310 The Storage account details and time of the issue is required, so that we can look into the backend logs and metrics for the cause of latency issue. 

If you don't wish to share this information, You could open a support ticket to troubleshoot this issue further.

**Comment by jalauzon-msft** [comment] 2022-05-05 18:55
Hi @vijaydulange1310, this difference in speed is likely because AzCopy uses a fundamentally different way to copy blobs across Storage accounts than `start_copy_from_url` in the Blob SDK.

For large blobs, AzCopy will perform the copy synchronously by using a series of [Put Block from URL](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url) calls whereas `start_copy_from_url` will use [Copy Blob From URL](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) meaning that, for blobs larger than 256 MB, it will be an asynchronous copy. The asynchronous copy will be inherently slower as the service will perform the copy "when it can" and does not guarantee the copy will be performed immediately.

It may be possible to get closer to the speed of AzCopy using the Blob SDK by using `stage_block_from_url` but you would have to split your blob up into blocks. I also believe AzCopy has some level of parallelism that would need to be replicated.

**Comment by vijaydulange1310** [comment] 2022-05-05 19:41
@jalauzon-msft Thanks for pointing out different. In our case we are working with Page blob, so I guess stage_block_from_url wont help us out. right ?

**Comment by navba-MSFT** [comment] 2022-05-09 03:29
Thanks @jalauzon-msft for your pointers.

@vijaydulange1310 Could you please let us know if you had a chance to implement the above suggestions provided by @jalauzon-msft ? Do you see an improvement in the performance ? Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-05-12 07:46
@vijaydulange1310 I wanted to do quick follow-up to check if you had a chance to follow the above action plan. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-05-16 03:13
@vijaydulange1310 The action is currently pending on you to follow the suggestions provided in [the above comment](https://github.com/Azure/azure-sdk-for-python/issues/24293#issuecomment-1118940009). We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-05-16 03:13 UTC
Labels: Storage, question, Client, customer-reported, needs-author-feedback, CXP Attention

**Comment by ubyjvovk** [comment] 2022-07-28 13:54
@navba-MSFT we're seeing the same issue, start_copy_from_url completes but the file is stuck in 'pending' state basically forever, even after the actual bytes have arrived into destination. Also, transfers are often pretty slow, around 10 mbps when pulling data from S3 (equivalent blob operations seem faster, but I might be wrong). Is there some workaround?
