### ISSUE TITLE
async download_blob authenticationerror when equal sign '=' in the url

### ISSUE THREAD

**Issue by gverkes** [Azure/azure-sdk-for-python#9783] opened 2020-02-08 21:38 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.1.0
- **Operating System**: Windows 10
- **Python Version**: 3.7.3

**Describe the bug**
Whenever there is a blob that has a equal sign ('=') in the url the async BlobServiceClient will give me an AuthenticationError. The same file without the equal sign or using non-async BlobServiceClient works fine.

**To Reproduce**
The following code will give me a an authentication error `AuthenticationErrorDetail:The MAC signature found in the HTTP request '...' is not the same as any computed signature.`
```python
from azure.storage.blob.aio import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(conn_str)

async with blob_service_client:
    container_client = blob_service_client.get_container_client("data")

    with open("./dl_test2/height=10.png", "wb") as f:
        stream = await container_client.download_blob("height=10.png")
        data = await stream.readall()
        f.write(data)
```
Whereas the following two work:
1) without the equal sign in the url:
```python
from azure.storage.blob.aio import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(conn_str)

async with blob_service_client:
    container_client = blob_service_client.get_container_client("data")

    with open("./dl_test2/height=10.png", "wb") as f:
        # exactly same file without the equal sign
        stream = await container_client.download_blob("height10.png")
        data = await stream.readall()
        f.write(data)
```
2) using the non-async BlobServiceClient, with the equal sign in the url
```python
from azure.storage.blob import BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string(conn_str)

async with blob_service_client:
    container_client = blob_service_client.get_container_client("data")

    with open("./dl_test2/height=10.png", "wb") as f:
        # with the equal sign
        stream = container_client.download_blob("height=10.png")
        data = stream.readall()
        f.write(data)
```

**Comment by kaerm** [comment] 2020-02-10 19:27
Thanks for the feedback @gverkes, I am looping in the right team to take a look at this.

**Comment by xiafu-msft** [comment] 2020-02-14 00:24
Hi @gverkes 

I was able to reproduce the problem. It should be a storage bug(either service or client) we are still investigating that.
Sorry about the inconvenience...

**Comment by xiafu-msft** [comment] 2020-02-14 02:28
Created an issue in our dependency and see if they have any insight about this https://github.com/aio-libs/yarl/issues/420

**Comment by aviramha** [comment] 2020-08-26 19:12
Probably a duplicate of this #11028

**Closed** 2020-09-10 18:41 UTC
Labels: Client, Service Attention, Storage, bug, customer-reported
