### ISSUE TITLE
msrestazure fails to install due to invalid (dos) character

### ISSUE THREAD

**Issue by brian-l-coker** [Azure/azure-sdk-for-python#1133] opened 2017-05-02 16:08 UTC
When executing python3-pip install azure

Downloading/unpacking msrestazure>=0.4.0,<0.5.0 (from azure-common[autorest]==1.1.4->azure-batch==1.0.0->azure)
  Downloading msrestazure-0.4.7.zip
  Running setup.py egg_info for package msrestazure
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/msrestazure/setup.py", line 1
        ﻿# --------------------------------------------------------------------------
          ^
    SyntaxError: invalid character in identifier
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/msrestazure/setup.py", line 1

    ﻿# --------------------------------------------------------------------------

      ^

SyntaxError: invalid character in identifier

Running a dos2unix command on the setup.py file seems to solve the problem.

**Comment by lmazuel** [comment] 2017-05-02 22:49
Hi @brian-l-coker 

Could you be more precise on your environment (version of pip, os, version of Python), since I'm not able to reproduce your issue.
Thanks

**Comment by lmazuel** [comment] 2017-05-02 22:59
Note that you fail parsing the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) of this file. BOM usage in front of a Python file is part of [PEP263](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding). I guess your version of pip is very old (since you download the zip and not the wheel, it's old), and this install issue is not an SDK bug.

I wait until you give to me your pip version, but it seems to be a pip issue fixed in recent version and not a SDK problem.

**Comment by brian-l-coker** [comment] 2017-05-03 03:25
Here are my OS, Python, and Pip versions:

Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.6.1.el7.x86_64
      Architecture: x86-64

pip 1.3.1 from /usr/lib/python3.3/site-packages (python 3.3)

**Comment by lmazuel** [comment] 2017-05-04 18:37
Hi @brian-l-coker 

We support pip from 6.0 with PEP440 support (semantic versioning). Please install "pip" locally (in your venv, or your user home) to a version superior to 6.0. Note you are not that far, since pip went from 1.5 to 6.0.

I close this issue since we will not modify files to support old version of pip, but feel free to still comment on it if you have any question.
Thank you,

**Closed by lmazuel** 2017-05-04 18:37 UTC
Labels: Packaging
