### ISSUE TITLE
Disk Size not returning for Snapshot Get Operation

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1112] opened 2017-04-26 14:33 UTC
Hi,

When I get snapshot using azure python sdk, disk_size_gb returning None.

Thanks,
Vikram

**Comment by lmazuel** [comment] 2017-04-26 16:05
Hi @VikramAIS 

Thank you for your report, I will test that asap.

**Comment by lmazuel** [comment] 2017-05-22 16:44
This is actually a duplicate of this issue https://github.com/Azure/azure-sdk-for-python/issues/672
This field is only filled if you have filled it yourself at first.
Thank you.

**Closed by lmazuel** 2017-05-22 16:44 UTC
Labels: ARM, Question
