### ISSUE TITLE
Exception: TypeError: '<' not supported between instances of 'int' and 'NoneType' hit in download_to_stream

### ISSUE THREAD

**Issue by AdmiralGT** [Azure/azure-sdk-for-python#22297] opened 2022-01-01 21:47 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.9.0
- **Operating System**: Linux (via Azure App Service)
- **Python Version**: 3.8.6

**Describe the bug**
Originally raised at https://github.com/jschneier/django-storages/issues/1097, when using django-storages to provide a FileResponse, the following exception is hit.

```
2021-12-12T13:36:51.739891275Z Traceback (most recent call last):
2021-12-12T13:36:51.739908176Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
2021-12-12T13:36:51.739920476Z     self.handle_request(listener, req, client, addr)
2021-12-12T13:36:51.739931676Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
2021-12-12T13:36:51.739943076Z     resp.write_file(respiter)
2021-12-12T13:36:51.739953676Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
2021-12-12T13:36:51.739964877Z     if not self.sendfile(respiter):
2021-12-12T13:36:51.739975477Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 355, in sendfile
2021-12-12T13:36:51.739986577Z     if not util.has_fileno(respiter.filelike):
2021-12-12T13:36:51.739997177Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/util.py", line 569, in has_fileno
2021-12-12T13:36:51.740008278Z     if not hasattr(obj, "fileno"):
2021-12-12T13:36:51.740019178Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/django/core/files/utils.py", line 38, in <lambda>
2021-12-12T13:36:51.740031578Z     fileno = property(lambda self: self.file.fileno)
2021-12-12T13:36:51.740042278Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/django/core/files/utils.py", line 38, in <lambda>
2021-12-12T13:36:51.740053978Z     fileno = property(lambda self: self.file.fileno)
2021-12-12T13:36:51.740064579Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/storages/backends/azure_storage.py", line 47, in _get_file
2021-12-12T13:36:51.740075879Z     download_stream.download_to_stream(file, max_concurrency=1)
2021-12-12T13:36:51.740086679Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 635, in download_to_stream
2021-12-12T13:36:51.740097979Z     self.readinto(stream)
2021-12-12T13:36:51.740108479Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 616, in readinto
2021-12-12T13:36:51.740119580Z     for chunk in downloader.get_chunk_offsets():
2021-12-12T13:36:51.740130480Z   File "/tmp/8d9bd73cfc52ab6/antenv/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 123, in get_chunk_offsets
2021-12-12T13:36:51.740141780Z     while index < self.end_index:
2021-12-12T13:36:51.740152580Z TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**To Reproduce**
1. Use django-storages v1.12.3 configured to use an Azure Blob Storage
2. Return a FileResponse

**Expected behavior**
No exception to occur and file to be served.

**Comment by tjprescott** [comment] 2022-01-03 17:49
@tasherif-msft could you please take a look?

**Comment by jalauzon-msft** [comment] 2022-01-11 20:42
Thanks for reporting the issue. We will investigate this and get back to you.

**Comment by jalauzon-msft** [comment] 2022-02-11 02:11
Hi @AdmiralGT, apologies for the delay. We have been focused on a recent release.

I took a look at what the latest version of `django-storages` is doing and tested that scenario on our end and it works as expected.  In version 1.12, `django-storages` upgraded to version 12 of the Storage blob SDK which is a pretty big change and does come with lots of breaking changes [CHANGELOG](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md#1200-2019-10-31). This is likely the cause of the issue. We can keep investigating from our end, but it might be helpful to have someone from `django-storages` take a look as well.

One thing I noticed is that they are using a deprecated method `StorageStreamDownloader.download_to_stream()` [source](https://github.com/Azure/azure-sdk-for-python/blob/ce738fc2b1ac826238a6b09352fb2444ce7a3a53/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L631) but that is likely not the direct cause of the issue.

**Comment by herberthamaral** [comment] 2022-05-27 10:42
@jalauzon-msft OP has posted a link to the original issue from the django-storages' repo. They are using this library as intended. Also, there's a TypeError deep down in this library code, so it'd be pretty odd if this is actually a bug in django-storages.

Could you please re-visit this? I was about to report the same issue when I found this one.

**Comment by AdmiralGT** [comment] 2022-06-04 01:53
I've done some more digging into this in my local dev environment. 

Ultimately the error that's reported is https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L125 where self.end_index is None. 

The root of this seems to be caused by the parsing of the initial request before parsing any information in the response. The range-header in the response to be set to `bytes=0-33554431` at https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/request_handlers.py#L134 since the end_range is None.

Basically nearly all of these fields are None. The content range tries to parse a non-existent response.properties.content_range https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L407 which gives us a None self._file_size and similarly self.size. 

This then causes the size property to be set back to None rather than the value actually provided in the response (I'm downloading a 1,5MB file here, well within a single chunk size).

With both the size and file_size set to None, when the ChunkDownloader tries to download the file, it just doesn't know anything about the size and hits the error I've shown.

I think this all stems from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L407 which is attempting to read content from a non-existent content_range property. 

I'm still inclined to believe this is a azure-storage-blob problem. It seems django-storages is using a fairly standard interface with the simple download_to_stream on the StorageStreamDownloader which is just redirecting to `readinto`.

**Comment by jalauzon-msft** [comment] 2022-06-07 00:28
Thanks @AdmiralGT Geoff, for your further investigation! I do agree that this is likely an issue in the SDK as we should never really be throwing that kind of `TypeError`. We can investigate this further. The issue I was having during my initial investigation is that I could not reproduce the error even trying the same scenario that `django-storages` looked to be doing. This made it quite hard to trace the error. I did not yet try setting up `django-storages` since I am entirely unfamiliar with that library mostly unfamiliar with Django in general.

It seems like you are able to reproduce this in your local environment. I assume this was using django-storages or were you able to repro just using the SDK? Would it be possible for you to share the steps you followed to get to this error and maybe a code snippet of your test so I can try and get that set up locally? (Accounting for the lack of knowledge I have with this library :) ) Thanks!

**Comment by AdmiralGT** [comment] 2022-06-07 18:17
Here's the script that I can reproduce the error with without using `django-storages`, where I'm connecting to a blob storage account with a `media` container.

```
from azure.storage.blob import BlobServiceClient
from tempfile import SpooledTemporaryFile


account_key = # REDACTED
account_name = # REDACTED
account_domain = # REDACTED
account_url = f"https://{account_domain}"
credential = {
    "account_name": account_name,
    "account_key": account_key,
}

service_client = BlobServiceClient(account_url, credential=credential)
client = service_client.get_container_client("media")

file = SpooledTemporaryFile(
    max_size=2 * 1024 * 1024, suffix=".AzureStorageFile", dir=None
)

path = # REDACTED
download_stream = client.download_blob(path, timeout=20)
download_stream.download_to_stream(file, max_concurrency=1)
```

Interestingly the error only occurs when using a CDN, if I use the storage account URL directly I get no such problem. So for instance, with the `account_url` above set to `https://<account_name>.blob.core.windows.net` no error is hit but if I use a CDN endpoint `https://<cdn_address>` where `<cdn_address>` is my Origin hostname and `https://<account_name>.blob.core.windows.net` is my Endpoint hostname then I get the exception given in my original post.

**Comment by jalauzon-msft** [comment] 2022-06-22 01:06
Hi @AdmiralGT Geoff, thanks so much for the sample and especially about the bit with the CDN! I was able to repro this issue when using a CDN. As you mentioned above, it seems responses from the CDN do not include the `Content-Range` header which is strange. I'm not entirely sure if this is supposed to be supported or if something is going wrong on the CDN -> Storage end.

I will investigate further and get back to you.

**Comment by jalauzon-msft** [comment] 2022-06-24 00:06
Hi again @AdmiralGT, so after some investigation we've concluded this to be an issue with the Azure CDN service and the way it interacts with the Storage service. The `Content-Range` header should always be returned from the blob download. We've started an escalation internally to get the CDN service team to look into this, but this could take some time to get fully fixed. Fortunately, I do have a suggestion for a possible workaround to get you unblocked.

We have found that the issue only occurs specifically with the `Microsoft CDN (classic)` pricing tier of an Azure CDN Profile. The other pricing tiers such as `Standard Verizon` or `Standard Akamai` seem to work as expected.
![image](https://user-images.githubusercontent.com/96087589/175434324-a3669e43-afec-41b7-95d4-f510e9d564e1.png)

So, if it's possible for you to do so, I would try using a CDN with a different pricing tier. I believe all their standard tiers should be comparably priced and have the same features. Unfortunately, there does not seem to be an easy way to simply change the pricing tier of an existing CDN so I believe you would have to create a new one. If this is not possible, you can try opening a support ticket on your CDN profile to see if they would be able to swap it for you (I'm not actually sure if this is possible).

I'm sorry I don't have a better answer than that but hopefully the provided workaround is something that can help you. In the meantime, we will work to get this fixed on the service side. Thanks again for your patience and assistance on this issue!

**Comment by dimbleby** [comment] 2022-06-24 07:54
If the SDK can't be made to cope without a `Content-Range` header, can it at least be taught to give a better error?

A message saying "Mandatory Content-Range is missing" and maybe "please report this at <wherever>" would have gained maybe six months on this issue.

**Comment by jalauzon-msft** [comment] 2022-08-11 20:39
Hi all, some final updates here:

After some internal investigation and discussion, it was found that the Microsoft CDN uses the presence of a range-like header to determine if the request is for partial content or the entire content. They use this information to inform the request they should make to the backing service, caching, and to determine what the response should look like. The issue is the CDN only accepts the standard HTTP `Range` header whereas the SDK uses the `x-ms-range` range header in all range requests. This was done in the SDK for come compatibility reasons when the SDK was first created.

This means the issue is more than just the response not containing the `Content-Range` header, but also that the response is going to be for the full blob not the requested range (since the CDN ignores our range header). For blobs under 32 MiB, this is fine because we request 32 MiB in the initial request (by default) but if the blob size is greater, this means the SDK is getting back data it didn't request.

With all that being understood, I want to provide one other workaround that will likely work for folks that are using the SDK directly if they want to continue to use the Microsoft CDN. A request hook can be used to convert the `x-ms-range` header on all requests to `Range`. So, something like this:
```python
def range_request_hook(request):
    range = request.http_request.headers.pop('x-ms-range', None)
    if range:
        request.http_request.headers['Range'] = range

service = BlobServiceClient(..., raw_request_hook=range_request_hook)
```

This will ensure all requests use `Range` so the CDN can properly interpret the request as a ranged read. Though this can likely work for most scenarios, it would not be an officially supported scenario since the SDK is built/tested with `x-ms-range` but I have tested it for blob download and it does seem to work.

Unfortunately changing the SDK to use `Range` by default and/or having the CDN accept `x-ms-range` are not likely to be prioritized/possible at this time so hopefully the workarounds presented in thread will suffice for most users.

I have gone and added a more useful error when the initial download response is missing the `Content-Range` header as suggested above so that this can be easier to diagnose if it comes up in the future.

**Closed by jalauzon-msft** 2022-08-11 20:39 UTC
Labels: bug, Storage, Client, customer-reported, needs-team-attention

**Comment by JeffreyCA** [comment] 2022-09-22 05:36
Hi @jalauzon-msft, I tried using the `raw_request_hook` workaround but it's still not working for me. While the `Range` headers are being rewritten in the HTTP requests, the download request still fails (this succeeds on non-Microsoft CDNs):

```
Incomplete download: ('Connection broken: IncompleteRead(8388608 bytes read, 53355845 more expected)', IncompleteRead(8388608 bytes read, 53355845 more expected))
Traceback (most recent call last):
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    yield
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\urllib3\response.py", line 592, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(8388608 bytes read, 53355845 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\urllib3\response.py", line 627, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\urllib3\response.py", line 565, in read
    with self._error_catcher():
  File "C:\Users\jeffreychen\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\urllib3\response.py", line 460, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(8388608 bytes read, 53355845 more expected)', IncompleteRead(8388608 bytes read, 53355845 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 169, in __next__
    chunk = next(self.iter_content_func)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(8388608 bytes read, 53355845 more expected)', IncompleteRead(8388608 bytes read, 53355845 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Public\Documents\Dev\sdk-repro\support2.py", line 35, in <module>
    download_stream = client.download_blob(path, timeout=120)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_container_client.py", line 1146, in download_blob
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_blob_client.py", line 871, in download_blob
    return StorageStreamDownloader(**options)
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_download.py", line 359, in __init__
    self._response = self._initial_request()
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_download.py", line 463, in _initial_request
    self._current_content = process_content(
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\storage\blob\_download.py", line 46, in process_content
    content = b"".join(list(data))
  File "C:\Users\Public\Documents\Dev\sdk-repro\env\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 185, in __next__
    raise IncompleteReadError(err, error=err)
azure.core.exceptions.IncompleteReadError: ('Connection broken: IncompleteRead(8388608 bytes read, 53355845 more expected)', IncompleteRead(8388608 bytes read, 53355845 more expected))
```

Test program (based on @AdmiralGT's code above):

```py
from tempfile import SpooledTemporaryFile
from azure.storage.blob import BlobServiceClient

ACCOUNT_URL_CDN = f"https://msftcdn.azureedge.net"
ACCOUNT_NAME = ""
ACCOUNT_KEY =  ""
CONTAINER_NAME = "media"

credential = { "account_name": ACCOUNT_NAME, "account_key": ACCOUNT_KEY }

def range_request_hook(request):
    range = request.http_request.headers.pop('x-ms-range', None)
    if range:
        request.http_request.headers['Range'] = range

blob_service_client = BlobServiceClient(
            account_url=ACCOUNT_URL_CDN,
            credential=credential, raw_request_hook=range_request_hook
)

client = blob_service_client.get_container_client(CONTAINER_NAME)
file = SpooledTemporaryFile(
    max_size=2 * 1024 * 1024, suffix=".AzureStorageFile", dir=None
)
path = 'uploads/test.pdf'
download_stream = client.download_blob(path, timeout=80)
download_stream.download_to_stream(file, max_concurrency=1)
```

**Comment by JeffreyCA** [comment] 2022-09-22 17:44
Note that in the older django-storages version, returning a FileResponse streams the file from the storage account URL and bypasses the custom domain/CDN which is why this error doesn't occur.
