### ISSUE TITLE
`EventGridClient` has a really awesome function named send_request that I shouldn't use

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-python#30571] opened 2023-05-30 22:33 UTC
- **Package name**: azure-eventgrid
- **Package Version**: azure-eventgrid==4.12.0b1 
- **Operating System**: Windows
- **Python Version**: Python 3.11 

**Describe the bug**

In our other messaging SDKs (Event Hubs, Service Bus) we use the `send` verb for all of our message sending functions (ie, SendMessage, SendEvent).

In the `EventGridClient` the verb is `publish` (which seems fine) but it ALSO has a function called `send_request` which seems so similar to SendEvents and SendMessages that it took me a second to realize it wasn't what I was looking for.

This might not matter, and perhaps there's a greater good being served here by having it exposed at the top level, but it's something we should consider changing if we can.

**Expected behavior**

Given the collision is it possible to rename or hide the send_request method? Or does it provide some utility to the customer and so needs to be front-and-center?

**Comment by l0lawrence** [comment] 2024-06-28 19:39
Closing by design a send_request gets generated to allow the customer to create/send their own httpRequest in special cases

**Closed by l0lawrence** 2024-06-28 19:39 UTC
Labels: Event Grid, Client
