### ISSUE TITLE
billing & consumption packages not working

### ISSUE THREAD

**Issue by AnushaY1** [Azure/azure-sdk-for-python#1386] opened 2017-08-23 06:22 UTC
Hi,

1. consumption package

```python
from azure.common.credentials import UserPassCredentials
from azure.mgmt.consumption import ConsumptionManagementClient

credentials = UserPassCredentials(user_name, passwords)
res = ConsumptionManagementClient(credentials, subscription_id)

rs=res.usage_details.list('subscriptions/subscription_id/providers/Microsoft.Billing/invoices/invoicename')
for i in rs:
    print i
```
i am getting below error

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/consumption/operations/usage_details_operations.py", line 118, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.consumption.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'
```

2. billing package
```python
 from azure.mgmt.billing import BillingManagementClient
dd = BillingManagementClient(credentials,subscription_id)
df = dd.invoices.list()
 for i in df:
...   print i
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/local/lib/python2.7/dist-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/billing/operations/invoices_operations.py", line 109, in internal_paging
    request, header_parameters, **operation_config)
  File "/usr/local/lib/python2.7/dist-packages/msrest/service_client.py", line 189, in send
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 346, in request
    self.token_updater(token)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 195, in _default_token_cache
    keyring.set_password(self.cred_store, self.store_key, str(token))
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 47, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

i followed these documents
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.billing.html
http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.consumption.html

can anyone please solve this error
thanks

**Comment by lmazuel** [comment] 2017-08-23 16:42
For problem 1, the scope should be real, not having `subscription_id` in it. For instance:
``` python
        scope = 'subscriptions/{}/providers/Microsoft.Billing/invoices/201704-117949190364043'.format(self.settings.SUBSCRIPTION_ID)
        output = list(self.consumption_client.usage_details.list(scope, expand='meterDetails,additionalProperties', top=10))
```

For 2, could you give me your version of keyring installed, and your system. Seems this is an authentication problem. At worst, could you try using the Adal wrapper (which is not using keyring):
https://docs.microsoft.com/python/azure/python-sdk-azure-authenticate

**Comment by lmazuel** [comment] 2017-08-23 16:53
For 2, could you also install `keyrings.alt` with `pip install -U keyrings.alt` to see if it helps

**Comment by lmazuel** [comment] 2017-08-23 23:48
For (2), please update to msrestazure 0.4.12 (`pip install -U msrestazure`)

**Comment by AnushaY1** [comment] 2017-08-24 06:18
Hi Imazuel,

OS version Centos 7.3
Python 2.7.5
keyring==10.4.0
keyrings.alt==2.2
msrestazure==0.4.12

**Comment by AnushaY1** [comment] 2017-08-24 06:33
I checked this in OS version Centos 7.3
 
 getting below errors

>>> from azure.mgmt.billing import BillingManagementClient
>>> dd = BillingManagementClient(credentials,subscription_id)
>>> **df = dd.invoices.list()**
>>> for i in df:
...    print i
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/lib/python2.7/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/billing/operations/invoices_operations.py", line 112, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.billing.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'


>>> **res = dd.invoices.get_latest()**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/azure/mgmt/billing/operations/invoices_operations.py", line 226, in get_latest
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.billing.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

Thanks

**Comment by lmazuel** [comment] 2017-08-24 15:29
@Panda-Wang any ideas?

**Comment by Panda-Wang** [comment] 2017-08-24 15:55
I’m no longer working on these RPs. Loop in current owner.

Thanks,
Panda

**Comment by lmazuel** [comment] 2017-08-24 18:46
(2) being fixed, (1) is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/1307

**Comment by lmazuel** [comment] 2017-08-25 16:42
Re-opening this one and closing #1307 instead.

@AnushaY1 Do you know you offer id? For instance:
https://azure.microsoft.com/en-us/offers/ms-azr-0025p/

Because there is some limitation based on offer id right now.

You should also be able to get a `error` attribute on the exception to get more details. I created an [issue ](https://github.com/Azure/msrest-for-python/issues/46)at the runtime level to improve the error message.

**Comment by lmazuel** [comment] 2017-08-25 16:44
You can also activate the DEBUG level the see what the payload is:
```python
import logging
logging.basicConfig()
logging.getLogger('msrest').setLevel(logging.DEBUG)
```
at the beginning of your script

**Comment by AnushaY1** [comment] 2017-08-26 06:59
yes, I know offer id.

**Comment by lmazuel** [comment] 2017-09-06 19:37
This offer ID is not supported yet, the service team is evaluating if this offer id can be supported.

**Comment by lmazuel** [comment] 2017-09-15 00:47
@AnushaY1 the service team confirmed they are working right now to add this offer id. More info soon (you can re-try regularly in the meantime).
Thanks!

**Comment by lmazuel** [comment] 2017-09-21 18:25
Hi @AnushaY1 
The service team tolds me that they added this offer id. Can you check if this is now working?
Thanks!

**Comment by AnushaY1** [comment] 2017-09-22 06:37
still am getting the same error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/usr/local/lib/python2.7/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python2.7/site-packages/azure/mgmt/billing/operations/invoices_operations.py", line 112, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.billing.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

 OS - centos 6.5(Red Hat 4.4.7-18) 
azure-mgmt-billing==0.1.0,keyring==10.4.0
Python 2.7.8

Ubuntu 16.04.1 LTS, 
python 2.7.12

**Comment by xiangyan99** [comment] 2021-12-07 23:16
@AnushaY1 the latest azure-mgmt-billing is 6.0.0. Could you help to try if it works?

**Closed** 2022-01-07 08:03 UTC
Labels: question, RestAPI, Service Attention, Mgmt, customer-reported, no-recent-activity, needs-author-feedback, Consumption - UsageDetailsAndExport
