### ISSUE TITLE
Cannot upload documents to Azure Cognitive Search

### ISSUE THREAD

**Issue by tcummin2** [Azure/azure-sdk-for-python#27724] opened 2022-11-29 22:21 UTC
- **Package Name**: azure.search.documents
- **Package Version**: 11.3.0
- **Operating System**: Windows
- **Python Version**: 3.9.5

**Describe the bug**
`SearchClient.upload_documents` throws exception when attempting to upload any documents to cognitive search. It can successfully create and delete the index, but not upload documents to it.

`requirements.txt`: 
```
azure-common==1.1.28
azure-core==1.23.0
azure-search-documents==11.3.0
certifi==2021.10.8
charset-normalizer==2.0.12
idna==3.3
isodate==0.6.1
msrest==0.6.21
oauthlib==3.2.0
requests==2.27.1
requests-oauthlib==1.3.1
six==1.16.0
typing_extensions==4.1.1
urllib3==1.26.8
```

`update-search-index.py`:
```python
import time
import sys
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents import SearchClient
from azure.search.documents.indexes.models import (
  CorsOptions,
  SearchIndex,
  SearchFieldDataType,
  SimpleField,
  SearchableField
)

service_name = sys.argv[1]
admin_key = sys.argv[2]
if not service_name:
  raise Exception('Service name cannot be empty')
if not admin_key:
  raise Exception('Azure search admin key cannot be empty')

index_name = "help"

# Create an SDK client
endpoint = f"https://{service_name}.search.windows.net/"
print (f'Endpoint: {endpoint}')
admin_client = SearchIndexClient(endpoint=endpoint,
                      index_name=index_name,
                      credential=AzureKeyCredential(admin_key))

# Specify the index schema
name = index_name
fields = [
        SimpleField(name="DocumentId", type=SearchFieldDataType.String, key=True),
        SearchableField(name="Content", type=SearchFieldDataType.String, analyzer_name="en.lucene"),
        SearchableField(name="Url", type=SearchFieldDataType.String, facetable=True, filterable=True),
        SearchableField(name="Title", type=SearchFieldDataType.String, facetable=True, filterable=True),
        SearchableField(name="MetaTitle", type=SearchFieldDataType.String, facetable=True, filterable=True),
        SearchableField(name="MetaDescription", type=SearchFieldDataType.String, facetable=True, filterable=True),
        SearchableField(name="Product", type=SearchFieldDataType.String, facetable=True, filterable=True, sortable=True),
        SearchableField(name="SubCategory", type=SearchFieldDataType.String, facetable=True, filterable=True, sortable=True),
    ]
cors_options = CorsOptions(allowed_origins=["*"], max_age_in_seconds=60)
scoring_profiles = [
                    {
                      "name": "boostTitles",
                      "text": {
                        "weights": {
                          "Title": 3,
                          "MetaTitle": 7,
                          "MetaDescription": 5,
                          "Product": 3,
                          "SubCategory": 3,
                          "Content": 1
                        }
                      }
                    }
                  ]

suggester = [{'name': 'sg', 'source_fields': ['Title', 'MetaTitle', 'MetaDescription', 'Product', 'SubCategory', 'Content']}]

#Delete existing index
try:
  result = admin_client.delete_index(index_name)
  print ('Index', index_name, 'deleted')
except Exception as ex:
  print (ex)

index = SearchIndex(name=name, fields=fields, scoring_profiles=scoring_profiles, suggesters = suggester, cors_options=cors_options)

# Recreate the index
try:
  result = admin_client.create_index(index)
  print ('Index', result.name, 'created')
except Exception as ex:
  print (ex)

def getSearchDocument():
  return {
    "@search.action": "upload",
    "DocumentId": "Intro",
    "Url": "contoso.com",
    "Content": "Here is the content of my document",
    "Title": "Intro to Contoso",
    "MetaTitle": "Intro to Contoso",
    "MetaDescription": "Intro to Contoso",
    "Product": "Contoso",
    "SubCategory": "Marketing",
  }

documents = [getSearchDocument()]
print('Documents: ', documents)

search_client = SearchClient(endpoint=endpoint,
                      index_name=index_name,
                      credential=AzureKeyCredential(admin_key))

try:
  print (f"Uploading {len(documents)} documents.")
  result = search_client.upload_documents(documents=documents)
  print ("Upload of new document succeeded:", result[0].succeeded)
  print ("Number of documents uploaded:", len(documents))

except Exception as ex:
  print (ex.message)

# Wait for the search index to complete its magic within Azure
time.sleep(10)
results = search_client.search(search_text="block", include_total_count=True)

result_count = results.get_count()
print ('Total documents matching test query:', result_count)
assert result_count > 0
```

Output: 
```
Endpoint: https://help-dev2-search.search.windows.net/
Index help deleted
Index help created
Documents:  [{'@search.action': 'upload', 'DocumentId': 'Intro', 'Url': 'contoso.com', 'Content': 'Here is the content of my document', 'Title': 'Intro to Contoso', 'MetaTitle': 'Intro to Contoso', 'MetaDescription': 'Intro to Contoso', 'Product': 'Contoso', 'SubCategory': 'Marketing'}]
Uploading 1 documents.
Operation returned an invalid status 'Not Found'
Traceback (most recent call last):
  File "C:\Users\JohnSmith\update-search-index.py", line 110, in <module>
    result_count = results.get_count()
  File "C:\Users\JohnSmith\AppData\Roaming\Python\Python39\site-packages\azure\search\documents\_paging.py", line 82, in get_count
    return self._first_iterator_instance().get_count()
  File "C:\Users\JohnSmith\AppData\Roaming\Python\Python39\site-packages\azure\search\documents\_paging.py", line 91, in wrapper
    self._response = self._get_next(self.continuation_token)
  File "C:\Users\JohnSmith\AppData\Roaming\Python\Python39\site-packages\azure\search\documents\_paging.py", line 115, in _get_next_cb
    return self._client.documents.search_post(
  File "C:\Users\JohnSmith\AppData\Roaming\Python\Python39\site-packages\azure\search\documents\_generated\operations\_documents_operations.py", line 310, in search_post
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\JohnSmith\AppData\Roaming\Python\Python39\site-packages\azure\core\exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'Not Found'
```

**To Reproduce**
1. Save the script and requirements.txt
2. `pip install -r requirements.txt`
3.  Create a Cognitive Search resource in Azure and note the resource name and primary admin key
4. Run `python  .\update-search-index.py <search-resource-name> <search-admin-key>`
5. The `search_client.upload_documents` step will throw an exception: "Operation returned an invalid status 'Not Found'"

**Expected behavior**
The script should not fail when uploading the documents to the newly-created index.

**Additional context**
The provided script is a trimmed-down version of one that we run during our production build pipeline. As of 10/20/22 the script started throwing this exception 100% of the time and we hadn't changed anything with our process, environment, script, or package versions.

I have been in contact with Azure Support over the last month about this issue and after trying everything they suggested, they told me to submit a bug report here.

In the meantime, we switched over to the Node.js Azure SDK for the purposes of uploading documents to an index.

**Comment by xiangyan99** [comment] 2022-11-30 23:52
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment] 2022-12-01 00:13
Hi @tcummin2, I followed your repros but unfortunately I couldn't reproduce the issue.

I ran 'pip install -r requirements.txt' in a new venv:
```shell
> pip list
Package                Version
---------------------- ---------
azure-common           1.1.28
azure-core             1.23.0
azure-search-documents 11.3.0
certifi                2021.10.8
charset-normalizer     2.0.12
idna                   3.3
isodate                0.6.1
msrest                 0.6.21
oauthlib               3.2.0
pip                    20.2.1
requests               2.27.1
requests-oauthlib      1.3.1
setuptools             49.2.1
six                    1.16.0
typing-extensions      4.1.1
urllib3                1.26.8
```

And ran your script. Here is the output:
```shell
Endpoint: https://rakshith-search.search.windows.net/
Index help deleted
Index help created
Documents:  [{'@search.action': 'upload', 'DocumentId': 'Intro', 'Url': 'contoso.com', 'Content': 'Here is the content of my document', 'Title': 'Intro to Contoso', 'MetaTitle': 'Intro to Contoso', 'MetaDescription': 'Intro to Contoso', 'Product': 'Contoso', 'SubCategory': 'Marketing'}]
Uploading 1 documents.
Upload of new document succeeded: True
Number of documents uploaded: 1
Total documents matching test query: 0
Traceback (most recent call last):
  File "app1.py", line 107, in <module>
    assert result_count > 0
AssertionError
```

I was using Python 3.8.6 on Windows.

Please feel free to let me know if I missed anything.

**Comment by tcummin2** [comment] 2022-12-01 14:41
Thanks for the quick response!

I did a little more digging and created Azure Cognitive Search resources in different regions. I found that the script works properly in the West US 2 region, but not the Central US region. Our operation is based in the Midwest so most of our resources belong to the Central US region.

Central US:
```
Endpoint: https://help-dev3-central-search.search.windows.net/
Index help deleted
Index help created
Documents:  [{'@search.action': 'upload', 'DocumentId': 'Intro', 'Url': 'contoso.com', 'Content': 'Here is the content of my document', 'Title': 'Intro to Contoso', 'MetaTitle': 'Intro to Contoso', 'MetaDescription': 'Intro to Contoso', 'Product': 'Contoso', 'SubCategory': 'Marketing'}]
Uploading 1 documents.
Operation returned an invalid status 'Not Found'
```

West US 2:
```
Endpoint: https://help-dev3-west-search.search.windows.net/
Index help deleted
Index help created
Documents:  [{'@search.action': 'upload', 'DocumentId': 'Intro', 'Url': 'contoso.com', 'Content': 'Here is the content of my document', 'Title': 'Intro to Contoso', 'MetaTitle': 'Intro to Contoso', 'MetaDescription': 'Intro to Contoso', 'Product': 'Contoso', 'SubCategory': 'Marketing'}]
Uploading 1 documents.
Upload of new document succeeded: True
Number of documents uploaded: 1
```

I will send this new information over to Azure support.

**Comment by xiangyan99** [comment] 2022-12-01 15:46
Thanks for the updates.

I will close the issue. Please open a service ticket to ask the service team to help.

**Closed by xiangyan99** 2022-12-01 15:46 UTC
Labels: question, Search, Client, customer-reported, needs-team-attention
