### ISSUE TITLE
 metric definitions does return the “supported aggregation types” for each metric

### ISSUE THREAD

**Issue by DanielLanger** [Azure/azure-sdk-for-python#2952] opened 2018-07-18 21:09 UTC
It appears "supportedAggregationTypes" when calling metric definitions never returns any values. The object returned for it is always empty/none.  https://docs.microsoft.com/en-us/rest/api/monitor/metricdefinitions/list#examples We have customers who want additional aggregations but right now we can only use the primaryAggregationType

**Comment by lmazuel** [comment] 2018-07-18 22:00
Hi @DanielLanger 

I don't reproduce it :(
```python
In [25]: from azure.mgmt.monitor.models import MetricDefinition

In [26]: m
Out[26]:
{'category': 'Capacity',
 'id': '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Storage/storageAccounts/clitest000002/providers/microsoft.insights/metricdefinitions/UsedCapacity',
 'isDimensionRequired': False,
 'metricAvailabilities': [{'retention': 'P93D', 'timeGrain': 'PT1H'},
  {'retention': 'P93D', 'timeGrain': 'PT6H'},
  {'retention': 'P93D', 'timeGrain': 'PT12H'},
  {'retention': 'P93D', 'timeGrain': 'P1D'}],
 'name': {'localizedValue': 'Used        capacity', 'value': 'UsedCapacity'},
 'namespace': 'Microsoft.Storage/storageAccounts',
 'primaryAggregationType': 'Average',
 'resourceId': '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Storage/storageAccounts/clitest000002',
 'supportedAggregationTypes': ['Total', 'Average', 'Minimum', 'Maximum'],
 'unit': 'Bytes'}

In [27]: md = MetricDefinition.deserialize(m)

In [28]: md.supported_aggregation_types
Out[28]:
[<AggregationType.total: 'Total'>,
 <AggregationType.average: 'Average'>,
 <AggregationType.minimum: 'Minimum'>,
 <AggregationType.maximum: 'Maximum'>]
```

When you say does not return it for "each" metric, does it mean you have it sometimes? and sometimes not?

**Comment by lmazuel** [comment] 2019-05-31 17:06
Closing, since I believe issue is solved, or not issue. Fell free to contact us Daniel if that's not the case. Thanks!

**Closed by lmazuel** 2019-05-31 17:06 UTC
Labels: Monitor, Service Attention, Waiting answer

**Comment by pykvyas** [comment] 2019-10-31 22:25
How can i get the used capacity (in bytes) value through metrics.

Please help me

**Comment by WhatDoesKmean** [comment] 2019-12-17 17:55
Call it like this:   metric.primary_aggregation_type.value
