### ISSUE TITLE
Eventhub Blob CheckpointStore - Server failed to authenticate the request "Request date header too old"

### ISSUE THREAD

**Issue by noirbee** [Azure/azure-sdk-for-python#16192] opened 2021-01-15 15:05 UTC
- **Package Name**: azure-eventhub-checkpointstoreblob
- **Package Version**: 1.1.1
- **Operating System**: Debian 10 "buster"
- **Python Version**: 3.7.3

**Describe the bug**
This is essentially (and intentionally) a duplicate of issue #14067, applied to the Blob Storage layer used for checkpointing in the eventhub client. Here's an example of the error we see in our logs: 

```
An exception occurred during list_ownership for namespace '****' eventhub '****' consumer group '****'. Exception is ClientAuthenticationError("Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:fb6cef5b-001e-0076-6692-e88e95000000
Time:2021-01-12T03:23:55.3383493Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:Request date header too old: 'Tue, 12 Jan 2021 03:08:02 GMT'")
```

I looked at updating the `policies` list in `sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/_shared/base_client.py` (and `base_client_async.py`) in the same way as in https://github.com/Azure/azure-sdk-for-python/pull/14629 and opening a PR, but unfortunately I can't even get the tests to run using `tox`, much less write one :(

**To Reproduce**
We have trouble to reproduce it ourselves as the error only shows on one of our environments (with almost non-existent load).
I expect the steps in #14067 would yield the same results.

**Expected behavior**
 The Request date header too old exceptions should not be thrown.

**Comment by yunhaoling** [comment] 2021-01-20 21:54
hey @noirbee , thanks for bring this to my attention.

Based on what you said, this is a known issue in the storage sdk and they have already get it fixed.
Currently the storage sdk code is vendored in the eventhub sdk, so I think we need to update the vendored storage code to accommodate the change.

You mentioned that "opening a PR", do you have link to your opened PR? I would be great if we could collaborate on fixing this :)

**Comment by yunhaoling** [comment] 2021-02-11 14:00
hey @noirbee , I have updated the vendor storage blob in this PR: https://github.com/Azure/azure-sdk-for-python/pull/16559

We'll do a bug fix release next month, thanks for your patience!

**Comment by yunhaoling** [comment] 2021-03-10 13:44
hey @noirbee , we have released a patch version of azure-eventhub-checkpointstore(-aio) with the updated vendored storage sdk. please upgrade to the latest version to try out the fix.

I'm closing the issue now assuming the issue is fixed within the latest release, but don't hesitate to reopen if you're still meeting with troubles.
thanks for you patience!

pypi:
https://pypi.org/project/azure-eventhub-checkpointstoreblob/1.1.3/
https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/1.1.3/

**Closed by yunhaoling** 2021-03-10 13:44 UTC
Labels: Client, Event Hubs, blocking-release, bug, customer-reported

**Comment by ervandew** [comment] 2021-04-16 17:31
We are running the latest version of azure-eventhub-checkpointstoreblob-aio (1.1.3) and have noticed this same issue occurring sporadically in our production environment across several partitions:

    azure.eventhub.aio._eventprocessor.event_processor: EventProcessor instance '...' of eventhub '...' partition '16' consumer group '...'. An error occurred while receiving. The exception is ClientAuthenticationError("Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    RequestId:...
    Time:2021-04-16T16:25:45.3236606Z
    ErrorCode:AuthenticationFailed
    Error:None
    AuthenticationErrorDetail:Request date header too old: 'Fri, 16 Apr 2021 16:09:49 GMT'").

Let me know what other information you may need. In the case of 1 partition the request date header sent looked to be almost 24hrs old, and soon after this error that consumer was suddenly hundreds of thousands of messages behind despite being no more than single digits behind prior to that, with no sudden spikes from producers.
