### ISSUE TITLE
Key Vault - Keys Sample Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-sdk-for-python#30877] opened 2023-06-25 09:46 UTC
1.
Section [link1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/samples/key_rotation.py#L62), [link2](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-keys/samples/key_rotation_async.py#L62):
![image](https://github.com/Azure/azure-sdk-for-python/assets/119990644/71c81408-647a-4b9d-a6d8-1ef70eeb4fb8)

**Reason**:
Values didn't match for `KeyRotationPolicyAction.rotate` equals `'Rotate'`, which causes:
AssertionError: The specified action should exist in the key rotation policy

**Suggestion1&2**:
Update code to `'rotate'`

**Suggestion3**:
Update code to `'notify'`

@rohit-ganguly, @lmazuel, @mario-guerra, @heaths, @mccoyp for notification.

**Comment by mccoyp** [comment] 2023-06-26 18:58
This issue was caused by a service regression that's being mitigated now -- ICM with details: https://portal.microsofticm.com/imp/v3/incidents/details/397947956/home

There was also a PR in JS to account for the change, but this has been closed since the service is correcting itself: https://github.com/Azure/azure-sdk-for-js/pull/26217

I'll close this issue since the problem should go away once service changes are fully deployed. Thank you @ChenxiJiang333 for your attention to this!

**Closed by mccoyp** 2023-06-26 18:58 UTC
Labels: KeyVault, Client, test-manual-pass
