### ISSUE TITLE
azure-mgmt-datafactory==1.1.0 fails to deploy ADF dataset json, worked with 1.0.0

### ISSUE THREAD

**Issue by mattiethecat** [Azure/azure-sdk-for-python#17413] opened 2021-03-18 03:37 UTC
# Code that fails
````
from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.identity import ClientSecretCredential
from azure.mgmt.datafactory.models import Dataset, PipelineResource

import json
import os
import sys
import pystache
import logging

from dotenv import load_dotenv

load_dotenv()

df_name = os.getenv("df_name") or os.environ['df_name']
rg_name = os.getenv("rg_name") or os.environ['rg_name']
client_id= os.getenv("client_id") or os.environ['client_id']
client_secret=os.getenv("client_secret") or sys.argv[1]
tenant_id =os.getenv("tenant") or os.environ['tenant']
subscription_id = os.getenv("subscription_id") or os.environ['subscription_id']
resource_for_query = os.getenv("resource_for_query") or os.environ['resource_for_query']
    
def get_adf_client():
    credentials = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
    return DataFactoryManagementClient(credentials, subscription_id)

def deploy_dataset(adf_client, name, dataset_json):
    dataset_dict = json.loads(dataset_json)
    logging.getLogger('msrest.serialization').setLevel(logging.ERROR)
    dataset = Dataset.from_dict(dataset_dict)
    logging.getLogger('msrest.serialization').setLevel(logging.WARNING)
    adf_client.datasets.create_or_update(rg_name, df_name, name, dataset)

adf_client = get_adf_client()
with open(f"DS_ADLS_CSV.json", 'r') as f:
    dataset_json = f.read()
name = "DS_ADLS_CSV"
dataset_json
deploy_dataset(adf_client, name, dataset_json)
````

# Json file to deploy to ADF ("DS_ADLS_CSV.json")
````
{
    "name": "DS_ADLS_CSV",
    "properties": {
        "description": "Writing to ADLS as a comma-delimited CSV",
        "linkedServiceName": {
            "referenceName": "LS_ADLS_Raw",
            "type": "LinkedServiceReference"
        },
        "parameters": {
            "table_name": {
                "type": "string"
            },
            "source_system": {
                "type": "string"
            }
        },
        "folder": {
            "name": "GenericLoad"
        },
        "annotations": [],
        "type": "AzureBlobFSFile",
        "typeProperties": {
            "format": {
                "type": "TextFormat",
                "columnDelimiter": ",",
                "rowDelimiter": "",
                "quoteChar": "\"",
                "nullValue": "",
                "treatEmptyAsNull": false,
                "skipLineCount": 0,
                "firstRowAsHeader": true
            },
            "fileName": {
                "value": "@concat(dataset().table_name, '-', addhours(utcnow(), 0, 'yyyy-MM-ddTHH:mm:ssZ'),'.parquet')",
                "type": "Expression"
            },
            "folderPath": {
                "value": "@concat('raw/' , dataset().source_system, '/', dataset().table_name, '/', addhours(utcnow(), 0, 'yyyy-MM-ddTHH:mm:ssZ') )",
                "type": "Expression"
            }
        }
    },
    "type": "Microsoft.DataFactory/factories/datasets"
}

````

# Expected: deploy dataset to ADF
No issues in version 1.0.0

# Actual: fails with error: 
File "", line 39, in deploy_dataset
    adf_client.datasets.create_or_update(rg_name, df_name, name, dataset)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\azure\mgmt\datafactory\operations\_datasets_operations.py", line 182, in create_or_update
    body_content = self._serialize.body(dataset, 'DatasetResource')
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\msrest\serialization.py", line 628, in body
    raise errors[0]
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\msrest\serialization.py", line 250, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\msrest\serialization.py", line 730, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'Dataset.linked_service_name' can not be None.

**Comment by catalinaperalta** [comment] 2021-03-18 17:44
Thanks for reaching out @mattiethecat! We'll investigate ASAP.
Adding @msyyc who can comment more about this issue.

**Comment by msyyc** [comment] 2021-03-19 01:54
@zhangyan133 Please provide help on this issue.

**Comment by shawnxzq** [comment] 2021-03-26 08:59
@zhangyan133 Any update on this? Thanks!

**Comment by shawnxzq** [comment] 2021-05-11 13:03
@zhangyan133 Any update? Thx

**Comment by shawnxzq** [comment] 2021-06-09 12:19
@msyyc @zhangyan133  Any update on this?

**Comment by msyyc** [comment] 2021-06-10 03:07
The error message hint that it lacks required parameter. Could you have a try to add it?
![image](https://user-images.githubusercontent.com/70930885/121458376-d1cfa800-c9db-11eb-949f-31d9e032f9c2.png)

**Comment by shawnxzq** [comment] 2021-07-07 11:37
@mattiethecat Could you please check the error shared above and confirm whether solve your issue? thanks!

**Comment by mattiethecat** [comment] 2021-07-09 01:23
I won't have capacity to look into this one and we will likely avoid deploying Json's in this way in future.

**Comment by shawnxzq** [comment] 2021-07-09 11:37
@mattiethecat I believe the error means we miss the dataset name, and if you don't need this any more, could you please close this issue? Thanks a lot!

**Comment by shawnxzq** [comment] 2021-08-05 03:24
@catalinaperalta Please help close this one since customer confirmed no need to track this and I don't have permission to do so, thanks!

**Closed** 2021-08-05 07:32 UTC
Labels: Data Factory, Mgmt, Service Attention, bug, customer-reported, needs-team-attention
