### ISSUE TITLE
Reference doc bug bash (look for both content issues and rendering issues) for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15110] opened 2020-11-08 19:30 UTC

**Comment by lmazuel** [comment] 2020-11-30 22:59
Duplicate of https://github.com/Azure/azure-sdk-for-python/issues/15121

**Comment by mccoyp** [comment] 2020-12-14 17:59
Below are the rendering issues found in the [reference docs](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) -- some are rendering/linking related, while some are content-related but need further investigation before fixing in source code.

| Bug type | Description | Source |
|---|---|---|
| Docs content | General KV overview page mentions that 4.x is recommended under "Libraries for data access", but there should also be a note about this under "Version 1.x.x" | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Rendering | Management library overview page is empty on docs, despite there being non-empty (even if sparse) READMEs on GitHub. We'll need to follow up with Scott to see why this is | [link](https://docs.microsoft.com/python/api/overview/azure/keyvault/management?view=azure-python) |
| Linking | Clicking the "Reference" link for `azure-keyvault` from KV overview page brings up the preview KV overview instead of the legacy overview | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Docs content | README that's linked to from the `azure-keyvault` "GitHub" link in reference docs is in a tag (but not a branch) in the repo. The link to the reference docs from the README is outdated, but I'm not sure how to update it to the legacy docs page since there's no branch with the legacy README content | [link](https://docs.microsoft.com/python/api/overview/azure/key-vault-index?view=azure-python) |
| Linking | Link for Python in the "Reference" TOC node in the KV service overview page directs to the management package reference, when it should probably link to the general KV overview | [link](https://docs.microsoft.com/azure/key-vault/general/overview) |
| Content/rendering | `begin_create_certificate` shows "HttpResponseError" under "Exceptions" twice, and lists all possible parameters as "Required" when some are optional keyword-only arguments. These issues exist for all methods that have required parameters (denoted by `:param x x:` in their docstring) as well as keyword arguments specified in their docstring (denoted by `:keyword x x:`). Methods that have only keyword arguments denoted by `:keyword x x:` don't render with duplicate exceptions in the reference docs, but their parameters are still listed as "Required". Keyword arguments that are denoted by `:param x x:` in docstrings don't show up as "Required" (see [`JsonWebKey`](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.jsonwebkey?view=azure-python)), but these can't coexist with required parameters | [link](https://docs.microsoft.com/python/api/azure-keyvault-certificates/azure.keyvault.certificates.certificateclient?view=azure-python#begin-create-certificate-certificate-name--policy----kwargs-) |
| Content/rendering | `KeyVaultKey` has code block examples in its docstring, such that they render in the [package class list](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys?view=azure-python) and aren't put in an "Examples" section like we do for other classes. Should this be changed? Can multiple examples be put in a single docstring using the `Example: literalinclude::` pattern? | [link](https://docs.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.keyvaultkey?view=azure-python) |

**Closed** 2020-12-15 02:48 UTC
Labels: Client, KeyVault
