### ISSUE TITLE
ChangeFeedClient.list_changes() causes InvalidQueryParameterValue error

### ISSUE THREAD

**Issue by sylnsr** [Azure/azure-sdk-for-python#24135] opened 2022-04-21 22:28 UTC
- **azure-storage-blob-changefeed**: 
- **12.10.0b3**: 
- **OSX**:
- **3.9**: 

I'm using the [sample code to list all change feed events](https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-changefeed-readme?view=azure-python-preview#enumerating-all-events). My code is almost the same, verbatim, save the fact that I need to [workaround for issue 12568](https://github.com/Azure/azure-sdk-for-python/issues/12568#issuecomment-661678790).  Following the sample code you provide, I get this error:

Exception: HttpResponseError: (InvalidQueryParameterValue) Value for one of the query parameters specified in the request URI is invalid.
RequestId:2bc2b517-f01f-0001-67cb-55e1c0000000
Code: InvalidQueryParameterValue

**To Reproduce**
Call this code to list all change events .. based on the [sample code provided example](https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-changefeed-readme?view=azure-python-preview#enumerating-all-events), but using the [workaround for issue 12568](https://github.com/Azure/azure-sdk-for-python/issues/12568#issuecomment-661678790)

        cf_client = ChangeFeedClient(
            account_url = "https://{}.dfs.core.windows.net".format(STORAGE_ACCOUNT),
            # bug work around - see: https://github.com/Azure/azure-sdk-for-python/issues/12568#issuecomment-661678790
            credential={"account_name": STORAGE_ACCOUNT, "account_key": KEY_STR}
        )

        change_feed = cf_client.list_changes()   # breaks here

**Expected behavior**
According to the documentation, we should be able to get a result without any error. I mean, its only 2 function calls at this point to get it to break .... what could a user be doing wrong at that point?

Both my STORAGE_ACCOUNT and KEY_STR values are correct since I use them with `azure-storage-file-datalake==12.5.0` without any problems.

**Additional context**
My requirements. file: [req.txt](https://github.com/Azure/azure-sdk-for-python/files/8535441/req.txt)

**Comment by rakshith91** [comment] 2022-04-22 19:31
@sylnsr Thanks for the issue. We will take a look asap

**Comment by jalauzon-msft** [comment] 2022-04-22 20:21
Hi @sylnsr Mike, I believe your issue might be caused by the fact that you are using the `dfs` endpoint for account URL. I believe we only support ChangeFeed on the Blob endpoint so you should provide the blob endpoint for your account when constructing the client. This matches the URL used in our samples. Additionally, I don't think you should need the workaround with `credential` in this case since you are using a standard account URL?

So, can you try something like this?
```python
cf_client = ChangeFeedClient(
    account_url = "https://{}.blob.core.windows.net".format(STORAGE_ACCOUNT),
    credential=KEY_STR
)

change_feed = cf_client.list_changes() 
```

Hopefully that helps, thanks!

**Comment by navba-MSFT** [comment] 2022-04-25 06:32
@sylnsr Thanks for reaching out to us. I hope you had a chance to follow the above suggestion provided by @jalauzon-msft. 

Only standard general-purpose v2, premium block blob, and Blob storage accounts can enable the change feed. Accounts with a hierarchical namespace enabled are not currently supported. More Info [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed?tabs=azure-portal#enable-and-disable-the-change-feed) and [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-feature-support-in-storage-accounts).

```
# [START create_change_feed_client]
   cf_client = ChangeFeedClient("https://{}.blob.core.windows.net".format(self.ACCOUNT_NAME),
                                credential=self.ACCOUNT_KEY)
   # [END create_change_feed_client]

   change_feed = cf_client.list_changes(results_per_page=10).by_page()

   # print first page of events
   change_feed_page1 = next(change_feed)
   for event in change_feed_page1:
       print(event)

   # print second page of events
   change_feed_page2 = next(change_feed)
   for event in change_feed_page2:
       print(event)
```
Python Sample code [here](https://docs.microsoft.com/en-us/python/api/azure-storage-blob-changefeed/azure.storage.blob.changefeed.changefeedclient?view=azure-python-preview).

**Comment by sylnsr** [comment] 2022-04-25 14:24
Can we at least get a more intuitive error message then please. The current error is a red-herring.

**Comment by jalauzon-msft** [comment] 2022-04-25 18:59
Hi @sylnsr Mike, you are correct that `StorageV2 (general purpose v2)` is the correct account type however what I believe @navba-MSFT was pointing out was that Change Feed is not supported for account with hierarchical namespace enabled. This is a property on a Storage account that can be seen on the home screen for an account:
![image](https://user-images.githubusercontent.com/96087589/165153097-da6eddc0-4c3d-45b7-92a1-1cbdd423fba8.png)

This was mentioned since you were trying to use the `dfs` URL which is typically used for hierarchical namespace accounts. So, changing your URL to use `blob` will fix the error but you may not get full change feed support on your account if hierarchical namespace is enabled. This support is documented [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed?tabs=azure-portal#feature-support). In either case, *only* the ".**blob**.core.windows.net" account URLs are supported since only the blob service is supported.

As for the error message, I agree that is fairly misleading, but it is also a tricky one for the service since the requests for ChangeFeed are just standard List/Get requests for the ChangeFeed blobs but the `dfs` endpoint interprets these requests a little differently and therefore throws the error. We can discuss improving this error message with the service team. Thanks for the feedback.

**Comment by sylnsr** [comment] 2022-04-25 19:40
Say whaaaat?. So this thing is even more misleading since ".**blob**.core.windows.net" is actually an **immutable** part of how the API is used, however, because it's taken as part of the param it therefore implies it's not.

It would make so much much more sense to simply take the storage account name only, as the param and then simply do:
`"https://{}.blob.core.windows.net".format(ACCOUNT_NAME_PARAM)` _inside_ the ctor in behalf of the caller.

The current design choice for that method is perplexingly illogical and un-intuitive.

**Comment by jalauzon-msft** [comment] 2022-04-25 21:48
@sylnsr Mike, sorry, I was simplifying a bit. We do need to support other account URLs such as [custom domains](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name?tabs=azure-portal), [CDNs](https://docs.microsoft.com/en-us/azure/cdn/cdn-create-a-storage-account-with-cdn), [static websites](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website), as well as some other upcoming features.. These would also work as long as they point to the blob endpoint. So we need to keep support for mutable URLs.

**Comment by sylnsr** [comment] 2022-04-25 21:51
OK, that makes a lot more sense. So yeah, if we could just get that error message improved. That would be great.

**Comment by jalauzon-msft** [comment] 2022-04-28 18:01
We will talk with the service team about trying to catch this specific case and put in a better error message, but it may be technically difficult. We're also reluctant to put in a client-side check here in case the service team adds support for this in the future.

Going to close this issue though, as it seems the primary issue has been resolved. Thanks

**Closed by jalauzon-msft** 2022-04-28 18:01 UTC
Labels: Storage, question, Client, customer-reported, needs-team-attention, CXP Attention
