### ISSUE TITLE
[Cognitive Service] properties in azure.mgmt.cognitiveservices.models.CognitiveServicesAccountCreateParameters

### ISSUE THREAD

**Issue by dafashiandongni** [Azure/azure-sdk-for-python#1060] opened 2017-03-31 09:27 UTC
I'm trying to use azure-sdk-for-python. In azure.mgmt.cognitiveservices.models.CognitiveServicesAccountCreateParameters, the docs syas: properties (object) – Must exist in the request. Must not be null.

I'm confused what the properties should be. Is there any example?

**Comment by lmazuel** [comment] 2017-03-31 16:33
Hi @dafashiandongni 
I know there is no sample for this service right now, I will try to do one asap to unlock you.

**Comment by dafashiandongni** [comment] 2017-04-01 00:56
@lmazuel That's great! Thank you so much. I really need it.

**Comment by jdneo** [comment] 2017-04-06 04:19
Hi @lmazuel, 

I have the same issue. I wrote a test code to create cognitive service:

```
"""
test creating cognitive service.
"""

from azure.mgmt.cognitiveservices import CognitiveServicesManagementClient
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.cognitiveservices.models import CognitiveServicesAccountCreateParameters, Sku
from azure.mgmt.resource.resources import ResourceManagementClient


SUBSCRIPTION_ID = '-----------------'

credentials = ServicePrincipalCredentials(
    client_id='-----------------',
    secret='------------------',
    tenant='-------------------'
)


cognitiveservices_client = CognitiveServicesManagementClient(
    credentials,
    SUBSCRIPTION_ID
)

resource_client = ResourceManagementClient(
    credentials,
    SUBSCRIPTION_ID
)
resource_client.providers.register('Microsoft.CognitiveServices')

sku = Sku('F0')

param = CognitiveServicesAccountCreateParameters(sku, 'Bing.Speech', 'West US', {})

res = cognitiveservices_client.cognitive_services_accounts.create('speech-recognition', 'testshengtempspeech', param)

res = cognitiveservices_client.cognitive_services_accounts.list()

print res
```

And got: 

`RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/----------------/resourceGroups/speech-recognition/providers/Microsoft.CognitiveServices/accounts/--------------?api-version=2016-02-01-preview (Caused by ResponseError('too many 502 error responses',))`

The code is referenced to the ruby [sample code](https://github.com/Azure-Samples/cognitive-services-ruby-create-account).

Any suggestions about this?

Thanks

**Comment by lmazuel** [comment] 2017-04-10 22:32
Hi,

I have no suggestion yet, I think I will wait for the new version to come in a few days and do the new sample at the same time. This is the PR that brings the meta-description of the new endpoint, that will be use as basis for the updated version of this SDK:
https://github.com/Azure/azure-rest-api-specs/pull/1090

**Comment by lmazuel** [comment] 2017-05-22 16:48
Hi @jdneo 
azure-mgmt-cognitiveservices is released and plugged in the Azure CLI. I think your problem should be solved now, could you check?
Thank you,

**Comment by jdneo** [comment] 2017-05-23 02:52
Hi @lmazuel 

Thank you for your information. I tried to use the azure-cli 2.0 to create the cognitive service. And got the below error:

```
az cognitiveservices account create -n speech012 -g tempGroup --kind Bing.Speech --sku F0 -l global --yes

Notice
Microsoft will use data you send to the CognitiveServices to improve Microsoft products and services.Where you send personal data to the Cognitive Services, you are responsible for obtaining sufficient consent from the data subjects.The General Privacy and Security Terms in the Online Services Terms do not apply to the Cognitive Services.Please refer to the Microsoft Cognitive Services section in the Online Services Terms (https://www.microsoft.com/en-us/Licensing/product-licensing/products.aspx) for details.Microsoft offers policy controls that may be used to disable new Cognitive Services deployments (https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-apis-create-account).
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 478, in _execute_command
    raise client_exception
ErrorException: Operation returned an invalid status code 'Bad Request'
```

After some investigation, I find out it's because the F0 quota is exceeded, after change to sky to S0, problem solved.

I think it will be great if the error message can be more user friendly.

Thanks you

**Comment by derekbekoe** [comment] 2017-05-23 04:21
@jdneo for CLI bugs, please also file an issue at https://github.com/azure/azure-cli/issues

**Comment by jdneo** [comment] 2017-05-23 04:50
@derekbekoe @lmazuel Sure. And for me, I have no more question about this issue now. Thank you for your guys' help.

**Comment by lmazuel** [comment] 2017-05-23 16:59
Thanks @jdneo 
I'm closing this issue, since I think the initial question is fixed (I will make feedback to the team about the RestAPI unfriendly behavior).
Thanks!

**Closed by lmazuel** 2017-05-23 16:59 UTC
Labels: ARM, Docs
