### ISSUE TITLE
[Azure Graphrbac] [Question] Track 2 release for Azure Graphrbac

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#17302] opened 2021-03-12 00:51 UTC
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
Azure graphrbac (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/graphrbac/azure-graphrbac/azure/graphrbac/graph_rbac_management_client.py#L60) still uses old auth.. What is the plan with Track 2 migration for this SDK?

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yunhaoling** [comment] 2021-03-12 16:52
hey @logachev , thanks for reaching out, we'll investigate asap.

@lmazuel @xiangyan99, looking into the code and commit history, it doesn't get updated for a while, wondering if you have more context on the the graphrbac package.

**Comment by lmazuel** [comment] 2021-03-12 17:27
Hi @logachev 
This is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/14022, hence closing this one. Feel free to thumbs / comment on the other.
Thanks!

**Closed by lmazuel** 2021-03-12 17:27 UTC
Labels: Client, Graph, Service Attention, customer-reported, question
