### ISSUE TITLE
Slow download and upload of large number of small files

### ISSUE THREAD

**Issue by Robotmurlock** [Azure/azure-sdk-for-python#28997] opened 2023-02-24 17:52 UTC
Downloading large number of small files (few KBs) seems to be very slow.

Using multiple threads or processes makes this process drastically faster. Same problems is for all other basic blob functions. On other side it seems that batch deletes solves this problem even better (faster). Is it possible to implement same functions for download and upload?

**Comment by navba-MSFT** [comment] 2023-02-27 03:05
@Robotmurlock Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by PramodValavala-MSFT** [comment] 2023-02-28 20:57
@Robotmurlock In the case of deletes, the blobs are merely "marked" for deletion and since there is hardly any network traffic apart from the initial request, it is faster by design with the actual deletion taking place later.

But as far as uploads/downloads are concerned, leveraging multiple threads and async features of the language would be the way to go for many operations since they are mostly I/O bound. Unfortunately, the connection overhead itself cannot be resolved with this.

This would be a feature request requiring support from the service side for batch upload/downloads with the SDKs following suit.

**Comment by jalauzon-msft** [comment] 2023-03-13 18:26
Closing due to lack of detail on specific client request and Batch upload/download requiring service support.

**Closed by jalauzon-msft** 2023-03-13 18:26 UTC
Labels: feature-request, Storage, Service Attention, customer-reported, needs-team-attention
