### ISSUE TITLE
TableStorage upsert_entity() fails when passed the hyphen character as RowKey

### ISSUE THREAD

**Issue by riccardo-di-lorenzo** [Azure/azure-sdk-for-python#21240] opened 2021-10-13 13:03 UTC
- **Package Name**: azure-data-tables
- **Package Version**:  12.1.0
- **Operating System**: Mac OS Big Sur 11.6 (20G165)
- **Python Version**:  3.9.5

**Describe the bug**
Despite being an [allowed](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN#characters-disallowed-in-key-fields) character, I cannot use the Python API to insert a RowKey containing an hyphen (').

**To Reproduce**
1. Make a test storage account
2. Run the following code
```python
import os

class Demo(): 
    def __init__(self):
        self.access_key = os.getenv("TABLES_PRIMARY_STORAGE_ACCOUNT_KEY")
        self.endpoint_suffix = os.getenv("TABLES_STORAGE_ENDPOINT_SUFFIX")
        self.account_name = os.getenv("TABLES_STORAGE_ACCOUNT_NAME")
        self.endpoint = "{}.table.{}".format(self.account_name, self.endpoint_suffix)
        self.connection_string = "DefaultEndpointsProtocol=https;AccountName={};AccountKey={};EndpointSuffix={}".format(
            self.account_name, self.access_key, self.endpoint_suffix
        )
        self.table_name = "users"
    
    def set(self, name):
        from azure.data.tables import TableClient
        from azure.data.tables import UpdateMode

        table_client = TableClient.from_connection_string(self.connection_string, self.table_name)
        
        e = {}
        e['PartitionKey'] = 'pk'
        e['RowKey'] = name
        table_client.upsert_entity(mode=UpdateMode.MERGE, entity=e)


if __name__ == "__main__":
    d = Demo()
    d.set("Jimmy O'Hare")
```
to run this you will need the "TABLES_PRIMARY_STORAGE_ACCOUNT_KEY", "TABLES_STORAGE_ENDPOINT_SUFFIX", "TABLES_STORAGE_ACCOUNT_NAME". All values you can find from the target resource (a table storage).

This leads to
> There is an unterminated string literal at position 39 in 'PartitionKey='pk',RowKey='Jimmy O'Hare''.
ErrorCode:InvalidInput

**Expected behavior**
Entry is inserted in Table Storage

**Screenshots**

![Screenshot 2021-10-13 at 14 43 45](https://user-images.githubusercontent.com/83587227/137134770-d664bb8d-7b04-4868-96de-fae5ee85d16a.png)

The issue is present also if the RowKey is sent as bytes, where it gets converted in a base64, but then is actually sent unencoded (notice the "RowKey" in the entity object vs "row_key", which is the parameter actually sent)

![Screenshot 2021-10-13 at 14 58 22](https://user-images.githubusercontent.com/83587227/137137199-0435c1a3-561f-41e0-b308-6bff0b2a655d.png)

**Additional context**
I'm actually using the async module of this, were the problem is present as well.
I tried to insert the entry into my table using Azure Storage Explorer, and as expected (since the hyphen character is allowed), I can insert the entry in the table.

**Comment by annatisch** [comment] 2021-10-13 15:37
Thanks @riccardo-di-lorenzo for the bug report!
This is actually a duplicate of issue #20301.
We have a fix in place for this, and are just waiting to roll it out. There has been some debate over whether this will break some customers how may have already worked around it - but we believe that impact should be very small, and most people who encounter this would consider it a bug. This fix should go out with the November release :)

Thanks again!

**Comment by annatisch** [comment] 2021-11-15 22:12
Hi @riccardo-di-lorenzo - this bug fix should now be released.
Please try out the latest package and let us know how it goes - or whether you still encounter any difficulties :)

**Closed** 2021-11-23 04:02 UTC
Labels: question, customer-reported, Tables, issue-addressed
