### ISSUE TITLE
[azure-mamt-reservations] Ref docs issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-python#20027] opened 2021-08-02 07:17 UTC
Error:
> Error analysis
> "Latest" -- Run build script (PowerShell)
> 
> <Matched Error>: c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\azure\mgmt\reservations\aio\operations\__init__.py:docstring of azure.mgmt.reservations.aio.operations.QuotaRequestStatusOperations.list:11: ERROR: Error parsing content block for the "list-table" directive: uniform two-level bullet list expected, but row 2 does not contain the same number of items as row 1 (1 vs 2).

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=225421&view=results
- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=225871&view=results
- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=226278&view=results

@danieljurek for notification.

**Comment by v-yilinhu** [comment] 2021-08-02 07:20
@danieljurek  I tried to delete the package and re-run the the docs build according to the steps in the [document](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/454/Ref-Docs-Build-and-Stability), but I couldn't find the package in [package.json](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/ci-configs/packages-latest.json).

**Comment by danieljurek** [comment] 2021-08-09 05:14
This is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/18077 we can close this one.

That package has been previously removed from the build which is why it's not showing up in the onboarding json file.

**Closed by danieljurek** 2021-08-09 05:14 UTC
Labels: Docs
