### ISSUE TITLE
ServiceBusReceiver consumes message but does not give it to output.

### ISSUE THREAD

**Issue by lubomirmatus** [Azure/azure-sdk-for-python#31711] opened 2023-08-18 09:23 UTC
- **Package Name**:  azure-servicebus
- **Package Version**: 7.8.2, 7.11.1
- **Operating System**: Windows 10 x64
- **Python Version**:  3.11.1

**Describe the bug**
Sometimes used to happen that receiver consumes message from topic/subscription but does not give it to output when calling `messages = receiver.receive_messages(...)`. The behavior is mostly deterministic with empty result, but sometimes, very occasionaly, happens that the message is returned. Receiver can correctly read messages that are already in topic (in time of receiver creation), but problem can be with new incoming messages.
I have spotted this behavior some time ago, maybe few months, but I did not realized that it is problem of Azure SDK.
In the some older versions (probably with older python) it was working correctly.

**To Reproduce**
We have ServiceBus topic with 2 subscriptions. There are already some messages in topic/subscription.
`client = ServiceBusClient.from_connection_string(conn_str='my_connection', logging_enable=False)`
`receiver = client.get_subscription_receiver(topic_name='my_topic', subscription_name='subscription2', receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE, keep_alive=0, prefetch_count=0)`
`messages = receiver.receive_messages(max_message_count=1000, max_wait_time=100)`  # Consumes all messages in subscription (all messages from subscription are in output, in my test there were less than 1000 messages in topic).
`time.sleep(30)`  # Wait some time.
Message is sent to topic from external system during wait.
Message can be immediately seen in Azure Portal Service Bus Explorer in subscription1.
Message cannot be seen in subscription2 (probably is consumed by receiver).
(Message can be seen in subscription2 only when this test is off and no one is consuming them).
`messages = receiver.receive_messages(max_message_count=1, max_wait_time=10)`
The receiver is waiting till timeout passed (longer timeout will not help), but no message is returned in result. The messages result is empty, no message.

**Expected behavior**
Expected is that all messages that have been sent to the topic can be correctly read.

**Comment by swathipil** [comment] 2023-08-18 22:24
Hi @lubomirmatus - Thanks for opening an issue! We're working on reproducing this right now, and think that this is related to prefetch/the issue you have here: https://github.com/Azure/azure-sdk-for-python/issues/31712.

We'll keep you updated as we work on finding the right fix. Thanks!

**Comment by swathipil** [comment] 2023-09-11 16:25
Hi @lubomirmatus - We've found the bug and are currently working on the right fix. We'll keep you updated as continue to work on it. Thanks!

More info: When receiving in receive and delete mode, the received message isn't appended to our internal buffer and is settled right away. When the user calls receive_messages again a little later, those messages are not in the internal buffer, so they are not returned to the user. The two bugs we're fixing:
1) When a message is received with prefetch>0, it should be appended to the internal buffer.
2) Our default prefetch behavior should be "off", and that's not behaving as intended.

**Comment by swathipil** [comment] 2023-10-09 20:05
Hi @lubomirmatus - We've merged the fix into the main branch of the repo. We will be releasing the fix this week. If you'd like to test out the change beforehand, you can build the wheel off of the main branch. Thanks!

**Comment by swathipil** [comment] 2023-10-11 21:38
Hi @lubomirmatus - The fix has been released in v7.11.3. https://pypi.org/project/azure-servicebus/7.11.3/

Thanks!

**Closed by swathipil** 2023-10-11 21:38 UTC
Labels: bug, Service Bus, Client, customer-reported, needs-team-attention, Messaging

**Comment by lubomirmatus** [comment] 2023-10-18 14:10
Ok, thank you.
