### ISSUE TITLE
[Key Vault Keys] Re-enable Key Rotation tests for MHSM

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-python#31190] opened 2023-07-18 21:30 UTC
When we originally added key rotation APIs to the Keys library, the feature was only available for Key Vault endpoints but not MHSM, meaning we had to disable tests that targeted endpoints for the latter. Now, MHSM has support for key rotation, so we need to make sure said tests are re-enabled.

**Comment by pallavit** [comment] 2023-09-20 17:45
Duplicate of #30889

**Closed by pallavit** 2023-09-20 17:45 UTC
Labels: KeyVault, Client
