### ISSUE TITLE
[Form Recognizer] "ServiceRequestError: Failed to establish a new connection, name or service not known" on UsGov and China cloud 

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#20648] opened 2021-09-10 09:12 UTC
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the form recognizer [test_business_card.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_business_card.py#L34), it runs failed and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1088493&view=logs&j=918de6bd-74c7-509e-0e6a-5240d551643f&t=ee3720e5-98a7-5fe7-0153-5be72e72dedf):
![image](https://user-images.githubusercontent.com/57166602/132819962-32aa19fc-4b83-453a-89c0-bbf144ca67d1.png)

**Error Track:**
The code that failed is [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/preparers.py#L21)：
![image](https://user-images.githubusercontent.com/57166602/132831125-99312be8-d324-4d0b-a8d8-f79ebd30b79a.png)

We guess that because the variable `formrecognizer_test_endpoint` is hard-coded, it only applies to public.

**Expected Behavior:**
The variable `formrecognizer_test_endpoint` which can be supported on UsGov and China cloud. Service can successfully send the request.

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa, @ramya-rao-a  for notification.

**Comment by kristapratico** [comment] 2021-09-10 15:48
@v-xuto the `formrecognizer_test_endpoint` is a dummy value used to sanitize the recordings so we don't expose the real endpoint value. I suspect something else is at play here - I'll take a look. Also if I recall correctly, our live tests weekly pipeline is not yet set up to run in China/USGov (the work was still in PR). Did you run this locally or on Devops?

**Comment by v-xuto** [comment] 2021-09-11 02:46
@kristapratico I run this on Devops. My current job is to make live tests weekly pipeline to support in Public/China/USGov. @benbp Do you have anything to add?

**Comment by kristapratico** [comment] 2021-09-14 01:00
Ah okay. If I understand correctly, our test-resources.json needs some updates to be able to deploy resources in China/USGov. Some work was done in this [PR](https://github.com/Azure/azure-sdk-for-python/pull/16964/files), but it wasn't finished because of the timeouts observed when running tests in China/USGov.

**Comment by v-xuto** [comment] 2021-09-24 09:04
@kristapratico - After investigation, it is found that the timeout is in this [test_copy_model.py::TestCopyModel::test_copy_model_fail ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py#L57), which may be related to region. We need to add the region of usgov and china. But do you have any suggestions on how to change it?
![image](https://user-images.githubusercontent.com/57166602/134646699-7c4722bb-d4aa-4d2e-8fca-de5aced6464a.png)

**Comment by kristapratico** [comment] 2021-09-24 16:16
This test intentionally sets the wrong region on line 63 to test that copy operation fails with mismatch of regions. Are you saying that it is hanging on that line? That seems like a service issue to me.

Also formrecognizer_region should have the correct value of the region set in DevOps. You could try something like this to workaround the timeout for now:

```
if formrecognizer_region == "usgov":
    pytest.skip("this test times out in usgov region. follow up with service team")
```

**Comment by v-xuto** [comment] 2021-09-30 09:13
@kristapratico I think it is not a better way to skip the test [test_copy_model_fail_V21](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_copy_model.py#L271) in cloud `UsGov` directly. 

I tried to directly change `resource_region="eastus"` to `resource_region=resource_regionA` (resource_regionA is usgovarizona or usgovvirginia), and the result of `test_copy_model_fail_v21` is PASS. More results details are [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1119262&view=logs&j=a9b86002-2a76-5050-7443-4afb874e24c9&t=657c7d4f-532b-5e0e-9229-529e1e4e3913). 

Because I don't know what the value of the parameter `formrecognizer_region` in the usgov environment variable is, I gave two regions (usgovarizona and usgovvirginia), and we judged one of them. After investigation, I found that in the test `test_copy_model_fail_v21`, the value of `resource_region` should be the region that exists under each cloud, not just `eastus` (exists only under public). The modification of the picture below is just for testing. What are your thoughts on how to modify it?

Now it times out in `test_receipt_from_url.py::TestReceiptFromUrl::test_pages_kwarg_specified`, I am still investigating.
![image](https://user-images.githubusercontent.com/57166602/135419867-40a4f4b5-b9a4-4cef-acb8-4fb48fd73f4e.png)

**Comment by kristapratico** [comment] 2021-09-30 16:20
@v-xuto the snippet you are showing me changes the purpose of the test by passing the correct region into get_copy_authorization - we intentionally pass the wrong region (eastus) to fail the copy (although you told me in the previous message that the test is hanging here instead of quickly failing). I need to check with the service team what the expected behavior is here, but suggest skipping this test in usgov for now.

**Comment by benbp** [comment] 2021-10-12 17:13
If the test is going to be skipped, I'd recommend to not skip on region but authority host is that will be global to the cloud and won't break if the test region is changed (e.g. https://github.com/Azure/azure-sdk-for-python/blob/1bb8e93679de2c25d832dad04f34da7c12b2da13/sdk/containerregistry/azure-containerregistry/tests/testcase.py#L234-L236).

**Comment by v-xuto** [comment] 2021-12-31 06:47
@benbp @kristapratico Skip this test([test_copy_model_fail_v21](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_ftc_copy_model.py#L88)) in UsGov and China clouds can solve the timeout problem. Now, are we going to close this issue directly, or hold to wait for your service team better solution?

**Comment by kristapratico** [comment] 2022-01-04 21:26
@catalinaperalta do you want to close this and open a new issue tracking this test in sovereign clouds? Not sure what the last update was with the service team on sovereign cloud testing expectations.

**Comment by catalinaperalta** [comment] 2022-01-04 21:41
Closing this issue and opening https://github.com/Azure/azure-sdk-for-python/issues/22322.

**Closed by catalinaperalta** 2022-01-04 21:41 UTC
Labels: Client, MQ, Cognitive - Form Recognizer, test-sovereign-cloud
