### ISSUE TITLE
TopicSender unable to recover after timeout

### ISSUE THREAD

**Issue by adamal** [Azure/azure-sdk-for-python#12665] opened 2020-07-22 12:57 UTC
- **Package Name**:
azure-servicebus 
- **Package Version**: 
0.50.2
- **Operating System**:
Experienced in Docker image `python:3.8-slim-buster` as well as locally on macOS 10.14.6
- **Python Version**: 
3.8

**Describe the bug**
Trying to send a message after the 240 s of inactivity results in various errors.

**To Reproduce**
1. Get a sender `sender = TopicClient.from_connection_string(connection_string).get_sender()`
2. Send a message (msg1)
3. Wait 241 s
4. Send a message (msg2)

**Observed behavior**
The send operation errors with 

```
ErrorCodes.ConnectionCloseForced: The connection was inactive for more than the allowed 240000 milliseconds and is closed by container
```

Usually, `sender.send()` of subsequent messages does succeed, however see **Additional context**

**Expected behavior**
Sender reconnects after experiencing the timed out connection, and sends msg2 transparently.

**Additional context**
The application is a small python program running in a container.
It reads messages from a subscription. Reads some data. Sends a message to another topic.
Both receiver and sender are instantiated on startup and not manually (by us) replaced.
Messages sometimes come in more than 240s apart.
We are not seeing any warnings or errors from the receiver.

From looking through logs, I see that the sender _usually_ recovers after failing the current message, and sends subsequent messages successfully. 

I'm am very unsure whether the following is in fact related or another issue, but I include it just in case:
Occasionally the sender enters an untenable state, where all subsequent send attempts fail with 
```
Handler failed: The supplied authentication has already been consumed by another connection. Please create a fresh instance.
```

This first happened after a few weeks of running continuously, with only occasional errors of the previously mentioned type.
More specifically this started on Jul 14 around 8.00 (Copenhagen time).
The problem went away after restarting the container, but reappeared on Jul 18 around 10.04. This time the error train looks to have begun with the aforementioned timeout error.

**Workarounds tried**
Catching the error, I have tried both calling `sender.reconnect()` and then re-sending the message and creating a new sender and resending the message. Both attempts result in errors stating that the message was already settled.

My current – so far seemingly working – workaround is to cache the last timestamp of activity and recreate the sender before sending a message if the last activity was more than 210s ago (240s - 30s margin).

**Comment by KieranBrantnerMagee** [comment] 2020-07-29 23:11
Hey adamal;

Thanks for reaching out, sorry you've run into this trouble.

The 4 minute timeout is a known behavior, this is a service-side timeout to terminate inactive links.  This was also ostensibly something addressed in version 0.50.3, the final pre-release version of Servicebus. (Our GA release currently is in beta, as a note.)  I would first encourage updating to that (`pip install azure-servicebus==0.50.3 --upgrade`) and seeing if the problem is addressed, as we ostensibly support this scenario (see this test [here](https://github.com/Azure/azure-sdk-for-python/blob/3daf5f9519cf60150408149915feda96597baada/sdk/servicebus/azure-servicebus/tests/test_queues.py#L1300).)  Do let me know if this doesn't mitigate the issue.

The second error you observed: "Handler failed: The supplied authentication has already been consumed by another connection. Please create a fresh instance." is not familiar to me offhand, will do some digging on what it might imply and get back to you here if I find anything suspicious, but I'd be interested to see if the fix above improves your situation altogether.

Profuse thanks as well for the very detailed issue report!

**Comment by adamal** [comment] 2020-08-18 09:12
Thanks. I'll keep that in mind. We haven't experienced issues since implementing the workaround mentioned above. I think we'll wait with the upgrade until the next version comes out of pre-release.

**Comment by KieranBrantnerMagee** [comment] 2020-08-18 19:06
Closing as mitigated; feel free to reopen if there are any further issues or questions on this that we can assist with.

**Closed by KieranBrantnerMagee** 2020-08-18 19:06 UTC
Labels: Client, Service Bus, customer-reported, needs-team-attention, question
