### ISSUE TITLE
Version doesn't report number

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-sdk-for-python#612] opened 2016-05-26 07:48 UTC
When installing using pip install azure --pre, I'm not getting a version number from the azure module:
azure.mgmt.compute.VERSION

This breaks a ton of dependencies, please fix!

**Comment by lmazuel** [comment] 2016-05-26 18:13
Hello,

The version number was not accurate before and did not reflect the current package version, it was an internal version number not relevant to the content.
Could you explain why it's breaking something in your case?

Thank you,

**Comment by trondhindenes** [comment] 2016-05-26 18:21
The AzureRM modules for Ansible (which were written by MSFT @devigned and some others) perform a version check. That version check seems to fail for newer versions of the module. I haven't dug too deep, but I feel we need all the consistency we can get, especially with the python modules changing left and right atm.

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/azure_rm_common.py#L78

**Comment by lmazuel** [comment] 2016-05-26 20:18
Actually the current Ansible plugin can not work with the RC4, I made the PR to fix the plugin:
https://github.com/ansible/azurerm/pull/12
https://github.com/ansible/ansible-modules-extras/pull/2319

**Comment by trondhindenes** [comment] 2016-05-30 14:20
Thanks, but we still need to be able to check the installed version thru code. The python module doesn't seem to honor the __version__ attribute, so how are we supposed to do that?

**Comment by trondhindenes** [comment] 2016-06-01 18:05
@lmazuel so what's the plan going forwad? How can I from within my python code check the installed version of the python module for azure?

**Comment by lmazuel** [comment] 2016-06-02 17:08
You can't currently :(
I talked with @nitzmahone at the PyCon, it seems that you can maybe disable this for now, and I will add a `__version__` attribute in the next release.

**Comment by trondhindenes** [comment] 2016-06-02 17:12
wow, you guys certainly don't make it easy for us. Thanks for adding __version__ back.

**Comment by trondhindenes** [comment] 2016-06-02 17:13
btw, it would be really great if the new `__version__` attribute would follow standard versioning formatting, like every other python module in the world does.

**Comment by lmazuel** [comment] 2016-06-02 18:13
@trondhindenes "don't make it easy"? :(
At the second I published the RC4, I was doing the PR to the Ansible repo with the new code. I didn't know that you were using the version attribute, since the content was false I didn't realize that someone could use it (my mistake). I answered to you as fast as possible, considering the PyCon. I went to the Ansible booth at the PyCon to discuss this point with you. I tell you that I will add the `__version__` attribute in the next release as a priority.
And yes, I will follow semantic versioning in the attribute.as the rest of the world does, I know the rest of the world does. Again, this version attribute was not "finished" and our plan was to make it clean for the stable release.
Why do you think I'm not cooperative with you? What do you want more?

**Comment by trondhindenes** [comment] 2016-06-02 18:26
My apologies, that was unnecessary.

**Comment by lmazuel** [comment] 2016-06-23 23:43
Hi @trondhindenes 

The releases 2.0.0RC5 / 0.30.0rc5 are released with the `__version__` attribute ready to use. Sorry again for the inconvenience caused by this issue.

**Comment by nitzmahone** [comment] 2016-06-23 23:51
@lmazuel Thanks!

**Closed** 2016-06-27 23:35 UTC
