### ISSUE TITLE
Status code 400 when trying to create budget with notification

### ISSUE THREAD

**Issue by kmai** [Azure/azure-sdk-for-python#3622] opened 2018-10-16 09:52 UTC
**What am I trying to do?**

I'm trying to create a budget for a subscription, with a notification defined.

**How?**

```python
assert client.budgets.create_or_update(
        budget_name="Monthly Budget",
        parameters={
            'category': 'cost',
            'time_grain': 'Monthly',
            'time_period': {
                'start_date': '2018-10-01T00:00:00Z'
            },
            'amount': 600,
            'notifications': {
                "DevOps": {
                    'enabled': True,
                    'operator': 'GreaterThanOrEqualTo',
                    'threshold': 80,
                    'contact_emails': ['devops.team@domain.com']
                }
            }
        }
    ), "Could not create budget"
```

**Additional info?**

I'm using a service principal account with permissions granted on the Resource Management API.

**What's the problem?**

The response message says:

```
File "/Users/kmai/.virtualenvs/tenant-automation/lib/python3.7/site-packages/azure/mgmt/consumption/operations/budgets_operations.py", line 278, in create_or_update
    raise models.ErrorResponseException(self._deserialize, response)

azure.mgmt.consumption.models.error_response.ErrorResponseException: (400) A valid email claim is required. Email claim is missing in the request header. Consider using a service principal with a valid email claim or a user principal/credential with an email claim. 
```

What does this actually mean?

**Comment by murraybutler** [comment] 2018-10-22 21:34
Hi kmai,

Since no one has picked this up yet, I'll point you to the right info...

"Calls to the budgets API enforce a user context. So you will need to call the budgets API in the context of a user and not a service principal. For customers using MFA the ARM client is an option to get a user token to use with the request."

https://azure.microsoft.com/en-us/blog/enhancements-to-azure-budgets-api-supporting-resource-groups-and-usage-budgets/

Sorry, I think they're working on making it open to SPUs, but not yet.  You can, however, use the deprecated UserPassCredentials object to auth and create your ConsumptionManagementClient to work with the budgets.

Thanks,

Murray

**Comment by lmazuel** [comment] 2019-03-01 21:27
Thanks @murraybutler for your answer. I'm sorry I wasn't able to help, I was expecting someone from the service team directly to answer and I should have follow-up. My bad.
Closing, since it seems the issue is solved.
Thanks

**Closed by lmazuel** 2019-03-01 21:27 UTC
Labels: Commerce, Consumption, Service Attention
