### ISSUE TITLE
[Perf framework] Text proxy support fails gzip decompress

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#19394] opened 2021-06-22 20:15 UTC
Responses that use gzip decompression are failing with the test-proxy returned recorded responses.
This can be repro-ed with the Translator tests:
https://github.com/Azure/azure-sdk-for-python/pull/19317

Behaviour is the same for both sync and async.
`Exception: Error -3 while decompressing data: incorrect header check`
cc @mikeharder

**Comment by scbedd** [comment] 2021-06-23 20:47
Hey @annatisch someone else hit this too! I'll bump pri on this and see if I can get it fixed this afternoon. FYI for test-proxy issues please feel free to CC me. If it's within the core of the test-proxy I'm definitely on call to fix it!

Duplicate of Azure/azure-sdk-tools#1670

**Closed** 2021-06-29 21:53 UTC
Labels: Central-EngSys, Client, Performance
