### ISSUE TITLE
VERY slow large blob downloads

### ISSUE THREAD

**Issue by argonaut76** [Azure/azure-sdk-for-python#10572] opened 2020-03-30 23:13 UTC
I am confused about how to optimize BlobClient for downloading large blobs (up to 100 GB). 

For example, on a ~480 MB blob the following code takes around 4 minutes to execute:

```
full_path_to_file = '{}/{}'.format(staging_path,blob_name)
blob = BlobClient.from_connection_string(conn_str=connection_string, container_name=container_name, blob_name=blob_name)
with open(full_path_to_file, "wb") as my_blob:
    download_stream = blob.download_blob()
    result = my_blob.write(download_stream.readall())
```
In the previous version of the SDK I was able to specify a max_connections parameter that sped download significantly. This appears to have been removed (along with progress callbacks, which is annoying). I have files upwards of 99 GB which will take almost 13 hours to download at this rate, whereas I used to be able to download similar files in under two hours.

How can I optimize the download of large blobs?

Thank you!

Edit: I meant that it took 4 minutes to download a 480 megabyte file. Also, I am getting memory errors when trying to download larger files (~40 GB).

**Comment by kaerm** [comment] 2020-03-31 17:27
@argonaut76 thanks for reaching out to us, I am tagging the right team to take a look at this @xgithubtriage

**Comment by argonaut76** [comment] 2020-03-31 17:56
Thanks, @kaerm. After some digging in the docs I switched over to readinto:

`
for blob_name in blob_names:
    full_path_to_file = '{}/{}'.format(staging_path,blob_name)
    blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)
    with open(full_path_to_file, "wb") as fp:
        blob_client.download_blob().readinto(fp)
` 

Which seems to have helped a bit with the speed, and resolved the memory error. However, speeds are still slow and the downloads now hang periodically. For instance, I've been stuck at 1.6 GB on a 44 GB file for over a half hour.

**Comment by xiafu-msft** [comment] 2020-03-31 20:17
Hi @argonaut76 

Thanks for reaching out!
The parameter max_connections is renamed to max_concurrency please try again with that parameter!

**Comment by argonaut76** [comment] 2020-03-31 20:31
Thanks, @xiafu-msft. A few questions:

1. Where is max_connections set? 
2. How do I go about setting a good value? Is it based on available threads?
3. Will setting this parameter fix the hanging issues?

**Comment by mockodin** [comment] 2020-04-05 02:31
I experienced timeouts on larger downloads as well >100GB commonly and >200GB would always fail, when using .readall(), more on that below. Of note, max_concurrency did NOT resolve this for me. For me it seems that the Auth header timestamp got older than the accepted 25 minute age limit. So the client isn't updating the header automatically. I was able to work around it, in a ugly manner. 

1. Download in 1GB Range-Based Chunking
      download_blob(offset=start, length=end).download_to_stream(MemBlob, max_concurrency=12)
2. Overwrite the retry settings, BlobServiceClient.from_connection_string(<here>), immediately fail (might be the cause of the timeout to begin with)
3. Validate the segment size is the size received
4. If an exception is thrown or the segment not the expected size (last segment will be almost always be smaller of course) then reauth and retry the last segment again

Rinse and repeat till the download completes. Note I build a checksum as I download since I know the checksum of the original file so I have high confidence of file integrity and validate at the end.
Performance wise on a 1Gbps link for a single blob out of cool storage I get ~430Mbps / 53.75MB/s. Azure side cool tier is 60MB/s limit or there about so it seems to work pretty well.

**Comment by xiafu-msft** [comment] 2020-04-06 19:23
Hi @mockodin 
Thanks for your workaround!
I guess setting read_timeout="a large number in second" when you initiate BlobServiceClient or BlobClient would help! Current the read_timeout is default to 2000. Also setting max_concurrency would help to increase the speed probably. While we found some place we want to optimize for download.. sorry about the inconvenience..

**Comment by xiafu-msft** [comment] 2020-04-06 19:27
Hi @argonaut76 

1. blob_client.download_blob(max_concurrency=3).readinto()
2. Currently we don't have a recommended value, probably you can try 5 first and see if it help?
3. I think set read_timeout="a large number in second" when you initiate BlobServiceClient or BlobClient. eg.BlobClient(account_url, container_name, blob_name, credential, read_timeout=8000)

**Comment by xiafu-msft** [comment] 2020-07-13 19:37
It looks like this issue is resolved? We would close this issue for now. Feel free to reopen it if you still have the problem or have any question!

**Comment by oersted** [comment] 2020-12-08 16:27
I'm still definitely experiencing this issue with `azure-storage-blob==12.6.0`, the symptoms are exactly the same as described above: most large downloads getting stuck and eventually crashing with an exception.

I haven't tried the workarounds suggested above just yet, but the issue is clearly not resolved and it makes it rather unusable in a production setting. I would suggest reopening the issue.

**Comment by xiafu-msft** [comment] 2020-12-08 23:34
Hi @oersted 

Thanks for reaching out. we've reopened the issue.
May I know the 
1. size of blob you are trying to download
2. when did the crash happens (eg. 15min after you started download)
3. your network speed

So I can try to reproduce this

**Comment by ivanst0** [comment] 2020-12-09 09:16
I've also seen `socket.timeout: The read operation timed out` error happening intermittently over last few months. The last failure happened yesterday while downloading a relatively small block blob (7 MB). This was part of a DevOps pipeline executing on a Microsoft-hosted build agent. I don't have exact timing as the pipeline step downloads multiple blobs. It seems that even blobs which were retrieved successfully were downloading much slower than usual (downloading all the blobs usually takes about 3 min, this time the exception occurred 50 min after download start).

**Comment by robertdavidrowland** [comment] 2020-12-09 23:10
This morning I had trouble pulling 0.8GB files.   The code appeared to be hanging with no response leaving a 0 byte file on disk.  I was  using:

```
download_file.write(blob_client.download_blob().readall())
```

After reading the comments in the thread from April I switched this to:

```
blob_client.download_blob(max_concurrency=10).readinto(download_file)
``` 

For good measure I set `read_timeout=7200` on the BlobServiceClient (from which I get the BlobClient).

Files are now taking ~1 minutes each to download which is fine for our purposes.

**Comment by oersted** [comment] 2020-12-15 11:14
@xiafu-msft Apologies for the late response. Actually, it looks like the symptom is not exactly the same. The download hangs right at the end, but checking the file size reveals that the full file was downloaded, the `readinto` function just doesn't return for larger files.

I am running some experiments to verify that the issue is not in my code and to provide you with file sizes where it happens / doesn't happen.

**Comment by oersted** [comment] 2020-12-15 11:34
I have verified that it is indeed not my code, I have simplified the execution as much as possible to isolate the issue.

```
    container, blob = source_path[len('az://'):].split('/', 1)
    blob = BlobClient.from_connection_string(conn_str=conn_str, container_name=container, blob_name=blob)
    download_stream = blob.download_blob(max_concurrency=DOWNLOAD_THREADS)

    try:
        os.makedirs(os.path.dirname(target_path))
    except FileExistsError:
        pass

    with open(target_path, 'wb') as target_file:
        download_stream.readinto(target_file)
```

In terms of file sizes:

- 21MB -> Not stuck
- 61MB -> Not stuck
- 43GB -> Stuck

Again, the download gets stuck right at the end. The full file is downloaded but `readinto` does not return.

**Comment by Vasi-Shche** [comment] 2020-12-22 15:01
@mockodin 
> Performance wise on a 1Gbps link for a single blob out of cool storage I get ~430Mbps / 53.75MB/s. Azure side cool tier is 60MB/s limit or there about so it seems to work pretty well.

Where did you get 60MB/s limit for cool tier? I don't see such numbers in the docs:
https://docs.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account
https://docs.microsoft.com/en-us/azure/storage/blobs/scalability-targets

Blob download speed seems to be limited by block size, number of threads and network.

**Comment by mockodin** [comment] 2020-12-24 16:45
This was from an older documentation (which did not specifically state cool as I recall) and appears to have been removed with newer tiers options.

a segment of the old doc from ~2016: https://github.com/uglide/azure-content/blob/master/includes/azure-storage-limits.md
a reference to it being removed and why: https://github.com/MicrosoftDocs/azure-docs/issues/27901

An updated doc on performance doesn't appear to be available at present, at least I didn't find it in a few minutes of searching. Presumably one exists somewhere, if for no other reason than that the backend would not be infinite for a single blob, it exists somewhere on a shared array of disk and to not throttle would be unmanageable at scale (cache and load balancers only take you so far)

A note too that most of the high speed data out there relates specifically to chunked parallel writes, or for super high speed (in either direction) a file being spread across multiple blobs to achieve those multi-10s-of-Gbps numbers that get referenced which is impressive and certainly achievable but not practical for many (most?) use cases.

Looking at Azure Files gives a fairly good guide to performance since that is blob storage on that backend.

**Comment by u-ashish** [comment] 2021-04-07 20:20
Hi @xiafu-msft 

This is still a problem, I'm running into the same issue on a roughly 41GB file.
```
azure_storage = BlobServiceClient(
    account_name=AZURE_ACCOUNT_NAME,
    account_key=AZURE_ACCOUNT_KEY,
    account_url=ACCOUNT_URL,
    credential=AZURE_ACCOUNT_KEY,
    max_chunk_get_size=TRANSFER_CHUNK_SIZE,
    max_single_get_size=TRANSFER_CHUNK_SIZE,
    read_timeout=36000
)

container_client = azure_storage.get_container_client(
        container_name
)

for blob in container_client.list_blobs():
    blob_client = azure_storage.get_blob_client(
            container=container_name,
            blob=blob.name
     )
     data = blob_client.download_blob(max_concurrency=6)
     for chunk in data.chunks():
         # do stuff with each chunk
```

This works on < 500MB files fine, but with a 41GB file it has a similar exception to the original author:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_download.py", line 47, in process_content
    content = b"".join(list(data))
  File "/usr/local/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 118, in __next__
    chunk = next(self.iter_content_func)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

I thought setting `read_timeout` in the `BlobServiceClient` would help but this exception happened after 30 minutes of the process running. Is the timeout not being respected?

**Comment by u-ashish** [comment] 2021-04-08 17:58
I also tried the following things which did not help

- Tried to set a custom `timeout` during `download_blob` i.e.
```
data = blob_client.download_blob(
    max_concurrency=20,
    timeout=72000
)
```

- Tried to play with lower or higher chunk sizes from `4MB` all the way to `100MB`, no dice.

It seems to be happening on large (10GB+ files) but feels guaranteed to happen on something greater than 20GB, from my fiddling.

**Comment by xiafu-msft** [comment] 2021-04-09 17:53
Hi @u-ashish 
Thanks for the feedback! It seems we found the problem and we are working on the fix and get back to you soon! sorry about the inconvenience

**Comment by u-ashish** [comment] 2021-04-12 15:15
@xiafu-msft thanks so much for getting back to me -- that makes perfect sense. I'll keep an eye out for any related PRs.

**Comment by amishra-dev** [comment] 2021-08-04 22:07
The fix has been merged.

**Closed by amishra-dev** 2021-08-04 22:07 UTC
Labels: Client, Service Attention, Storage, bug, customer-reported

**Comment by tsw025** [comment] 2021-09-02 19:49
Hi I'm kind of  the same issue, as per my understanding it takes about 2hrs to complete a 1.2GB record as of current stable release 12.8.1

`    async def download_file(self) -> bool:
        try:
            blob_service_client = BlobClient.from_connection_string(
                conn_str=""
                container_name=CONTAINERNAME, blob_name=BLOBNAME)
            async with blob_service_client:
                stream = await blob_service_client.download_blob(max_concurrency=20)
                st = time.time()
                async for chunk in stream.chunks():
                    encoded = str(chunk, 'utf-8')
                    print ("Size of chunk: {}".format(len(encoded)))
                    print ("Processing chunk: time taken: {}".format(time.time() - st))
                    with open(LOCALFILENAME, "a+") as file:
                        file.write(encoded)
                    st = time.time()
        except Exception as e:
            raise WatchlistBucketDataDownloadFailure(str(e))
`
Size in Bytes:

> Size of chunk: 4194304
> Processing chunk: time taken: 33.31716775894165
> Size of chunk: 4194304
> Processing chunk: time taken: 36.29805946350098
> Size of chunk: 4194304
> Processing chunk: time taken: 36.34725785255432
> Size of chunk: 4194304
> Processing chunk: time taken: 28.56964635848999
> Size of chunk: 4194304
> Processing chunk: time taken: 33.63842010498047
> Size of chunk: 4194304
> Processing chunk: time taken: 30.97656750679016
> Size of chunk: 4194304
> Processing chunk: time taken: 33.94185709953308
> Size of chunk: 4194304
> Processing chunk: time taken: 32.79628658294678
> Size of chunk: 4194304
> Processing chunk: time taken: 26.248417854309082
> Size of chunk: 4194304

Any suggestion would be helpful.

**Comment by delahondes** [comment] 2022-08-22 21:40
Building on @mockodin fine remarks I implemented a file like object on top of blob object, and I was very successful (it does not the reauth trick he mentionned because I did not need that), the downloading speed was enhanced maybe ten times when using this iterator vs the one included in the SDK, many thanks to you, @mockodin !

```python
class ObjectFile:
    """An ObjectFile in object storage that can be opened and closed.
    See Objects.open()"""
    def __init__(self, name, client,mode, size):
        """Initialize the Object object with a name and a blob_client
        mode is w or r, size is the blob size.
        """
        self.name = name
        self.client = client
        self.block_list = []
        self.mode=mode
        self.__open__=True
        if mode=='r':
            self.write = forbid('write', 'r')
        elif mode=='w':
            self.__iter__ = forbid('__iter__', 'w')
            self.read = forbid('read', 'w')
        self.pos = 0
        self.size = size


    def write(self, chunk):
        """Write a chunk of data (a part of the data) into the object"""
        block_id = str(uuid.uuid4())
        self.client.stage_block(block_id=block_id, data=chunk)
        self.block_list.append(BlobBlock(block_id=block_id))
    
    def close(self):
        """Finalise the object"""
        if self.mode=='w':
            self.client.commit_block_list(self.block_list)
        self.__open__=False

    def __del__(self):
        if self.__open__:
            self.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.__open__:
            self.close()

    def __iter__(self):
        self.pos=0

        #stream = self.client.download_blob(max_concurrency=10)
        return self

    def __next__(self):
        data = BytesIO()
        if self.pos>=self.size:
            raise StopIteration()
        elif self.pos+CHUNK_SIZE>self.size:
            size=self.size-self.pos
        else:
            size=CHUNK_SIZE
        self.client.download_blob(offset=self.pos, length=size
            ).download_to_stream(data, max_concurrency=12)
        self.pos += size
        return data.getvalue()
        
    def read(self, size=None):
        if size is None:
            return self.client.download_blob().readall()
        else:
            if self.pos>=self.size:
                return ''
            elif self.pos+size>self.size:
                size=self.size-self.pos
            data = BytesIO()
            self.client.download_blob(offset=self.pos, length=size
                ).download_to_stream(data, max_concurrency=12)
            self.pos += size
            return data.getvalue()
```
