### ISSUE TITLE
[breaking change detector] distinguish `Enum` and `Model` in changelog

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#37171] opened 2024-09-02 02:55 UTC
SDK models can be divided into two big kinds: `Model` and `Enum` so we would like them to be distinguished in changelog. For example:
for https://github.com/azure-sdk/azure-sdk-for-python/pull/8279, the changelog is:
![image](https://github.com/user-attachments/assets/7f94949c-374d-4c87-8a66-e082becf7034)

Some models (e.g. CloudNativeType) are actually Enum:
![image](https://github.com/user-attachments/assets/562d89c0-7e26-4e3f-8f41-6f054c00af1b)

nit: base class of `enum` in generated SDK` is always `str, Enum` which is easy to use to distinguish with Model.

**Comment by catalinaperalta** [comment] 2024-09-04 01:56
This is a duplicate of: https://github.com/Azure/azure-sdk-for-python/issues/36082. Closing in favor of the other issue. I'll pick this item up next.

**Closed by catalinaperalta** 2024-09-04 01:56 UTC
Labels: breaking-changes-tool
