### ISSUE TITLE
ARM resources list operation not returning the properties.

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-sdk-for-python#1143] opened 2017-05-04 10:24 UTC
Hi,

I am using the [list operation with "filter" parameter ](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.resources.v2016_09_01.operations.html#azure.mgmt.resource.resources.v2016_09_01.operations.ResourcesOperations.list)to list all the resources. The result list not returning the properties of the resources. 

Please help me on this.

Als, please let us know how to use expand parameters in the list method.

Thanks,
Vikram

**Comment by lmazuel** [comment] 2017-05-04 15:45
Hi @VikramAIS 

This is a duplicate of this issue: https://github.com/Azure/azure-sdk-for-python/issues/1127
I will answer in that issue asap, but currently all the available time is focused on //build/ ... :(

**Closed by lmazuel** 2017-05-04 15:46 UTC
