### ISSUE TITLE
[API Management Management] Python SDK ocumentation not accurate for export_api

### ISSUE THREAD

**Issue by Dvgz65** [Azure/azure-sdk-for-python#16452] opened 2021-02-01 18:09 UTC
- **Package Name**:  azure.mgmt.apimanagement
- **Package Version**: 1.0.0
- **Operating System**: Linux
- **Python Version**:  3.8

**Describe the bug**
Customer Reported the following:

The class ApiExportOperations the get method is supposed to return an Object of type APIExportResult with 3 properties 
azure.mgmt.apimanagement.models.ApiExportResult 

**id (str)** – ResourceId of the API which was exported.

**export_result_format** (str or ExportResultFormat) – Format in which the Api Details are exported to the Storage Blob with Sas Key valid for 5 minutes. Possible values include: “swagger-link-json”, “wsdl- link+xml”, “wadl-link-json”, “openapi-link”.

**value** (ApiExportResultValue) – The object defining the schema of the exported Api Detail.

After running a script we are seeing that export and value properties are reported with none value 

{'additional_properties': {'properties': {'format': 'openapi-link', 'value': {'link': 'https://apimstu9tjyndpsbrohlr2pk.blob.core.windows.net/api-export/Echo API.yaml?sv=2017-04-17&sr=b&sig=v0OaBgcE6sFwK55iRFufdBv78dO3mnH95pbxD%2BlrvEc%3D&se=2021-02-01T18:08:59Z&sp=r'}}, 'type': 'Microsoft.ApiManagement/service/apis', 'name': 'echo-api'}, 'id': '/subscriptions/<subsID>/resourceGroups/apimanagement/providers/Microsoft.ApiManagement/service/devasqu2apim/apis/echo-api', **'export_result_format': None, 'value': None**}

Instead, there is an additional_properties field which contains the information require when running the export. 
Complain is why this additional properties is not mentioned in the docs anywhere.

**To Reproduce**
Create a script to call 

result = ApiManagementClient(credentials,subsid).api_export.get(rg, api_service,api, ExportFormat.OPENAPI, ExportApi.TRUE)

**Expected behavior**
We expect to see the export_result_format and value fields with the correct data as it is supposed to be, if this is a bug, then add the additional_properties to the documentation. 

**Screenshots**

**Additional context**

**Comment by bala-muthugurusamy-by** [comment] 2021-02-01 19:13
Thanks @Dvgz65 

The `additional_properties` property  has  not been documented as well

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-apimanagement/1.0.0/azure.mgmt.apimanagement.models.html#azure.mgmt.apimanagement.models.ApiExportResult

https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-apimanagement/1.0.0/azure.mgmt.apimanagement.models.html#azure.mgmt.apimanagement.models.ApiExportResultValue

**Comment by 00Kai0** [comment] 2021-02-03 07:29
Hi @Dvgz65 , thanks for your report. I got this issue:
![image](https://user-images.githubusercontent.com/26342317/106712348-c89c8c00-6633-11eb-978f-3c373fde1a07.png)
And this `additional_properties` is in [base model](https://github.com/Azure/msrest-for-python/blob/master/msrest/serialization.py#L182). It will not be shown in document.

The problem is that the API does not return the fields defined by the model.
It will be fixed in next version :)

**Comment by 00Kai0** [comment] 2021-02-03 07:31
And @Dvgz65 please delete the screenshot you show. It exposes the secret, there is a risk of leakage。

**Comment by Dvgz65** [comment] 2021-02-04 23:24
@00Kai0  Do you know if in other SDKs this behavior is the same or this is only specific for Python?

**Comment by Dvgz65** [comment] 2021-03-09 18:09
@00Kai0 
I would like to know if there has been any progress on the investigation/resolution of this issue.

**Closed** 2021-12-22 10:05 UTC
Labels: question, API Management, Mgmt, customer-reported, issue-addressed
