### ISSUE TITLE
[Eventhub] test_receive.py AMQPOverWebsocket timing issues

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-for-python#24470] opened 2022-05-17 00:05 UTC
Async version of this test is performing correctly. With the sync version, when running in the _connection.py listen() function it is taking a really long time to read and process the incoming frames. This is causing the assertion to fail for this test in the pipeline. Investigate why this test is taking so long to run. 

Potential Eventhub Latency eror?

**Comment by kashifkhan** [comment] 2022-05-17 18:27
We are seeing an issue when using `AmpqOverWebsocket` sync while trying to receive events. There is a significant delay getting events compared to the same call when using `Amqp`. This call `data = self.ws.recv()` in _read `_transport.py` is where things are slow if there are fewer frames available than the max of 300. As the number of frames cross that things resume at normal speed

**Steps to reproduce**
* The branch with websockets is located [here](https://github.com/azure/azure-sdk-for-python/tree/feature/eventhub/pyproto) which has pyamqp with websocket support
* Create a brand new EH using `test-resources.ps1`
* Using the `send.py` and `recv.py` under `sync_samples` folder to populate the EH
* Set the `transport_type` for the `consumer_client` by passing in the kwarg `transport_type=TransportType.AmqpOverWebsocket` in to `from_connection_string`
* At this point when this sample is run, there should be the delay when receiving events. If the `transport_type` is set to `TransportType.Amqp` it will work as expected.

**Comment by l0lawrence** [comment] 2022-05-17 22:28
prefetch in consumerclient on the sync side works over AmqpOverWebsocket, adding in prefetch also fixes the connection not closing issue.

**Comment by kashifkhan** [comment] 2022-07-08 20:58
This issue was due to the websockets code throw a `WebSocketException` exception which was not being handled. This resulted in the messaging loop continuously asking for new messages from EH and ultimately timing out making it look like a time delay. Async looked like it was working fine because the coroutines would fire and finish in the background but would ultimately hang as well just like sync. It has been fixed in pyamqp

**Closed by kashifkhan** 2022-07-08 20:58 UTC
Labels: Event Hubs, Messaging, AMQP Python
