### ISSUE TITLE
Aio clients don't honor session_owner with shared transport

### ISSUE THREAD

**Issue by bhperry** [Azure/azure-sdk-for-python#33810] opened 2024-01-11 21:30 UTC
- **Package Name**: All azure aio clients, using `azure-storage-blob` in this example
- **Package Version**: 
azure-common                       1.1.28
azure-core                         1.29.6
azure-mgmt-core                    1.4.0
azure-storage-blob                 12.19.0

- **Operating System**: ubuntu
- **Python Version**: 3.8.18

**Describe the bug**

When creating a client with a shared transport, the official [example](https://github.com/Azure/azure-sdk-for-python/blob/623cec06ee8a4ae18fb86a7d5f0086811c77664c/sdk/core/azure-core/samples/example_shared_transport_async.py#L60) (and [blog post](https://devblogs.microsoft.com/azure-sdk/transport-sharing-in-azure-sdk-for-python/)) indicate that you should pass `shared_owner=False` into the client to prevent the transport from being closed. However when using it in this way, the transport's session is closed after the first client is closed. I see that there is a session_owner kwarg for `AioHttpTransport` which would prevent closing the session from the clients, guessing that might be the correct place to set this value.

As far as I can tell, the aio clients don't do anything at all with the `session_owner` kwarg, so the example is misleading.

**To Reproduce**
```
async def shared_transport_async_with_pooling():
    conn = aiohttp.TCPConnector(limit=100)
    session = aiohttp.ClientSession(connector=conn)
    shared_transport = AioHttpTransport(session=session)
    async with shared_transport:
        # Succeeds
        async with BlobServiceClient.from_connection_string(
            connection_string, transport=shared_transport, session_owner=False
        ) as client:
            containers1 = client.list_containers()
            async for contain in containers1:
                print(contain.name)

        # Fails
        async with BlobServiceClient.from_connection_string(
            connection_string, transport=shared_transport, session_owner=False
        ) as client:
            containers2 = client.list_containers()
            async for contain in containers2:
                print(contain.name)
```

**Expected behavior**

Not entirely clear to me what the correct behavior should be. Possibly the answer is to not use the clients as context managers when using a shared transport. Either way, the examples should be updated to use the `session_owner` kwarg correctly so as to not be misleading.

**Comment by xiangyan99** [comment] 2024-01-11 22:33
Thanks for reporting the issue.

Yes. session_owner should be set for the AioHttpTransport rather than the client.

Can you try this?

```py
async def shared_transport_async_with_pooling():
    conn = aiohttp.TCPConnector(limit=100)
    session = aiohttp.ClientSession(connector=conn)
    shared_transport = AioHttpTransport(session=session, session_owner=False)
    async with shared_transport:
        # Succeeds
        async with BlobServiceClient.from_connection_string(
            connection_string, transport=shared_transport
        ) as client:
            containers1 = client.list_containers()
            async for contain in containers1:
                print(contain.name)

        # Fails
        async with BlobServiceClient.from_connection_string(
            connection_string, transport=shared_transport
        ) as client:
            containers2 = client.list_containers()
            async for contain in containers2:
                print(contain.name)
```

Sorry for the confusion.

**Comment by bhperry** [comment] 2024-01-11 22:45
Hi @xiangyan99, yes I've switched to settings `session_owner=False` on the transport and that works. Although I believe in the example you've shown `async with shared_transport` will not actually close the session, because now the transport is not the owner of the session.

Currently using my own parent `close` method and explicitly closing both `shared_transport` and `shared_transport.session` in order to get around that.

**Comment by xiangyan99** [comment] 2024-01-11 23:08
Thanks for the feedback.

Yes. It is by design that if you want to share the transport, you own the lifecycle of the transport and IOW, you need to handle the closing of the session.

In your case, shared_transport. close() is still called, just it does not close the session when its close method is called.

I will update the sample.

Thanks.

**Comment by bhperry** [comment] 2024-01-11 23:35
Ok great, thanks for clarifying

**Closed** 2024-01-11 23:35 UTC
Labels: Storage, question, Client, customer-reported, issue-addressed
