### ISSUE TITLE
[Ignite] [blob] authentication code in blob storage README does not work

### ISSUE THREAD

**Issue by jhuseman** [Azure/azure-sdk-for-python#8496] opened 2019-11-07 16:13 UTC
The authentication code specified in the [python blobs client library](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob#types-of-credentials) for generating a SAS token seems to not be working properly.
Here is the exact code that is failing (with my account credentials removed):
```python
#%% import modules
from datetime import datetime, timedelta
from azure.storage.blob import BlobServiceClient, generate_account_sas, ResourceTypes, AccountSasPermissions

#%% set credentials - substitute with your relevant credentials
credentials={
	"account_name":"<storage-account-name>",
	"account_key":"<account-access-key>"
}

#%% make connection to blob service
def get_sas_token(credentials):
	return generate_account_sas(
		account_name=credentials["account_name"],
		account_key=credentials["account_key"],
		resource_types=ResourceTypes(service=True),
		permission=AccountSasPermissions(read=True),
		expiry=datetime.utcnow() + timedelta(hours=1)
	)

blob_service_client = BlobServiceClient(
	account_url="https://{account_name}.blob.core.windows.net".format(
		account_name=credentials["account_name"]
	), 
	credential=get_sas_token(credentials)
)
```
This code returns as expected, but when I later run some code to use the created client, I start to get strange errors:
```python
#%% Create container "books"
container_client = blob_service_client.get_container_client("books")
container_client.create_container()
```
```
Traceback (most recent call last):
  File ".\AzureBlobTest.py", line 39, in <module>
    container_client.create_container()
  File "C:\Python27\lib\site-packages\azure\core\tracing\decorator.py", line 62, in wrapper_use_tracer
    return func(*args, **kwargs) # type: ignore
  File "C:\Python27\lib\site-packages\azure\storage\blob\_container_client.py", line 272, in create_container
    process_storage_error(error)
  File "C:\Python27\lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this resource type.
RequestId:c0f8c1f6-001e-0052-7384-95317c000000
Time:2019-11-07T15:57:08.8292156Z
ErrorCode:AuthorizationResourceTypeMismatch
Error:None
```
Now, if I substitute my authentication code with the following (to use a connection string instead), the rest of my code works perfectly:
```python
#%% make connection to blob service
connection_string = "<connection_string>" # replace with string copied from Azure portal
blob_service_client = BlobServiceClient.from_connection_string(conn_str=connection_string)

#%% Create container "books"
container_client = blob_service_client.get_container_client("books")
container_client.create_container()

#%% Print all names and sizes
for blob in container_client.list_blobs():
	print('{name}:\t{size}'.format(name=blob.name, size=blob.size))
```

**Comment by mayurid** [comment] 2019-11-07 16:18
@rakshith91 please take a look

**Comment by annatisch** [comment] 2019-11-07 17:10
Thanks @jhuseman - I am able to repro the error and am digging into the issue now!
Adding @xiafu-msft as well.

**Comment by annatisch** [comment] 2019-11-07 17:29
Hi again,
I believe this error is related to the mismatch of specified resource and operation.
The SAS is generated for service-level operations, but the operation is on the container level.
In addition to this - the SAS is generated with only read permissions, so you will also need to give it create permissions in order to create the container. Using the following snippet should work:
```
#%% make connection to blob service
def get_sas_token(credentials):
	return generate_account_sas(
		account_name=credentials["account_name"],
		account_key=credentials["account_key"],
		resource_types=ResourceTypes(container=True),
		permission=AccountSasPermissions(read=True, create=True),
		expiry=datetime.utcnow() + timedelta(hours=1)
	)
```
@xiafu-msft , @zezha-msft - can you confirm whether this is the expected behaviour of the SAS generation operation?

**Comment by xiafu-msft** [comment] 2019-11-08 03:23
Hi @annatisch, thanks so much for looking into this!
I think you are right! @jhuseman should set `ResourceTypes` to the correct one(container=True for container level operations) and give the corresponding permission to that resource type.

This form lists the operations(they should have similar name as the sdk API, maybe not exactly the same. Because the listed operations are rest level API name, not sdk level API) and the corresponding resource type and permission required to that operation. 
https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#account-sas-permissions-by-operation

Feel free to tell us if you need any other help!

**Comment by annatisch** [comment] 2019-11-08 17:35
Thanks @xiafu-msft!
This seems to be resolved, so closing for now. Please let us know if you're still encountering errors and I can re-open. :)

**Closed by annatisch** 2019-11-08 17:35 UTC
Labels: Client, Storage, customer-reported
