### ISSUE TITLE
Downloading blob from a storage account using BobClient fails after some time with "The condition specified using HTTP conditional header(s) is not met."

### ISSUE THREAD

**Issue by ewongbb** [Azure/azure-sdk-for-python#16069] opened 2021-01-11 01:55 UTC
- **Package Name**: 
  azure-storage-blob
- **Package Version**: 
  12.6.0
- **Operating System**:
  Windows 8.1

- **Python Version**: 
  Python 3.8.1

**Describe the bug**
With the following code: 

```
import os
from azure.identity import (
    ClientSecretCredential
)

# Import the client object from the Azure library
from azure.storage.blob import BlobClient

t_id = "<tenant_id>"
c_id = "<client_id>"
s_acct = "<storage_account_name>"
s_acct_url = "%s.blob.core.windows.net" % s_acct
sek = "<client_sekret>"

print("+ Setup credentials.")
credential = ClientSecretCredential(t_id, c_id, sek)
print("+ Setup Blob Client")
bobc = BlobClient(s_acct_url, <container_name>, <blob_name>,
                  credential=credential)
print("+ Setup streamer")
ssd = bobc.download_blob()
print("+ Get properties")
print(ssd.get_blob_properties())
```

The download proceeds after a bit then at random times (between 900MB to 1.8GB of a 127GB file),
the script errors with the following:

```
+ Setting up stream
+
+ Download stream:
+    Size: 136365212160
Traceback (most recent call last):
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_download.py", line 192, in _download_chunk
    _, response = self.client.download(
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_generated\operations\_blob_operations.py", line 179, in download
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The condition specified using HTTP conditional hea
der(s) is not met.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "azuredl.py", line 29, in <module>

  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_download.py", line 579, in download_to_stream
    self.readinto(stream)
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_download.py", line 561, in readinto
    downloader.process_chunk(chunk)
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_download.py", line 125, in process_chunk
    chunk_data = self._download_chunk(chunk_start, chunk_end - 1)
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_download.py", line 201, in _download_chunk
    process_storage_error(error)
  File "C:\Program Files\Git\python38\Lib\site-packages\azure\storage\blob\_shared\response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ResourceModifiedError: The condition specified using HTTPconditional header(s) is not met.
RequestId:efd9999c-b01e-015c-4dbb-e72b4e000000
Time:2021-01-11T01:43:31.3886449Z
ErrorCode:ConditionNotMet
Error:None
```

**To Reproduce**
1.  Use code as provided.
2.  Run code via python <script name>.py  

**Expected behavior**
The file should download to the local directory.

I have even tried using the connection string method:
```
#!/bin/env python

import os
from azure.identity import DefaultAzureCredential

# Import the client object from the Azure library
from azure.storage.blob import BlobClient

credential = DefaultAzureCredential()

def get_url(in_storage_acct, in_acct_key):
    url_list = ["DefaultEndpointsProtocol=https",
                "AccountName=%s" % in_storage_acct,
                "AccountKey=%s" % in_acct_key,
                "EndpointSuffix=core.windows.net"]
    return ";".join(url_list)


storage_acct = <storage_account_name>
in_key = <storage_key>
container_name = <container_name>
blob_name = <blob_name>

blob_url = get_url(storage_acct, in_key)

# Create the client object using the storage URL and the credential
blob_client = BlobClient.from_connection_string(
    blob_url,
    container_name=container_name,
    blob_name=blob_name)

with open(blob_name, "wb") as my_blob:
        print("+ Setting up stream")
        download_stream = blob_client.download_blob()
        print("+")
        print("+ Download stream:")
        print("+    Size: %d" % download_stream.size)
        download_stream.download_to_stream(my_blob)
        # my_blob.write(download_stream.readall())
```

Still get the same error.

**Comment by xiafu-msft** [comment] 2021-01-11 23:20
Hi @ewongbb

Thanks for reaching out. 
We checked service log and confirmed the error description is "The blob last modification time does not match."
We will look into SDK could and see what the problem is.

Thanks for your patience!

**Comment by xiafu-msft** [comment] 2021-01-11 23:46
Hi @ewongbb 

it looks like during the download process your blob is modified, can you double check to see if this caused the error?

**Comment by ewongbb** [comment] 2021-01-12 00:43
I think I see what the issue is,  and yeah.  I'm an idiot.  Just realized that the blob was being updated every so often and would co-incide with the downloading.   Thanks @xiafu-msft !  I thought I was going crazy or something.

**Comment by tasherif-msft** [comment] 2021-01-19 06:55
Hi @ewongbb, it appears this issue has been resolved, I will close this issue in the meantime. Let us know if anything else is needed.

**Closed by tasherif-msft** 2021-01-19 06:55 UTC
Labels: Client, Storage, customer-reported, needs-team-attention, question
