### ISSUE TITLE
Implement secure token cache with platform APIs (Win, Mac, Linux) for azure.identity

### ISSUE THREAD

**Issue by MIchaelMainer** [Azure/azure-sdk-for-python#13189] opened 2020-08-18 17:30 UTC
**Is your feature request related to a problem? Please describe.**
Token cache for azure.identity is in plain text file. Token cache should be stored in platform secure store.

**Describe the solution you'd like**
https://github.com/microsoftgraph/msgraph-cli/pull/8/files#diff-39e48daaa73b67cd3d41a272766dbb71R48
I'd like for this to be included in azure.identity instead of a custom InteractiveBrowserCredential.

**Describe alternatives you've considered**
Created a custom InteractiveBrowserCredential that uses encrypted token cache. 

**Additional context**
https://github.com/microsoftgraph/msgraph-cli/issues/9
https://github.com/microsoftgraph/msgraph-cli/pull/8

**Comment by chlowell** [comment] 2020-08-18 17:59
Which file are you referring to? In azure-identity stable releases (1.4.0 is the latest) `InteractiveBrowserCredential` caches only in memory--it doesn't write anything to disk. Recent beta versions of `InteractiveBrowserCredential` optionally use a persistent cache, but that cache is encrypted by default.

**Comment by MIchaelMainer** [comment] 2020-08-20 16:16
This is excellent news! We are using InteractiveBrowserCredential for Microsoft Graph CLI. We implemented a custom InteractiveBrowserCredential with persistent cache using the different platform encryption APIs. Ideally we don't do this and depend on InteractiveBrowserCredential for this. 

Can you point us at the branch that contains your updated InteractiveBrowserCredential?
Where is the released beta that contains this? I see 1.4 and its previous beta.
When do you expect to release this out of beta into production?

cc: @jobala

**Comment by chlowell** [comment] 2020-08-20 17:23
The code is on our master branch. It's the same as in 1.4.0b7 and will be released again in 1.5.0b1 early next month. We're aiming for a stable release in November. We removed the feature from 1.4.0 because we want to add more configuration. The API won't change in the next release though, so here's how it works in 1.4.0b7 and the upcoming 1.5.0b1. You can enable persistent caching with a keyword argument: `InteractiveBrowserCredential(enable_persistent_cache=True)`. The cache is implemented by [msal-extensions](https://github.com/AzureAD/microsoft-authentication-extensions-for-python), encrypted by default, and supported on Windows, macOS, and Linux. The Linux implementation encrypts with libsecret through [PyGObject](https://pypi.org/project/PyGObject/). Because those dependencies aren't available everywhere, we added another argument for opting in to an unencrypted fallback when they aren't present:
`InteractiveBrowserCredential(enable_persistent_cache=True, allow_unencrypted_cache=True)`. With that configuration the credential attempts to use an encrypted cache and falls back to plaintext if encryption isn't possible.

How does your custom credential protect the cache on Linux?

**Comment by MIchaelMainer** [comment] 2020-08-31 15:19
@jobala Finds that cache isn't working as expected and the user has to authenticate on every call. Japheth, can you provide more information including a repro?

**Comment by jobala** [comment] 2020-09-01 16:34
Thanks for @MIchaelMainer for re-openning this issue

## Steps To Reproduce
1. Create a credential object
```python
credential = InteractiveBrowserCredential(enable_persistent_cache=True)
```
2. Call authenticate on the credential object
```python
credential.authenticate(scopes=scopes)
```
3. Call `get_token` on the credential object, note that the user is prompted to login again.

**Comment by chlowell** [comment] 2020-09-02 01:07
Which version of azure-identity are you using?

**Comment by chlowell** [comment] 2020-09-03 00:33
This works as expected in the cases I've tried, so I need to know more about yours 😃

Can you share the value of `scopes` you're passing to `authenticate`? Do you see the same behavior in an ordinary case like this:
```py
SCOPE = "https://vault.azure.net/.default"
credential = InteractiveBrowserCredential(enable_persistent_cache=True)
credential.authenticate(scopes=[SCOPE])
credential.get_token(SCOPE)
```

**Comment by jobala** [comment] 2020-09-03 08:21
Ah I see, I was passing different scopes int `authenticate` and `get_token`

**Comment by jobala** [comment] 2020-09-03 16:48
Ah I see, can you try the following
1. Open a python shell
2. Authenticate
3. Exit shell
4. Open shell again
5. Get token

Observe that you are prompted to log in when you call `get_token`

**Comment by jobala** [comment] 2020-09-07 08:19
@chlowell did you manage to repro the issue?

**Comment by chlowell** [comment] 2020-09-08 15:25
No, that also works for me. Are you initializing the credential with the `AuthenticationRecord` (returned by `authenticate`) the second time?

If you start with this:
```py
first_credential = InteractiveBrowserCredential(enable_persistent_cache=True)
record = first_credential.authenticate(scopes=[SCOPE])
```

This will prompt again:
```py
second_credential = InteractiveBrowserCredential(enable_persistent_cache=True)
second_credential.get_token(SCOPE)
```

But this will not:
```py
second_credential = InteractiveBrowserCredential(enable_persistent_cache=True, authentication_record=record)
second_credential.get_token(SCOPE)
```
The cache may contain data from any number of users. The `AuthenticationRecord` tells the credential which user to authenticate.

**Comment by jobala** [comment] 2020-09-15 05:22
@chlowell  using **AuthenticationRecord** works as expected. @MIchaelMainer, you  can close this issue at your convenience.

**Closed** 2020-09-15 05:56 UTC
Labels: Azure.Identity, Client, customer-reported, question
