### ISSUE TITLE
[Anomaly Detector] sample_multivariate_detect.py: Ran into a deserialization error

### ISSUE THREAD

**Issue by swazeeer** [Azure/azure-sdk-for-python#18780] opened 2021-05-17 23:36 UTC
running this script creates the following error. key, endpoint url, data source url are all correct.
[sample_multivariate_detect.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/anomalydetector/azure-ai-anomalydetector/samples/sample_multivariate_detect.py)

> Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1501, in failsafe_deserialize
    return self(target_obj, data, content_type=content_type)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\serialization.py", line 1539, in _unpack_content
    return RawDeserializer.deserialize_from_http_generics(
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\pipeline\universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\msrest\pipeline\universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html
Traceback (most recent call last):
  File "C:\Users\NAME\Desktop\anomaly detector\detector.py", line 119, in <module>
    model_id = sample.train(datetime(2021, 1, 1, 0, 0, 0), datetime(2021, 1, 2, 12, 0, 0))
  File "C:\Users\NAME\Desktop\anomaly detector\detector.py", line 27, in train
    model_list = list(self.ad_client.list_multivariate_model(skip=0, top=10000))
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\ai\anomalydetector\operations\_anomaly_detector_client_operations.py", line 643, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\NAME\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'Not Found'

**Comment by swathipil** [comment] 2021-05-18 15:01
@swazeeer Thanks for reporting this issue! Directing it to the right people.

**Comment by swazeeer** [comment] 2021-05-18 17:28
[_anomaly_detector_client_operations.py line 571](https://github.com/Azure/azure-sdk-for-python/blob/ef56f999bfc7d35aa5752a335c733b0a3b37fa81/sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/operations/_anomaly_detector_client_operations.py#L571)

**Comment by DavidZeLiang** [comment] 2021-05-19 12:06
@swazeeer Hello, could you please provide your region info of your Instance where you met this error?

**Comment by swazeeer** [comment] 2021-05-19 21:55
Hi @DavidZeLiang , my Instance was located in central Canada. I just created one in West US and the script was able to run successfully. Thanks for your assistance.

**Comment by DavidZeLiang** [comment] 2021-05-20 04:13
@swazeeer Currently we do support multivariate anomaly detection in East US, East US 2, South Central US, UK South, West Europe and West US 2, and will support more regions in the future (so I guess the successful one was on West US 2, not West US).
So the error you got is by design to notify users that MVAD is not supported yet in specific regions. 
@swathipil FYI

**Comment by swathipil** [comment] 2021-05-20 15:27
Hi @swazeeer, it seems that your question has been answered. I'm closing the issue for now. If you have any further questions, please feel free to open the issue again! Thanks!

**Closed by swathipil** 2021-05-20 15:27 UTC
Labels: Cognitive - Anomaly Detector, Service Attention, bug, customer-reported
