### ISSUE TITLE
New version of NetApp module does not work with get_client_from_json_dict

### ISSUE THREAD

**Issue by sschols** [Azure/azure-sdk-for-python#16760] opened 2021-02-16 14:12 UTC
- **Package Name**: azure-mgmt-netapp
- **Package Version**: 1.0.0
- **Operating System**: MacOS 11
- **Python Version**: 3.9

**Describe the bug**
Creating a new NetAppManagementClient via the get_client_from_json_dict function of the client factory fails:
```
  File "/opt/cloud/lnwcloud/operations/azure.py", line 41, in _get_az_client
    client = get_client_from_json_dict(NetAppManagementClient, config_dict)
  File "/opt/cloud/env_linux/lib/python3.9/site-packages/azure/common/client_factory.py", line 171, in get_client_from_json_dict
    return _instantiate_client(client_class, **parameters)
  File "/opt/cloud/env_linux/lib/python3.9/site-packages/azure/common/client_factory.py", line 34, in _instantiate_client
    return client_class(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'credential'
```

**To Reproduce**
1. Create client config JSON
2. run `get_client_from_json_dict(NetAppManagementClient, client_config_dict)`
3. Watch it fail

**Expected behavior**
A NetApp Management Client should be created

**Additional context**

There seem to have been many changes with https://github.com/Azure/azure-sdk-for-python/commit/8fae515f3f795548c6bc7c53f2f93478a6e53fdd#diff-e0ab8e5f8b111235d15c2b525ecdf6a9531826e786d90a30c0a34fa1f1f371e4, including renaming of the `credentials` parameter (https://github.com/Azure/azure-sdk-for-python/commit/8fae515f3f795548c6bc7c53f2f93478a6e53fdd#diff-e0ab8e5f8b111235d15c2b525ecdf6a9531826e786d90a30c0a34fa1f1f371e4R14). The credentials parameter is the one being set by get_client_from_json_dict. This is likely the cause of this

The documentation also seems to not reflect the changes to the `azure.mgmt.netapp` package yet, there is no information on the `NetAppManagementClient` in https://docs.microsoft.com/de-de/python/api/azure-mgmt-netapp/azure.mgmt.netapp, it still refers to the `AzureNetAppFilesManagementClient` implementation.

**Comment by xiangyan99** [comment] 2021-02-16 16:48
Thanks for the feedback, we’ll investigate asap.

**Comment by lmazuel** [comment] 2021-02-16 17:56
Hi @sschols 
This is a duplicate of https://github.com/Azure/azure-sdk-for-python/issues/15075

The new generation of SDK do not support this factory.

**Comment by sschols** [comment] 2021-02-16 18:07
Thanks @lmazuel for the update. Are there any plans on updating the documentation accordingly? When I install the azure-mgmt-netapp module via pip right now, I get the 1.0 (beta?) version, which is not documented in the official SDK docs yet, which is very confusing.

**Comment by lmazuel** [comment] 2021-03-12 23:53
We discussed on our team and concluded we do not want to support the JSON or file factory for security purposes, and we don't want to encourage practices that feel unsecure.
We wrote a migration guide for scenario:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/migration_guide.md

Please let me know any feedback or questions related to this.

**Comment by lmazuel** [comment] 2021-03-12 23:55
@sschols if the documentation is still not accurate, would you mind creating another issue about it? I like to keep issues focuses, since otherwise it ends up with many many different people and the success rate of fixes becomes low.
Thanks!

**Closed** 2021-04-03 08:00 UTC
Labels: Mgmt, Network - Application Gateway, Service Attention, bug, customer-reported, needs-author-feedback, no-recent-activity
