### ISSUE TITLE
BlobServiceClient.get_account_information() failing with ResourceNotFound

### ISSUE THREAD

**Issue by riedgar-ms** [Azure/azure-sdk-for-python#21810] opened 2021-11-18 13:59 UTC
- **azure-storage-blob**: 
- **12.9.0**: 
- **Win11**:
- **3.6.13**: 

**Describe the bug**

I have created a `BlobServiceClient` using `DefaultAzureCredential`, and I can use this to list containers in the storage account. However, when I try to call the `get_account_information()` method it fails with:

```
ResourceNotFoundError: The specified resource does not exist.
RequestId:833b8155-a01e-006b-3183-dc555b000000
Time:2021-11-18T13:50:31.7291603Z
ErrorCode:ResourceNotFound
```

**To Reproduce**

Following was in a Jupyter notebook:
```python
from azure.identity import AzureCliCredential, DefaultAzureCredential

creds = DefaultAzureCredential(exclude_shared_token_cache_credential=True)

bsc = BlobServiceClient(account_url=account_url, credential=creds)

# Following prints out a list of containers
for c in bsc.list_containers():
    print(c['name'])

# Following throws the above ResourceNotFoundError
bsc.get_account_information()
```

**Expected behaviour**

To get back information about the storage account. Or at least an error which makes sense

**Comment by tasherif-msft** [comment] 2021-11-24 21:38
Hi @riedgar-ms this usually means that you don't have the appropriate permissions to be able to get the account info.
What is your role set to for this account you're using? (for example contributor, reader, etc.)

**Comment by riedgar-ms** [comment] 2021-11-25 15:56
On the subscription, I'm at least contributor. And as I note, I was able to list the containers in the storage account using the same client.

**Comment by tasherif-msft** [comment] 2021-12-02 00:46
Could you provide me with a requestId, I'm unable to reproduce this issue.

**Comment by tasherif-msft** [comment] 2021-12-03 23:24
Hi @riedgar-ms looking at your req id it seems the credential being used is an OAuth token. This is an insufficient credential to use this API (please refer to https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information) 
Your credential/default credential needs to be based on either a shared key or an account/service level SAS. So this is by design.
I will proceed to close this issue in the meantime. Feel free to reopen if you need further clarification!

**Closed by tasherif-msft** 2021-12-03 23:24 UTC
Labels: bug, Storage, Client, needs-team-attention

**Comment by riedgar-ms** [comment] 2021-12-04 14:29
If the credential is incorrect, why is the error not a 401 or a 403?
