### ISSUE TITLE
[azure-servicebus] C# Diserialization of message sent from service bus client fails

### ISSUE THREAD

**Issue by mabecke** [Azure/azure-sdk-for-python#7075] opened 2019-09-05 12:51 UTC
Recently we moved from Python 2 to Python 3 and started using azure-servicebus package.
Some of the messages that we publish are consumed by C# SB libraries.
After we moved to azure-servicebus library, the receiver end(C#) receives the following error:

Exception Details
===================================
`Exception Type: System.Runtime.Serialization.SerializationException (AggregateException's InnerException #1 out of 1)
Message: There was an error deserializing the object of type System.String. The input source is not correctly formatted.
Target Site: System.Object ReadObjectHandleExceptions(System.Runtime.Serialization.XmlReaderDelegator, Boolean, System.Runtime.Serialization.DataContractResolver)
Help Link: 
Source: System.Runtime.Serialization
HResult: -2146233076`
 
Stack Trace Details 
-----------------------------------
`
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at Microsoft.ServiceBus.Messaging.DataContractBinarySerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at Microsoft.ServiceBus.Messaging.DataContractBinarySerializer.ReadObject(Stream stream)
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.GetBody[T](XmlObjectSerializer serializer)
   at SomeClass.SomeTopicSubscriber.GetPayloadObjectFromBody(BrokeredMessage msg)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ServiceBusCommon.TopicSubscriber`1.<PerformCallbackActionAndCompleteMessageOnSuccess>d__58.MoveNext()`
`

When searching for the error, we found possible solutions detailed here:

1. https://stackoverflow.com/questions/48338448/sending-message-to-azure-service-bus-as-a-string-using-azure-logic-app
2. https://stackoverflow.com/questions/51420863/service-bus-message-error-deserializing-the-object-of-type-system-string-but-mes

But we'd like to fix this on the sender side

Thanks

**Comment by kaerm** [comment] 2019-09-05 19:13
Thanks @mabecke for reporting this - our team will take a look at it

**Comment by annatisch** [comment] 2019-10-03 21:21
Adding @KieranBrantnerMagee :)

**Comment by KieranBrantnerMagee** [comment] 2019-10-30 19:41
Hey @mabecke; thanks for your patience as we looked into this. 

The long and short of the issue is that the old libraries encoded the message type within the body itself with a specific structure.  Problem being, the c# libs in the links you sent (Assuming you're also using the historical .NET standard Microsoft.servicebus) are quite dated, to the point that finding the corresponding python code to generate the proper schema is nontrivial.  Could I bother to ask you what version of the servicebus library you were using in python2?

In leiu of that, I went down a bit of a rabbit hole and hacked together a workaround for the current py3 libs in the sender vs. the net standard receiver.  Have no illusions, this is an absolute quick-fix,  breaks on strings > ~65000 characters, and probably bears no resemblance to any sort of best practice,  but was the quickest path to "something functional" absent specific version info. (Attempted a handful of historical versions but even as early as .21 the incompatibility was present)

    from struct import pack

    import json

    topic_client = TopicClient.from_connection_string("...")

    body = {'id':42, 'name':"demo"}

    serialized_body = json.dumps(body).encode('utf-8')

    if not serialized_body:

        serialized_body = b'\x00'

    serialized_body_length = pack('I', len(serialized_body)).rstrip(b'\x00')

    serialized_header_length = pack('I', 152 + len(serialized_body_length)).rstrip(b'\x00')

    terminator = b'\x01' if len(serialized_body) > 255 else b''

    payload = b'@\x06string\x083http://schemas.microsoft.com/2003/10/Serialization/' + serialized_header_length + serialized_body_length + serialized_body + terminator

    topic_client.send(Message(payload))


A warning at the risk of stating the obvious: the incompatibility is bidirectional, so if you're sending from the old .net standard libs and receiving with new python libs, you'll potentially run into comparable issues.  I'll also use this "stating-the-obvious" section to recommend upgrading your receiver library if possible, none of these fixes are going to be great, but can understand if that's a constraint.

**Comment by KieranBrantnerMagee** [comment] 2019-11-12 00:25
Closing this given the aforementioned workaround, and suggestion for posterity that if a SDK gap this large is present, the best practice would likely be to update both ends to a recent version.

Feel free to reopen this thread if any issues with the mitigation, any questions, or further aspects of this problem that we can assist with.

**Closed by KieranBrantnerMagee** 2019-11-12 00:25 UTC
Labels: Client, Service Bus, customer-reported
