### ISSUE TITLE
azure-storage-queue 12.6.0 mypy error: Self? has no attribute "receive_message" [attr-defined]

### ISSUE THREAD

**Issue by KevinMarquette** [Azure/azure-sdk-for-python#28960] opened 2023-02-23 11:10 UTC
- **Package Name**: azure-storage-queue
- **Package Version**: 12.6.0
- **Operating System**: Ubuntu
- **Python Version**: 3.9.16

**Describe the bug**
Updating  azure-storage-queue from 12.5.0 to 12.6.0 causes several `attr-defined` mypy errors. This caused several of our CI/CD pipelines to start failing so we reverted back to the previous version.

**To Reproduce**
1. upgrade azure-storage-queue from 12.5.0 to 12.6.0
2. run mypy on this code:
```
from azure.storage.queue import QueueClient

client = QueueClient.from_queue_url("")
client.get_queue_properties()
```
3. Get this error:
```
script.py:4: error: Self? has no attribute "get_queue_properties"  [attr-defined]
            q_info = self._q_client.get_queue_properties()
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Expected behavior**
We expect minor version packages updates like this to not cause mypy errors in our pipelines.

**Screenshots**
Here is an additional log dump showing multiple methods raising validation errors.

```
script.py:58: error: Self? has no attribute "get_queue_properties"  [attr-defined]
            q_info = self._q_client.get_queue_properties()
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
script.py:62: error: Returning Any from function declared to return "QueueProperties"  [no-any-return]
            return q_info
            ^~~~~~~~~~~~~
script.py:76: error: Self? has no attribute "get_queue_properties"  [attr-defined]
            q_info = self._q_client.get_queue_properties()
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
script.py:83: error: Self? has no attribute "receive_message"  [attr-defined]
            q_item = self._q_client.receive_message(visibility_timeout=requeue_time)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
script.py:117: error: Self? has no attribute "send_message"  [attr-defined]
            q_msg = self._q_client.send_message(
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
script.py:148: error: Self? has no attribute "delete_message"  [attr-defined]
            self._q_client.delete_message(q_obj_id, pop_receipt)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Additional context**
current mypy settings defined in `pyproject.toml`:
```
[tool.mypy]
disallow_untyped_defs=true
warn_redundant_casts=true
disallow_untyped_calls=true
warn_return_any=true
warn_unreachable=true
pretty=true
show_error_codes=true
```

**Comment by kashifkhan** [comment] 2023-02-23 14:24
Thank you for the feedback @KevinMarquette . We will investigate and get back to you

**Comment by jalauzon-msft** [comment] 2023-02-24 01:36
Hi @KevinMarquette Kevin, thanks for bringing this to our attention. So, it turns out the MyPy errors are coming from our use of `typing_extensions.Self`. While it has been available in typing extensions for some time, since around Nov 2021, MyPy support for it was not added until recently in version `1.0.0`.

Updating your MyPy version to `>1.0.0` would likely fix the issue but we also realize this version of MyPy was only just released a couple of weeks ago and may come with some changes/breaks. So, if you are able to update your MyPy version that would be one solution but if not, we may also consider patching out the use of `Self` for some period of time while the dust settles on MyPy 1.0. Thanks.

**Comment by KevinMarquette** [comment] 2023-02-24 17:47
I have confirmed that updating MyPy to 1.0.1 resolves this issue for me (without any other side effects). I am happy with that as the solution for my environment. Thank you.

**Comment by jalauzon-msft** [comment] 2023-02-24 22:24
Thanks for confirmed @KevinMarquette. I'll go ahead and close this issue.

**Closed by jalauzon-msft** 2023-02-24 22:24 UTC
Labels: Storage, question, customer-reported
