### ISSUE TITLE
AzureML Managed Identity Auth error

### ISSUE THREAD

**Issue by mas-mreyes** [Azure/azure-sdk-for-python#24898] opened 2022-06-17 17:51 UTC
- **Package Name**: 
- **Package Version**: 
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20220601.v1

ENV AZUREML_CONDA_ENVIRONMENT_PATH /azureml-envs/sklearn-1.0
# Create conda environment
RUN conda create -p $AZUREML_CONDA_ENVIRONMENT_PATH \
    python=3.8 pip=21.3.1 -c anaconda -c conda-forge

# Prepend path to AzureML conda environment
ENV PATH $AZUREML_CONDA_ENVIRONMENT_PATH/bin:$PATH

# Install pip dependencies
RUN pip install 'matplotlib~=3.5.0' \
                'psutil~=5.8.0' \
                'tqdm~=4.62.0' \
                'pandas~=1.3.0' \
                'scipy~=1.7.0' \
                'numpy~=1.21.0' \
                'ipykernel~=6.0' \
                'azureml-core==1.42.0.post1' \
                'azureml-defaults==1.42.0' \
                'azureml-mlflow==1.42.0' \
                'azureml-telemetry==1.42.0' \
                'scikit-learn~=1.0.0'
```
- **Operating System**: Linux
- **Python Version**:  3.8

**Describe the bug**
When trying to run an experiment, and trying to initialize a Workspace Object in order to read from a DataSet on a Compute Cluster, I am getting the following error when trying to use ManagedIdentityAuthentication, even though when using ManagedIdentity inside AzureML Notebooks there is no such error when trying to authenticate.
Error on cluster
<img width="880" alt="image" src="https://user-images.githubusercontent.com/67907777/174349391-177ae32c-eda3-4689-9f3f-fd1481fd8ade.png">
No error on Notebook
<img width="370" alt="image" src="https://user-images.githubusercontent.com/67907777/174351753-0e4f9556-3589-4b6b-99f8-dd79648d8f91.png">

**To Reproduce**
1. Create a Compute Cluster on AzureML
2. Create and assign a User Assigned Managed Identity to Compute Cluster
3. Create a training script which uses Workspace to initialize a workspace object

<img width="326" alt="image" src="https://user-images.githubusercontent.com/67907777/174350289-79bbc98f-164d-431b-9ec4-b355d19d24dc.png">

4. Configure training run to use curated environment **AzureML-sklearn-1.0-ubuntu20.04-py38-cpu**
5. Deploy the training script to the compute cluster

<img width="400" alt="image" src="https://user-images.githubusercontent.com/67907777/174350705-2538a872-06f4-46b1-a890-218592e09d39.png">

**Expected behavior**
It is expected that the Workspace object should authenticate correctly, and allow interacting with instead of crashing.

**Comment by kristapratico** [comment] 2022-06-20 17:29
@azureml-github can you take a look at this issue?

**Comment by v-chhbhoi** [comment] 2022-07-19 14:36
Closing this. Tried to reproduce the issue from given steps but due to the container or other constraints not able to get the exact issue. Please update the details here and feel free to reopen this if it occurs again. Thanks

**Closed** 2022-08-13 08:03 UTC
Labels: bug, Client, customer-reported, no-recent-activity, needs-team-attention, needs-author-feedback, ML-CoreUI, CXP Attention
