### ISSUE TITLE
Login failed for user ''. (18456) while connecting to Azure Sql Database.

### ISSUE THREAD

**Issue by vishveshtrivedi** [Azure/azure-sdk-for-python#29336] opened 2023-03-14 15:58 UTC
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
We are trying to connect to sql database from azure functions. The credentials are stored in keyvault. The error is taking place on the azure portal. We are getting the following error:
Exception: InterfaceError: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user ''. (18456) (SQLDriverConnect)")

Does anyone know how to fix this?

**Expected behavior**
We want to connect to sql database so that we can update it.

**Screenshots**
Result: Failure
                                                                        Exception: InterfaceError: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456) (SQLDriverConnect)")
                                                                        (Background on this error at: https://sqlalche.me/e/14/rvf5)
                                                                        Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 452, in _handle__invocation_request
                                                                            call_result = await self._loop.run_in_executor(
                                                                          File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
                                                                            result = self.fn(*self.args, **self.kwargs)
                                                                          File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 718, in _run_sync_func
                                                                            return ExtensionManager.get_sync_invocation_wrapper(context,
                                                                          File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
                                                                            result = function(**args)
                                                                          File "/home/site/wwwroot/regatta_association/__init__.py", line 32, in main
                                                                            con_out = api.get_azure_db_connection(engine_options = {"fast_executemany": False})
                                                                          File "/home/site/wwwroot/api/database.py", line 97, in get_azure_db_connection
                                                                            with ret.connect() as conn:
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
                                                                            return self._connection_cls(self, close_with_result=close_with_result)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
                                                                            else engine.raw_connection()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
                                                                            return self._wrap_pool_connect(self.pool.connect, _connection)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
                                                                            Connection._handle_dbapi_exception_noconnection(
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
                                                                            util.raise_(
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
                                                                            raise exception
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
                                                                            return fn()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 327, in connect
                                                                            return _ConnectionFairy._checkout(self)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
                                                                            fairy = _ConnectionRecord.checkout(pool)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
                                                                            rec = pool._do_get()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
                                                                            self._dec_overflow()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
                                                                            compat.raise_(
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
                                                                            raise exception
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
                                                                            return self._create_connection()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
                                                                            return _ConnectionRecord(self)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
                                                                            self.__connect()
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
                                                                            pool.logger.debug("Error on connect(): %s", e)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
                                                                            compat.raise_(
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
                                                                            raise exception
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
                                                                            self.dbapi_connection = connection = pool._invoke_creator(self)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/create.py", line 578, in connect
                                                                            return dialect.connect(*cargs, **cparams)
                                                                          File "/home/site/wwwroot/.python_packages/lib/site-packages/sqlalchemy/engine/default.py", line 598, in connect
                                                                            return self.dbapi.connect(*cargs, **cparams)

**Comment by kashifkhan** [comment] 2023-03-14 17:45
Hi @vishveshtrivedi, I just wanted to get some clarity around the issue - Are you having trouble with the keyvault client or some other aspect of the azure function ? 

If its the keyvault client or any other azure clients please fill in the bug report template that shows python version, clients being used, sample repro code so that we can assist you better.

**Comment by vishveshtrivedi** [comment] 2023-03-14 19:29
Hi @kashifkhan,
Actual the thing is I am trying to connect to azure based on the function which we have written in Python.
The basic code is as follows:
con_in = api.get_northstar_connection(secrets_manager := api.SecretsManager())

con_out = api.get_azure_db_connection(engine_options = {"fast_executemany": False})

After that to connect to database we use the following code:

def get_azure_db_connection(db: "str | None" = None, host: "str | None" = None, wait_for_success_attempts: int = 10, *, connection_options: "dict[str, str] | None" = None, engine_options: "dict[str, Any] | None" = None, driver: "str" = "{ODBC Driver 17 for SQL Server}") -> sqlalchemy.engine.Engine:
    """Gets a connection to the Azure database

    Parameters
    ----------
    db : str
        The database to connect to. Defaults to the AZURE_DB_NAME environment variable.
    host : str
        The database server to connect to. Defaults to the AZURE_DB_HOST environment variable.
    wait_for_success_attempts : int
        How many times to retry until a successful connection is established. Each attempt takes up to 30 seconds. 0 means do not wait. Defaults to 10 attempts, or 5 minutes.
    connection_options : dict[str, str]
        See ODBC connection string documentation. Must be supplied as a keyword argument. Default options are {"Encrypt": "yes", "TrustServerCertificate": "no"}
    engine_options : bool | str
        See SQLAlchemy engine creation documentation. Must be supplied as a keyword argument. Default options are {"fast_executemany": True}
	driver : str 
		ODBC driver to use. Defaults to "{ODBC Driver 17 for SQL Server}"
    Returns
    -------
    sqlalchemy.engine.Engine
        The connection engine
    """
    
    if db is None:
        db = os.getenv("AZURE_DB_NAME")
    if host is None:
        host = os.getenv("AZURE_DB_HOST")

    con_options = {"Encrypt": "yes", "TrustServerCertificate": "no", "Authentication": "ActiveDirectoryMsi"}
    if connection_options is not None:
        con_options.update(connection_options)
    con_options_str = ";".join(f"{x[0]}={x[1]}" for x in con_options.items())

    connection_string = f";Driver={driver};Server=tcp:{host};Database={db};Connection Timeout=30;{con_options_str}"
    url = sqlalchemy.engine.URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})

    eng_options = {"fast_executemany": True}
    if engine_options is not None:
        eng_options.update(engine_options)

    ret = sqlalchemy.engine.create_engine(url, **eng_options)

    # Retry for a success
    for i in range(wait_for_success_attempts):
        try:
            with ret.connect() as conn:
                if i != 1:
                    logging.info(f"Connection attempt {i + 1} to {host}/{db} was successful.")
                break
        except Exception:
            raise
            if i + 1 == wait_for_success_attempts:
                logging.error(f"Connection attempt {i + 1} to {host}/{db} failed. All attempts failed.")
            else:
                logging.warn(f"Connection attempt {i + 1} to {host}/{db} failed. Retrying...")
    return ret


AZURE_DB_NAME & AZURE_DB_HOST are the name of environment variables setup on azure portal for the azure function.

azure function can get secrets credential from azure keyvault using system assigned managed identity.

We have setup sql server and sql database on azure portal.

We push the code from local machine to gitlab and from there it connects to azure.

Following are the versions of libraries:
1) azure-identity= 1.12.0
2) azure-functions= 1.11.0
3) azure-keyvault = 4.2.0
4) python = 3.9.7

We had given all the role assignments required to connect to different resources on azure.
After the proper connection following message should come:
Connection attempt 1 to "AZURE_DB_HOST/AZURE_DB_NAME" was successful.

Following is the error on local machine:
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('CE267', "[CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error 12029 opening URL http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F (0) (SQLDriverConnect); [CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error requesting access token, HTTP status -1, expected 200 (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Failed to authenticate the user '' in Active Directory (Authentication option is 'ActiveDirectoryMSI').\r\nError code 0xA190; state 41360\r\n (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258].  (258); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Unable to complete login process due to delay in login response (258)")
(Background on this error at: https://sqlalche.me/e/14/dbapi)

Thanks!!

**Comment by xiangyan99** [comment] 2023-03-14 22:10
Thanks for the information.

I am not quite clear about your scenario.

1. Where do you run the code? in gitlab or in azure function?
2. It seems to me you want to use connection string to access the SQL server, is it correct?

Thank you.

**Comment by vishveshtrivedi** [comment] 2023-03-14 22:18
The code runs on gitlab and from there it is connecting to azure function app.
We are using connection string in our code. Is it necessary to create connection string on azure function app.
For authentication of sql server I am using Azure Active Directory admin option available under settings tab.

Thanks.

**Comment by xiangyan99** [comment] 2023-03-14 22:23
OK. So you are connecting to SQL server from the azure function, not the code running in gitlab?

**Comment by vishveshtrivedi** [comment] 2023-03-14 22:34
Actually the Process is as follow:
I push my code to gitlab.
gitlab has CI/CD pipeline which takes my code and have gitlab runner configured on the azure. From there it invokes azure function which will execute the code and will try to connect to SQL server.

**Comment by xiangyan99** [comment] 2023-03-14 22:45
This is my hypothesis:
You code uses AAD to access key vault and retrieve the connection string.
gitlab runner does not have AAD configured hence it fails to access key vault.

If possible, we can do some experiments:
1. Instead of using key vault to store the connection string, we can use it directly. This experiment can get rid of the AAD part.
2. After getting the connection string, instead of using it to access SQL server, just print it in logs to verify if we get it successfully.

**Comment by vishveshtrivedi** [comment] 2023-03-14 22:53
Ok.
So Instead of taking values from key vault, I should try to pass those values to the environment variables in my code itself.
Right?

Thanks

**Comment by xiangyan99** [comment] 2023-03-14 22:56
If this succeeds, it can validate our hypothesis which is the failure is due to the AAD settings.

If it is true, I would suggest we using service principal rather than managed identity to access key vault.

**Comment by vishveshtrivedi** [comment] 2023-03-15 22:35
Hello,
I was able to get the connection string from the below code:


if db is None:
        db = os.getenv("AZURE_DB_NAME")
    if host is None:
        host = os.getenv("AZURE_DB_HOST")

    con_options = {"Encrypt": "yes", "TrustServerCertificate": "no", "Authentication": "ActiveDirectoryMsi"}
    if connection_options is not None:
        con_options.update(connection_options)
    con_options_str = ";".join(f"{x[0]}={x[1]}" for x in con_options.items())

    connection_string = f";Driver={driver};Server=tcp:{host};Database={db};Connection Timeout=30;{con_options_str}"
    logging.info(connection_string)
    url = sqlalchemy.engine.URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})
    logging.info(url)
    eng_options = {"fast_executemany": True}
    if engine_options is not None:
        eng_options.update(engine_options)

    ret = sqlalchemy.engine.create_engine(url, **eng_options)
    logging.info(ret)

Keyvault does not have values of connection string.
The values of environment variables are defined in configuration of azure function.

![azure](https://user-images.githubusercontent.com/46259190/225432220-91b92769-4c57-4728-9233-61415c3e42da.JPG)

Whenever I put ret.connect() I get the following error:
  
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('CE267', "[CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error 12029 opening URL http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F (0) (SQLDriverConnect); [CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error requesting access token, HTTP status -1, expected 200 (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Failed to authenticate the user '' in Active Directory (Authentication option is 'ActiveDirectoryMSI').\r\nError code 0xA190; state 41360\r\n (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258].  (258); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [CE267] [Microsoft][ODBC Driver 17 for SQL Server]Unable to complete login process due to delay in login response (258)")
(Background on this error at: https://sqlalche.me/e/14/dbapi)

Do i need to add connection string in azure function or should I add sql sever app registration to the keyvault?

**Comment by xiangyan99** [comment] 2023-03-15 22:51
It looks to me the problem is not related to the SDK, neither azure functions.

Let's simplify the code. 

(assuming you are using sqlalchemy library to connect to sql)

can you only use the library and the connection string to connect to sql?

You can run the code in your dev box.

**Comment by vishveshtrivedi** [comment] 2023-03-15 23:09
Could you please provide the sample code?

**Comment by xiangyan99** [comment] 2023-03-15 23:12
You can just use your

get_azure_db_connection() method and hard code connection string. 

You don't need to deploy it into gitlab or azure-function. Just run it locally to see if it works.

**Comment by xiangyan99** [comment] 2023-03-15 23:12
Within the code, there is no azure sdk involved.

**Comment by vishveshtrivedi** [comment] 2023-03-16 13:25
Hello,
Actually the problem is not within the code. The thing is it failing to authenticate the user.
Failed to authenticate the user '' in Active Directory (Authentication option is 'ActiveDirectoryMSI')

Is there anyway to findout what user it is refering to?
Also do i need to assign azure function the necessary permissions to access the SQL Server database.?

Thanks

**Comment by xiangyan99** [comment] 2023-03-16 15:36
Thank you for the confirmation.

Agreed that this problem is not related to the SDK.

I think you may need to talk to the SQL service team for the help.

I will close the issue and please open a ticket to the service team.

**Closed as completed by xiangyan99** 2023-03-16 15:36 UTC
Labels: question, customer-reported, needs-team-attention
