### ISSUE TITLE
exists() method for existing subdirectory raises exception

### ISSUE THREAD

**Issue by proyVolt** [Azure/azure-sdk-for-python#33045] opened 2023-11-08 16:04 UTC
- **Package Name**: azure-storage-file-share
- **Package Version**: 12.14.2
- **Operating System**: MacOS 14.0 ARM64
- **Python Version**: 3.11.5

**Describe the bug**
Calling `exists()` method on subdirectory which does exist in a file share raises an `azure.core.exceptions.HttpResponseError` with the following contents:
````
The specifed resource name contains invalid characters.
RequestId:<contents redacted for sharing in github Issue>
Time:<contents redacted for sharing in github Issue>
ErrorCode:InvalidResourceName
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:<contents redacted for sharing in github Issue>
Time:<contents redacted for sharing in github Issue></Message></Error>
````

**To Reproduce**
1. Create `ShareServiceClient` with file SAS URL (with all available permissions, for testing)
2. Create  `ShareClient` via `get_share_client()` method from parent `ShareServiceClient` which represents the share I'm working in
3. Create `ShareDirectoryClient` via `get_directory_client()` method from parent `ShareClient` which represents the root of the file share
4. Create `ShareDirectoryClient` via `get_subdirectory_client(directory_name='dir_name')` method from parent `ShareDirectoryClient`, where dir_name is the name of a directory verified via the web console to exist in the file share
5. Call `exists()` method on subdirectory `ShareDirectoryClient`

**Expected behavior**
Return a `bool` which describes the existence or lack thereof, as per the method signature

**Additional context**
I've testing this issue in multiple file shares in the same storage account, and I even created a brand new storage account and accompanying file share to double verify for the purposes of opening this issue. All names of all storage accounts, file shares, and directories contain exclusively letters.

**Comment by proyVolt** [comment] 2023-11-08 16:45
I'm also getting that exact same exception when I try to create a new subdirectory:

````python
for dir in ['config', 'auth']:
  if dir not in existing_dirs:
    new_dir = parent_dir.create_subdirectory(directory_name=dir)
    new_dir.create_directory()
````

In general it seems like either something fundamental is broken or I'm making some bad assumptions about how these objects are expected to be created and used.

**Comment by kristapratico** [comment] 2023-11-08 16:55
@proyVolt thanks for your detailed issue, we'll investigate and get back to you as soon as possible.

**Comment by vincenttran-msft** [comment] 2023-11-08 20:40
Hi @proyVolt Patrick, thanks for your inquiry. From my local testing I am not running into the same errors you are facing. Attached below is my code sample containing two different workflows (one creates the sub-directory just like any other directory, while the other creates the sub-directory using the parent directory's client):
```
from azure.storage.fileshare import ShareServiceClient

ACCOUNT_URL = 'https://<account_name>.file.core.windows.net'
CREDENTIAL = '<SAS_TOKEN>'

share_service_client = ShareServiceClient(ACCOUNT_URL, CREDENTIAL)

# Create sub-directory from the sub-directory level itself
share_client = share_service_client.get_share_client('testshare')
dir_client = share_client.get_directory_client('directory')
dir_client.create_directory()
sub_dir = dir_client.get_subdirectory_client('dir_name')
sub_dir.create_directory()
ret = sub_dir.exists()
print(ret)

# Create sub-directory from the parent-level
share_client = share_service_client.get_share_client('testshare')
dir_client = share_client.get_directory_client('directory')
dir_client.create_directory()
sub_dir = dir_client.create_subdirectory('dir_name')
ret = sub_dir.exists()
print(ret)
```

If you could please try the above code (comment out one of the blocks as they cannot both run) and see if you are still facing the issues you described in your original post, or at least hopefully the above code can give you an idea of where your code is going awry. The above code assumes that a share named `testshare` already exists on the specified Storage account.

Some other observations include:

- The error seems to be related to containing invalid characters. You mention that it exclusively contains letters, but is it possible there is some non-standard character somehow making its way into your Storage account?
- In your follow-up post, you are calling `create_subdirectory` from the parent directory client and then calling `create_directory` from the new (presumably "sub-dir") client. This is not necessary as the `create_subdirectory` call already creates the sub directory. [Documentation](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_directory_client.py#L843-L844)

With that being said, hopefully some of the above information can help you identify the root cause of the blocker in your workflow. Otherwise we can look into other possibilities.

Thanks!

**Comment by proyVolt** [comment] 2023-11-08 22:57
I can list all of the files and directories in my share and do everything up to calling the `exists()` and `create_subdirectory` methods, which indicates to me that the storage account and share name are devoid of gremlins. I am also sure that the string I am typing into the `directory_name` parameter is standard utf-8.

In your second suggested code block, you have:

````python
dir_client = share_client.get_directory_client('directory')
````
Am I correct in interpreting that as meaning that the directory client would be for a folder called directory within the root of the file share? I am currently calling it this way:

````python
    parent_dir = share_client.get_directory_client()
````

Thank you for pointing out my not needing the second create_directory

**Comment by vincenttran-msft** [comment] 2023-11-10 02:07
Hi @proyVolt Patrick, you are correct with that interpretation of the code block I have provided. If none of the above feedback seems to help you get closer to resolving the issue, could you provide us with the following:

1. End-to-end complete code sample (i.e. the code block I provided in a previous reply) that can be ran on a fresh Storage account and will reproduce the issue you are finding on your end. Hopefully with this I can run this locally on my machine and face the same exception, thus being able to identify the root cause.
2. Another option (or additional information you can provide) is a `RequestID` from a failing request. Please provide the most up-to-date `RequestID` when possible, as these are cleared on a rolling basis. With this, we would be able to look up the exact same request you made instead of trying to reproduce it locally.

Thanks!

**Comment by proyVolt** [comment] 2023-11-13 17:42
I have adjusted my assumptions about how I should be working with this client. Opening the root directory as a directory client (i.e. argument `directory_path` not provided) and trying to create subdirectories consistently produces exceptions. I have instead moved to an approach modeled from your suggestion where each directory gets its own client. As such, my work blocking issue has been resolved.

I can re-produce the issue and provide RequestIDs if the behavior of not providing a `directory_path` and still being able to create files and subdirectories is something you wish to continue to troubleshoot.

**Comment by vincenttran-msft** [comment] 2023-11-15 23:32
Hi @proyVolt Patrick, thanks for your response and including a succinct example of reproducing the issue! I am glad you were able to find a resolution for your workflow for the time being, but in fact what you were experiencing was actually a bug and so I have attached a pull-request above that resolves this issue.

After the fix, opening the root directory as a `ShareDirectoryClient` and using `get_subdirectory_client` will no longer yield a non-working `ShareDirectoryClient` that would throw `InvalidResourceName` on any operation called by it 😄 

With that being said, I will close out the thread upon the successful merge of the above pull-request, and this fix should be available along with the next release!

Thanks!

**Closed** 2023-11-16 22:56 UTC
Labels: Storage, question, Client, customer-reported, needs-team-attention
