### ISSUE TITLE
Some network/cbs auth issue will cause message lost or delay to return to caller during receive

### ISSUE THREAD

**Issue by enoeden** [Azure/azure-sdk-for-python#20086] opened 2021-08-04 17:40 UTC
- **Package Name**: azure-servicebus
- **Package Version**: 7.3.1
- **Operating System**: Ubuntu
- **Python Version**: 3.7.1

**Describe the bug**
We observe msg delay or re-delivery in our env, so we write some simple send-receive code to re-produce.
After running for several days, we found the issue happened many times and many reason will lead to this while few can handle by user, so we fire this ticket to report and see if any enhance point or workaround.

**To Reproduce**
1. We setup the queue with max delivery count 2, lock duration 2min, sender will send 20 msg (msg body contains the timestamp while sending) in batch every 150 secs, and there receiver in container will receive the msg and settle it after around 20~30sec and also log the duration between send and receive. 
2. We use ClientSecretCredential for service bus auth and websocket as transport_type and also open debug log of servicebus and uamqp.
3. By hunting for long during msg and analyze the log of that host during that time, we can identify the abnormal point.

From our test log we can see some msg be re-delivery as the duration is 120s, we even found some msg can deley 180s/300s and seems the underlying link receive the TRANSFER frame but it have no chance to return to caller which also cause lock expired error when we try to settle it, also some DISPOSITION frame will send failed but sdk are not aware of it.

We select several cases and give a brief description here so that you may easily re-produce.

![Untitled](https://user-images.githubusercontent.com/11899900/128218936-73ed52a7-6f12-427a-8609-b889e3aff6e3.png)

> Timezone in description below and picture is UTC-8 and the raw log use UTC time, also import the log into elasticsearch or some tool will help a log while digging.
> The extra two line in picture is for comparation, we use sdk 7.0.1 and we only provide log of 7.3.1 here.
> In description, host are equal to host field in log, seq means the seq_number of msg (if msg re-delivery happen , we can look for the first time of this seq_number shows)

1.  2021-07-26 19:22:11.685 ~ 2021-07-26 19:30:45.873 host 743584b73a35 receive transfer @July 26th 2021, 19:25:14.998 but app recv it @July 26th 2021, 19:27:57.671 the flow issued @July 26th 2021, 19:22:48.114	and cbs refresh attempt @10sec later
2. 2021-07-27 01:54:16.968 ~ 2021-07-27 01:58:19.850 host 8c8853256ac9 receive seq 38575 @July 27th 2021, 01:55:03.135	but link down @July 27th 2021, 01:55:32.268 which cause disposition seems faild
3. 2021-07-27 03:07:48.910 ~ 2021-07-27 03:14:11.168 similiar as case 1 host fa72d36c25be receive transfer @July 27th 2021, 03:08:37.180 but app recv it @July 27th 2021, 03:11:09.292 along with cbs auth failed, the flow issued @July 27th 2021, 03:05:56.452	and cbs refresh attempt @10sec later
4. 2021-07-27 06:48:12.438 ~ 2021-07-27 06:59:46.704 similiar as case2 seq 40893, host 8c8853256ac9 can not realize the connection issue till cbs refresh timeout.
5. 2021-07-27 16:14:15.362 ~ 2021-07-27 16:20:53.051 similiar as case 1 , host 743584b73a35 normal recv ops seems disturbed by cbs refresh ? around July 27th 2021  16:15:26.546, and back to normal after 5 min, cause the 30sec delay
6. 2021-07-28 00:43:58.664 ~ 2021-07-28 01:00:05.928 host 743584b73a35 seq 49431 error message "Failed to complete the message as the handler has already been shutdown.Please use ServiceBusClient to create a new instance." settle during handler re-connection caused message re-dispatch, other settle after re-connection is success via management link
7. 2021-07-28 14:10:50.323 ~ 2021-07-28 14:23:06.054 all host has connection error and seq 55763 just show for second time, the chance can be ws link lost dring some transfer?   
8. 2021-07-28 16:08:19.154 ~ 2021-07-28 16:12:50.000 almost same as case7
9. 2021-07-29 01:08:09.143 ~ 2021-07-29 01:23:29.195 similiar as case4 in host fa72d36c25be

We classify cases above to 2 types below and seems they are not handled properly.

- 1 underlying network error,  we can see msg “b'on_underlying_ws_error called with error code 4' (b'/data/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/wsio.c':b'on_underlying_ws_error':450)”  and the issue can be 
- 1.1 DISPOSITION frame will lost while sdk think it's settled and we will see the msg re-delivery
- 1.2 some times it will take quite a long time before the underlying error found and the operation which make the link not work (receive and settle ) till reset.

- 2 CBS refresh related issue, we can see msg like "Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down." and even see get token timeout and the issue can be
- 2.1 uamqp and ClientSecretCredential have time window gap when token is about to expire, uamqp will try refresh 6mins before expire while ClientSecretCredential will only refresh 5mins before expire(before that only cached token return), so we can see uamqp do the token refresh rapidly (once 50ms for about 1min) in the gap minute and the normal receve operation seems not work during that time and if have TRANSFER frame before fresh, it will delay to emit or lost . Also not sure whether the rapid refresh operation will affect the connection and lead to "Authorization timeout" later.
- 2.2 some times the get token will hang till 300s timeout (we see visit login.microsoft ... timeout error log), in that case, TRANSFER frame not emitted will lost/delay and the whole receiver will hang which makes max wait time not work.

For underlying network error, we have tried to move the receiver to azure vm which in same region with the service bus and seems it helps while the CBS refresh error "Authorization timeout" still exist.

**Expected behavior**
We expect the sdk can have a nice error handle to avoid "msg lost"/ "delivery already expired msg to client" in cases above and maybe give some advice for client user. 
For CBS refresh, not sure the "refresh window gap caused rapid token refresh" and "get token timeout the whole receive operation" is a proper workflow

**Screenshots**

**Additional context**
[rawlogs.zip](https://github.com/Azure/azure-sdk-for-python/files/6933339/rawlogs.zip)

**Comment by tjprescott** [comment] 2021-08-04 20:29
Thank you for the detailed report! @yunhaoling can you please take a look and advise?

**Comment by yunhaoling** [comment] 2021-08-09 23:28
hey @enoeden, thanks for reaching out and your very detailed analysis.

re "msg lost"/ "delivery already expired msg to client":
- may I ask what's the message receiving and handling pattern that your application code is using -- are you receiving a batch, handling one by one; have you set the prefetch count when creating the receiver?
- The description _the underlying link receive the TRANSFER frame but it have no chance to return to caller which also cause lock expired error when we try to settle it_ makes me wonder if it's the handling pattern or a mixture with prefetch that leads to the lock expiry
  - the lock expiration is calculated based on the time when the message arrives at the client side, not the time when the message is returned to the application code.
  - receiving a batch messages while handling them one by one for long duration could lead to message lock expiration for the latter part of messages. e.g. receiving 10 messages which have lock expiration of 2mins at a time, handling 1 messages for 2 mins, the remaining 9 would get expired.
  - prefetch is could lead to lock expiration if messages not handled timely as prefetch is telling the service bus to send `prefetch` amount of messages if possible and those messages will be cached in the client and returned to the application code if receive is coded.

The recommendation would be use either receiving and handling one message at a time or receiving multiple messages but register all of them into [AutoLockRenewers](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/auto_lock_renew.py) (which is a tool class for doing auto lock renewing automatically for a fixed amount of time) first before handling.

------

re CBS refresh:

thanks for bringing it up, sorry I'm unaware of the 5 mins cache thing before, this is interesting, I will reproduce it first and see if there's any improvement could be made!

**Comment by enoeden** [comment] 2021-08-10 02:43
hi @yunhaoling

#### for "receiving and handling pattern",
1. We use one main thread for batch receive msgs with batch size 10 wait time 20sec, and 20 threads will handle the received msg (record some meta to log, sleep(random.randint(20, 30)) )and settle the msg in thread finally.(we sleep here to simulate some workload)
> Since we use multi-threading to handle received msgs (3 container, every container use multi-threading) and sender will only send 20 msgs per 150sec, we don't think these operation will cause 2min locktimeout here, also if msgs are already expired when it returned from `receive_messages(max_message_count=MaxNumberOfMessages, max_wait_time=WaitTimeSeconds)` , so AutoLockRenewers won't help here.

2. The receiver are reused between batch receives and the prefetch count is set to 0 when create receiver and the FLOW frame logged during recevicer create in raw log can also shows that.

#### for the description _the underlying link receive the TRANSFER frame but it have no chance to return to caller which also cause lock expired error when we try to settle it_

We observed this becaue our code will log once it get the msg received from main thread's batch receive and we found it already timeout, so we dig into the raw log and seems that TRANSFER frame is normal but normally we will see logs write by our code right after the TRANSFER frame , but in this case, log of our code shows 3mins later and expired already. 
Actually we reporduce it in case 1 and case 3 and you can dig into the raw log to double comfirm and for your reference we suspect the cbs refresh log around the receive time is related.

Just let us know if you need any infomation which can help.

Also, can you give some comments or advice for section ` 1 underlying network error, we can see msg “b'on_underlying_ws_error called with error code 4' (b'/data/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/wsio.c':b'on_underlying_ws_error':450)”`?

**Comment by yunhaoling** [comment] 2021-08-17 20:01
hey @enoeden, thanks for the input. I'll take a closer look into the log.

Is there any chance that you could share the code snippets with me which could reproduce the issue?

**Comment by enoeden** [comment] 2021-08-18 03:15
hi @yunhaoling, thanks for the reply.

[service_bus_debug.zip](https://github.com/Azure/azure-sdk-for-python/files/7004233/service_bus_debug.zip)

The code used to reproduce attached, it's a little messy cause I just rewrite it from our source code tree and we have a wrapper around service bus sdk cause we also need support other platforms like aws sqs. 

The credential you need to fill in is marked as "tbd" and you should run it for maybe days and leverage some log analyze tool to find reproduction.

After we see this issue, we make this control test in our env  (you can find them in docker-compose file in code attached).
The original raw log we provide use sdk 7.3.1 over websocket and the containers run just in our office. 
After suspecting the network error maybe related, we move test env to one azure vm in same region with test service bus queue and seems the websocket error disappear but message can still lost.

We use "amqp over websocket" casue we found amqp port is not available in our company's outbound network during development and after code complete, this transport type keeps, we can change to amqp when deploying in azure env but we are not sure if "amqp" is better than "amqp over websocket" in this case.

**Comment by yunhaoling** [comment] 2021-08-31 04:01
@enoeden sorry for keeping you wait for so long and I finally got some time to check the code/logs.

----------------

I've read your code which looks good to me.
Also I've read into the logs and I could observe the keep attemping refreshing token pattern.

-----------------

1. underlying network error

- The error code "4" literally means [underlying network error](https://github.com/Azure/azure-uamqp-python/blob/master/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/inc/azure_c_shared_utility/uws_client.h#L56) here, it usually indicates network down/client disconnected.

1.1 DISPOSITION frame lost

- There's is a missing feature/bug in the underlying uamqp library that currently we're unable to detect whether settlement succeeds or not from the client side. So the client side is always assuming settlement succeeds.

1.2 some times it will take quite a long time before the underlying error found and the operation which make the link not work (receive and settle ) till reset.\
  - The underlying error is be triggered by operation as the SDK is implemented as pull mode underneath which keeps listen for socket. The receive could be treated as doing a while loop internally until certain timeout or message acount is met. So if the receive doesn't get executed for a while -- either due to some long duration opearion/high cpu load, the underlying error can't not be found/raise.

2 CBS refresh related issue, we can see msg like "Unexpected error occurred (TimeoutError('Authorization timeout.')). Handler shutting down." and even see get token timeout and the issue can be.

- Auth timeout happens when the client fails to be authenticated by the service (put token operation is not completed) within the auth_timeout (which is 60s by default).
- The error could be networking socket lost. Retry should help.

2.1 uamqp and ClientSecretCredential have time window gap...

- This is an excellent finding, I double check the authentiation logic and I think your observation is correct. If ClientSecretCredential is returning cache until 5 mins expiration while the refresh windows in uamqp is 6 mins, than in the 1 mins gap, the client would keep try refreshing token while not returning messages.

2.2 some times the get token will hang till 300s timeout...

- that's also a good finding, I think this case happens when outage happens in Azure.
- it's something that the SDK might be able to take care of, e.g. set the timeout for get token operation to be equal to the auth timeout setting within the SDK. I will check the identity library.

-----------------

- We expect the sdk can have a nice error handle to avoid "msg lost"/ "delivery already expired msg to client" in cases above and maybe give some advice for client user.
  - msg lost, we would need to add the missing feature for checking disposition result.
  - delivery already expired, I feel this should be fixed by the cbs refresh issue.
- For CBS refresh, not sure the "refresh window gap caused rapid token refresh" and "get token timeout the whole receive operation" is a proper workflow
  - Yes, we should definitely improve on this

-----------------

The workaround I'm thinking of is:

- msg delay
  - I would recommend simply increasing the lock duration to see if it help mitigate the issue.
- re-delivery
  - This is a tough one to be honest as the feature of getting disposition result is missing, is it possible for you to first locally check if a message is handled?

**Comment by enoeden** [comment] 2021-09-02 07:40
hi @yunhaoling, thanks for the detailed reply.

We may deal with the msg re-delivery for now since seems it's inevitable when network error happen by SDK design but we still think uamqp should add this essential feature, otherwise msg just lost...

As for cbs refresh, we are looking forward to the enhancement and will see if it can help in our use case when it's ready.

**Comment by yunhaoling** [comment] 2021-09-07 21:17
hey @enoeden , 

I have created separate work items:

refresh window: https://github.com/Azure/azure-sdk-for-python/issues/20573
disposition acknowledgement: https://github.com/Azure/azure-sdk-for-python/issues/20576

the refresh window should be easy to handle, while the disposition acknowledgement might take a while to implement.
We'll prioritize the items depending on the resourcing we have.

Thanks for your patience in advance!

**Closed** 2022-01-07 17:50 UTC
Labels: Service Bus, question, Client, customer-reported, MQ, needs-team-attention, Messaging
