### ISSUE TITLE
Timezone not converted to UTC for generate_blob_sas

### ISSUE THREAD

**Issue by SamFangshan** [Azure/azure-sdk-for-python#34890] opened 2024-03-22 06:30 UTC
- **Package Name**: azure-storage-blob
- **Package Version**: 12.9.1
- **Operating System**: Mac
- **Python Version**: 3.8

**Describe the bug**
I am trying to use this function: `azure.storage.blob.generate_blob_sas`.

This [documentation](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python#azure-storage-blob-generate-blob-sas) claims that for the `expiry` parameter, Azure will always convert it to UTC.

But when I look at the [code](https://github.com/Azure/azure-sdk-for-python/blob/a3039b12b0b73b3e098b78c18031cc99c4fa3986/sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/_shared/parser.py#L19) that deals with datetime conversion, it doesn't convert the timezone to UTC at all. This has resulted in the SAS token expiry to be set wrongly when I called `generate_blob_sas`.

**Expected behavior**
https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python#azure-storage-blob-generate-blob-sas
The `expiry` datetime object's timezone can be properly converted.

**Screenshots**

**Additional context**

**Comment by vincenttran-msft** [comment] 2024-03-26 21:29
Hi @SamFangshan , thanks for your inquiry! After some internal conversation, I have gone ahead and corrected the docstring to more accurately describe the intended behavior.

In short, it is intended that all datetime objects and/or date strings are interpreted as UTC. I have attached a pull-request containing the updates to the docstrings!

Thanks again for your inquiry, and with the successful merge of the pull-request this issue will also be marked as resolved!

**Closed** 2024-03-26 21:29 UTC
Labels: Storage, question, Service Attention, Client, customer-reported, needs-team-attention
