### ISSUE TITLE
Change log version check ignored unreleased tag when releasing package

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-python#9848] opened 2020-02-13 01:01 UTC
Version check must ensure that "Unreleased" tag is not present in version title when releasing package. for an instance, change log was not updated to release date for azure-storage-file-datalake

Fore.g. Version title should not have tag like the one in below sample. 
## 1.2.3 (Unreleased)

**Comment by weshaggard** [comment] 2020-03-17 18:07
Closing as a duplicate of https://github.com/Azure/azure-sdk-tools/issues/421. We should have a common script that will verify the changelog on release.

**Closed by weshaggard** 2020-03-17 18:07 UTC
Labels: EngSys
