### ISSUE TITLE
There is no documentation for the require_guest_provision_signal parameter, how to use it, possible return values, etc.

### ISSUE THREAD

**Issue by v-doquag** [Azure/azure-sdk-for-python#9514] opened 2020-01-18 00:27 UTC
- **Package Name**: N/A
- **Package Version**: N/A
- **Operating System**: Linux
- **Python Version**: 3.x

**Describe the bug**
There is no documentation for the require_guest_provision_signal parameter, how to use it/check it, possible return values, how to control it from within the virtual machine (or whether it is entirely under Azure's control?) and so on.  Is the require_guest_provision_signal something that the user/creator of the virtual machine can control from within the VM? If you set require_guest_provision_signal to TRUE when you are creating the virtual machine, then what do you do next? The documentation only says "Specifies whether the guest provision signal is required from the virtual machine."

**To Reproduce**
1. N/A 

**Expected behavior**
The expectation is that some documentation will be written by Microsoft along with some sample code in Python for how to use require_guest_provision_signal and what to do after setting it to TRUE.  If this signal is something that the user can control from within the virtual machine, then sample Python code for controlling the signal from within the virtual machine should be provided too.  

**Screenshots**
N/A

**Additional context**
https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2019_07_01.models.osprofile?view=azure-python

Thanks,
Douglas

**Comment by kaerm** [comment] 2020-01-21 19:29
@v-doquag thanks for reporting this, looping in some of the team to take a look at this //cc: @nickzhums @mozehgir

**Comment by nickzhums** [comment] 2020-01-22 03:11
@v-doquag Thanks for bringing this up. It seems like there is not too much documentation around this property. I will follow up and let you know

**Comment by nickzhums** [comment] 2020-01-22 03:58
Looks like this doc does not contain the sufficient information either
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate

Adding service attention tag here:

Could someone from the service team take a look at this property and explain what the property is for?

**Comment by v-doquag** [comment] 2020-01-27 22:31
I haven't seen any updates for almost a week.  Did this issue get routed to a dead-end one-way street?  What's the latest status on this?  Has someone found the documentation?

**Comment by nickzhums** [comment] 2020-01-28 14:52
@mjconnection @Drewm3 could you provide more info on this parameter? Thanks a lot

**Comment by loadedlouie** [comment] 2020-01-30 15:23
Hi all, I'm currently working on ARM templates with my current company.
We are trying to implement vnets Vms etc.. for production infrastructure. 
We are encountering problems deploying the virtual machines. 
Can Microsoft give feedback about this issue? 

Thanks in advance.

**Comment by nickzhums** [comment] 2020-01-31 15:09
@loadedlouie could you open a separate issue and describe the details? :) 

Thanks!

**Comment by v-doquag** [comment] 2020-02-03 17:35
@nickzhums  @mjconnection @Drewm3 - could you PLEASE provide any documentation for the require_guest_provision_signal parameter, how to use it, possible return values and so on?

**Comment by Drewm3** [comment] 2020-02-09 21:00
Sorry for the delay. I am looking into this now, and will provide and update soon.

**Comment by Drewm3** [comment] 2020-02-13 23:34
Hi @v-doquag, thanks for bringing this to my attention. This feature was added as an "experimental" without appropriate documentation clarifying that the parameter is not available for general use. Currently this feature cannot be used in any subscription that is not whitelisted for the experimental feature.  

We do not intend to roll-out this feature broadly in the near term. The documentation will either be updated to clarify this is an unavailable parameter that cannot be used currently, and the parameter may be removed in a future release.

For now, please ignore this parameter.  I apologize for the confusion caused by the addition being made to the API without the appropriate level of documentation.

**Comment by v-doquag** [comment] 2020-02-14 00:01
Ok.  Thanks.

**Comment by nickzhums** [comment] 2020-02-14 03:36
Thanks @Drewm3 
Since the issue is explained, I'm closing the issue for now. @v-doquag  feel free to re-open

**Closed by nickzhums** 2020-02-14 03:36 UTC
Labels: Compute - VM, Docs, Mgmt, Service Attention, customer-reported
