### ISSUE TITLE
Azure-identity importing for Python3 Runbook throws OpenSSL issue

### ISSUE THREAD

**Issue by CedricOettel** [Azure/azure-sdk-for-python#21719] opened 2021-11-11 16:48 UTC
- **Package Name**: azure-identity
- **Package Version**: 1.7.1
- **Operating System**: Azure Automation Account
- **Python Version**: 3.8.0

**Describe the bug**
There seems to be a version conflict with OpenSSL package from Python3 vs. OpenSSL from package "cryptography", which is a dependency package from azure-identity or azure-storage-blob.
When using the [Import_py3package_from_PyPi](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/automation/python-3-packages.md#import-a-package-with-dependencies) script in an Azure Automation Account, the following error occurs on the second run:
```
Traceback (most recent call last):  File "C:\Temp\etqormcy.jez\be1925d7-d9b7-4f8c-80e7-2a98f1a60b25", line 127, in <module>
    token = get_automation_runas_token()  File "C:\Temp\etqormcy.jez\be1925d7-d9b7-4f8c-80e7-2a98f1a60b25", line 35, in get_automation_runas_token
    from OpenSSL import crypto  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\crypto.py", line 15, in <module>
    from OpenSSL._util import (  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 203, in <module>
    _verify_package_version(cryptography.__version__)  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 192, in _verify_package_version
    raise ImportError(ImportError: The version of cryptography does not match the loaded shared object.
    This can happen if you have multiple copies of cryptography installed in your Python path.
    Please try creating a new virtual environment to resolve this issue. Loaded python version: 35.0.0, shared object version: b'2.8'
```

**To Reproduce**
1. Use Import Runbook to import "pandas" (works as expected)
2. Use Import Runbook to import "azure-identity" (works as expected)
3. Use Import Runbook to import "azure-storage-blob" (Error is thrown)

The Error is thrown in the Import_py3package_from_pypi runbook in method:
```
def get_automation_runas_token():
      from OpenSSL import crypto
```

On the first run the error is not thrown. But Azure-Identity also installs cryptography package. Importing the second azure-storage-blob package then throws the error as shown above. You can also reverse the order of installation with the same error (azure-storage-blob first, then error when importing azure-identity)

**Expected behavior**
The same procedure worked when using Python 2.7 Runbooks for importing both azure-identity and azure-storage-blob package.
Also within logic runbooks there were no error when using "from OpenSSL from crypto" for Authentication.
Python 3 Environment seems to deliver a separate OpenSSL version that is not compatible with the referenced OpenSSL in package "cryptography", which itself is used in azure-identity

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment] 2021-11-11 18:51
@CedricOettel Msal (one of the identity dependencies) recently made a change of the dependent cryptography version. (https://github.com/AzureAD/microsoft-authentication-library-for-python/commit/16dcb22690c1c66e96a7c96b4dda4cf7ceb58e00#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)

It bumped cryptography from <4 to 35 which may be the cause.

Could you try install cryptography<4?

Does it solve the problem?

**Comment by CedricOettel** [comment] 2021-11-12 08:17
How can i do that in an Azure Automation Account?
Do i need to reference a specific version of azure-identity which does not have the reference to 35.0.0 ? If so, which version of azure-identity has a lower version of MSAL than 1.15.0?

**Comment by xiangyan99** [comment] 2021-11-12 16:31
I am not an expert of Azure Automation. Is it possible that you can specify something like requirements and install cryptography < 4 before installing identity library?

**Comment by irm-phoudek** [comment] 2021-11-12 16:35
Hello,
we have tried to install cryptography 3.2.2 (the version, that is installed with azure-identity/-storage-blob for Python 2.7 in Azure) before. Then the same error occures on the first install of azure-identity or -storage-blob. So it seems not to be a problem of the "wrong" version of cryptography.

**Comment by xiangyan99** [comment] 2021-11-16 00:19
@irm-phoudek when you say same error, do you mean the error with message
"Please try creating a new virtual environment to resolve this issue. Loaded python version: 35.0.0, shared object version: b'2.8'"

Isn't 35.0.0 the version of cryptography library?

**Comment by irm-phoudek** [comment] 2021-11-16 07:17
@xiangyan99 of cause the versionnumber is changed as also the id of the runbook-VM and a few line numbers, but stacktrace and error is the same:
```Fehler
Traceback (most recent call last):  File "C:\Temp\a1315bzt.kjf\6906cfc5-c203-4dbc-a68a-fae3c64e56a0", line 127, in <module>
    token = get_automation_runas_token()  File "C:\Temp\a1315bzt.kjf\6906cfc5-c203-4dbc-a68a-fae3c64e56a0", line 35, in get_automation_runas_token
    from OpenSSL import crypto  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\crypto.py", line 15, in <module>
    from OpenSSL._util import (  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 170, in <module>
    _verify_package_version(cryptography.__version__)  File "C:\WPy64-3800\python-3.8.0.amd64\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 159, in _verify_package_version
    raise ImportError(ImportError: The version of cryptography does not match the loaded shared object.
    This can happen if you have multiple copies of cryptography installed in your Python path.
    Please try creating a new virtual environment to resolve this issue. Loaded python version: 3.3.2, shared object version: b'2.8'```

**Comment by xiangyan99** [comment] 2021-11-16 17:22
Looks like cryptography 2.8 is installed in Azure Automation Account. @automation team, can anyone help to confirm it?

**Comment by mahakjain314** [comment] 2021-12-08 11:19
Yes, cryptography 2.8 is installed in Automation Sandbox to support assets in Python.

**Comment by xiangyan99** [comment] 2021-12-08 19:10
@mahakjain314 Thanks for the information. Just to confirm, after Sandbox installs 2.8, it is ok to upgrade cryptography to a higher version, right?

**Comment by mahakjain314** [comment] 2021-12-13 13:35
Ideally, one should be able to upgrade to a higher package version but we have identified an issue because of which installing the new version of crypto package is not overriding the previous one.

**Comment by Angivare** [comment] 2022-01-28 19:01
@mahakjain314, do you have any reference to this issue so I can track it? If not, what's the status on this?

This currently prevents us from using the latest azure.mgmt libraries on Azure Automation in Python3 runtime, and as the libraries that are already installed are apparently ~4 years old, they have very limited functionality for the more recent Azure services.

If this issue is not expected to be resolved anytime soon, we will have to try and temporarily switch to Python2 runtime I guess

**Comment by xiangyan99** [comment] 2022-04-25 17:28
Closing because this is not an SDK issue.

Please open service support ticket to track it.

**Closed by xiangyan99** 2022-04-25 17:28 UTC
Labels: question, Automation, Client, customer-reported, Azure.Identity, needs-team-attention

**Comment by sid-motorq** [comment] 2022-07-15 05:12
If anyone is looking for a workaround, creating a fresh automation account (without any packages installed) and running to importpypackage runbook from it targeting my actual automation account made it work
