### ISSUE TITLE
azure-mgmt-applicationinsight CloudError: <Response [201]>

### ISSUE THREAD

**Issue by jmalobicky** [Azure/azure-sdk-for-python#3141] opened 2018-08-14 18:17 UTC
When create a web_test I get the following error:

`
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): management.azure.com
DEBUG:urllib3.connectionpool:https://management.azure.com:443 "PUT /subscriptions/REDACTED/resourceGroups/temp/providers/microsoft.insights/webtests/pingtest?api-version=2015-05-01 HTTP/1.1" 201 2356
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/env/lib/python3.6/site-packages/azure/mgmt/applicationinsights/operations/web_tests_operations.py", line 227, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: <Response [201]>
`

I can see that the web test is created fine. I am using version 0.1.0 of library. Please let me know if there is additional information needed.

**Comment by lmazuel** [comment] 2018-08-14 20:25
That's likely a bug in the Swagger description of the service, let me create an issue for that:
https://github.com/Azure/azure-rest-api-specs/issues/3638

**Comment by lmazuel** [comment] 2018-08-14 20:27
If you feel cumfortable to edit the code in the meantime, edit this line:
https://github.com/Azure/azure-sdk-for-python/blob/61234a3d83f8fb481d1dd2386e54e888864878fd/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py#L231

to put
```python
if response.status_code in [200, 201]
```

And this line:
https://github.com/Azure/azure-sdk-for-python/blob/61234a3d83f8fb481d1dd2386e54e888864878fd/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py#L224
to
```python
 if response.status_code not in [200, 201]:
```

**Comment by jmalobicky** [comment] 2018-08-14 20:29
Great. I will modify those lines to see if it works.

**Comment by jmalobicky** [comment] 2018-08-15 17:00
@lmazuel I patched the file and tested. It works with your proposed changes. Will I need to wait for a next release of the azure-mgmt-applicationinsights for this fix?

**Comment by lmazuel** [comment] 2018-08-15 17:12
@jmalobicky That's  good news!
Yes, since the code is generated from a RestAPI specifiction, I need the spec to be fixed in order to release the fix. Good news is you fixed at the same time all SDK (Go, C#, Java, etc.), bad news is it takes a little more time...
Will try to poke them now you confirmed it worked.
Thanks.

**Comment by lmazuel** [comment] 2018-08-15 18:02
@jmalobicky Considering the current workload of the team and vacation, to do the fix in the RestAPI description and double-check this is the right fix will take roughly 2 to 3 weeks. Would this be ok for you?

**Comment by jmalobicky** [comment] 2018-08-15 18:08
@lmazuel That is fine, I have patched the file locally so it works. I will keep an eye on when the version bumps. Thanks for checking on this.

**Comment by lmazuel** [comment] 2018-09-11 18:44
Service team confirmed they hot-fixed the server to stop returning 201. SDK should work again unchanged. Thanks for the initial report!

**Closed by lmazuel** 2018-09-11 18:44 UTC
Labels: Application Insights, Swagger
