### ISSUE TITLE
[azure-mgmt-containerinstance] Error 'ImageRegistryCredential' object is not iterable

### ISSUE THREAD

**Issue by davidemiceli** [Azure/azure-sdk-for-python#9832] opened 2020-02-12 15:39 UTC
- **Package Name**: azure-mgmt-containerinstance
- **Package Version**:  1.5.0
- **Operating System**: Ubuntu
- **Python Version**: 3.7

**Describe the bug**

Returning a TypeError ("object is not iterable") error on creation of an Azure Container Instance of an image hosted on a Azure Container Registry:

```bash
Traceback (most recent call last):
  File "app.py", line 60, in <module>
    client.container_groups.create_or_update(resource_group_name, name, cgroup)
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 337, in create_or_update
    **operation_config
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 280, in _create_or_update_initial
    body_content = self._serialize.body(container_group, 'ContainerGroup')
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/msrest/serialization.py", line 583, in body
    errors = _recursive_validate(data_type, data_type, data)
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/msrest/serialization.py", line 133, in _recursive_validate
    return data.validate()
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/msrest/serialization.py", line 227, in validate
    validation_result += _recursive_validate(attr_name, attr_type, value)
  File "/home/someuser/anaconda3/envs/some-env/lib/python3.7/site-packages/msrest/serialization.py", line 125, in _recursive_validate
    for content in data:
TypeError: 'ImageRegistryCredential' object is not iterable
```

**To Reproduce**

1. Run a container from an image hosted on the Azure Container Registry.

Can use the following code:

```python
from azure.common.client_factory import get_client_from_auth_file
from azure.mgmt.containerinstance import ContainerInstanceManagementClient
from azure.mgmt.containerinstance.models.image_registry_credential import ImageRegistryCredential
from azure.mgmt.containerinstance.models import (
    ContainerGroup, Container, ContainerPort, Port, IpAddress,
    ResourceRequirements, ResourceRequests, ContainerGroupNetworkProtocol, OperatingSystemTypes
)

# Create the client
client = get_client_from_auth_file(ContainerInstanceManagementClient)

# Parameters
resource_group_name = '...'
location = 'westeurope'
memory, cpu = 1, 1
name = 'myimage'
image = 'myregistry.azurecr.io/samples/myimage:v1'
command = 'some command'
image_registry_credentials = ImageRegistryCredential(
    server='myregistry.azurecr.io',
    username='...',
    password='...'
)
# port = 3000
# environment_variables=

# Set memory and cpu
container_resource_requests = ResourceRequests(memory_in_gb=memory, cpu=cpu)
container_resource_requirements = ResourceRequirements(requests=container_resource_requests)

# Define the container
container = Container(
    name=name,
    image=image,
    resources=container_resource_requirements,
    command=command
    # ports=[ContainerPort(port=port)],
    # environment_variables=environment_variables
)

# Define the container group
cgroup = ContainerGroup(
    location=location,
    containers=[
        container
    ],
    restart_policy='Never',
    # Defaults os_type and ip_address for container group:
    os_type=OperatingSystemTypes.linux,
    # ip_address=IpAddress(
    #     type='public',
    #     ports=[Port(protocol=ContainerGroupNetworkProtocol.tcp, port=port)]
    # ),
    image_registry_credentials=image_registry_credentials
)

# Create the container group
client.container_groups.create_or_update(resource_group_name, name, cgroup)
```

**Expected behavior**

I expected the Azure container instance was created.

**Comment by kaerm** [comment] 2020-02-12 21:15
@davidemiceli thanks for reporting this, looping in the right team to take a look at this //cc: @nickzhums

**Comment by nickzhums** [comment] 2020-02-13 01:51
@RodgeFu can you take a look at this please, thanks!

**Comment by RodgeFu** [comment] 2020-02-13 01:56
@changlong-liu to have a look. thanks.

**Comment by changlong-liu** [comment] 2020-02-13 11:06
Hi @davidemiceli , the parameter image_registry_credentials of ContainerGroup(...) should be assigned as a list. In this case, would you please help to try below instead?
```
...
image_registry_credentials=[image_registry_credentials, ]
)
``` 
Thanks.

**Comment by RodgeFu** [comment] 2020-05-23 06:44
Got a thumb-up from davidemiceli :),  so assume the issue is fixed and close this one to clean up our issues. Feel free to reopen if needed. thanks.

**Closed by RodgeFu** 2020-05-23 06:44 UTC
Labels: Container Instances, Mgmt, bug, customer-reported
