### ISSUE TITLE
EventHub unexpectedly closes connection

### ISSUE THREAD

**Issue by claria** [Azure/azure-sdk-for-python#29961] opened 2023-04-19 13:34 UTC
- **Package Name**: azure-eventhub
- **Package Version**: 5.11.2
- **Operating System**:Ubuntu 22.04.2
- **Python Version**: Python 3.10.6

**Describe the bug**
We process messages from the builtin eventhub in iothub in 8 partitions. 

We use the checkpoint store, which updates the checkpoint every couple of minutes (we batch messages from a single device for a couple of minutes and always update the checkpoint to the oldest successfully event). Thus, the checkpoints lags always 10 minutes behind the current event.

Every couple of days (mostly at night or in the morning), we receive the following error:

[2023-04-19 06:09:24,631] azure.eventhub._pyamqp.aio._connection_async - ERROR   - END frame received on invalid channel. Closing connection.

This affects all partitions but the errors are spread over ~15 minutes. After the error, we continue to receive events, but we seem to have restarted at the oldest events in the affected partition, not at the checkpoint.

The following logs show the state before the error and after the error. The numbers are the sequence numbers, and the watermark is the difference of the latest sequence number to the current sequence number.

[2023-04-19 06:09:17,928]   - INFO    - Partition 2: Checkpoint: 182280527, Current: 182284438, Latest: 182284438, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 7: Checkpoint: 35976136, Current: 35980359, Latest: 35980359, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 1: Checkpoint: 165200412, Current: 165207858, Latest: 165207858, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 0: Checkpoint: 176898458, Current: 176908895, Latest: 176908895, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 5: Checkpoint: 38114026, Current: 38118748, Latest: 38118748, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 4: Checkpoint: 35067842, Current: 35075820, Latest: 35075820, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 3: Checkpoint: 154759160, Current: 154763232, Latest: 154763232, Watermark: 0
[2023-04-19 06:09:17,928]   - INFO    - Partition 6: Checkpoint: 43058778, Current: 43065847, Latest: 43065847, Watermark: 0

[2023-04-19 06:09:24,631] azure.eventhub._pyamqp.aio._connection_async - ERROR   - END frame received on invalid channel. Closing connection.
[2023-04-19 06:09:24,703] azure.eventhub._pyamqp.aio._connection_async - ERROR   - END frame received on invalid channel. Closing connection.

[2023-04-19 06:09:27,929]   - INFO    - Event rate: 62 evt/s. Pending batches: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 2: Checkpoint: 182281169, Current: 182284438, Latest: 182284438, Watermark: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 7: Checkpoint: 35976136, Current: 35980359, Latest: 35980359, Watermark: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 1: Checkpoint: 165200520, Current: 165207977, Latest: 165207977, Watermark: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 0: Checkpoint: 176898504, Current: 176909095, Latest: 176909095, Watermark: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 5: Checkpoint: 38114026, Current: 37137155, Latest: 38123512, Watermark: 986357
[2023-04-19 06:09:27,929]   - INFO    - Partition 4: Checkpoint: 35067842, Current: 35075928, Latest: 35075928, Watermark: 0
[2023-04-19 06:09:27,929]   - INFO    - Partition 3: Checkpoint: 154759234, Current: 153722074, Latest: 154767118, Watermark: 1045044
[2023-04-19 06:09:27,929]   - INFO    - Partition 6: Checkpoint: 43059007, Current: 43066009, Latest: 43066009, Watermark: 0

The consumer is created as follows:

```[python]
self.consumer = EventHubConsumerClient.from_connection_string(
            conn_str=config.EVENT_HUB_CONN_STR,
            consumer_group=config.EVENT_HUB_CONSUMER_GROUP,
            eventhub_name=config.EVENT_HUB_NAME,
            checkpoint_store=self.checkpoint_store,
            uamqp_transport=False
        )
```

And we run the receiver:

```[python]
await self.consumer.receive_batch(on_event_batch=self._on_event_batch,
                                                on_partition_close=self.on_partition_close,
                                                on_partition_initialize=self.on_partition_initialize,
                                                starting_position='-1',
                                                starting_position_inclusive=False,
                                                track_last_enqueued_event_properties=True,
                                                prefetch=1000,
                                                partition_id=partition_id,
                                                on_error=self.on_error)
```

Am i correct that the starting_position parameter is only used if there is no checkpoint? Otherwise this could at least explain this behaviour. When i stop and restart the service, the event consumer starts at the expected checkpoint .

**Comment by xiangyan99** [comment] 2023-04-19 15:51
Thanks for the feedback, we’ll investigate asap.

**Comment by kashifkhan** [comment] 2023-04-19 17:19
Hi @claria , you are correct that `starting_point` comes in to play when there is no checkpoint store at all. What it seems like is that the connection drops for some reason and during retry when connection is re-established the `starting_point` is using -1 and therefore going back to the beginning. When you are stopping and restarting, with a fresh client, its doing the proper flow to make sure the check point is used. 

Thats my initial guess based on the logs and whats been described, Ill have more once I repro the issue on my side.

**Comment by kashifkhan** [comment] 2023-04-24 14:09
@claria would you be able to provide us with debug logs please? Would really be interested to see whats happening behind the scenes as we are not able to reproduce that error in our environment, can help us further with that.

**Comment by claria** [comment] 2023-04-24 14:59
Hi @kashifkhan,

if you tell me what log levels you want me to set in which loggers i am glad to further assist.

**Comment by kashifkhan** [comment] 2023-04-24 15:06
Thank you @claria, just need you to set the following please 

with the `logging_enable` that is optional, it will output whats going across the wire. If there is sensitive information, I can provide you my email to send the info otherwise its optional :)

```python
import logging
import sys

logger = logging.getLogger("azure.eventhub")
logger.setLevel(logging.DEBUG)

self.consumer = EventHubConsumerClient.from_connection_string(
            conn_str=config.EVENT_HUB_CONN_STR,
            consumer_group=config.EVENT_HUB_CONSUMER_GROUP,
            eventhub_name=config.EVENT_HUB_NAME,
            checkpoint_store=self.checkpoint_store,
            uamqp_transport=False,
            logging_enable=True,
        )

```

**Comment by claria** [comment] 2023-04-24 15:46
Changed the loglevels. Will report back to you with the logs when it happens the next time.

**Comment by claria** [comment] 2023-04-25 05:47
Hi @kashifkhan,

here are the logs when it happened again. I can send you the logs over the complete runtime when you send me your email, since it contains endpoints, namespaces etc.
```
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 3: Checkpoint: 161122035, Current: 161123161, Latest: 161123161, Watermark: 0, Checkpoint age: 0:10:05.084000
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 1: Checkpoint: 171565008, Current: 171566056, Latest: 171566056, Watermark: 0, Checkpoint age: 0:10:18.394000
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 4: Checkpoint: 41240695, Current: 41242131, Latest: 41242131, Watermark: 0, Checkpoint age: 0:10:03.377000
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 5: Checkpoint: 44394738, Current: 44395705, Latest: 44395705, Watermark: 0, Checkpoint age: 0:09:59.959000
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 6: Checkpoint: 50068325, Current: 50069253, Latest: 50069253, Watermark: 0, Checkpoint age: 0:10:02.549000
[2023-04-24 23:07:59,766] message_batcher.queue_handler  - INFO    - Partition 0: Checkpoint: 183622955, Current: 183624742, Latest: 183624742, Watermark: 0, Checkpoint age: 0:10:57.686000
[2023-04-24 23:07:59,767] message_batcher.queue_handler  - INFO    - Partition 2: Checkpoint: 188697935, Current: 188699248, Latest: 188699248, Watermark: 0, Checkpoint age: 0:10:04.179000
[2023-04-24 23:07:59,767] message_batcher.queue_handler  - INFO    - Partition 7: Checkpoint: 42380570, Current: 42382727, Latest: 42382727, Watermark: 0, Checkpoint age: 0:10:05.961000

[2023-04-24 23:08:01,709] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.ERROR: 6>
[2023-04-24 23:08:01,709] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link receiver state changed: <LinkState.ATTACHED: 3> -> <LinkState.ERROR: 6>
[2023-04-24 23:08:01,709] azure.eventhub._pyamqp.aio._cbs_async - INFO    - CBS error occurred.
[2023-04-24 23:08:01,710] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.ERROR: 6>
[2023-04-24 23:08:01,710] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link sender state changed: <LinkState.ATTACHED: 3> -> <LinkState.ERROR: 6>
[2023-04-24 23:08:01,710] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACHED: 3> -> <LinkState.ERROR: 6>
[2023-04-24 23:08:01,710] azure.eventhub._pyamqp.aio._session_async - INFO    - Session state changed: <SessionState.MAPPED: 3> -> <SessionState.END_RCVD: 5>
[2023-04-24 23:08:01,711] azure.eventhub._pyamqp.aio._session_async - INFO    - Session state changed: <SessionState.END_RCVD: 5> -> <SessionState.UNMAPPED: 0>
[2023-04-24 23:08:01,711] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.OPENED: 9> -> <ConnectionState.DISCARDING: 12>
[2023-04-24 23:08:01,711] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.DISCARDING: 12> -> <ConnectionState.END: 13>
[2023-04-24 23:08:01,711] azure.eventhub._pyamqp.aio._connection_async - ERROR   - END frame received on invalid channel. Closing connection.
[2023-04-24 23:08:01,712] azure.eventhub._pyamqp.aio._session_async - INFO    - Session state changed: <SessionState.UNMAPPED: 0> -> <SessionState.END_SENT: 4>
[2023-04-24 23:08:01,799] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: None -> <ConnectionState.START: 0>
[2023-04-24 23:08:01,801] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.START: 0> -> <ConnectionState.HDR_SENT: 2>
[2023-04-24 23:08:01,801] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.HDR_SENT: 2>
[2023-04-24 23:08:01,801] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.HDR_SENT: 2> -> <ConnectionState.OPEN_PIPE: 4>
[2023-04-24 23:08:01,802] azure.eventhub._pyamqp.aio._session_async - INFO    - Session state changed: <SessionState.UNMAPPED: 0> -> <SessionState.BEGIN_SENT: 1>
[2023-04-24 23:08:01,802] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
[2023-04-24 23:08:01,802] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link receiver state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
[2023-04-24 23:08:01,802] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
[2023-04-24 23:08:01,803] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link sender state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
[2023-04-24 23:08:01,803] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.OPEN_PIPE: 4> -> <ConnectionState.OPEN_SENT: 7>
[2023-04-24 23:08:01,854] azure.eventhub._pyamqp.aio._connection_async - INFO    - Connection state changed: <ConnectionState.OPEN_SENT: 7> -> <ConnectionState.OPENED: 9>
[2023-04-24 23:08:01,905] azure.eventhub._pyamqp.aio._session_async - INFO    - Session state changed: <SessionState.BEGIN_SENT: 1> -> <SessionState.MAPPED: 3>
[2023-04-24 23:08:01,956] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
[2023-04-24 23:08:01,956] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link receiver state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
[2023-04-24 23:08:02,007] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
[2023-04-24 23:08:02,007] azure.eventhub._pyamqp.aio._management_link_async - INFO    - Management link sender state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>
[2023-04-24 23:08:02,007] azure.eventhub._pyamqp.aio._cbs_async - INFO    - CBS completed opening with status: <ManagementOpenResult.OK: 1>
[2023-04-24 23:08:02,212] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
[2023-04-24 23:08:02,216] azure.eventhub._pyamqp.aio._link_async - INFO    - Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.ATTACHED: 3>


[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 3: Checkpoint: 161122035, Current: 161123184, Latest: 161123184, Watermark: 0, Checkpoint age: 0:10:14.960000
[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 1: Checkpoint: 171565008, Current: 171566080, Latest: 171566080, Watermark: 0, Checkpoint age: 0:10:27.728000
[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 4: Checkpoint: 41240695, Current: 41242156, Latest: 41242156, Watermark: 0, Checkpoint age: 0:10:13.680000
[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 5: Checkpoint: 44394756, Current: 44395720, Latest: 44395720, Watermark: 0, Checkpoint age: 0:10:04.993000
[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 6: Checkpoint: 50068338, Current: 50069266, Latest: 50069266, Watermark: 0, Checkpoint age: 0:09:59.205000
[2023-04-24 23:08:09,767] message_batcher.queue_handler  - INFO    - Partition 0: Checkpoint: 183623147, Current: 183624771, Latest: 183624771, Watermark: 0, Checkpoint age: 0:10:03.581000
[2023-04-24 23:08:09,768] message_batcher.queue_handler  - INFO    - Partition 2: Checkpoint: 188697959, Current: 188699259, Latest: 188699259, Watermark: 0, Checkpoint age: 0:10:07.133000
[2023-04-24 23:08:09,768] message_batcher.queue_handler  - INFO    - Partition 7: Checkpoint: 42380570, Current: 42116745, Latest: 42382768, Watermark: 266023, Checkpoint age: -1 day, 16:49:28.199000



```

**Comment by claria** [comment] 2023-04-25 05:58
Hi @kashifkhan i just noticed that i had configured my log handlers to info level so you are missing the debug logs. However when i restarted with debug log level, i noticed it generates log entries for each events, which just generates tons of gb of logs.

So i set this logger to info level :

logging.getLogger('azure.eventhub._pyamqp.aio._receiver_async').setLevel(logging.INFO)

**Comment by claria** [comment] 2023-04-27 05:40
Hi @kashifkhan, attached you will find the debug logs. I attached also logs from the minutes before the incident, the error happens at [2023-04-25 23:31:04,751].

Regarding the jumpback of the checkpoint to the beginning, i have a suspicion. I am using the async BlobCheckpointStore and pass the instance to the eventhub (async) task. However, i am not updating the checkpoints from the receiver side (e.g. every 10000 events or so)

I am having a separate task which checks which events were successfully processed and updates the checkpoints accordingly. This task receives the same instance of the BlobCheckpointStore. Maybe this is related to the problem that the event_receive does not correctly restart at last checkpoint after a connection loss.


[eventhub_logs.txt](https://github.com/Azure/azure-sdk-for-python/files/11339828/eventhub_logs.txt)

**Comment by kashifkhan** [comment] 2023-04-27 13:56
Hi @claria, thank you so much for sending the debug logs. From the looks of it the connection loss is happening due to inactivity, and reconnecting which is normal (unless there is a steady stream of events and no "downtime" ). The issue on our end is that we are not able to reproduce the `end frame received on an invalid channel` error, so maybe this can help. Also, good to know that its a separate task that is updating the checkpoints using the same instance of the checkpoint store. 

So far in our tests here the checkpoints are resuming properly after disconnects or interrupts, so I'm also wondering if sharing the same instance of the store is causing some issues. Would you be able to test by passing in a new instance of checkpoint store into your updater, this way there is one checkpoint store updating and another one reading?

**Comment by claria** [comment] 2023-04-28 07:21
Hi @kashifkhan,

i can not completely understand the reason due to inactivity. 
For me it looks like the connection is closed due to inactivity here:

[2023-04-25 23:31:04,751] azure.eventhub._pyamqp.aio._link_async - DEBUG   - <- DetachFrame(handle=0, closed=True, error=[b'amqp:connection:forced', b"The connection was inactive for more than the allowed 240000 milliseconds and is closed by container '3977945755c747a1877e2c553b95b9df_G14'.", None])

However the state at 2023-04-25 23:31:01

[2023-04-25 23:31:01,829] message_batcher.queue_handler  - INFO    - Partition 5: Checkpoint: 45466666, Current: 45467525, Latest: 45467525, Watermark: 0, Checkpoint age: 0:10:20.984000
[2023-04-25 23:31:01,829] message_batcher.queue_handler  - INFO    - Partition 1: Checkpoint: 172642919, Current: 172644329, Latest: 172644329, Watermark: 0, Checkpoint age: 0:10:54.419000
[2023-04-25 23:31:01,829] message_batcher.queue_handler  - INFO    - Partition 4: Checkpoint: 42211144, Current: 42212282, Latest: 42212282, Watermark: 0, Checkpoint age: 0:10:32.947000
[2023-04-25 23:31:01,830] message_batcher.queue_handler  - INFO    - Partition 0: Checkpoint: 184721163, Current: 184721341, Latest: 184721341, Watermark: 0, Checkpoint age: 0:10:01.171000
[2023-04-25 23:31:01,830] message_batcher.queue_handler  - INFO    - Partition 3: Checkpoint: 162165316, Current: 162167066, Latest: 162167066, Watermark: 0, Checkpoint age: 0:10:04.778000
[2023-04-25 23:31:01,830] message_batcher.queue_handler  - INFO    - Partition 6: Checkpoint: 51203461, Current: 51204195, Latest: 51204195, Watermark: 0, Checkpoint age: 0:10:04.861000
[2023-04-25 23:31:01,830] message_batcher.queue_handler  - INFO    - Partition 2: Checkpoint: 189784103, Current: 189785580, Latest: 189785580, Watermark: 0, Checkpoint age: 0:10:12.326000
[2023-04-25 23:31:01,830] message_batcher.queue_handler  - INFO    - Partition 7: Checkpoint: 43465045, Current: 43466913, Latest: 43466913, Watermark: 0, Checkpoint age: 0:10:04.091000

and the state at 2023-04-25 23:30:51

[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 5: Checkpoint: 45466666, Current: 45467513, Latest: 45467513, Watermark: 0, Checkpoint age: 0:10:11.264000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 1: Checkpoint: 172642919, Current: 172644305, Latest: 172644305, Watermark: 0, Checkpoint age: 0:10:44.840000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 4: Checkpoint: 42211144, Current: 42212265, Latest: 42212265, Watermark: 0, Checkpoint age: 0:10:22.633000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 0: Checkpoint: 184721149, Current: 184721339, Latest: 184721339, Watermark: 0, Checkpoint age: 0:09:41.078000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 3: Checkpoint: 162165222, Current: 162167038, Latest: 162167038, Watermark: 0, Checkpoint age: 0:10:26.893000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 6: Checkpoint: 51203445, Current: 51204169, Latest: 51204169, Watermark: 0, Checkpoint age: 0:10:09.612000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 2: Checkpoint: 189784103, Current: 189785533, Latest: 189785533, Watermark: 0, Checkpoint age: 0:10:02.372000
[2023-04-25 23:30:51,828] message_batcher.queue_handler  - INFO    - Partition 7: Checkpoint: 43464870, Current: 43466875, Latest: 43466875, Watermark: 0, Checkpoint age: 0:11:18.716000


Current is the last event passed by on_event callback. And all event sequence numbers changed. So i would suspect all connections to be active and not be idling.

Regarding the checkpoint issue: Will try your suggestion.

**Comment by claria** [comment] 2023-05-02 21:34
In the meantime, i checked again with separate checkpoint stores for updating and reading.

It does not help.

**Comment by kashifkhan** [comment] 2023-05-03 13:37
thanks for the update @claria. If its failing with separate checkpoint stores, then its definitely an issue with the client.

**Comment by claria** [comment] 2023-05-04 09:03
Hi @kashifkhan,

over the last two days i was running with uamqp instead of pyamqp and there everything worked perfectly.

I even tried to provoke the checkpoint issue by killing the tcp connection for one partition, but it looks like uamqp just recovered the connection and continued at the current event and did not even use the checkpoint. (My checkpoints are always around 10 minutes lagging behind) but the processing continued at the current event with the new connection.

**Comment by macieyng** [comment] 2023-05-19 10:37
We've experienced similar issue with `azure-servicebus==7.10`. 
`END frame received on invalid channel. Closing connection. (/usr/local/lib/python*/site-packages/azure/servicebus/_pyamqp/_connection.py:_incoming_end)`

I start to think that moving to _pyamqp should be a part of 8.0 release. I'll downgrade my servicebus to 7.9, but will look into logs and provide you with some more info on my case.

**Comment by kashifkhan** [comment] 2023-06-19 18:28
Just wanted to update this issue and apologies for the long delay in between responses. I am working on resolving this issue during this sprint. 

This is happening due to a low level issue where the service issues a disconnect after the timeout period from the service has been reached.  

@macieyng for the service bus issue, can you create a new issue please and if you have any logs that can help it would be great.

**Comment by kashifkhan** [comment] 2023-06-26 18:48
I have a PR to fix the end channel error that is being received. This error prevents a proper retry loop happening and cause issues when a new connection is created #30860

**Comment by macieyng** [comment] 2023-07-02 08:30
@kashifkhan do we still need to open another issue for the service bus then?

**Comment by kashifkhan** [comment] 2023-07-05 13:28
> @kashifkhan do we still need to open another issue for the service bus then?

@macieyng No, the upcoming release for Service Bus & Event Hub will have this bug fixed. The linked PR has details, but the error shows up when there is no network activity happening between the client & server for over 60 seconds, causing the service to issue a disconnect.

**Comment by kashifkhan** [comment] 2023-07-05 13:54
@claria We were not able to reproduce the checkpoint store issue on our end, but did notice that the end frame on incorrect channel could cause some issues when going in to a retry loop. Would you be able to test in your environment using my PR to see if the issue surfaces after this fix? 

The next release will also have some other improvements regarding keep alives etc. which is in another PR.

**Comment by macieyng** [comment] 2023-07-17 15:58
@kashifkhan we've updated servicebus to 7.11.1 and now we're not seeing END frame errors like we used to, but instead we're seeing a lot of `Connection closed with error: [b'amqp:connection:forced', b"The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'de9c0655b1684a31b24a94d4a733ed5e_G4S2'.", None]` errors. That definitely is coming from https://github.com/Azure/azure-sdk-for-python/blob/ee85ddd394052efaaa35352e2567b39b6d2a215e/sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp/_connection.py#L478-L485.

I'm not sure whether this should be considered an error message, but I don't really understand how this amqp protocol works. 

I want to be clear about one thing that may have something to do with it: we create an instance of ServiceBusClient and use it outside of context manager, and the same for topic or queue senders. The reason for this approach is performance - we prefer connection being closed due to inactivity over `manual` connection closing (like with calling `close` or context manager). This seems reasonable to us, because other solution would be to initialize service bus worker thread that would monitor connection time and send messages asynchronously.

I would be very grateful for your support 🙏

**Comment by kashifkhan** [comment] 2023-07-17 17:40
Hi @macieyng, glad to hear that the previous errors are now gone. Just so that I understand are you asking that if ERROR is the right level for that message ? 

This error happens from the service side as there is no communication between the client and itself for 24,000ms, so it times out. the location that you linked is where any other errors come from the service would also be logged.

**Comment by macieyng** [comment] 2023-07-18 20:31
Yes, @kashifkhan this is exactly what I wanted to ask. Sorry if that was not clear on my end. 

Most errors coming from 3rd party libraries I treat as something I should probably take care of or there is an issue I should resolve somehow. In this case, I don't think I could do anything more, so on one hand I would silence this logger, but other error may occur that I wouldn't know about.

Given that, there's a possibility that my whole solution is badly implemented and that's why this error is showing up.

**Comment by kashifkhan** [comment] 2023-07-19 13:19
@macieyng no worries about that :) thanks for clarifying. I just wanted to make sure we were on the same page

Let me check with the team on thoughts as that error falls into the category of one that will cause the client library to try and reconnect. If its expected that there will be instances where there is a quiet period, then its nothing to worry about otherwise it can also indicate some network issues. 

In the meantime I would encourage you to open another issue as this one is a different ask from the original thread. Itll help in tracking things :)

**Comment by claria** [comment] 2023-07-19 13:31
@kashifkhan 

I will try as soon as possible to reproduce the issue with the checkpoint service  using the latest version. However, this will take a couple of days.

**Comment by macieyng** [comment] 2023-07-20 12:44
> In the meantime I would encourage you to open another issue as this one is a different ask from the original thread. Itll help in tracking things :)
✅ 👉 https://github.com/Azure/azure-sdk-for-python/issues/31229

**Comment by kashifkhan** [comment] 2023-08-28 19:29
Hi @claria , checking in to see if the issue with the checkpoint restarting still exists. We fixed a bug in the last released of EH that I think will resolve this.

**Closed** 2023-09-19 01:22 UTC
Labels: bug, Event Hubs, Client, customer-reported, no-recent-activity, needs-author-feedback, Messaging
