### ISSUE TITLE
Unable to resolve the DataFactory.models LinkedServiceResource #datafactory API 

### ISSUE THREAD

**Issue by rkworkzone** [Azure/azure-sdk-for-python#26201] opened 2022-09-14 03:28 UTC
I have migrated from  
azure-mgmt-datafactory = "==2.6.0" to azure-mgmt-datafactory = "==2.7.0"

getting following error in PyCharm in 2.7.0 version. However, there is no issue in 2.6.0 version. Unable to use any module in this library. 

Unresolved reference 'LinkedServiceResource' 

Please find the code snippet. 
------------
import sys
from azure.mgmt.datafactory.models import *
ls_azure_storage = LinkedServiceResource(
        properties=AzureBlobFSLinkedService(type='AzureBlobFS',
                                            connect_via=IntegrationRuntimeReference(type="IntegrationRuntimeReference",
                                                                                    reference_name=
                                                                                    pconfs['PIPELINES']['ls_adls'][
                                                                                        'ir']),
                                            url="https://{sa}.dfs.core.windows.net".format(sa=confs['adls'])))
    ls = adf_client.linked_services.create_or_update(confs['rg'], confs['adf'], pconfs['PIPELINES']['ls_adls']['name'],
                                                     ls_azure_storage)
------------
PipEnv file:

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
azure-mgmt-resource = "==21.1.0"
azure-mgmt-datafactory = "==2.7.0"
azure-identity = "*"
setuptools = "*"
wheel = "*"
twine = "*"
pyyaml = "*"

[dev-packages]

[requires]
python_version = "3.9"

----------------------------------------

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/29694593/190051968-d9303305-dbd8-4d78-9e80-32c954f7b0a6.png">

<img width="964" alt="image" src="https://user-images.githubusercontent.com/29694593/190051873-4c59be0d-19bf-47be-80ba-1085b19a0eb2.png">

**Comment by kristapratico** [comment] 2022-09-14 16:27
Hi @rkworkzone thanks for your detailed issue. Just checking - does the error actually occur at runtime or does it just show up in Pycharm like in your screenshots?

**Comment by rkworkzone** [comment] 2022-09-14 17:54
Hi @kristapratico, 
It does show up in the Pycharm as in the screenshots.

**Comment by rkworkzone** [comment] 2022-09-14 17:56
Hi @kristapratico, 
When I downgrade the version to <2.6 there are no errors.

**Comment by msyyc** [comment] 2022-09-15 06:34
Hi @rkworkzone Thanks for your feedback. We can reproduce it locally and will discuss about how to handle it: https://github.com/Azure/autorest.python/issues/1444.
nit: vscode works well and you can have a try

**Comment by rkworkzone** [comment] 2022-09-16 12:19
@msyyc, @SaurabhSharma-MSFT 
Thanks for the quick response. 
Unfortunately, we can't use VSCODE in our org. We must handle it in PyCharm IDE. 
Regards,
RK.

**Comment by msyyc** [comment] 2022-09-19 02:10
Hi @rkworkzone I think it is more Pycharm's bug than SDK's since other IDE like vscode works well. I advise you report a bug for Pycharm: https://www.jetbrains.com/help/pycharm/reporting-issues.html#report-an-issue

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-21 17:13
@rkworkzone We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-09-21 17:13 UTC
Labels: question, Data Factory, Mgmt, customer-reported, issue-addressed, CXP Attention
