### ISSUE TITLE
[Bug] Multiple partition key on cosmos db is not supported/has a bug in python cosmos sdk

### ISSUE THREAD

**Issue by kaushikc3** [Azure/azure-sdk-for-python#30670] opened 2023-06-07 17:12 UTC
We were trying to use cosmos db with multiple partition keys and the python code kept failing with an error "ValueError: Unsupported paths count.".

We did a big of analysis on this and found out the root cause of the problem. It seems to be coming in from the following piece of code under azure / cosmos / _base.py.

# Parses the paths into a list of token each representing a property
def ParsePaths(paths):
    if len(paths) != 1:
        raise ValueError("Unsupported paths count.")

Stack Trace below:
----------------------------------------------------------------------------------------------------------------------------------------------------
File "C:\Users\kramac3\Source\Repos\misc\python-comp-key-trial\quickTry.py", line 16, in create_pad
    cases_container.create_item(pad_doc.__dict__)
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\cosmos\container.py", line 566, in create_item
    result = self.client_connection.CreateItem(
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\cosmos\_cosmos_client_connection.py", line 1125, in CreateItem
    options = self._AddPartitionKey(database_or_container_link, document, options)
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\cosmos\_cosmos_client_connection.py", line 2645, in _AddPartitionKey
    partitionKeyValue = self._ExtractPartitionKey(partitionKeyDefinition, document)
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\cosmos\_cosmos_client_connection.py", line 2654, in _ExtractPartitionKey
    partition_key_parts = base.ParsePaths(partitionKeyDefinition.get("paths"))
  File "C:\Users\kramac3\AppData\Roaming\Python\Python39\site-packages\azure\cosmos\_base.py", line 607, in ParsePaths
    raise ValueError("Unsupported paths count.")
----------------------------------------------------------------------------------------------------------------------------------------------------

This function needs to be changed to support extraction of multiple partition keys.

**Comment by kashifkhan** [comment] 2023-06-07 20:20
Thank you for the feedback @kaushikc3 . We will investigate and get back to you asap.

**Comment by simorenoh** [comment] 2023-06-07 21:11
Hi @kaushikc3, thank you for using our SDK. Were you trying to make use of hierarchical partition keys? https://learn.microsoft.com/en-us/azure/cosmos-db/hierarchical-partition-keys?tabs=net-v3%2Cbicep

Just wondering what you were trying to do here so we can understand on our end. Do you have samples of this working on any of the other SDKs?

**Comment by kaushikc3** [comment] 2023-06-07 21:16
Sorry, to answer your question. Yes, we have the nodejs code working just fine with the hierarchical partition keys. But, we are blocked with python sdk not working. .Net, Java, Nodejs - all seem to be doing fine. We have one particular piece where NodeJS and Python both work on cosmos db documents.

**Comment by simorenoh** [comment] 2023-06-07 21:18
@kaushikc3 I see - yeah that is by design, our Python SDK does not yet support hierarchical partitioning. We are currently working on those changes, and they should be out by July. We'll keep you posted on this as the feature is developed/ released.

**Comment by lmazuel** [comment] 2023-06-12 20:52
@simorenoh let's also update https://feedback.azure.com/d365community/idea/286ff8dc-dbfa-ed11-a81c-000d3a0d3715 when it's out. Thanks!

**Comment by bambriz** [comment] 2023-07-13 17:27
@kaushikc3 the pr for subpartitioning is in review, should be available by end of July. [PR 31121](https://github.com/Azure/azure-sdk-for-python/pull/31121)

**Comment by aksjadha-amdocs** [comment] 2023-08-03 12:15
I am also facing the same issue, but meanwhile is there any alternative or workaround for this?
thanks in advance.

**Comment by bambriz** [comment] 2023-10-10 17:39
@kaushikc3 @aksjadha-amdocs PR to support  subpartitioning (Multiple partition keys) has been merged see https://github.com/Azure/azure-sdk-for-python/pull/31121

**Comment by bambriz** [comment] 2023-10-18 19:40
Hello @kaushikc3  @aksjadha-amdocs  I am happy to announce that Sub partitioning has been released on Version 4.5.2b1. Please note that MultiHash Partition keys in the python SDK are managed as a list.

**Closed by bambriz** 2023-10-18 19:40 UTC
Labels: question, Cosmos, Service Attention, Client, customer-reported, issue-addressed
