### ISSUE TITLE
[Form Recognizer] "Could not access Azure blob storage account." in USGOV and China Clouds

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-python#22379] opened 2022-01-07 09:00 UTC
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the test [test_custom_forms_from_url_async.py::TestCustomFormsFromUrlAsync::test_custom_form_continuation_token](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_custom_forms_from_url_async.py#L161), it runs failed and the error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1278164&view=logs&j=c9b636ae-c3c7-55c0-c769-7777f7222b9a&t=117f2755-ff68-5a46-ec6f-d3be490739f1):
![image](https://user-images.githubusercontent.com/57166602/148518200-d4a05649-590b-492c-b900-b7935bb44e64.png)
test([test_content_from_url.py::TestContentFromUrl::test_content_multipage_url](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/tests/test_content_from_url.py#L124)) error message:
![image](https://user-images.githubusercontent.com/57166602/148518342-02bf7072-f441-4a2d-ae2d-07356e1022c8.png)

**Expected Behavior:**
Please create Azure storage account and upload blobs to the corresponding container in **UsGov** and **China** Clouds.

@benbp, @jameszliao-msft, @lmazuel, @meeraharidasa , @mayurid, @catalinaperalta for notification.

**Comment by catalinaperalta** [comment] 2022-01-11 00:52
Hi @v-xuto! I'm checking whether we already have storage accounts available with these files for the USGov and China clouds. Will let you know soon!

**Comment by catalinaperalta** [comment] 2022-01-15 01:27
Hi @v-xuto, if you leverage `sub-config-gov-test-resources` in your test configuration yaml instead of the current `sub-config-azure-cloud-test-resources` that should set everything up and work as expected with the test_resources.json if you're using that for testing. See how we set up our subscription configuration [here in tests.yml](https://github.com/Azure/azure-sdk-for-python/blob/c9dce46185a8125194f633ee3481542ad4c7d6ce/sdk/formrecognizer/tests.yml#L17).

**Comment by v-xuto** [comment] 2022-01-19 07:53
@catalinaperalta I have already added `sub-config-gov-test-resources` and `sub-config-cn-test-resources` in [formrecognizer/tests.yml](https://github.com/Azure/azure-sdk-for-python/blob/3085e83f6a2b7e7276e1044e4a80feed74e8081e/sdk/formrecognizer/tests.yml) in my [PR](https://github.com/Azure/azure-sdk-for-python/pull/20082). For more details about pipeline results please click [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1307769&view=logs&j=d84cc36b-4187-53df-0252-2bebbda51dd2&t=1c562075-57ff-5fe6-3a04-e4de45127eff). 

@catalinaperalta @benbp Through the error message and local testing, maybe because not all containers and blobs are created in the storage account (`azuresdktrainingdata`) in **UsGov** and **China**, please help to create containers and upload blobs, make it the same as the storage account(`azuresdktrainingdata`) on **Public**.

Or give me the subscription permission of the storage account (`azuresdktrainingdata`) on **Public**,  and I will create the required containers and upload blobs in **UsGov** and **China**.

**Comment by v-xuto** [comment] 2022-01-29 06:17
@benbp Who can help me to create containers and upload blobs in Usgov and china? Or give me the subscription permission of the storage account (azuresdktrainingdata) on Public.

**Comment by catalinaperalta** [comment] 2022-01-31 17:17
Hey @v-xuto, I requested access myself to the USGov cloud, but I am still waiting for permission to access it. Once I have it, I can check whether the container has all of the necessary content uploaded. I will check with @benbp about who can be granted permission.

**Comment by benbp** [comment] 2022-01-31 17:34
@catalinaperalta and I worked to grant access to USGov.

**Comment by catalinaperalta** [comment] 2022-01-31 19:13
I've checked the storage container in USGov and there were several missing blobs. I have uploaded those blobs that were missing and are used in our tests. @v-xuto please let me know if the tests in USGov can pass now. 

As for the storage container in the China cloud, I am still working with Ben to get access. Will let you know when I have an update with that one.

**Comment by v-xuto** [comment] 2022-02-08 08:56
@catalinaperalta  I rerun the weekly pipeline and found that there are still some missing blobs, such as: `testingdata/label_table_variable_rows1.pdf`. For more details please click [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1348883&view=logs&j=d2e848db-263f-5203-2100-103b0dfc34a3&t=b4a04cf1-3294-507a-09e7-d1bc997cc43d).

@benbp Could you give me the subscription permission of the storage account (`azuresdktrainingdata`) on Public? I check and upload blobs, maybe more efficient. Because I have the permission of `UsGov` and `China`.

**Comment by catalinaperalta** [comment] 2022-02-10 22:58
@v-xuto on Tuesday I updated the `testingdata` container to include missing files that weren't added from the public cloud. However, I did notice several other differences between the public cloud containers and the us gov containers. I will be correcting these differences today. I will let you know once those updates are complete.

**Comment by catalinaperalta** [comment] 2022-02-24 00:21
@v-xuto sorry for the delay, the US Gov containers look complete to me now. I've been trying to upload blobs to the China cloud containers but I'm having access issues, I'll talk to Ben about it. If you already have access to both the `USGov` and `China` cloud accounts you could start copying the blobs from USGov to the China cloud containers.

**Comment by zedy-wj** [comment] 2022-02-24 09:26
@catalinaperalta - We have access to both the `UsGov `and `China` cloud accounts, and we have uploaded the blobs in `China` cloud. We've tried all the tests locally and pass.

But UsGov and China's tests in the pipeline always fail. It's the latest result in pipeline, you can get the details at [here ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1384698&view=results).

Error description: 
![image](https://user-images.githubusercontent.com/81678720/155490793-b383672e-7767-4735-abc5-db83b7184b79.png)

We are confused about the difference in results locally and in the pipeline, and not clear what happened in UsGov and China clouds. Could you help to take a look? Thanks.

**Comment by catalinaperalta** [comment] 2022-02-25 19:48
@zedy-wj - Thanks for uploading the blobs to the `China` cloud account. I triggered a build yesterday and have been looking through the results. I'm not seeing errors related to missing files anymore in the storage accounts. I also just checked again and saw that @v-xuto triggered a couple of builds yesterday and US Gov passed, as well as several environments in the China cloud. The containers for both the US Gov and China clouds seem complete now with the tests passing. The errors you're seeing now are due to another issue that I'm looking into where some tests fail occasionally when downloading images or attempting to access the storage blob accounts, I will let you know when I have a solution or workaround.

**Comment by zedy-wj** [comment] 2022-03-11 10:06
@catalinaperalta - 
1. For live tests: `Error: The file is corrupted or format is unsupported.` After we increase the expired time of sastoken, it is no longer reproduced.
![image](https://user-images.githubusercontent.com/81678720/157840469-840564c8-53a3-4d2a-a3be-c26f87682d6a.png)

2. For samples tests: `some tests fail occasionally when downloading images or attempting to access the storage blob accounts.` We try to add retries(now the number is 5 times) in the tests to make the results of the pipeline more stable, and it also no longer has such errors at this time, but we don't think it's the best solution. Do you have a better suggestion?

For more details click here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1420526&view=results

**Comment by catalinaperalta** [comment] 2022-03-12 01:11
@zedy-wj I have implemented a similar workaround by adding a sleep time between each test. The concern with the retries is that the service may still be affected with increased requests, but since it is for the samples which are a limited number of calls, I think that solution can remain for now and we can revert once the environments are more stable. I do agree that these are not the best solutions and I am following up with the service team to get these environments more stable. A question though, were smaller increases in the expire time of the SAS token not effective?

**Comment by zedy-wj** [comment] 2022-03-14 01:54
@catalinaperalta - Since the service's response time on the UsGov and China clouds is also unstable, we set the timeout time for the form recognizer pipeline to be 400 minutes, sometimes even timeout, so it is set for 8 hours, but for now, 5-6 hours after stabilization is enough.

**Comment by zedy-wj** [comment] 2022-03-22 01:50
@catalinaperalta - Most of the environments in UsGov have timeouts, and we set the timeout to 8 hours. After investigation, it was found that the current running of a single test for up to an hour caused the current timeout. Could you help to take a look?

**Comment by catalinaperalta** [comment] 2022-03-24 03:30
@zedy-wj this seems to be a service issue. I will reach out to them and work out what the problem is. I will update here when I have more information.

**Comment by catalinaperalta** [comment] 2022-04-01 17:29
@zedy-wj the service team says the issue has been mitigated. Please let me know if you are seeing that? Thanks!

**Comment by zedy-wj** [comment] 2022-04-02 02:23
@catalinaperalta - FormRecognizer is currently able to pass stably on UsGov and China clouds, thank you for your help, we will close this issue, if the same problem occurs again, we will reopen it.

**Closed** 2022-04-02 02:24 UTC
Labels: Client, Cognitive - Form Recognizer, test-sovereign-cloud
