### ISSUE TITLE
HTTP transport has already been closed only on ClientSecretCredential

### ISSUE THREAD

**Issue by erpola** [Azure/azure-sdk-for-python#38264] opened 2024-11-01 17:05 UTC
- **Package Name**:  azure-keyvault
- **Package Version**: 4.2.0
- **Operating System**: ubuntu
- **Python Version**:  3.10.12

**Describe the bug**
When attempting to iterate over the AsyncItemPaged[SecretProperties] content I receive the following error

`ERROR:root:An error occurred: HTTP transport has already been closed. You may check if you're calling a function outside of the "async with" of your client creation, or if you called `await close()` on your client already.`

**To Reproduce**

**while using ClientSecretCredential**
1.  `secrets = client.list_properties_of_secrets()`
2.  `secret_names = [s.name async for s in secrets]`

**Expected behavior**
Gather and iterate over the secrets stored inside of the targeted key vault

**Screenshots**
![Image](https://github.com/user-attachments/assets/4fd1cf50-868c-47d4-aa18-97bf23ad6878)
![Image](https://github.com/user-attachments/assets/9c19f226-ed0b-4039-beb4-c27941631aac)

**Additional context**

I have tested the exact same code using both the DefaultAzureCredential and the ManagedIdentityCredential which do not return this error.
![Image](https://github.com/user-attachments/assets/2d059f6e-d9ab-466f-b1e2-7e691734a21b)

I also want to add that I have attempted the same thing with the `async with client:`  and have removed finally client.close() which have also failed.

**Comment by mccoyp** [comment] 2024-11-01 20:10
Hi @erpola, thank you for opening an issue; this is definitely unexpected behavior. Would you be able to share the version of `azure-identity` that you're using?

**Comment by erpola** [comment] 2024-11-01 20:13
@mccoyp i am using azure-identity==1.19.0

**Comment by mccoyp** [comment] 2024-11-04 23:07
@erpola Thank you for the information. Are you sharing the credential object with any other clients? I see on line 17 of your second screenshot that the `client` experiencing the errors is using `self.credential`. This makes me wonder if other clients are also using `self.credential` -- if so, closing one of these other clients or the credential elsewhere could cause this issue.

When the error doesn't appear while using ManagedIdentityCredential or DefaultAzureCredential, are you changing the value of `self.credential` and continuing to use it the same way? Or is the client in `get_all_secrets` being given its own credential?

**Comment by erpola** [comment] 2024-11-04 23:51
@mccoyp I have a subclass, `RotatorService`, and a base class, `KeyVaultService`. A shared credential is used across both instances, with each function that utilizes the Graph client or the Secret client relying on this shared credential. 

```python

class RotatorService(KeyVaultService):
    def __init__(self, vault_url: str, credential: Union[ClientSecretCredential, DefaultAzureCredential, ManagedIdentityCredential], key_rotation_interval_in_days: int):
        super().__init__(vault_url, credential)
        self.graph = GraphServiceClient(credential)
        self.key_rotation_interval_in_days = key_rotation_interval_in_days
        self.credential = credential
```

After the `RotatorService` object is instantiated, the credential remains open until the script has fully executed.
```python
    finally:
        if rotator:
            if rotator.credential:
                await rotator.credential.close()
```

When testing the use of `DefaultAzureCredential` and `ManagedIdentityCredential`, I simply change the initial declaration of the credential variable, as follows:

```python
credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
```
to
```python
credential = DefaultAzureCredential()
```

everything else remains the same

**Comment by jamespet77** [comment] 2024-11-06 20:53
I am seeing the same issue.  I do not have secondary clients using the connection.  I am iterating over files from a sharepoint drive and downloading.  After about 30 min, I am getting this error.  No other process is happening.  Is there a timeout for disconnect? If so can it be adjusted.

**Comment by mccoyp** [comment] 2024-11-11 22:57
Apologies for the delayed response. @jamespet77, you can configure the connection timeout of your transport with the [`connection_timeout` keyword argument](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport). This can either be provided to a transport object that you then provide to the client, as shown in the linked example, or can be passed directly to the client constructor.

@erpola is there a delay before your transport is closed, similar to @jamespet77's scenario? Or does the error present immediately? If it's the latter case, we might want to address @jamespet77's problem in a new issue.

**Comment by erpola** [comment] 2024-11-11 23:37
@mccoyp the transport is closed immediately

**Comment by mccoyp** [comment] 2024-11-13 02:36
Hi @erpola, I unfortunately haven't been able to reproduce the issue. I tried creating 100 secrets and then iterating over them in the same way you do in the code snippet you provided, but it works as expected. Do you know how many secrets are being fetched in your scenario?

Also, does the issue appear regularly or intermittently? Are you able to make successful requests with the SecretClient, using the ClientSecretCredential, otherwise? I ask because iterating over the result of `client.list_properties_of_secrets()` is what causes an actual service request to be sent, so the error is being raised during the client's first real use. That makes me wonder if the credential is somehow failing, which could possibly be shown with a different client request, like `client.get_secret`.

**Comment by erpola** [comment] 2024-11-13 15:35
@mccoyp below is a similar project, where a managed identity is leveraged. I believe if you run this projects code and swap the ManagedIdentityCredential for a ClientSecretCredential you will experience the same issue. The module in question is 

[https://github.com/erpola/azure-service-principal-rotator/blob/main/func/core/services/kv/main.py](url)

This code will run using any credential other than ClientSecretCredential

**Comment by mccoyp** [comment] 2024-11-15 23:56
@erpola I cloned the repository and tried to reproduce the issue, but I still just see `get_all_secrets` working as it should. Inside `kv/main.py` I defined an async function in which I create a KeyVaultService with a ClientSecretCredential and `await kv_service.get_all_secrets()` -- I just get the secrets back successfully. I also tried calling `update_secrets` first, to see if the `client.close()` call at the end of that method would somehow affect the client used in `get_all_secrets`, but things still succeed.

Have you had a chance to get to the points I asked about in my previous message?
> Also, does the issue appear regularly or intermittently? Are you able to make successful requests with the SecretClient, using the ClientSecretCredential, otherwise? I ask because iterating over the result of client.list_properties_of_secrets() is what causes an actual service request to be sent, so the error is being raised during the client's first real use. That makes me wonder if the credential is somehow failing, which could possibly be shown with a different client request, like client.get_secret.

If you insert a different client request in the start of `get_all_secrets` -- e.g. `self.client.set_secret` -- does this succeed?

**Closed** 2024-12-08 01:28 UTC
Labels: bug, KeyVault, Client, customer-reported, Azure.Identity, no-recent-activity, needs-author-feedback
