### ISSUE TITLE
[ServiceBus] Send message didn't recovered after network disconnect.

### ISSUE THREAD

**Issue by cropse** [Azure/azure-sdk-for-python#15473] opened 2020-11-20 06:24 UTC
- **Package Name**:  azure-servicebus
- **Package Version**: 7.0.0b8
- **Operating System**: Mac 10.15.5
- **Python Version**: 3.6.10

**Describe the bug**
sending message was infinitely blocked when network interrupted

**To Reproduce**
with the function from example like this
```
def send_batch_message(sender):
    batch_message = sender.create_message_batch()
    print('disconnect network here')
    time.sleep(15)
    for _ in range(10):
        try:
            batch_message.add_message(ServiceBusMessage("Session Message inside a ServiceBusMessageBatch", session_id=SESSION_ID))
        except ValueError:
            # ServiceBusMessageBatch object reaches max_size.
            # New ServiceBusMessageBatch object can be created here to send more data.
            break
    sender.send_messages(batch_message)
    print('success')
```
1. disconnect the network in time.sleep()
2. then wait till it to `sender.send_messages`
3. reconnect network
4. infinite block

**Expected behavior**
should have mechanism to retry or raise exception at least

**Comment by yunhaoling** [comment] 2020-11-24 18:47
hey @cropse , thanks for reaching out.

I tried to reproduce the issue locally but failed. I could get the error raised out.
I'm working on a Windows machine, what I did to disconnect the network is to:
- when the program starts sleeping, I go into the `Control Panel\Network and Internet\Network Connections` disabling all the networks.

Could you tell me which platform you're on and how you disconnect the network?

---------My reproduce error log----------

In azure-servicebus 7.0.0b8, disconnecting the network would give me `ServiceBusConnectionError`, my error log is as follows:

```
ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')
Traceback (most recent call last):
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\authentication\cbs_auth.py", line 76, in create_authenticator
    self._connection.container_id)
  File ".\src/cbs.pyx", line 73, in uamqp.c_uamqp.CBSTokenAuth.__cinit__
ValueError: Unable to open CBS link.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_base_handler.py", line 247, in _do_retryable_operation
    return operation(**kwargs)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_servicebus_sender.py", line 187, in _send
    self._open()
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_servicebus_sender.py", line 175, in _open
    self._handler.open(connection=self._connection)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\client.py", line 259, in open
    self._build_session()
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\client.py", line 214, in _build_session
    on_attach=self._on_attach)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\authentication\cbs_auth.py", line 82, in create_authenticator
    "Please confirm target hostname exists: {}".format(connection.container_id, connection.hostname))
uamqp.errors.AMQPConnectionError: Unable to open authentication session on connection b'SBSender-ffa68263-b4db-4604-ae1f-09b10aac2f56'.
Please confirm target hostname exists: b'xxx.servicebus.windows.net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../azure-sdk-for-python/sdk/servicebus/azure-servicebus/samples/sync_samples/session_send_receive.py", line 68, in <module>
    send_batch_message(sender)
  File "../azure-sdk-for-python/sdk/servicebus/azure-servicebus/samples/sync_samples/session_send_receive.py", line 45, in send_batch_message
    sender.send_messages(batch_message)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_servicebus_sender.py", line 370, in send_messages
    require_last_exception=True
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_base_handler.py", line 251, in _do_retryable_operation
    last_exception = self._handle_exception(exception, **kwargs)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\azure\servicebus\_base_handler.py", line 228, in _handle_exception
    raise error
azure.servicebus.exceptions.ServiceBusConnectionError: Failed to open handler: Unable to open authentication session on connection b'SBSender-ffa68263-b4db-4604-ae1f-09b10aac2f56'.
Please confirm target hostname exists: b't1sbtest.servicebus.windows.net'.
```

As you may know, we have just released azures-servicebus 7.0.0 GA version in which we improved our error design by switching to an condition based approach.

I also tried to reproduce the issue in 7.0.0 which now would give me `ServiceBusError`, my error log is as follows:

```
ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.')
end sleeping
Traceback (most recent call last):
  File "..\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\_base_handler.py", line 293, in _do_retryable_operation
    return operation(**kwargs)
  File "..\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\_servicebus_sender.py", line 238, in _send
    self._handler.send_message(message.message)
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\client.py", line 725, in send_message
    running = self.do_work()
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\client.py", line 397, in do_work
    return self._client_run()
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\client.py", line 650, in _client_run
    self._connection.work()
  File "..\Anaconda3\envs\servicebus37\lib\site-packages\uamqp\connection.py", line 251, in work
    raise self._error
uamqp.errors.ConnectionClose: ErrorCodes.UnknownError: Connection in an unexpected error state.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../azure-sdk-for-python/sdk/servicebus/azure-servicebus/samples/sync_samples/session_send_receive.py", line 68, in <module>
    send_batch_message(sender)
  File "../azure-sdk-for-python/sdk/servicebus/azure-servicebus/samples/sync_samples/session_send_receive.py", line 45, in send_batch_message
    sender.send_messages(batch_message)
  File "..\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\_servicebus_sender.py", line 393, in send_messages
    require_last_exception=True
  File "..\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\_base_handler.py", line 297, in _do_retryable_operation
    last_exception = self._handle_exception(exception)
  File "..\azure-sdk-for-python\sdk\servicebus\azure-servicebus\azure\servicebus\_base_handler.py", line 252, in _handle_exception
    raise error
azure.servicebus.exceptions.ServiceBusError: Connection in an unexpected error state. Error condition: ErrorCodes.UnknownError.
```

**Comment by cropse** [comment] 2020-11-26 09:39
I'm using Mac as test operating system, so probably is the specific issue only on macOS.

here is entire code:
```python
#!/usr/bin/env python

import time
from azure.servicebus import ServiceBusClient, ServiceBusMessage

CONNECTION_STR = ""
TOPIC_NAME = ''
SUBSCRIPTION_NAME = ''
SESSION_ID = ''


def send_batch_message(sender):
    batch_message = sender.create_message_batch()
    print('disconnect network here')
    time.sleep(15)
    for _ in range(10):
        try:
            batch_message.add_message(ServiceBusMessage("Session Message inside a ServiceBusMessageBatch", session_id=SESSION_ID))
        except ValueError:
            # ServiceBusMessageBatch object reaches max_size.
            # New ServiceBusMessageBatch object can be created here to send more data.
            break
    print('start to send message, reconnect your network!!')
    sender.send_messages(batch_message)
    print('success !!')


servicebus_client = ServiceBusClient.from_connection_string(conn_str=CONNECTION_STR, logging_enable=False, retry_total=10)
with servicebus_client:
    receiver = servicebus_client.get_subscription_receiver(
        topic_name=TOPIC_NAME,
        subscription_name=SUBSCRIPTION_NAME
    )
    sender = servicebus_client.get_topic_sender(TOPIC_NAME)
    with sender:
        send_batch_message(sender)

print("Receive is done.")
```

**Comment by yunhaoling** [comment] 2020-12-04 21:57
thanks for the code @cropse, I'll try it on my mac

**Comment by yunhaoling** [comment] 2020-12-07 18:24
hey @cropse , confirming the issue on macOS.

However, the issue seems to be with the deeper C layer (azure-c-shared-utility) which is not able to detect the network is down.
I need more time into investigation.

If you want the code to work first, you could probably do some local check to mitigate:

```python
from azure.servicebus.exception import OperationTimeoutError
with sender:
    try:
        while tried_time <= 3:
            sender.send_messages(message, timeout=10)
        else:
            # all retry failed, shutdown the sender, create a new sender and start the send flow again
    except OperationTimeoutError:
        tried_time += 1

```

**Comment by yunhaoling** [comment] 2021-01-06 23:15
hey @cropse, we have enhanced the underlying C library to be able to detect error IO status on MacOS.

[uamqp v1.2.13](https://pypi.org/project/uamqp/1.2.13/) is released today to include the fix.
Please upgrade to the latest uamqp version (e.g. `pip install uamqp --upgrade`) to see if it solves your problem.

I'm closing the issue now, feel free to reopen if you still get trouble with the latest version.

**Closed by yunhaoling** 2021-01-06 23:15 UTC
Labels: Service Bus, customer-reported, needs-team-attention, question
