### ISSUE TITLE
StorageManagementClient (3.1.1) : TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by dparkar** [Azure/azure-sdk-for-python#4776] opened 2019-04-04 01:03 UTC
```
(dev) dparkar@dparkar-ws-u:~$ pip freeze | grep 'azure'
You are using pip version 18.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
azure-cli-command-modules-nspkg==2.0.2
azure-cli-core==2.0.54
azure-cli-nspkg==3.0.3
azure-cli-profile==2.1.1
azure-cli-telemetry==1.0.0
azure-common==1.1.16
azure-graphrbac==0.53.0
azure-mgmt-authorization==0.50.0
azure-mgmt-batchai==2.0.0
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.0
azure-mgmt-containerregistry==2.6.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==2.1.0
azure-mgmt-storage==3.1.1
azure-nspkg==3.0.2
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.1
azure-storage-blob==1.3.1
azure-storage-nspkg==3.0.0
azureml-core==0.1.0.2123685
azureml-dataprep==0.5.3
azureml-dataprep-native==11.2.0
azureml-explain-model==0.1.0.2123685
azureml-pipeline==0.1.0.2123685
azureml-pipeline-core==0.1.0.2123685
azureml-pipeline-steps==0.1.0.2123685
azureml-sdk==0.1.0.2123685
azureml-telemetry==0.1.0.2123685
azureml-train==0.1.0.2123685
azureml-train-automl==0.1.0.2123685
azureml-train-core==0.1.0.2123685
azureml-train-restclients-hyperdrive==0.1.0.2123685
msrestazure==0.6.0
```
Code : 
```
from azure.common import credentials
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.storage import StorageManagementClient

creds = credentials.ServicePrincipalCredentials(
        client_id='MYCLIENTID',
        secret='MYCLIENTSECRET',
        tenant='MYTENANT')

resource_client = ResourceManagementClient(creds, 'MYSUBSCRIPTIONID')
storage_client = StorageManagementClient(creds, 'MYSUBSCRIPTIONID')

```

Output : 
```
Traceback (most recent call last):
  File "azure_rg_manager.py", line XXX, in <module>
    main(args)
  File "azure_rg_manager.py", line XX, in main
    creds, 'MYSUBSCRIPTIONID')
TypeError: __init__() takes 2 positional arguments but 3 were given
```
The error is coming from:
`storage_client = StorageManagementClient(creds, 'MYSUBSCRIPTIONID')`

Change to the following to make it work: 
```
storage_client = StorageManagementClient(
        credentials=creds,
        subscription_id='MYSUBSCRIPTIONID')
```

Documentation uses previous syntax : 
- https://azure.microsoft.com/en-us/resources/samples/storage-python-manage/

Note that ResourceManagementClient does not complain. 

Also came across this : https://stackoverflow.com/questions/53556192/getting-error-while-creating-storage-on-azure-with-python-script-getting-error

May be just need to update the documentation ?

**Comment by lmazuel** [comment] 2019-04-04 19:16
Hi @dparkar ,

First, the StackOverflow you mention is about models creation, not client creation, and I answered myself to it to explain the problem :)

Your traceback is incomplete and doesn't match your code. I understand you want to edit it for confidentiality, but here it's really too much to the point the traceback cannot be used to make a conclusion.

This code:
```python
storage_client = StorageManagementClient(creds, 'MYSUBSCRIPTIONID')
```
will work with 100% certainty, and your traceback is showing a new line nefore `creds`, so I can't conclude what your code is actually.

Doc for details:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.storagemanagementclient?view=azure-python

Thanks

**Comment by lmazuel** [comment] 2019-04-04 19:20
Something I want to add, I agree that the repo you mention has not been updated in two years and doesn't match the latest SDK, but it will not fail in the line you point.

**Comment by lmazuel** [comment] 2019-04-05 16:35
Hi @dparkar 
I updated the sample you mentioned, thanks for the report!
I'm closing this issue, since I can confirm there is no problem with the syntax you mention, feel free to open a new issue if necessary.
Thanks!

**Closed by lmazuel** 2019-04-05 16:35 UTC
Labels: Mgmt, Storage
