### ISSUE TITLE
ContainerClient: get_container_properties & exists does not work with permissions limited to that container

### ISSUE THREAD

**Issue by jpvlerbe** [Azure/azure-sdk-for-python#18012] opened 2021-04-13 16:57 UTC
- **Package Name**: azure.storage.blob
- **Package Version**: 12.6.0
- **Operating System**: Linux
- **Python Version**: 3.6

**Describe the bug**
With a SAS token with permission limited to a single container. `get_container_properties` fails on that container.

**To Reproduce**
```
>>> from azure.storage.blob.aio import BlobServiceClient
>>> sc = BlobServiceClient.from_connection_string(conn_str="BlobEndpoint=https://something.blob.core.windows.net;Accountname=something;SharedAccessSignature=sp=racwlme&...")
>>> cc = sc.get_container_client("container")
>>> loop.run_until_complete(cc.get_container_properties())
Traceback (most recent call last):
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/aio/_container_client_async.py", line 331, in get_container_properties
    **kwargs)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/_generated/aio/operations_async/_container_operations_async.py", line 195, in get_properties
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'This request is not authorized to perform this operation.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/aio/_container_client_async.py", line 333, in get_container_properties
    process_storage_error(error)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation.
RequestId:e5d5762e-e01e-0015-1f85-306896000000
Time:2021-04-13T16:54:21.0721310Z
ErrorCode:AuthorizationFailure
Error:None

```

**Comment by xiangyan99** [comment] 2021-04-15 22:05
Thanks for the feedback, we’ll investigate asap.

**Comment by tasherif-msft** [comment] 2021-04-16 00:36
Hi @jpvlerbe this is expected behavior. You can refer to permission levels per operation here: 
https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob
In the meantime I will close this issue. Let me know if you have any other questions.

**Comment by jpvlerbe** [comment] 2021-04-16 07:41
The `get_container_properties`-function fails at this line: [https://github.com/Azure/azure-sdk-for-python/blob/46b402fa34ff2158ad2fbf5fa14f4f2a3611af3e/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L492](https://github.com/Azure/azure-sdk-for-python/blob/46b402fa34ff2158ad2fbf5fa14f4f2a3611af3e/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L492)
Which is the same function the `exists`-function is using. Is it also expected behavior that if you have permissions to a container you cannot check it if actually exists?
When using this library what would the desired sequence be to check connection to and existence of the container before trying to read/write blobs?

**Comment by isidentical** [comment] 2021-05-05 10:13
Hey @tasherif-msft, we are hitting this issue on [dvc](https://github.com/iterative/dvc) too and would love to see this to be resolved since it is making azure blob storage unusable for people who are using limited tokens.

**Comment by isidentical** [comment] 2021-06-28 12:52
@tasherif-msft a gentle ping

**Comment by amishra-dev** [comment] 2021-08-05 18:21
@isidentical Hi Batuhan, This is an ask we have raised with the service team, i will keep this issue open and update when i hear back.

**Comment by xiafu-msft** [comment] 2021-08-10 06:25
Hi @jpvlerbe @isidentical and @Katzmann1983 

Thanks for reaching out. 
It looks like @tasherif-msft is correct that based on the doc, container properties should be accessed using account SAS instead of service SAS.

Here's what the doc says:
```
A service SAS cannot grant access to certain operations:

Containers, queues, and tables cannot be created, deleted, or listed.
**Container metadata and properties cannot be read or written.**
Queues cannot be cleared and their metadata may not be written.
Containers cannot be leased.
```

So just want to make sure that you were using account SAS instead of service SAS when you were trying to access the container properties.

Let me know if you have any questions!

**Comment by dynamicwebpaige** [comment] 2021-09-19 18:05
Bumping up this issue, as well, as we have been testing DVC with Codespaces.

[Reference issue, on the DVC side.](https://github.com/iterative/dvc/issues/5589)

Thank you! :)

**Comment by vincenttran-msft** [comment] 2022-06-03 22:56
Hi @jpvlerbe, just wanted to check in if this issue still needs support from our team, or if the issue has been resolved? Just to re-iterate, it is expected behavior that `get_container_properties()` and `exists()` fail with a container-level SAS, and that those require at minimum an account-level SAS as stated by @xiafu-msft in a previous reply! 

If we don't hear back from you within a week, I will consider this issue resolved, but please do not hesitate to reach out again if there are any doubts!
Thanks!

**Closed** 2022-06-11 06:24 UTC
Labels: Storage, Service Attention, Client, customer-reported, no-recent-activity, needs-author-feedback
