### ISSUE TITLE
VirtualMachine object's attribute "resources" doesn't give proper VirtualMachineExtension objects.

### ISSUE THREAD

**Issue by thelazy** [Azure/azure-sdk-for-python#2165] opened 2018-03-14 08:17 UTC
I compared the output given by azure CLI and the python SDK for Virtual Machines's resources which have objects of "VirtualMachineExtension". Python SDK gives objects which have most of its attributes as "None", while CLI lists all the attributes properly. 
Can someone please help with the inconsistencies between these two results. 

Python sample code: 
`    for VM in compute_client.virtual_machines.list_all():`
`for resource in VM.resources:`
`print resource.__str__()`

CLI:
`az vm show -g MyResourceGroup -n MyVm -d`
parse the CLI output for "resources"

**Comment by lmazuel** [comment] 2018-03-15 00:27
It's because the CLI is iterating other this list to ask instanceView of the VM

**Comment by thelazy** [comment] 2018-03-15 06:38
Sorry, but I didn't understand your comment. Can you please elaborate over that?
Also, it would be good if you can suggest me a way to list the details of VM extensions using python SDK.

**Comment by lmazuel** [comment] 2018-03-16 00:13
You can two different VM view, summary and detailled. Detailled is called "instanceView":
```python
        # Get instanceView
        result_iv = self.compute_client.virtual_machines.get(
            resource_group.name,
            names.vm,
            expand=virtual_machines_models.InstanceViewTypes.instance_view
        )
        self.assertTrue(result_iv.instance_view)
```
All list operation are returning summary, meaning if you want to fill the details, you need to iterate and call all VM to get details. See for instance: 
https://github.com/Azure/azure-sdk-for-python/issues/573

@yugangw-msft , how do you list extensions installed on a VM?

**Comment by hankok** [comment] 2018-03-27 22:24
Same problem here, 

        instances = self._compute_client.virtual_machines.list(self._resource_group, expand='instanceview')

This will return a VM with instance_view object set to None. Had to call:
                vm = self._compute_client.virtual_machines.get(self._resource_group, instance.name, expand='instanceview')

every each time when to get the powerstauts of a VM

**Comment by lmazuel** [comment] 2018-03-27 22:29
Closing, since duplicate of https://github.com/Azure/azure-sdk-for-python/issues/573

**Closed by lmazuel** 2018-03-27 22:29 UTC
Labels: ARM, Docs
