### ISSUE TITLE
Issue creating VM from custom Image

### ISSUE THREAD

**Issue by andrewgross** [Azure/azure-sdk-for-python#562] opened 2016-03-31 15:20 UTC
Hey,

I have been following the v2.0.0 tutorial [here](http://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagementcomputenetwork.html) to try and spin up some Azure VMs from a custom image I made.  I had to tweak a bit of the code to fix it for some minor API changes, however, when I attempt to launch the VM I am getting an issue that my newly created storage container already had an existing lease.  I am unsure where the bug is, if my code is wrong, if the python SDK is making bad calls, or if the Azure endpoint is not processing them properly.

### Python Script

As far as I can tell the important bit should be the last few lines of the python script where I actually populate the storage engine models and pass them to `create_or_update`.

```python
import azure
import azure.mgmt.compute
import azure.mgmt.network
import azure.mgmt.resource
import azure.mgmt.storage

import time
import random
import string
import os
from base64 import b64decode

from azure.mgmt.compute import ComputeManagementClient, ComputeManagementClientConfiguration
from azure.mgmt.network import NetworkManagementClient, NetworkManagementClientConfiguration
from azure.mgmt.resource.resources import ResourceManagementClient, ResourceManagementClientConfiguration
from azure.mgmt.storage import StorageManagementClient, StorageManagementClientConfiguration

from azure.common.credentials import UserPassCredentials

SUBSCRIPTION_ID = '1234567890-acvdf-1232353465-asddgsd'

PASSWORD = os.getenv('AZURE_PASSWORD')

credentials = UserPassCredentials(
    'myemail@onmicrosoft.com',
    PASSWORD,
)

compute_client = ComputeManagementClient(
    ComputeManagementClientConfiguration(
        credentials,
        SUBSCRIPTION_ID
    )
)

network_client = NetworkManagementClient(
    NetworkManagementClientConfiguration(
        credentials,
        SUBSCRIPTION_ID
    )
)

resource_client = ResourceManagementClient(
    ResourceManagementClientConfiguration(
        credentials,
        SUBSCRIPTION_ID
    )
)

storage_client = StorageManagementClient(
    StorageManagementClientConfiguration(
        credentials,
        SUBSCRIPTION_ID
    )
)

BASE_NAME = "foobar"

GROUP_NAME = BASE_NAME
STORAGE_NAME = BASE_NAME
VIRTUAL_NETWORK_NAME = BASE_NAME
SUBNET_NAME = BASE_NAME
NETWORK_INTERFACE_NAME = BASE_NAME
VM_NAME = BASE_NAME
OS_DISK_NAME = BASE_NAME
PUBLIC_IP_NAME = BASE_NAME
COMPUTER_NAME = BASE_NAME

REGION = 'southcentralus'

ADMIN_USERNAME='azureadminuser'
ADMIN_PASSWORD='<some_password>'

# Create Resource Group
result = resource_client.resource_groups.create_or_update(
    GROUP_NAME,
    azure.mgmt.resource.resources.models.ResourceGroup(
        location=REGION,
    ),
)

# Create Storage Group
result = storage_client.storage_accounts.create(
    GROUP_NAME,
    STORAGE_NAME,
    azure.mgmt.storage.models.StorageAccountCreateParameters(
        location=REGION,
        account_type=azure.mgmt.storage.models.AccountType.standard_lrs,
    ),
)
result.wait()



def create_network_interface(network_client, region, group_name, interface_name, network_name, subnet_name, ip_name):
    result = network_client.virtual_networks.create_or_update(
        group_name,
        network_name,
        azure.mgmt.network.models.VirtualNetwork(
            location=region,
            address_space=azure.mgmt.network.models.AddressSpace(
                address_prefixes=[
                    '10.1.0.0/16',
                ],
            ),
            subnets=[
                azure.mgmt.network.models.Subnet(
                    name=subnet_name,
                    address_prefix='10.1.0.0/24',
                ),
            ],
        ),
    )
    result.wait()
    subnet = network_client.subnets.get(group_name, network_name, subnet_name)
    result = network_client.public_ip_addresses.create_or_update(
        group_name,
        ip_name,
        azure.mgmt.network.models.PublicIPAddress(
            location=region,
            public_ip_allocation_method=azure.mgmt.network.models.IPAllocationMethod.dynamic,
            idle_timeout_in_minutes=4,
        ),
    )
    result.wait()
    public_ip_address = network_client.public_ip_addresses.get(group_name, ip_name)
    public_ip_id = public_ip_address.id
    result = network_client.network_interfaces.create_or_update(
        group_name,
        interface_name,
        azure.mgmt.network.models.NetworkInterface(
            name=interface_name,
            location=region,
            ip_configurations=[
                azure.mgmt.network.models.NetworkInterfaceIPConfiguration(
                    name='default',
                    private_ip_allocation_method=azure.mgmt.network.models.IPAllocationMethod.dynamic,
                    subnet=subnet,
                    public_ip_address=azure.mgmt.network.models.PublicIPAddress(
                        id=public_ip_id,
                    ),
                ),
            ],
        ),
    )
    time.sleep(30)  # result.wait() throws errors, but need to wait before getting the ID
    network_interface = network_client.network_interfaces.get(
        group_name,
        interface_name,
    )
    return network_interface.id


nic_id = create_network_interface(
    network_client,
    REGION,
    GROUP_NAME,
    NETWORK_INTERFACE_NAME,
    VIRTUAL_NETWORK_NAME,
    SUBNET_NAME,
    PUBLIC_IP_NAME,
)

result = compute_client.virtual_machines.create_or_update(
    GROUP_NAME,
    VM_NAME,
    azure.mgmt.compute.models.VirtualMachine(
        location=REGION,
        name=VM_NAME,
        os_profile=azure.mgmt.compute.models.OSProfile(
            admin_username=ADMIN_USERNAME,
            admin_password=ADMIN_PASSWORD,
            computer_name=COMPUTER_NAME,
        ),
        hardware_profile=azure.mgmt.compute.models.HardwareProfile(
          vm_size="Basic_A0"
        ),
        network_profile=azure.mgmt.compute.models.NetworkProfile(
            network_interfaces=[
                azure.mgmt.compute.models.NetworkInterfaceReference(
                    id=nic_id,
                ),
            ],
        ),
        storage_profile=azure.mgmt.compute.models.StorageProfile(
            os_disk=azure.mgmt.compute.models.OSDisk(
                caching=azure.mgmt.compute.models.CachingTypes.none,
                create_option=azure.mgmt.compute.models.DiskCreateOptionTypes.from_image,
                name=OS_DISK_NAME,
                os_type="Linux",
                vhd=azure.mgmt.compute.models.VirtualHardDisk(
                    uri='https://{0}.blob.core.windows.net/vhds/{1}.vhd'.format(
                        "my_storage_account",
                        OS_DISK_NAME,
                    ),
                ),
                image=azure.mgmt.compute.models.VirtualHardDisk(
                    uri='https://my_storage_account.blob.core.windows.net/vhds/my_image_name.vhd'
                ),
            )
        ),
    ),
)
try:
    result.wait()
finally:
    import ipdb; ipdb.set_trace()
    print result._response.text
```

### JSON Response

Here is the json error message returned by Azure:

```json
{
  "operationId": "d8470aaa-ed18-4a23-90f8-259c989e5e64",
  "status": "Failed",
  "startTime": "2016-03-31T14:49:08.5167284+00:00",
  "endTime": "2016-03-31T14:49:09.6417511+00:00",
  "error": {
    "code": "ContainerAlreadyOnLease",
    "message": "There is already a lease on the storage container holding the blob with URI https://my_storage_Account.blob.core.windows.net/vhds/foobar.vhd."
  }
}
```

**Comment by andrewgross** [comment] 2016-03-31 16:04
Did a bit more debugging, and as far as I can see the codebase is only doing 1 PUT request with a body similar to this:

```json
{'location': 'southcentralus',
 'name': 'foobar',
 'properties': {'hardwareProfile': {'vmSize': 'Basic_A0'},
                'networkProfile': {'networkInterfaces': [{'id': '/subscriptions/4f1f1c8d-84e7-47f3-bb31-5aa4c1910390/resourceGroups/foobar/providers/Microsoft.Network/networkInterfaces/foobar'}]},
                'osProfile': {'adminPassword': '<somepassword>',
                              'adminUsername': 'azureadminuser',
                              'computerName': 'foobar'},
                'storageProfile': {'osDisk': {'caching': 'None',
                                              'createOption': 'fromImage',
                                              'image': {'uri': 'https://my_storage_account.blob.core.windows.net/vhds/my_image_name.vhd'},
                                              'name': 'foobar',
                                              'osType': 'Linux',
                                              'vhd': {'uri': 'https://yipitproxy2.blob.core.windows.net/vhds/dxgwzcermsqugtnbgntq.vhd'}}}}}
```

I checked before the PUT request was done that the storage account did not have any blobs in it, so there is no way that the lease was already in place.  Is this is an issue I need to escalate to the Azure API teams?  It seems like such a simple action though that I think I am doing something wrong.  If style of action were broken someone would have noticed by now.

**Comment by lmazuel** [comment] 2016-03-31 17:14
Hi,

Thank you for your very precise report. Are you using 2.0.0rc1 or rc2? Because the API-version of Compute has changed because this two versions.
It does not seems to be a Python problem, but as your are saying directly a Compute problem directly. I will try to reproduce it to be sure.

**Comment by andrewgross** [comment] 2016-03-31 17:38
Hey,

I am using 2.0.0rc2

```
$ pip freeze | grep azure
azure==2.0.0rc2
```

**Comment by andrewgross** [comment] 2016-03-31 19:13
What is also strange, is if I go to the storage account for this script, it does not show any blobs/containers actually being created.  So it seems that either the error message is wrong, or I am calling it in a very unexpected fashion.

**Comment by andrewgross** [comment] 2016-03-31 19:15
I take that back, it is creating them, just not under the storage account I thought.

**Comment by andrewgross** [comment] 2016-03-31 19:30
I guess I am a bit confused about how this should.  In my "classic" storage account I have a VHD container with VHD of my base image, as well as the VHDs of these new machines I am creating.  Looking in the console several of them have existing leases, while several do not.  The error message:

```
 "message": "There is already a lease on the storage container holding the blob with URI https://my_storage_name.blob.core.windows.net/vhds/foobarbaz.vhd."``

Implies that a storage container can only have 1 lease at a time, which seems crazy to me.  Even if it is really referring to there being a lease on that particular blob, I don't get how that is happening since I am only making 1 call, but somehow trying to take out the lock twice.

**Comment by andrewgross** [comment] 2016-03-31 19:37
I am wondering I should be using `StorageProfile.image_reference` instead of `OSDisk.image` to setup my virtual machine.  However, if that is the case where would I get the info for `publisher, offer, sku, version`.  That information only seems to be available for public images.

**Comment by andrewgross** [comment] 2016-03-31 19:56
So it looks like the Storage Container for VHDs that I am using *does* have an outstanding lock on it.  I am not sure what is holding the lock or why it would need one, but I'll see if I can figure out how to deactivate and see if that lets me start a machine.  Oddly, even though there is a lock I am able to create the new VHDs for these machines, but I cannot use them when creating a VM.

**Comment by andrewgross** [comment] 2016-03-31 20:45
I think I found my issue.  My VHD was created using a "classic" Storage account, and I am trying to use it to create a VM in ARM.

```
Can I create a Virtual Machine using the new Azure Resource Manager APIs from a user image that was created using the Azure Service Management APIs.  I will try to copy the VHD (or create a new image) in the new system.

This is not supported at the moment. However, you can copy the VHD files from a Storage Account that was created using the Service Management APIs and copy it to a new account created using the using the new Azure Resource Manager APIs.
```

https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-compare-deployment-models/

**Comment by andrewgross** [comment] 2016-03-31 20:48
Unsure why everything on the storage accounts are locked, or if that is a red herring error message masking this issue.

**Comment by lmazuel** [comment] 2016-03-31 20:52
Honestly, I didn't try your case before. It's interesting to read your experiment, please continue :)
I'm not surprised that ASM don't work in ARM stuff. And yes, I sometime saw error messages which are not related to the exact problem, I think you can have found your problem.

**Comment by andrewgross** [comment] 2016-03-31 20:55
I am making a new ARM image, I will update if I have more issues.

**Comment by andrewgross** [comment] 2016-03-31 22:08
Using an ARM image and the "image" url provided by the `azure` CLI when making the image fixed the issue.  I don't think there is a "problem" here beyond perhaps poor API errors.  Thanks for looking in to this.

**Comment by lmazuel** [comment] 2016-04-01 00:06
Thank you for you detailed comments! This can help people who find this post :)
I close it since you solve your problem, please feel free to re-open it or open a new one if you find another problem.

**Closed by lmazuel** 2016-04-01 00:06 UTC
