### ISSUE TITLE
DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet

### ISSUE THREAD

**Issue by alegend4u** [Azure/azure-sdk-for-python#33451] opened 2023-12-09 12:55 UTC
- **Package Name**: azure-ai-ml
- **Package Version**: 1.12.1
- **Operating System**: Ubuntu 22.04
- **Python Version**: 3.10

**Describe the bug**
I'm using Azure Machine Learning v2 SDK to create an online model endpoint on a Kubernetes compute attached to an AML workspace. I'm able to deploy it locally as part of testing before deploying online. However, when tried to deploy online using `KubernetesOnlineDeplyoment`, I received:

`DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet Details:Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg`. (More detailed error below)

**To Reproduce**
1. I provisioned an AKS Cluster via terraform.
```
resource "azurerm_kubernetes_cluster" "deployment" {
  name                              = local.resource_base_name
  location                          = var.location
  resource_group_name               = var.resource_group
  dns_prefix                        = local.resource_base_name
  kubernetes_version                = var.k8s_version
  node_resource_group               = "${var.resource_group}-aks-${local.resource_base_name}"
  azure_policy_enabled              = true
  public_network_access_enabled     = true
  role_based_access_control_enabled = true
  oidc_issuer_enabled               = true
  private_cluster_enabled           = true
  workload_identity_enabled         = true
  sku_tier                          = "Free"

  default_node_pool {
    name                        = "default"
    vm_size                     = local.node_sku
    node_count                  = var.node_count
    vnet_subnet_id              = azurerm_subnet.cluster_nodes.id
    orchestrator_version        = var.k8s_version
    enable_auto_scaling         = false
    max_pods                    = 250
    temporary_name_for_rotation = "defaulttemp"
    enable_host_encryption      = true
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    dns_service_ip    = "10.12.0.10"
    service_cidr      = "10.12.0.0/14"
    load_balancer_sku = "standard"
    network_plugin    = "azure"
    network_policy    = "azure"
    outbound_type     = "loadBalancer"
  }

  timeouts {
    update = "3h"
  }

}
```

2. I deployed Azure Machine Learning Extension on the AKS cluster using [this official tutorial page](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-kubernetes-extension?view=azureml-api-2&tabs=deploy-extension-with-cli)

```
az k8s-extension create --name $extension_name --extension-type Microsoft.AzureML.Kubernetes --config enableTraining=False enableInference=True inferenceRouterServiceType=LoadBalancer allowInsecureConnections=True InferenceRouterHA=False --cluster-type managedClusters --cluster-name $cluster_name --resource-group $resource_group --scope cluster
```

3. Create an AML Workspace

```
resource "azurerm_machine_learning_workspace" "default" {
  name                    = "${var.aml_base_name}-mlw"
  location                = var.location
  resource_group_name     = var.resource_group
  application_insights_id = azurerm_application_insights.default.id
  key_vault_id            = var.key_vault_id
  storage_account_id      = var.storage_account_id
  container_registry_id   = var.container_registry_id
  identity {
    type = "SystemAssigned"
  }
}
```

4. Attaching the AKS cluster to the AML Workspace
```
compute = "testfooamlXXXX-c"

from azure.ai.ml import load_compute

compute_params = [
    {"name": compute},
    {"type": "kubernetes"},
    {
        "resource_id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/test-foo-aml/providers/Microsoft.ContainerService/managedClusters/testfooamlXXXX",
    },
    {"identity": {"type":"SystemAssigned"}},
]
k8s_compute = load_compute(source=None, params_override=compute_params)
```

5. Create an online endpoint
```
endpoint = KubernetesOnlineEndpoint(
    name=endpoint_name,
    compute=compute,
    description="this is a sample online endpoint",
    auth_mode="key",
    tags={"foo": "bar"},
)
ml_client.begin_create_or_update(endpoint).result()
```
6. Create the deployment
```
blue_deployment = KubernetesOnlineDeployment(
    name="blue",
    endpoint_name=endpoint_name,
    model=Model(path=str(model_path)),
    environment=Environment(name=env_name, version=env_version),
    code_configuration=CodeConfiguration(
        code=str(model_script_path.parent), scoring_script=model_script_path.name
    ),
    instance_count=1,
)
ml_client.begin_create_or_update(blue_deployment).result()
```

Above step results into below exception:

```
---------------------------------------------------------------------------
OperationFailed                           Traceback (most recent call last)
File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:757, in LROBasePolling.run(self)
    756 try:
--> 757     self._poll()
    759 except BadStatus as err:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:789, in LROBasePolling._poll(self)
    788 if _failed(self.status()):
--> 789     raise OperationFailed("Operation failed or canceled")
    791 final_get_url = self._operation.get_final_get_url(self._pipeline_response)

OperationFailed: Operation failed or canceled

The above exception was the direct cause of the following exception:

HttpResponseError                         Traceback (most recent call last)
/home/rishabh/aml/test-foo-model-deployments.ipynb Cell 51 line 1
----> 1 ml_client.begin_create_or_update(blue_deployment).result()

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:251, in LROPoller.result(self, timeout)
    242 def result(self, timeout: Optional[float] = None) -> PollingReturnType_co:
    243     """Return the result of the long running operation, or
    244     the result available after the specified timeout.
    245 
   (...)
    249     :raises ~azure.core.exceptions.HttpResponseError: Server problem with the query.
    250     """
--> 251     self.wait(timeout)
    252     return self._polling_method.resource()

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:270, in LROPoller.wait(self, timeout)
    266 self._thread.join(timeout=timeout)
    267 try:
    268     # Let's handle possible None in forgiveness here
    269     # https://github.com/python/mypy/issues/8165
--> 270     raise self._exception  # type: ignore
    271 except TypeError:  # Was None
    272     pass

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/_poller.py:185, in LROPoller._start(self)
    181 """Start the long running operation.
    182 On completion, runs any callbacks.
    183 """
    184 try:
--> 185     self._polling_method.run()
    186 except AzureError as error:
    187     if not error.continuation_token:

File ~/miniconda3/envs/rishabh/lib/python3.11/site-packages/azure/core/polling/base_polling.py:772, in LROBasePolling.run(self)
    765     raise HttpResponseError(
    766         response=self._pipeline_response.http_response,
    767         message=str(err),
    768         error=err,
    769     ) from err
    771 except OperationFailed as err:
--> 772     raise HttpResponseError(response=self._pipeline_response.http_response, error=err) from err

HttpResponseError: (None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet Details:Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
Code: None
Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet Details:Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
Exception Details:  (None) DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet Details:Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
    Code: None
    Message: DeploymentIdentityError: Failed to create Kubernetes deployment identity, Reason:RefreshExtensionIdentityNotSet Details:Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'. The identity is used to give access for user container, such as pull image from ACR. Please see troubleshooting guide, available here: https://aka.ms/amlarc-tsg
```

Regarding the error, quoting the [official documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-kubernetes-compute?view=azureml-api-2#error-refreshextensionidentitynotset):
> ERROR: RefreshExtensionIdentityNotSet This error occurs when the extension is installed but the extension identity is not correctly assigned. You can try to reinstall the extension to fix it.

I tried re-installing the extension and deploying but got the same error.
**Expected behavior**
The exception shouldn't be raised and the model deployment should be done successfully.

**Additional context**

The error detail says: `Managed identity of AzureML extension is not assigned to the node pool of 'aks-default-XXXXXXXX-vmss000000'`.

I checked the [documentation to deploy the AzureML extension](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-kubernetes-extension?view=azureml-api-2&tabs=deploy-extension-with-cli) and it doesn't specify a way to assign a `SystemAssigned` managed identity to an AzureML extension because Kubernetes Extensions in general have an `identity` argument (Refer [this page](https://learn.microsoft.com/en-us/azure/templates/microsoft.kubernetesconfiguration/extensions?pivots=deployment-language-arm-template#extensions-1)) (although only `SystemAssigned` identity type is supported there).

One more thing I observed is that once the extension is created, I used `az k8s-extension show` command to get its details and it had a field `aksAssignedIdentity` which had `principalId` but the field `identity` was `null`. On checking the azure portal, there were two `UserAssigned` managed identities created in the node resource group: `ext-XXXXXX` and `extensionmanager-XXXXX`. The `principalId` of `ext-XXXXXX` matched with that of the AzureML extension.

**Comment by alegend4u** [comment] 2023-12-13 15:18
Seems like `aad-pod-identity` was intereferring with extension's identity controller. Removing the deployment `aad-pod-identity` resolved the issue.

**Comment by banibrata** [comment] 2023-12-21 11:21
closing as the issue is resolved

**Closed** 2023-12-21 11:20 UTC
Labels: question, Machine Learning, Service Attention, customer-reported, needs-team-attention
