### ISSUE TITLE
Track service end typo in Python Tables Storage error message

### ISSUE THREAD

**Issue by YalinLi0312** [Azure/azure-sdk-for-python#26402] opened 2022-09-22 21:34 UTC
There are two tests for invalid table names in tables storage failing in Python - [async test](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/tests/test_table_client_async.py#L111), [sync test](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/tests/test_table_client.py#L112)

We are testing with a list of invalid storage table names, some are failing("1table", "a//", "my_table"), not all of them.

Here's one of the response we got:

`'message': 'The specifed resource name contains invalid characters.\n'
            'RequestId:6783e6ea-a002-006a-3c48-c912e9000000\n'
            'Time:2022-09-15T21:15:28.7300879Z\n'
'ErrorCode:InvalidResourceName'`

You can find there's a typo in response message so that we can't catch it and convert it to a ValueError to users.

**Comment by YalinLi0312** [comment] 2022-09-22 21:46
The typo exists for a while, it breaks all of our live pipelines. Please give some priorities to fix it.

**Comment by YalinLi0312** [comment] 2022-09-22 21:46
The typo exists for a while, it breaks all of our live pipelines. Please give some priorities to fix it.

**Comment by xiangyan99** [comment] 2023-01-04 15:51
@YalinLi0312 to help me understand better, do you mean this is a service issue? Or a storage issue?

Thanks.

**Comment by YalinLi0312** [comment] 2023-01-04 21:50
> @YalinLi0312 to help me understand better, do you mean this is a service issue? Or a storage issue?
> 
> Thanks.

The typo exists in the error message which returned from service end, I need service team to help to resolve it.

**Comment by xiangyan99** [comment] 2023-01-04 22:01
Thanks for the clarification.

Given it is not a bug in SDK, we can close the issue or if you want, use the issue to track the service change request (let's update the title to make it clearer that this is used to track the issue).

**Comment by YalinLi0312** [comment] 2023-01-04 22:26
Hi @klaaslanghout, I find you as the bot tagged your name above. I know you were working on Storage from your GitHub description, do you know anyone in Storage team that can help to resolve this issue?

**Closed** 2024-09-23 18:07 UTC
Labels: bug, Service Attention, Client, Tables
