### ISSUE TITLE
Method "check_ip_address_availability" returns always None regarding the status of IP

### ISSUE THREAD

**Issue by igoro1975** [Azure/azure-sdk-for-python#924] opened 2016-12-18 11:10 UTC
Method "check_ip_address_availability" returns always None regardless the status of IP.

![image](https://cloud.githubusercontent.com/assets/4538009/21293103/3103182e-c523-11e6-922f-fc6ceff7fd21.png)
![image](https://cloud.githubusercontent.com/assets/4538009/21293105/427fbecc-c523-11e6-8e8d-cac26355f548.png)
![image](https://cloud.githubusercontent.com/assets/4538009/21293106/49c8352e-c523-11e6-9ca3-92574850e79b.png)

**Comment by lmazuel** [comment] 2016-12-19 17:11
Hi @igoro1975 

Could you confirm the version of your package? There is an RestAPI version change between 0.30.0rc6 and 0.30.0, it would help to know what you use.

@derekbekoe @johanste did you experience that?

I'll take a look asap

**Comment by lmazuel** [comment] 2016-12-19 18:33
Not reproduced under 0.30.0
![image](https://cloud.githubusercontent.com/assets/1050156/21324305/10be61a0-c5d6-11e6-9a12-236da29544da.png)

If you're using 0.30.0rc6, please upgrade to 0.30.0. If you're using 0.30.0, please give more context so I can try to figure out why you have a problem and not me.

**Comment by lmazuel** [comment] 2016-12-19 19:16
FYI, just added a [unit test](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_network.py#L340) (indeed I didn't have time to add one when this feature arrived) with [success](https://travis-ci.org/Azure/azure-sdk-for-python/builds/185238018).

**Comment by igoro1975** [comment] 2016-12-21 07:03
Thank you @lmazuel. We do use 0.30.0rc6 version. I'll check it with 0.30.0 and update the issue.

**Comment by igoro1975** [comment] 2016-12-21 16:51
@lmazuel , it works in the version 0.30.0.

But how can we "override" the dependencies now? azure-2.0.0rc6 has requirements for azure-mgmt==0.30.0rc6 and it has requirements for azure-mgmt-network==0.30.0rc6 but we need azure-mgmt-network==0.30.0.

Thank you.

**Comment by lmazuel** [comment] 2016-12-21 17:23
It's not a real problem actually, you have two valid solutions:
- Stop using the "azure" meta-package. This package is intended to have an "easy to start" step for the Azure SDK for Python. Usually, people only use some packages only and not every dependencies. My guess is you use it for VM (resource/compute/network/storage), so you can change:
```python
azure==2.0.0rc6
```
to
```python
azure-mgmt-resource~=0.31.0
azure-mgmt-compute~=0.32.0
azure-mgmt-network~=0.30.0
azure-mgmt-storage~=0.30.0
```
You save time and space on installation.
- Upgrade Network only, pip does not forbid update
```
pip install azure==2.0.0rc6
pip install azure-mgmt-network==0.30.0
```

I guarantee to you, you will have not conflict of version, from 0.30.0rc2 to current 0.3x.y version, underlying runtime and dependencies are equivalent. Also, [this page](http://azure-sdk-for-python.readthedocs.io/en/latest/installation.html) can give you an overview of how I present the current state of packages.

ETA for 2.0.0 stable is February 2017 (in sync with other languages, we wait for the final go from the core SDK team of Azure). I think I will publish a 2.0.0rc7 in January after the holiday time, because there is currently too much gap between 2.0.0rc6 and the latest package of each service. I initially hoped to go directly from 2.0.0rc6 to 2.0.0, but unfortunately this wasn't possible,,, Sorry for the inconvenience caused by that... Be sure I do my best for the best user experience, it's why I published asap every service update as individual package.

**Comment by lmazuel** [comment] 2016-12-29 20:20
Hi @igoro1975 , could we close the issue? Thank you,

**Comment by lmazuel** [comment] 2017-01-10 19:43
I close this issue due to inactivity and I humbly think the problem is solved. Please add a comment here or open a new issue if you still experiment some problem. Thank you.

**Closed by lmazuel** 2017-01-10 19:43 UTC
Labels: ARM
