### ISSUE TITLE
HDInsightOnDemandLinkedService class errors from multiple runs.

### ISSUE THREAD

**Issue by glstream** [Azure/azure-sdk-for-python#2223] opened 2018-03-19 21:33 UTC
I am testing the use of On Demand clusters with the Python SDK. I can get a Cluster pipeline up and running fine, but when I manually delete the cluster and then re-porvision to test a new pre-action on the cluster I get the error:

{
    "errorCode": "2310",
    "message": "The cluster not found, ClusterEndpoint=https://sdkrun54bf5f8b-eb52-4b13-ab75-b53a22398a32.azurehdinsight.net/",
    "failureType": "UserError",
    "target": "spark-sqldb"
}

At the time of this error I have manually deleted the cluster that came from the previous pipeline. Why would an On Demand Linked service be looking for the URI of a previous cluster? If I wait a few hours my .py will execute fine and no longer have this specific error. Please let me know if code samples would make this issue more clear.

**Comment by lmazuel** [comment] 2018-03-22 17:26
I feel like your question is more a HDInsight RestAPI / service question then a Python one? You should probably reach out directly to the HDInsight team directly, since this repo doesn't have HDInsight Python SDK :(

**Comment by arun1024** [comment] 2018-08-29 21:46
@glstream would it be possible to share your code samples. I am trying to create HDInsight cluster using python sdk and there is not much documentation like Boto. 

Arun

**Comment by hvermis** [comment] 2019-06-07 21:53
This is by design. ADF keeps track of created OnDemand HDIs, and deletes them if they have not been used for the duration of the "time to live" property. If you delete it from outside, ADF will still try to submit your job on the cluster since it's not marked as deleted yet internally. So don't delete HDI on demand clusters, use time to live setting, and ADF will clean them up if they are not used. This is done to save time on bringing up the cluster and let you run multiple jobs one after another without waiting.

**Closed by hvermis** 2019-06-07 21:53 UTC
Labels: Data Factory, Question, Service Attention
