### ISSUE TITLE
[ServiceBus] Ensure autolockreceiver halts session renewal on volntary close, determine if desired for messages.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14336] opened 2020-10-07 19:54 UTC
AutoLockRenew doesn't appear to halt itself when a session is closed voluntarily.

This probably applies to normal receivers via message renewal as well? But what about our 'fallback' mechanism to allow settlement even after close.  Determine if we want this as well, but the former item is certainly desired.

Normal process, implement, tests, document etc.

**Comment by ramya-rao-a** [comment] 2020-10-29 00:26
@rakshith91 Please note that we are moving this out of the November milestone since it can be added post GA without it being a breaking change. If you were planning to start on this, please pick the next item for Service Bus in the November milestone instead.

I discussed this with @KieranBrantnerMagee over chat

**Comment by rakshith91** [comment] 2020-11-03 16:46
Unable to reproduce this - however this would need a validation.
Having a full integration test for "renewer halts properly when session receiver shuts down" may be worthwhile.

**Comment by yunhaoling** [comment] 2020-12-08 21:28
writing a test case for this

**Comment by swathipil** [comment] 2021-04-26 21:01
if potential fix needs to be added to set `ALR._shutdown.is_set()` to True when receiver/session is closed voluntarily (not just a test case), it will probably be around here: https://github.com/Azure/azure-sdk-for-python/blob/97978c41e2939aa73fb6e7fec905896c296f9114/sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py#L479

**Closed** 2021-04-30 15:33 UTC
Labels: Client, Messaging, Service Bus
