### ISSUE TITLE
Update matrix for livetests - python

### ISSUE THREAD

**Issue by KarishmaGhiya** [Azure/azure-sdk-for-python#4803] opened 2019-04-08 17:42 UTC
Livetests in python need to be run on more platform (Windows, Linux, MacOS) and python versions (2.7, 3.4, 3.5, 3.6, 3.7) (for both servicebus and eventhub as discussed with Anna)

**Comment by AlexGhiondea** [comment] 2019-04-22 23:06
This is a dupe of https://github.com/azure/azure-sdk-for-python/issues/4793

**Closed by AlexGhiondea** 2019-04-22 23:06 UTC
Labels: EngSys
