### ISSUE TITLE
Using InteractiveBrowserCredential with keyring on Windows crashes authentication

### ISSUE THREAD

**Issue by superhrusha** [Azure/azure-sdk-for-python#9928] opened 2020-02-20 15:49 UTC
**Environment**
- azure-storage-blob: 
- 12.2.0 
- Windows 10:
- 3.7: 

I obtain a token from InteractiveBrowserCredential. While obtaining it, I store a serialized version of the token in keyring for later use. 

I then try to access BlobServiceClient with this credential. I get an error saying "OSError: [WinError 1783] The stub received bad data". (Full Stack trace below).

Here comes the crazy part. I debugged it a bit and found out that the reason this happens has something to do with the length of the password (the token in this case) I store inside of keyring. 
In my environment, if I set it to a value longer than 1280- I get the error. Any value shorter than that is ok. 

Note that I do not get any error from keyring itself. It crashes only when the authentication is attempted.
Also - this works perfectly on Mac/Linux. The problem is only on Windows.

**To Reproduce**

```
import json
from typing import Any
from azure.core.credentials import AccessToken
from azure.identity import InteractiveBrowserCredential
from azure.storage.blob import BlobServiceClient
import keyring

class BuggyInteractiveBrowserCredential(InteractiveBrowserCredential):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def get_token(self, *scopes, **kwargs):  # type: (*str, **Any) -> AccessToken
        # other custom code here
        token = super().get_token("https://storage.azure.com/user_impersonation")
        keyring.set_password("storage", "storage", json.dumps(token._asdict())) #in practice, any string longer than 1280 crashes !
        return token

cred = BuggyInteractiveBrowserCredential(client_id="...", tenant_id="...")
blobber = BlobServiceClient(account_url="...", credential= cred)

for c in blobber.list_containers():
    print(c.name)
```

**Expected behavior**
Expected the flow to succeed in authentication and print the containers.

**Comment by chlowell** [comment] 2020-02-20 16:30
Hi @superhrusha, thanks for reporting this. I'm closing this issue as a duplicate of jaraco/keyring#355 because the Azure SDK doesn't depend on `keyring` or use the Windows credential vault, meaning we can't address that behavior here.

That being said, we're working on a persistent cache design for `InteractiveBrowserCredential` that I hope will make custom caching code unnecessary (tracked by #9744).

**Closed by chlowell** 2020-02-20 16:30 UTC
Labels: Client, customer-reported
